### ISSUE TITLE
eslint-plugin-import requires outdated version of eslint as peer dependency

### ISSUE THREAD

**Issue by caraya** [benmosher/eslint-plugin-import#1002]
I'm installing eslint 4.1.1 and get the following message during install:

```
npm WARN eslint-plugin-import@1.16.0 requires a peer of eslint@2.x - 3.x but 
none is installed. You must install peer dependencies yourself
```

Am I missing something? Should the peer dependency be bumped?

I am not installing eslint globally so #989 and #916 are not applicable as this is being installed in a project specific folder.

**Comment by ljharb** [comment]
That is an outdated version of eslint-plugin-import, which is not compatible with eslint 4.

Upgrade eslint-plugin-import to the latest version, and you'll be able to use it with eslint 4.

**Comment by caraya** [comment]
Thanks, I just figured out where it came from and have updated it accordingly. Sorry about the noise

**Comment by AwaisFayyaz** [comment]
Can you tell me how it was fixed. I am having same issue

**Comment by ljharb** [comment]
@AwaisFayyaz what does `npm ls` print out?

**Comment by AwaisFayyaz** [comment]
A long tree structure. In between, this 

<img width="298" alt="screen shot 2018-04-26 at 12 11 07 pm" src="https://user-images.githubusercontent.com/11820112/39291013-fa384596-494a-11e8-90da-c99b7b484980.png">

And at the end

<img width="568" alt="screen shot 2018-04-26 at 12 10 33 pm" src="https://user-images.githubusercontent.com/11820112/39290982-d90c2964-494a-11e8-9291-541db4a0fec3.png">

**Comment by ljharb** [comment]
@AwaisFayyaz ok, so your issue is the same - you're using a too-old version of eslint-plugin-import, eslint-plugin-jsx-a11y, and eslint-plugin-react. Update all of them.

**Comment by AwaisFayyaz** [comment]
can you tell me the commands to update these. Thanks

**Comment by ljharb** [comment]
The same commands you used to install them in the first place, basically. This repo isn’t the place to give an npm tutorial, unfortunately.

**Comment by enextus** [comment]
AwaisFayyaz you can try some comands (example) in console:

npm restart
npm i eslint@^2.0.0
npm i eslint@^2.10.2
etc..

that works
