### ISSUE TITLE
Custom resolver: Webpack

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#102]
Needs to take a file path as config, but have some default fallback akin to Webpack's (i.e. `webpack.config.js` as sibling to nearest ancestor `package.json`).

- [ ] find webpack config (use some lib to find package.json and look in that dir)
- [ ] use aliases to resolve paths (fixes #89)
- [ ] live in `resolvers/webpack`, use from custom resolver config
- [ ] document custom resolvers

**Comment by gausie** [comment]
I use an ES6 webpack file that is converted on-the-fly to JS by Webpack (https://github.com/webpack/webpack/pull/956) using node-interpret.

This step isn't carried out by the Webpack resolver when it loads the config though unfortunately.
