### ISSUE TITLE
Error while loading rule 'import/group-exports': rule.create is not a function

### ISSUE THREAD

**Issue by SammyM** [benmosher/eslint-plugin-import#1031]
I think, due to the `export default` within _group-exports.js_, it's causing the following error when I try to lint my JavaScript:
```
Error while loading rule 'import/group-exports': rule.create is not a function
```
because it compiles it to `exports.default = {};` instead of `module.exports = {`.

**Comment by ljharb** [comment]
Whoops. Yeah that needs fixing.

**Comment by jshado1** [comment]
@ljharb could this get released? it looks like the latest release was published the day before this fix.
