### ISSUE TITLE
Doesn't work correctly with package.json trick

### ISSUE THREAD

**Issue by arnsa** [benmosher/eslint-plugin-import#1033]
Hello,

so in my project I am using this little neat trick with package.json file. Let's say I have images folder and inside that folder I have a package.json file with only one line: `{ "name":"images" }`. That way, I can use imports like this:

`import MarkerImage from 'images/marker.png';`

And it will work just fine. The problem is that eslint-plugin-import that it's unable to resolve path module and also that "images" should be listed in the project's dependencies. Is there any way to fix this without disabling these rules?

**Comment by ljharb** [comment]
This "trick" is generally a bad practice (having nested package.json files), but I think this is related to #935 and #904?

**Comment by arnsa** [comment]
Okay, I see. I've found a solution in one of the issues you've linked. Thanks!
