### ISSUE TITLE
Lint Dynamic Imports for no-unresolved

### ISSUE THREAD

**Issue by tgreen7** [benmosher/eslint-plugin-import#1035]
For code-splitting in our app we have
```
import(/* webpackChunkName: "WelcomePage" */ "./components/WelcomePage")
```

However, we don't get the same awesome eslint error if that path doesn't exist. It would be great to have that linted as well.

**Comment by ljharb** [comment]
Seems reasonable, altho it would require using babel-eslint.

**Comment by ljharb** [comment]
Actually tho - import() uses urls, not paths, so I’m not sure how this would work properly.

**Comment by vikr01** [comment]
> import() uses urls, not paths
Doesn't it use paths and webpack transforms them into urls?

I've also noticed that `import/resolve` doesn't work on `require.*` statements (i.e. `require.resolve` and `require.ensure`). This would be a really neat feature to have.

**Comment by ljharb** [comment]
`require.ensure` is nonstandard webpack nonsense, but `require.resolve` would make some sense.
