### ISSUE TITLE
Auto fix for rule "first"

### ISSUE THREAD

**Issue by fengkfengk** [benmosher/eslint-plugin-import#1040]
I would like to work on the rule `first` auto fixer. The small and controllable problem should be auto fixed. If can be merged, I may start working now. The strategy is put the no-first import declarations into the bottom of the first import declarations.

**Comment by ljharb** [comment]
That sounds fine, as long as the following criteria apply:
1. imports are never re-ordered relative to each other, even if `absolute-first` is set.
1. if an import creates an identifier, and that identifier is referenced at module level *before* the import itself, that must also not be re-ordered.

**Comment by fengkfengk** [comment]
About the second point.
`const foo = bar;
import bar from './bar.js';`
This won't be re-ordered?

**Comment by ljharb** [comment]
@fengkfengk correct, because that code will currently throw a TDZ error, and that error should be maintained by the autofixer.
