### ISSUE TITLE
Pass env variable to webpack configuration

### ISSUE THREAD

**Issue by kamalbennani** [benmosher/eslint-plugin-import#1043]
Following https://github.com/benmosher/eslint-plugin-import/pull/938, I am facing a problem where my project is composed of a several applications and each them might define a "custom" webpack configuration which extends a common configuration which is defined in the root of the project.
```
/
apps/
- app1/
  webpackConfig.js  <-- specific to app1
  .eslintrc
- app2/
  webpackConfig.js  <-- specific to app2
  .eslintrc
- app3/
  webpackConfig.js <-- specific to app3
  .eslintrc
webpack.config.js <-- common configuration
```
A custom webpack configuration looks like so:
__apps/app1/webpackConfig.js__
```JS
export function (baseConfig) => {
 newConfig = baseConfig
 // Some custom manipulation
 ....
 return newConfig
}
```

**Note that the common webpack configuration is responsible for determining which webpack configuration to load based on the application name**.
So for instance, to run the `app1`, we execute the following command :
```SH
webpack-dev-server  --config webpack.config.js --env app1
```

The problem is that the 'env' variable is being ignored, So I can't do something like that:
__apps/app1/.eslintrc__
```JS
const path = require('path');
module.exports = {
  settings: {
    'import/resolver': {
      webpack: {
        config: path.resolve(__dirname, '../../webpack.config.js'),
        env: 'app1'
      }
    }
  },
};
```
The solution is to grab the env from the settings and to pass it to the webpackConfig in the webpack resolver:
__resolvers/webpack/index.js__
```JS
var env = get(settings, 'env')
if (typeof webpackConfig === 'function') {
   webpackConfig = webpackConfig(env)
}
```

**Comment by ljharb** [comment]
Do you have `"root": true` in each of those eslintrc files?

**Comment by VladimirPal** [comment]
Sorry, just found it was fixed https://github.com/benmosher/eslint-plugin-import/commit/084464558d11509254d496688d9957649f95ebe3

If it does not work for you, you have to set env variable in loader config path:
.eslintrc example:
```
  "settings": {
    "import/resolver": {
      "webpack": {
        "env": "development",
        "config": "./webpack.config.base.js"
      }
    }
  }
```
