### ISSUE TITLE
import/no-extraneous-dependencies should check `export from`

### ISSUE THREAD

**Issue by penx** [benmosher/eslint-plugin-import#1049]
The following is correctly picked up by `import/no-extraneous-dependencies`

```js
import { myUtil } from '@my/utils';
export { myUtil };
```

The following code is equivalent but does not get picked up by `import/no-extraneous-dependencies`

```js
export { myUtil } from '@my/utils';
```

Can support for this be added?

**Comment by marcusdarmstrong** [comment]
Open to contributions on this?

**Comment by penx** [comment]
I think the ‘help wanted‘ tag from @ljharb means yes 🙂
