### ISSUE TITLE
order rule should be fixable

### ISSUE THREAD

**Issue by ThiefMaster** [benmosher/eslint-plugin-import#1051]
Fixing import order/grouping manually is :monkey:-work. It would be nice if the rule included a fixer for it.

PS: I found this fork of the rule that has a fixer, but no idea how well it works (didn't test it): https://github.com/AlexJuarez/eslint-plugin-import-order-autofix/blob/master/src/rules/order.js

**Comment by ljharb** [comment]
Covered by #908.
