### ISSUE TITLE
Support css imports for import/order

### ISSUE THREAD

**Issue by tgreen7** [benmosher/eslint-plugin-import#1072]
I really like the --fix option for import order, and it works most of the time. However, if I have something like
```
import React from "react"
import "./style.css"
import { forEach } from "lodash"
```
then the --fix option does not work

**Comment by ljharb** [comment]
It's not because it's a CSS import, it's because it's a side-effecting import - ie, it doesn't import a value. It's not safe for the autofixer to reorder side-effecting imports; you'll have to do that manually.
