### ISSUE TITLE
JSX fragments syntax recognized as import error

### ISSUE THREAD

**Issue by jeron-diovis** [benmosher/eslint-plugin-import#1074]
Trying to use new [JSX fragments syntax](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html). 

Got this:

<img width="693" alt="screenshot 2018-04-10 19 26 00" src="https://user-images.githubusercontent.com/2756868/38570023-77411d2c-3cf5-11e8-8ec1-07bed4b96aa6.png">

Installed `eslint-plugin-import@2.10.0`.

**Comment by ljharb** [comment]
Are you using babel 7 and babel-eslint?

**Comment by jeron-diovis** [comment]
babel 6.5.2, babel-eslint 7.2.3

**Comment by ljharb** [comment]
Babel 7 is required for fragment syntax. Use React.Fragment until then.
