### ISSUE TITLE
Doc is uncomplete for resolvers

### ISSUE THREAD

**Issue by budarin** [benmosher/eslint-plugin-import#1090]
Hi!
We have code:
```js
require('!!file-loader?name=[name].[hash].[ext]!../common/assets/css/fonts.css');
```
but it produces an error: ```import/no-unresolved```

from the documentation for resolvers it's unclear what is foo and how to resolve the import above

**Comment by ljharb** [comment]
That looks like webpack-specific syntax; you'll need to use the webpack resolver to make this work.
