### ISSUE TITLE
evaluate/implement semantic-release

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#1092]
https://github.com/semantic-release/semantic-release

evaluate this. would be ideal to have the release process more automated to minimize time from merges to releases.

**Comment by ljharb** [comment]
I'm a very strong -1 on this. Only humans should ever publish releases.

The releaser is, and should be, the only decision maker for the semverness of a release - using semantic-release delegates this important safety net (for `npm publish`, the only truly irrevocable action) to individual PR authors and reviewers.

**Comment by ljharb** [comment]
Closing while I'm the only one doing releases, given my comment above :-)

**Comment by benmosher** [comment]
fair enough 😁
