### ISSUE TITLE
Need forced restart atom after edit webpack config

### ISSUE THREAD

**Issue by tebaly** [benmosher/eslint-plugin-import#1099]
Webpack contain resolve aliases. After add or edit alias - Nothing happens(eslint shows an error “import/extensions”). For the changes to take effect restart atom is required. Is it normal? How can i fix it?

```
"plugins": ["import"],
  "settings": {
    "import/resolver": {
        "webpack": {
            config: 'webpack.config.js'
        }
  },
```

- webpack: 4.8.1
- eslint: 4.19.1
- eslint-plugin-import: 2.11.0
- eslint-import-resolver-webpack: 0.9.0

atom comunity q copy https://discuss.atom.io/t/need-forced-restart-atom-after-edit-webpack-config/54982

**Comment by ljharb** [comment]
Yes, many editors need to be restarted when config or plugins change.

**Comment by benmosher** [comment]
That is surprising given that I am _just literally right now_ publishing the caching for the webpack resolve function.

There is an in-memory cache of resolved files but it has a TTL of 30s, IIRC. if you wait ~1 minute, do you see your changes reflected?

**Comment by tebaly** [comment]
No. only restart atom helped

**Comment by ljharb** [comment]
I don’t think this is an issue with this plugin - atom in particular often needs to be restarted whenever anything changes in its plugin deps.

**Comment by tebaly** [comment]
But changed only 'alias' configuration in general webpack config
* https://webpack.js.org/configuration/resolve/#resolve-alias

This in not "changes in its plugin deps".

```
alias: {
  Utilities: path.resolve(__dirname, 'src/utilities/'),
  Templates: path.resolve(__dirname, 'src/templates/')
}

// Add one line alias

alias: {
  Utilities: path.resolve(__dirname, 'src/utilities/'),
  Templates: path.resolve(__dirname, 'src/templates/'),
  Core: path.resolve(__dirname, 'src/core/') 
}
```

Eslint error in line use alias Core like 
` import CoreUtil from 'Core/Util'; `

To apply changes webpack config - restart atom.

**Comment by ljharb** [comment]
Right. This is an atom issue, because restarting atom fixes it :-)

**Comment by Tbhesswebber** [comment]
@tebaly I'm not certain about Atom's plugin, but the VSCode plugin for ESLint generates its own server in the background and only reads external configs right when it starts, loading them into memory.  I would ask within the Atom plugin repository if there is a way to manually restart the server or to have the server reload the configuration.
