### ISSUE TITLE
Please release new version early to hotfix performance issue <3

### ISSUE THREAD

**Issue by kamronbatman** [benmosher/eslint-plugin-import#1100]
@benmosher, I would very much love it if you could release the next version early, or a hotfix that has the performance fix. It would definitely save my sanity.  Thank you!

EDIT: I think it will require a new version of `eslint-import-resolver-node` and `eslint-import-resolver-webpack` to be published too?

**Comment by benmosher** [comment]
👍🏻

**Comment by benmosher** [comment]
btw I didn't see any node resolver changes in the intervening commits, do you have something in mind that needs to published for that?

**Comment by kamronbatman** [comment]
@benmosher, it was specifically this change: https://github.com/benmosher/eslint-plugin-import/commit/f0d0c4ffaee09bf2056f125271186caa50677e49
Which looks like it touches the node and webpack resolvers.
This was supposed to fix the ~90sec lint times.

Let me know if I am misunderstanding.  Thanks!

**Comment by kamronbatman** [comment]
I thought PR #1091 fixed Issue #788.
Indeed, I just tested and I am still having an issue. Now I am not sure if it is related or not.
