### ISSUE TITLE
Upgrade Lodash to avoid `npm update` security issue

### ISSUE THREAD

**Issue by ehmicky** [benmosher/eslint-plugin-import#1101]
`npm update` reports a security vulnerability tied to [this Lodash issue](https://nodesecurity.io/advisories/577). Upgrading Lodash to >=4.17.5 would solve this problem.

**Comment by ljharb** [comment]
We don’t use any of the vulnerable methods mentioned in that issue, so npm audit is wrong to report it - it’s a false positive.

Since we use a semver range on lodash, a fresh install should give you the latest version already, with no action needed here.

**Comment by ehmicky** [comment]
Sorry about this, you're right. I'm having some hard time wrapping my head around `npm audit`. This seems like there are some issues. If I only install `eslint-plugin-import` as sole dependency, it gives no warnings, but if other dependencies install the wrong version of Lodash, then it seems to complain about `eslint-plugin-import` as well. Sorry!
