### ISSUE TITLE
multiple packageDir cover

### ISSUE THREAD

**Issue by mo-n** [benmosher/eslint-plugin-import#1109]
```
    "import/no-extraneous-dependencies": [
      "error",
      {
        "packageDir": [
        './node_modules/nuxt',
        './',
      ]}
    ],
```
`./node_modules/nuxt/package.json`  same field is covered by ` ./package.json `

[no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L45)

![image](https://user-images.githubusercontent.com/3423000/40645816-05d42fe0-635a-11e8-911d-a447ef187597.png)
![image](https://user-images.githubusercontent.com/3423000/40645870-2a59c3ca-635a-11e8-83f4-163919096b12.png)

**Comment by mo-n** [comment]
@benfletcher

**Comment by mo-n** [comment]
@benmosher

**Comment by mo-n** [comment]
#1103

**Comment by Tymek** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/8c9c3b86ac8bf22ca194caad51102335b088d28b/src/rules/no-extraneous-dependencies.js#L45
https://github.com/benmosher/eslint-plugin-import/blob/8c9c3b86ac8bf22ca194caad51102335b088d28b/src/rules/no-extraneous-dependencies.js#L51

Shallow object merge bug IMHO. Is anybody working on this right now? Could I contribute?
