### ISSUE TITLE
import/named doesn't ignore Flow identifier syntax type import

### ISSUE THREAD

**Issue by zeorin** [benmosher/eslint-plugin-import#1115]
"Identifier syntax":
```javascript
// @flow
import { type Dispatch } from 'redux';
```
Gives following error:
```
2:15  error    Dispatch not found in 'redux'        import/named
```
Whilst the "declaration syntax":
```javascript
// @flow
import type { Dispatch } from 'redux';
```
Generates no error.

This is especially annoying for users that use the [`flowtype/type-import-style`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-type-import-style) rule with the default setting ("identifier") and run ESLint with `--fix`, since that rule will automatically change the syntax, which then triggers `import/named`.

The point of the identifier syntax is to combine type and value imports in the same statement, e.g.

```javascript
// @flow
import { configureStore, type Dispatch } from 'redux';
```

The [docs for this rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md) state:
> Note that type imports, as used by Flow, are always ignored.

So I think this is a bug. Can we ignore the identifier syntax for this rule also?

**Comment by rostislav-simonik** [comment]
Fixed in PR #1117
