### ISSUE TITLE
no-relative-parent-imports didn't check if path start with './'

### ISSUE THREAD

**Issue by Alex-Sokolov** [benmosher/eslint-plugin-import#1123]
When add rule to config
`import blockIcons from '../../components/test/test.js'` — FAIL
but
`import blockIcons from './../../components/test/test.js'` — OK

ref: https://github.com/benmosher/eslint-plugin-import/pull/1093

**Comment by ljharb** [comment]
cc @chrislloyd 

we may want to use the resolver here to normalize the paths?

**Comment by chrislloyd** [comment]
Working on this now - thanks for filing the issue @Alex-Sokolov
