### ISSUE TITLE
[import/named] not working for index.js in folder which exports object

### ISSUE THREAD

**Issue by jairusd** [benmosher/eslint-plugin-import#1124]
https://github.com/eslint/eslint/issues/10518

**Tell us about your environment**

* **ESLint Version:** 4.19.1
* **Node Version:** 8.9.4
* **npm Version:** 5.6.0

**What parser (default, Babel-ESLint, etc.) are you using?** babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
extends: airbnb
env:
  browser: true
  node: true
  es6: true
parser: babel-eslint
plugins:
  - react
rules:
  array-callback-return: 0
  camelcase: 0
  class-methods-use-this: 0
  comma-dangle:
    - 1
    - never
  func-names: 0
  generator-star-spacing:
    - 0
    -
      before: true
      after: false
  guard-for-in: 0
  no-console: off
  no-param-reassign:
    - 1
    -
      props: true
      ignorePropertyModificationsFor:
        - errors
        - columnObject
  no-unused-vars:
    - 1
    -
      args: none
  semi: 0
  react/no-array-index-key: 0
  react/require-default-props: 0 # to be removed
  react/prop-types: 0 # to be removed
  react/forbid-prop-types: 0
  react/no-children-prop: 0
  react/jsx-no-bind: 0
  react/jsx-filename-extension: 0
  react/no-unescaped-entities: 0

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

![image](https://user-images.githubusercontent.com/36670564/41846029-074eb274-78a8-11e8-809c-50da673b47bd.png)

![image](https://user-images.githubusercontent.com/36670564/41846057-17c656de-78a8-11e8-9d23-25a89915f98c.png)

```bash

```
i'm using sublime nad have eslint run in background

**What did you expect to happen?**
expected to detect `globalSelector` to be detected since it does exist from the object I exported from `index.js`

**What actually happened? Please include the actual, raw output from ESLint.**
![image](https://user-images.githubusercontent.com/36670564/41846182-7b2e1a18-78a8-11e8-8f57-91d1d6c65390.png)

As you can see i'm calling `globalSelector` from `index.js` in `reselect` folder and as you can see from `index.js` i'm exporting an object with `globalSelector` in it.

**Comment by ljharb** [comment]
I think that because you’re not exporting with the export keyword, the rule can’t detect it. Is there a reason you’re combining import with module.exports?

**Comment by jairusd** [comment]
Yes. That is to make references to all files in a folder structure in the index.js. For now that is only just one but in the future it could probably be a lot so that way i can control the references and have each file  referenced with a custom name which in turn i reference when importing it as a named import.

**Comment by ljharb** [comment]
Why not `export { globalSelector }`?

**Comment by ljharb** [comment]
They definitely don't work the same; using module.exports is exporting a single object, which can't be tree-shaken. Using named exports means you can import each thing you need. CJS files can use `exports.foo = bar` all over the code too - the solution with either CJS or ESM exports is to use a linter to enforce placement.

If it's possible to support, that'd be great, but it just doesn't make any sense to use `module.exports` in an ESM codebase (and it prevents webpack 2+ from using treeshaking)

**Comment by jairusd** [comment]
I see. I guess I need to make more research about this I don't have much idea about what you are talking about, I thought tree shaking was always possible if you selectively import keys from the exported object. `export { ...items }` seems to work and satisfies what I wanted in the first place. Is it a good practice?

**Comment by jairusd** [comment]
That was just a sample though, anyway thanks for the fast response and I was able to resolve this issue by using either export {} or export default something. thanks!
