### ISSUE TITLE
Grouped export/import not working

### ISSUE THREAD

**Issue by EddyVinck** [benmosher/eslint-plugin-import#1138]
I am getting errors with certain grouped imports. Some are working, and some are not & I cannot figure out why ESLint is giving me errors. Webpack compiles just fine and the functions seem to be executing also.

This is my repository in case you want to look more into it: https://github.com/EddyVinck/Activity-Randomizer/tree/feature/refactoring-001/src/js

This works, but of course gives the `import/no-duplicates` error.
```js
// activity-randomizer.js
import appendCol from './partials/activity-randomizer/dom';
import appendPre from './partials/activity-randomizer/dom';
import getDocumentID from './partials/activity-randomizer/dom';
```

This does not work, it gives me these errors: `appendCol/appendPre/getDocumentID not found in './partials/activity-randomizer/dom' (import/named)`
```js
// activity-randomizer.js
import { appendCol, appendPre, getDocumentID } from './partials/activity-randomizer/dom';
```

```js
// ./partials/activity-randomizer/dom
import getCookies from '../../cookies/cookies';

const getDocumentIDFromDocumentInput = () => {
  //stuff

  return documentID;
};

const getDocumentID = () => {
  const cookies = getCookies();
  // stuff

  return documentID;
};

const appendPre = (message) => {
  // stuff
};
const appendCol = (activity, time) => {
  // stuff
};

module.exports = { getDocumentID, appendPre, appendCol };
```

My config:

```json
{
  "extends": 
    [
      "airbnb-base", 
      "prettier"
    ],
  "rules": {
    "linebreak-style": 0,
    "no-param-reassign": 0,
    "no-use-before-define": [
      "warn",
      {
        "functions": false,
        "classes": true,
        "variables": true
      }
    ]
  },
  "env": {
    "browser": true,
    "node": true,
    "jasmine": true
  },
  "globals": {
    "gapi": true,
    "$": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "settings": {
    "import/resolver": "node"
  }
}
```

This is all strange, because some other grouped imports are actually working. 

These are working:
```js
// activity-randomzier.js
import { getFilters, filterActivities } from './partials/activity-randomizer/filters/filters';
```
```js 
// ./partials/activity-randomizer/filters/filters
const getFilters = () => {
  // stuff
  return filters;
};

const filterActivities = (activities, filters) => {
  // stuff
  return filteredActivities;
};

module.exports = { getFilters, filterActivities };

**Comment by EddyVinck** [comment]
I think I found what is causing the issues.

The files with errors both import something themselves. Is there a way to fix this? I need to import modules in those files. 

Is this an error? Because Webpack compiles this code without errors or warnings.

**Comment by ljharb** [comment]
The issue is that you’re using import with module.exports. Is there a reason you’re not using the export keyword?

**Comment by EddyVinck** [comment]
Like this?
```js
export { getDocumentID, appendPre, appendCol };
```

There's no particular reason I was using `module.exports` other than having always used it like that and I was not getting errors for using it. 
I was looking through the docs and found [rules/group-exports](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/group-exports.md) so I did not think using it was an issue.

After using just `export` the errors disappeared and there was a warning for not using `export default` so I assume everything is working correctly. However, I am not getting an error or warning for using `module.exports`. 

How can I configure this with [`no-common-js`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-commonjs.md) correctly? I'm not too familiar with ESLint yet and this does not seem to cause errors or warnings when using `module.exports` :
```json
"settings": {
    "import/resolver": "node",
    "import/no-commonjs": true
  }
```

I also have another question you might know more about. Do you have any idea why I have to reload VSCode for the errors to go away for these imports/exports?

**Comment by ljharb** [comment]
In general, you don't want to mix module systems - a file should use require/module.exports, or import/export.

vscode, like most editors, is often brittle around file changes that aren't the file you're currently working on. you'll want to file that on their repo.

`import/no-commonjs` is a rule, not a setting - and rules are enabled with a severity, not a boolean.

**Comment by EddyVinck** [comment]
Thank you so much for explaining that to me. It makes a lot more sense to me now. I managed to further configure my settings and fix all issues now.
