### ISSUE TITLE
Resolving with eslint-import-resolver-webpack silently fails when module is not installed

### ISSUE THREAD

**Issue by balazsczap** [benmosher/eslint-plugin-import#1146]
After a while of debugging, I found that if a 'webpack' resolver configuration is given in `.eslintrc`, but no installation of `eslint-import-resolver-webpack` is found, the resolve process then tries to use `webpack` itself (since it tries to use the configuration name as a custom package, if a package with the conventional name is not found) as a resolver. 

- If `webpack` is intalled, this obviously fails, since `webpack.resolveImport` is undefined, but instead of an error message, the rule is shown as having failed.
- If `webpack` is not installed, the rule check correctly fails with `Resolve error: unable to load resolver "webpack"`.

**Comment by ljharb** [comment]
How do you suggest fixing this?

**Comment by balazsczap** [comment]
I've started working on a pull request, which should check if the required method (`.resolveImport` for v1 and `.resolve` for v2) is available on the resolver object being passed to withResolver.

I realize this is only a quick fix, but it will at least provide users with info on why their import rules are failing.

**Comment by helicese** [comment]
I just wonder why `eslint-import-resolver-webpack` is not in dependences

**Comment by balazsczap** [comment]
If I understand correctly, the node resolver is default, and works well enough. The webpack resolver is only needed (in some cases) if you're using webpack. 

In my case the webpack resolver was added to devDependencies as it should be (and thus installed locally), but ESLint was being run globally, and tried to load the resolver globally as well, which it couldn't.

**Comment by ljharb** [comment]
Closed by #1148.
