### ISSUE TITLE
no-amd

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#115]
AMD analog of `no-require`. Should flag valid AMD `define` and `require` calls.

- [ ] 2 arg: array, callback (`require` and `define`)
- [ ] 1 arg `define`: can be function or value (anything)
- [ ] double-check there aren't other major forms

**Comment by xjamundx** [comment]
You can use this version:
https://github.com/xjamundx/eslint-plugin-modules/blob/master/rules/no-define.js

**Comment by benmosher** [comment]
@xjamundx thanks!
