### ISSUE TITLE
unable to resolve path to module "moment-range" (import/no unresolved)

### ISSUE THREAD

**Issue by slim-hmidi** [benmosher/eslint-plugin-import#1155]
I'm installing `moment-range` in my application:
```js
const momentRange = require('moment-range'); 
```
I got this eslint error:
```js
unable to resolve path to module "moment-range" (import/no unresolved)
```
However the module was installed and exists in `package.json`.

.eslintrc.json
```json
{
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "env": {
        "node": true
    },
    "extends": "airbnb-base"
}
```

I have already open an issue [Unable to resolve path to module 'moment-range' import/no-unresolved](https://github.com/eslint/eslint/issues/10288) on `eslint` project. How can I fix this problem because the only solution that I use now is `eslint-disable-line`.
**eslint-plugin-import:** 2.8.0
**moment-range:** 4.0.0
**node:** 8.11.3
**npm:** 5.6.0
**OS:** Ubuntu 18.04.1LTS (64-bit)

**Comment by ljharb** [comment]
If you open up the repl (`node`), can you require moment-range successfully?

**Comment by slim-hmidi** [comment]
@ljharb It works on repl.

**Comment by ljharb** [comment]
What's the structure of your project? Do you just have one package.json at the root?

**Comment by slim-hmidi** [comment]
@ljharb  I have only one package.json file

**Comment by ljharb** [comment]
And the eslint error you get is on the command line? Can you share the full command and output?

**Comment by wcandillon** [comment]
I can confirm the exact same issue with the moment-range package.

**Comment by ljharb** [comment]
@wcandillon same questions above to you then

**Comment by ljharb** [comment]
Given that https://unpkg.com/browse/moment-range@4.0.2/package.json points to https://unpkg.com/browse/moment-range@4.0.2/dist/moment-range.js, but https://unpkg.com/browse/moment-range@4.0.0/package.json has jsnext-main that points to a nonexistent file, this seems to have been a bug in moment-range that they've now fixed.
