### ISSUE TITLE
`no-named-as-default` is a little too opinionated.

### ISSUE THREAD

**Issue by Asday** [benmosher/eslint-plugin-import#1162]
I disagree with [no-named-as-default](https://github.com/benmosher/eslint-plugin-import/blob/f7bd328f7b86c9f6d95c58c261b0b513df14bbd5/docs/rules/no-named-as-default.md), and was wondering whether the rationale has considered the following pattern, which I see regularly, (and see no problem with):

```es6
export class ComponentWithAForm extends React.Component {
  ...
}

export default reduxForm()(ComponentWithAForm
```

And similarly:

```es6
export class Container extends React.Component {
  ...
}

export default connect(mapStateToProps, mapDispatchToProps)(Container)
```

In these examples, it doesn't make sense to import the default export as anything other than the original class' name, as it _is_ the original class, with some extra behaviour that's used in normal operation.

The above pattern allows for much nicer testing.  You import the _named_ export in your tests, and you can wrap it in your mock wrappers.  With it having the same name, everything you'd expect is turned up when you grep over the codebase.

**Comment by ljharb** [comment]
First, if you disagree with a rule, you can simply choose not to enable it.

Second, the pattern you're using - of exporting the unwrapped component - is imo an antipattern, and presumably you're only doing it for testing purposes. Exporting `Container` when it's never used in production without `connect` is a huge code smell.

In other words, it's not actually nicer testing - it's substandard testing.

**Comment by Asday** [comment]
I would be very interested to hear why that's the case.

**Comment by ljharb** [comment]
Because then you’re not testing a valid code path. All your tests are proving is that the inner component works - but if you never use the inner one by itself, that knowledge is pretty useless - you need to know if it works *when used in concert with the wrapper*.

In general, exposing *anything* just for testing is a huge antipattern. If it’s not exposed to real code, it shouldn’t be directly tested.

**Comment by ljharb** [comment]
It's not *directly* exposed, so it shouldn't be directly tested.

At any rate, this is an eslint plugin - every rule is opinionated, that's the point. If you don't agree, don't enable the rule.
