### ISSUE TITLE
Conflict with prettier

### ISSUE THREAD

**Issue by chris-verclytte** [benmosher/eslint-plugin-import#1169]
Hi,

This issue is a transfer from [initial issue](https://github.com/prettier/eslint-config-prettier/issues/50) on eslint-config-prettier as it would indeed [make more sense to improve eslint-plugin-import](https://github.com/prettier/eslint-config-prettier/issues/50#issuecomment-419990636).

I am currently using prettier through eslint run and there is a (tricky) rule that seems to break.

I am using JS without semicolons which implies declaration of IIFE with a semicolon before parenthesis. Then I have the following case:
- Ok for prettier, not ok for eslint that will consider that first line is ending after the ";" and then eslint returns an "import/newline-after-import" error
```js
const EventStore = require('../service/eventStore')

;(async () => {
  const eventBus = await EventBus.getInstance()
  eventBus.stanConnection.on('connect', registerCommandHandlers)
})()
```

- Ok for eslint, not ok for prettier that returns a "Delete ↵" on line 3.
```js
const EventStore = require('../service/eventStore')
;

(async () => {
  const eventBus = await EventBus.getInstance()
  eventBus.stanConnection.on('connect', registerCommandHandlers)
})()
```

Could not find a suitable solution for this particular use case.

**Comment by ljharb** [comment]
(I’m confused why you’d ever need an IIFE in a world with modules)

I’m not sure how to address this conflict; it seems omitting semicolons isn’t compatible with both prettier and this particular eslint rule, and you may need to stop using one of those three.

A PR is welcome if it doesn’t involve adding an option.

**Comment by chris-verclytte** [comment]
In this case, IIFE is just useful at the top level of a service to provide async/await functionality. While it could be handled by using a `.then` method, I prefer keeping async/await style everywhere. But indeed, maybe the conjunction of "no semicolons", "import eslint rule" and "async/await style" is too specific to justify an update.

**Comment by charlex** [comment]
I received this error as well with two lines:

```
Delete `⏎⏎`eslint(prettier/prettier)
```

**Comment by ljharb** [comment]
Now that top-level `await` exists, there's even less usefulness for an IIFE.

**Comment by lydell** [comment]
Possibly related: https://github.com/prettier/prettier/issues/1510

**Comment by ljharb** [comment]
Given the obsolescence of IIFEs, the existence of top-level await, and the issue in prettier, I’m going to close this as unactionable here.
