### ISSUE TITLE
Trying to understand the no-named-as-default rule

### ISSUE THREAD

**Issue by DominicTobias** [benmosher/eslint-plugin-import#1173]
Hi,

I wanted to export my module like this:

```js
export {
  ReactCrop,
  ReactCrop as default,
  ReactCrop as Component,
  getPixelCrop,
  makeAspectCrop,
  containCrop,
};
```

I'm trying to understand why this rule thinks this is bad. This is so that a user can import with either `import ReactCrop...` or `import { ReactCrop, getPixelCrop }...`. `ReactCrop` is the default export, but you can also explicitly import it in braces if you want - I'm trying to understand why that would be a bad thing and can't figure it out from https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md

Not a big deal to enforce that it is imported only as a default i.e. `import ReactCrop, { otherStuff }` but don't know why this is an issue.

Thanks

**Comment by ljharb** [comment]
Having two ways to access a thing is bad - it will confuse users expecting one and getting the other. This rule is to attempt to enforce that there is only one way your thing is exported.

**Comment by DominicTobias** [comment]
Thanks make sense, I've change it to just be the default export
