### ISSUE TITLE
Bug: Multiple packageDirs in no-extraneous-dependencies

### ISSUE THREAD

**Issue by aravindet** [benmosher/eslint-plugin-import#1175]
According to the docs, packageDirs accepts an array of paths, and (presumably) the package.json's found at all the paths have some effect.

In the current implementation, only the last element in the array is used.

This is because [`Object.assign()` is used](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L45) to merge the dependencies found in each file. As `Object.assign()` performs a shallow merge, and the [extractDepFields function](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L15-L22) adds default empty objects for fields that are not defined in `package.json`, every field ends up being overridden in each iteration.

I suggest that a deep merge be performed here instead of `Object.assign`.

**Comment by ljharb** [comment]
You're right that this logic is incorrect. It'd be great to get a failing test :-)

**Comment by pzhine** [comment]
@aravindet @ljharb Already fixed this in a PR, with a test that fails for the current version.
@benmosher Can you review #1176 and merge if it looks good?
