### ISSUE TITLE
import/no-sibling-import new rule ? Or import/no-restricted-paths

### ISSUE THREAD

**Issue by SebT** [benmosher/eslint-plugin-import#1179]
Greetings,

I'm having a hard time trying to prevent imports between sibling folders in my app. I think the use case is pretty common but I can't seem to make it work with `import/no-restricted-paths`.

My project structure :
```
src/
  app/
    moduleA/
    moduleB/
    moduleC/
  components/
  other/
```

I just want to prevent modules in `src/app` to import each other, but they should still be able to import from any other folder than `src/app`.

I tried to enforce this with `{ "zones": [ { "target": "./src/app/*", "from": "./src/app/*" } ] }`, but this prevents ANY import. So files under the same module can't even import each other.

Am I using the rule wrong or do we need a new one?

**Comment by ljharb** [comment]
I think you want #1154.

**Comment by SebT** [comment]
That's it, thanks. I'll thumb it up
