### ISSUE TITLE
[Suggestion] Refactor to monorepo

### ISSUE THREAD

**Issue by vikr01** [benmosher/eslint-plugin-import#1221]
[`yarn` workspaces]:https://yarnpkg.com/lang/en/docs/workspaces
[`lerna`]:https://github.com/lerna/lerna

Seems this repo still does manual linking (or `linklocal`/`file:<path>` installs) because it was made a while ago. With tools like [`yarn` workspaces] (and/or [`lerna`]), this repo could be refactored to make this process easier.

Somewhat of a proposed structure:
```diff
.
├── docs
+│   ├── resolvers.md
│   └── rules
-├── memo-parser
├── package.json
+├── packages
+│   ├── eslint-import-resolver-node
+│   ├── eslint-import-resolver-webpack
+│   ├── eslint-module-utils
+│   ├── eslint-plugin-import
+│   └── memo-parser
-├── resolvers
-│   ├── README.md
-│   ├── node
-│   └── webpack
-├── src
├── tests
-├── utils
+└── yarn.lock
```

If it's welcome, I can submit a PR to switch to [`yarn` workspaces]. Note that developing would require `yarn@>=1`.

**Comment by ljharb** [comment]
I’m very against using yarn, and Lerna doesn’t work well (we use it in enzyme).

**Comment by vikr01** [comment]
@ljharb Do you have any alternatives in mind? Agree on `lerna` not working well.

**Comment by ljharb** [comment]
The status quo is a great alternative.

**Comment by vikr01** [comment]
@ljharb Meant alternative tools, just in general for any monorepo.

Maybe I should have given a bit more context as to why I feel this is better:

- Linting is a bit confusing right now, some files use `var`, others `let`/`const`, and some mixing the two. `babel` is used in some areas but isn't in others (I think it's run on `tests` only?). `eslint` seems to only be run on the `src` directory.
- It's not easily clear that there are other packages in this repo on first glance. It might be confusing seeing no references to `../moduleVisitor` but seeing `eslint-module-utils/`.
- We can test on multiple `eslint` versions without using environment variables.

Just my opinions, if it's not welcome I understand.

**Comment by ljharb** [comment]
It's only desirable to test one at a time, so you can do it in parallel for CI. enzyme only uses karma for a set of tests (that have been failing for years; karma is incredibly unreliable) - it uses node for its actual tests.
