### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by dariagrudzien** [benmosher/eslint-plugin-import#1225]
@benmosher @ljharb @jfmengels  Hi guys, thank you for this package. Would you mind adding the license file to the npm packages:

- eslint-module-utils@2.2.0 and latest,
- eslint-import-resolver-node@0.3.2 and latest

Without it we're not really able to use them, because it makes the npm package a distribution of proprietary code.

Many thanks.

**Comment by ljharb** [comment]
The license file applies to the whole repo, and https://github.com/benmosher/eslint-plugin-import/blob/master/utils/package.json#L22 and https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/package.json#L25 declare MIT such that no court would interpret the license to be anything else.

That said, it certainly seems fine to add the files (they’d only show up in the next version, of course, files can’t ever be added to already-published versions).

**Comment by patricksmms** [comment]
@ljharb, the license file was not included in the packages on the latest releases, even though its on the repos. The packages were probably published with an old version of npm that didn't include it yet unless whitelisted on the files array of package.json.

**Comment by ljharb** [comment]
There’s only one license file in the repo, at the root - these subpackages don’t have one.

(We should stop using the files array anyways, it’s dangerous - but i don’t think it’s related to this issue)

**Comment by patricksmms** [comment]
Oops, I just had a quick glimpse at the repo, didn't notice it's a mono-repo., disregard what I said. And I also agree with the files array question.

**Comment by ljharb** [comment]
Seems reasonable to do it on their next release, but license file or not, there’s precisely zero chance any software in this repo could be interpreted as anything but MIT, so there’s no rush.

**Comment by soryy708** [comment]
[eslint-module-utils](https://www.npmjs.com/package/eslint-module-utils)
and
[https://www.npmjs.com/package/eslint-import-resolver-node](eslint-import-resolver-node)
both have `"license": "MIT"` in their `package.json`
and they're all in this repository, which already has a [LICENSE file](https://github.com/benmosher/eslint-plugin-import/blob/master/LICENSE).

Can this be closed?

**Comment by opichals** [comment]
@soryy708 Not really the license file is required (see this https://github.com/babel/babel/pull/7308#issuecomment-367615152 for more details)
