### ISSUE TITLE
Cannot parse @deprecated JSDoc on file with line ending \r\n

### ISSUE THREAD

**Issue by ljqx** [benmosher/eslint-plugin-import#1233]
The code in `ExportMap` explicitly requires the line ending to be `\n`, but it's not always true. On Windows, we have default line ending `\r\n`.
 https://github.com/benmosher/eslint-plugin-import/blob/798eed7e559adab2eac07bf1b3e3518d4b7a4296/src/ExportMap.js#L233

I can send fix for this.

**Comment by ljharb** [comment]
Thanks, that'd be great.
