### ISSUE TITLE
Add extensions order support for import/order

### ISSUE THREAD

**Issue by atassis** [benmosher/eslint-plugin-import#1239]
It would be nice to order imports based on their extension. For our case, we want to leave all css modules imported at the end of the imports list
```import React from 'react';
import styles from '../styles.scss';
import CustomModule from './custom-module';```
Here it is more preferable to warn us move `styles` after `CustomModule`

**Comment by fuko-fabio** [comment]
Would be perfect if we could add this feature. We have the same case with `css` files.

**Comment by rjhilgefort** [comment]
Would love to see this as well.

**Comment by Glinkis** [comment]
I  thought this could be accomplished with the `pathGroups` option, like this:
```json
"pathGroups": [
  {
    "pattern": "**/*.scss",
    "group": "index",
    "position": "after"
  }
]
```
But I can't seem to get this to work.

**Comment by Glinkis** [comment]
After some experimenting, this seems to do the trick:
```json
"pathGroups": [
  {
    "pattern": "./*.scss",
    "group": "sibling",
    "position": "after"
  }
]
```

**Comment by zero-t4** [comment]
> I thought this could be accomplished with the `pathGroups` option, like this:
> 
> ```json
> "pathGroups": [
>   {
>     "pattern": "**/*.scss",
>     "group": "index",
>     "position": "after"
>   }
> ]
> ```
> 
> But I can't seem to get this to work.

Im also stuck with it.
@ljharb Why this case does not work?

**Comment by constgen** [comment]
`"**/*.scss"` pattern will not match paths started with  `./` and `../`. It only matches paths like `@/styles/index.css` and `styles/index.css`. To make it work you have to use `"{.,..}/**/*.css"` pattern. For example my config looks like 

```json
"pathGroups": [
  {
    "pattern": "**/*.+(css|sass|less|scss|pcss|styl)",
    "patternOptions": {"dot": true, "nocomment": true},
    "group": "unknown",
    "position": "after"
  },
  {
    "pattern": "{.,..}/**/*.+(css|sass|less|scss|pcss|styl)",
    "patternOptions": {"dot": true, "nocomment": true},
    "group": "unknown",
    "position": "after"
  }
],
```
Used 2 patterns to cover all cases

**Comment by itayganor** [comment]
> `"**/*.scss"` pattern will not match paths started with `./` and `../`. It only matches paths like `@/styles/index.css` and `styles/index.css`. To make it work you have to use `"{.,..}/**/*.css"` pattern. For example my config looks like
> 
> ```json
> "pathGroups": [
>   {
>     "pattern": "**/*.+(css|sass|less|scss|pcss|styl)",
>     "patternOptions": {"dot": true, "nocomment": true},
>     "group": "unknown",
>     "position": "after"
>   },
>   {
>     "pattern": "{.,..}/**/*.+(css|sass|less|scss|pcss|styl)",
>     "patternOptions": {"dot": true, "nocomment": true},
>     "group": "unknown",
>     "position": "after"
>   }
> ],
> ```
> 
> Used 2 patterns to cover all cases

Nice, I've been using the following pattern lately:

```{.,..}/**/*.{less,css,scss}```

But I have some imports that start with `../../` and this glob won't match :( 
Do you have any idea how to match **everything** with a file extension?

This is frustrating

**Comment by ljharb** [comment]
`**/*.*`?

**Comment by constgen** [comment]
Unfortunately this is a known problem and the solution is ugly - list all possible "up" paths (1,2,3,4,5... levels up)
https://github.com/atomspace/atomspace-eslint/blob/master/src/configs/import.config.json#L104
And keep finger crossed that the project structure will be not very deep

**Comment by MoradiDavijani** [comment]
To solve this, you can set [`matchBase`](https://github.com/isaacs/minimatch#matchbase) property in `patternOptions`.

```js
{
  pathGroups: [
  {
    pattern: '*.scss',
    group: 'index',
    patternOptions: { matchBase: true },
    position: 'after'
  ]
}
```

**Comment by itayganor** [comment]
@MoradiDavijani This is amazing. You made my day ❤️

**Comment by yuri-sakharov** [comment]
Doesn't work for me
```
"import/order": ["error", {
            "groups": ["external", ["internal", "parent", "sibling", "index"], "unknown"],
            "pathGroups": [
                {
                    "pattern": "*.scss",
                    "patternOptions": { "matchBase": true },
                    "group": "unknown",
                    "position": "after"
                }
            ],
            "pathGroupsExcludedImportTypes": [],
            "newlines-between": "always"
        }],
```

expected `.scss` in bottom but result is still same.
```
import './AvatarsGroup.scss';
import { Avatar } from 'components/Avatar';
import { PlusIndicator } from 'components/PlusIndicator';
```
Any ideas?

**Comment by ljharb** [comment]
@yuri-sakharov you may also need to set up the import/extensions settings as described in the readme.

**Comment by constgen** [comment]
@yuri-sakharov this is expected to work so. You faced a completely different issue. There are already several opened tickets for this https://github.com/benmosher/eslint-plugin-import/issues?q=is%3Aissue+is%3Aopen+side+effect+label%3A%22import%2Fexport+ordering%22+

**Comment by nickvirdenlegalshield** [comment]
@yuri-sakharov I was having trouble just like you with other solutions, such as with solutions by @constgen and @MoradiDavijani, which were helpful in solving the issue.

After some toying around with it, I figured out that I had to set `warnOnUnassignedImports` to `true`.

Once I did that, it started picking up on the unassigned imports (e.g. `import './foo.scss';`, but it would put them after `sibling` instead at the very end of the import order like I wanted - after `object`.

Here's my configuration:

**Eslint version:** 7.31.0
**eslint-plugin-import version:** 2.24.0

### Import order
```jsx
import './foo.scss';
import barModule from '../../barModule';
import bazModule from './bazModule';
```

### ESLint configuration
```js
'import/order': [
    // other config here
    'pathGroups': [
      {
        pattern: '{.,..}/*\.scss', // same directory only
        // pattern: '{.,..}/**/*\.scss' // same & outside directories (e.g. import '../foo/foo.scss')
        group: 'object',
        position: 'after'
      }
    ],
    'warnOnUnassignedImports': true
  }
]
```

**Comment by debjyoti-pandit** [comment]
@nickvirdenlegalshield  getting the same issue.
Did you guys have the solution to why it is importing before the nearest sibling?

**Comment by andrmoel** [comment]
@nickvirdenlegalshield unfortunately `warnOnUnassignedImports` does not work with autofix.

**Comment by 20manas** [comment]
In summary, to match one or more extensions, including unassigned imports:
```js
'pathGroups': [
  {
    pattern: '*.{css,scss}',
    patternOptions: {matchBase: true},
    group: 'unknown',
    position: 'after',
  },
],
// no auto-fix
'warnOnUnassignedImports': true,
```

**Comment by hackel** [comment]
All the solutions given here seem to be for "internal" imports.  What about importing CSS files from external imports?  I would like to import external JS first, but import external CSS last.  Is this currently impossible?
