### ISSUE TITLE
Release with new merged features

### ISSUE THREAD

**Issue by fsmaia** [benmosher/eslint-plugin-import#1249]
Hi!

Just found out there are unreleased merged features, including some new rules.

Is there any plan or help wanted to make a new release?

Thx!

**Comment by afenton90** [comment]
Is there anything the community could do to free up some time for the maintainers? Whether it be in this project or others to get these new features and bug fixes out. @benmosher

**Comment by benmosher** [comment]
working on it in #1254 right now

**Comment by afenton90** [comment]
Thanks @benmosher
