### ISSUE TITLE
Document "env" option for eslint-import-resolver-webpack

### ISSUE THREAD

**Issue by linvain** [benmosher/eslint-plugin-import#1258]
I use env variable in my webpack config:
```
module.exports = function (env) {
    ...
}
```
This leads to a hell of errors:
```
Resolve error: Cannot read property 'production' of undefined
```
The issue can be resolved by adding env option to resolver settings:
```
  "settings": {
    "import/resolver": {
      "webpack": {
        "env": "development"
      }
    }
  }
```
But this is not documented.
P.S.: Thanks @VladimirPal (#1043)

**Comment by brycekunkel** [comment]
@linvain / @ljharb , I know this is closed, but before I file a new issue, is there a way to acknowledge that environment variables exist, but not set their value? Maybe I'm misunderstanding how to use that config. My complex webpack setup allows the user to pass in additional options on the command line, but it throws all kinds of errors as were mentioned in the beginning of this issue.

**Comment by ljharb** [comment]
I think that you might need to have a JS-based config that *reads* those command-line values :-/
