### ISSUE TITLE
error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by chandu89** [benmosher/eslint-plugin-import#1263]
When I am adding Webpack merge, I am getting error.
I have  created separate webpack config for devlopment and prod.
> error  'webpack-merge' should be listed in the project's dependencies. Run 'npm i -S webpack-merge' to add it  import/no-extraneous-dependencies

Can Anyone help me on this?

**Comment by ljharb** [comment]
Is it in your package.json?

**Comment by Fried-Chicken** [comment]
You can add a glob to your eslint config file to fix this issue.

```
"rules": {
    "import/no-extraneous-dependencies": [
      "error", {
        "devDependencies": [
          "**/webpack.*.js"
        ]
      }
    ],
}
```

**Comment by nyngwang** [comment]
@Fried-Chicken But why? Sorry for continuing the old thread. I'm learning this stuff.

**Comment by ljharb** [comment]
@nyngwang because the rule, by default, assumes everything's for production. If you want that file pattern to be eligible for having dev deps, you have to tell the rule where it is.

**Comment by nyngwang** [comment]
@ljharb Thanks, but I dropped off the use of webpack merge instead, lol.
