### ISSUE TITLE
Error while installing the package

### ISSUE THREAD

**Issue by tmanzi** [benmosher/eslint-plugin-import#1264]
It's impossible to install the package from npm, appearly the problem comes from the eslint-module-utils version.

npm install eslint-plugin-import

npm ERR! code ETARGET
npm ERR! notarget No matching version found for eslint-module-utils@^2.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'eslint-plugin-import'
npm ERR! notarget

**Comment by ljharb** [comment]
Looks like it exists: https://unpkg.com/eslint-module-utils@2.3.0/

Are you using an internal npm repo?
