### ISSUE TITLE
Error `Cannot find module 'eslint/lib/util/source-code'` in monorepo setup with 2.15.0

### ISSUE THREAD

**Issue by egidijusj** [benmosher/eslint-plugin-import#1265]
I have a mono-repo with all dependencies hoisted to root `node_modules` except for `eslint` (it's due to custom config and plugin within mono-repo which eslint cannot resolve otherwise). The repo follows this structure:
```
./project-root
--node_modules
----eslint-plugin-import
--eslint-config-custom
--eslint-plugin-custom
--some-package
----node_modules
------eslint
```

With 2.15.0 version of `eslint-plugin-import` linting stopped working with following error: `Cannot find module 'eslint/lib/util/source-code'`
With 2.14.0 it works just fine.

Here is a script that setups a minimal scenario to reproduce:
```
VERSION="2.15.0"

# create temp dir to play around with the issue
mkdir /tmp/some-lerna-monorepo-$VERSION && cd /tmp/some-lerna-monorepo-$VERSION

# setup top-level package
npm init -y
npm i --save-dev eslint-plugin-import@$VERSION \
                 eslint-config-standard@latest \
                 eslint-plugin-mocha@latest \
                 eslint-plugin-node@latest \
                 eslint-plugin-promise@latest \
                 eslint-plugin-standard@latest

# setup internal package
mkdir /tmp/some-lerna-monorepo-$VERSION/internal-pkg && cd /tmp/some-lerna-monorepo-$VERSION/internal-pkg
npm init -y
npm i --save-dev eslint@latest

# add eslint config
echo '{"parserOptions":{"ecmaVersion": 2017, "sourceType": "module"}, "extends": ["standard"]}' >> .eslintrc

# add a file to lint against
echo 'foo(\n' >> index.js
npx eslint index.js

```
If you change `VERSION="2.15.0"` to `VERSION="2.14.0"` at the top of the script and run again, it works just fine.

**Comment by ljharb** [comment]
https://unpkg.com/eslint@5.12.1/lib/util/source-code.js is definitely there - have you tried updating eslint?

**Comment by egidijusj** [comment]
Provided reproduction script does install latest version of eslint:
```
# setup internal package
mkdir /tmp/some-lerna-monorepo-$VERSION/internal-pkg && cd /tmp/some-lerna-monorepo-$VERSION/internal-pkg
npm init -y
npm i --save-dev eslint@latest
```

**Comment by ljharb** [comment]
wait - why is `eslint` not hoisted normally?

**Comment by egidijusj** [comment]
> wait - why is `eslint` not hoisted normally?

I've already pointed it out in first comment:
> it's due to custom config and plugin within mono-repo which eslint cannot resolve otherwise

**Comment by egidijusj** [comment]
> right, but shouldn't that be hoisted too?

It cannot be hoisted, custom plugin and config source code is part of the mono-repo internal packages. 

> it's pretty critical that all eslint plugins share the same version of eslint.

Same version or same instance? 
Same version across mono-repo is guaruanteed, because all internal packages have synchronised versions of common dev dependencies.
Same instance IMO would only be relevant if I were to lint multiple packages within single process (say, from a script in root package.json), which is not relevant for my use-case - although it might be the case for other people though. Then again, this setup did work a version ago, was it a coincidence?

**Comment by ljharb** [comment]
Sure, but the custom plugin and config should be hoisted too.

Same instance. It's always relevant in any plugin system - there must only be one copy of eslint in the entire repo, fjll stop.

**Comment by egidijusj** [comment]
There was never an issue with multiple instances because I either:
- run lint on internal package. Eslint is loaded from `./node_modules`, plugins are loaded from `../node_modules`
- run lint on all repo in parallel processes, which is the same as point above

What I get from your argument is that it is strictly necessary for **`eslint` and plugins/configs to be in the same folder** and not that **there must be a single instance of `eslint` in memory**. Do I get it right?

**Comment by ljharb** [comment]
Yes, that is a requirement of eslint itself.

**Comment by ljharb** [comment]
Unfortunately you’re running the risk of the same thing happening with any eslint dep change;  i’d recommend fixing the underlying problem.

**Comment by egidijusj** [comment]
IMO underlying problem is that eslint ecosystem enforces a specific folder structure which does not make sense given there is npm package resolution mechanism. We're talking workarounds here, not solutions.

**Comment by ljharb** [comment]
That's how everything in the npm ecosystem works; all peer deps must be hoisted to the top always, *due* to how node - not npm - resolves paths.

**Comment by gurrrung** [comment]
For people who are gonna come here in future, just remove node_modules folder and do `npm install` again.

**Comment by aditodkar** [comment]
@gurrrung  Removed node_modules and installed again but still same error in browser 
``` 
./src/index.js
Error: Cannot find module 'eslint/lib/util/source-code'
Referenced from:
```

**Comment by ljharb** [comment]
Be sure you have the latest version of the plugin.

**Comment by aditodkar** [comment]
I have created react app using create-react-app after that I want to install eslint in my project. So I did `eslint --init` after that when I do `npm start` it gives error in terminal see screenshot below: 
![Screenshot_11](https://user-images.githubusercontent.com/16613832/61169832-519a3100-a57f-11e9-8028-21375fd5acce.png)
After following steps mentioned in above screenshot it still shows same error. So I have created .env file and then added `SKIP_PREFLIGHT_CHECK=true` inside .env file but still it is showing this error in browser see screenshot below:

![Screenshot_10](https://user-images.githubusercontent.com/16613832/61169849-8d34fb00-a57f-11e9-9151-b705143e1f08.png)

**Comment by aditodkar** [comment]
@ljharb When I do `eslint --init` I get error see screenshot below: 

![Screenshot_2](https://user-images.githubusercontent.com/16613832/61170491-7c888300-a587-11e9-9651-e44ee369a3d4.png)

**Comment by ljharb** [comment]
CRA requires eslint 5; you’ll have to downgrade eslint.
