### ISSUE TITLE
v2.15.0 is leaking memory

### ISSUE THREAD

**Issue by asapach** [benmosher/eslint-plugin-import#1266]
After updating to v2.15.0 eslint started running out of memory on our fairly large project.
I was able to reproduce something similar when running the plugin against a dozen copies of [lodash-es](https://github.com/lodash/lodash/tree/es). I can create a repro case, but it's rather trivial.
One rule is enough to see the difference between v2.14.0 and v2.15.0:
```yml
plugins:
  - import

rules:
  import/default: 2
```

This seems to be caused by 05c3935048577bd7b025d6b833d8503807f02189. I've run some memory profiles, but I can't pinpoint the exact source of the leak other than that it seems to originate in [ExportMap.js](https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js). It's possible that the leak was always there, but extra parsing and memory allocations made it more evident.

**Comment by benmosher** [comment]
Thanks for identifying the commit! This is not the first time `ExportMap` has had a major memory leak after a minor change.

Memory leaks are always my top priority after a release. I'll try to take a look at lunch today.

**Comment by sergei-startsev** [comment]
@benmosher you might also want to take a look at PR #1271

**Comment by benmosher** [comment]
Sure, but the SourceCode instances shouldn’t be retained at all to begin with. And I don’t think they cost much CPU-wise.

**Comment by benmosher** [comment]
Published as 2.16.0. Thanks so much for both of your help on this!
