### ISSUE TITLE
[Regression] eslint-module-utils@2.3.0 causes invalid "Resolve error: webpack with invalid interface loaded as resolver"

### ISSUE THREAD

**Issue by ronjouch** [benmosher/eslint-plugin-import#1269]
See minimal reproduction case with script and pre-run output at [ronjouch/repro-eslint-bug-cra](https://github.com/ronjouch/repro-eslint-bug-cra) .

As demonstrated by the `demo` script, reverting to 2.2.0 inside eslint-plugin-import (`cd node_modules/eslint-plugin-import && npm install eslint-module-utils@2.2.0`) fixes the issue.

Reproduced and fixed on many machines (node 10.15.0 & npm 6.7.0 on Linux, node 8 on macOS, and in a CI Docker). I'm available for more debug info if necessary.

**Comment by benmosher** [comment]
@ronjouch what version of `eslint-import-resolver-webpack` are you using? I don't see it referenced in either the `package-lock.json` or the `package.json`.

**Comment by ronjouch** [comment]
> what version of `eslint-import-resolver-webpack` are you using? I don't see it referenced in either the `package-lock.json` or the `package.json`.

@benmosher thanks for the fast reply 👍. Uh, from what I understand, I'm not using `eslint-import-resolver-webpack`, neither in the minimal scenario, nor in the production web app I extracted it from. 

Here's an `npm ls | grep eslint` for the production web app:

```
├─┬ UNMET PEER DEPENDENCY babel-eslint@8.2.6
│ ├─┬ eslint-scope@3.7.1
│ └── eslint-visitor-keys@1.0.0
├─┬ eslint@4.19.1
│ ├── eslint-scope@3.7.1 deduped
│ ├── eslint-visitor-keys@1.0.0 deduped
├─┬ eslint-config-airbnb-base@13.1.0
│ ├── eslint-restricted-globals@0.1.1
├── eslint-config-react-app@2.1.0
├─┬ eslint-loader@1.9.0
├─┬ eslint-plugin-flowtype@2.39.1
├─┬ eslint-plugin-import@2.15.0
│ ├─┬ eslint-import-resolver-node@0.3.2
│ ├─┬ eslint-module-utils@2.2.0 invalid
├─┬ eslint-plugin-jsx-a11y@5.1.1
├─┬ eslint-plugin-react@7.4.0
npm ERR! peer dep missing: babel-eslint@^7.2.3, required by eslint-config-react-app@2.1.0
npm ERR! invalid: eslint-module-utils@2.2.0 /home/ronanj/work/console/client/node_modules/eslint-plugin-import/node_modules/eslint-module-utils
```

Does that make sense to not depend on `eslint-import-resolver-webpack`? Did we miss migration steps at some point? Should I add it as dependency? If so, is new configuration needed?

*Note: all that stuff is pretty obscure to me, so sorry for the noise. I just happen to be the engineer at $WORK most comfortable narrowing down on the broken package to make our build pass again. My point of view is simple: 2.3.0 broke the build and pinning 2.2.0 fixes it. Is this a regression, or was it already ineffective/useless and it just started being vocal about it?*

**Comment by benmosher** [comment]
Sounds like it was silently failing over to the node resolver before. Makes sense it would look like a regression 🙂

If you don’t have the webpack resolver installed, you have two solid options:

- remove this block from your package.json:
```
    "settings": {
      "import/resolver": "webpack"
    },
```
Or,
- install `eslint-import-resolver-webpack` and see if that works better. 

The former is fewer dependencies so I’d try that first, but up to you. Is a little strange you’d end up with the config pointing to it without it in your dependencies.

**Comment by ronjouch** [comment]
@benmosher makes sense! Removing the `settings` block worked 🙂 (and happily started complaining about errors accumulated over the last months 😄).

> Is a little strange you’d end up with the config pointing to it without it in your dependencies.

Yup, traced to a bad initial commit copy-pastaed / badly adjusted from an example.

Thanks again for the help! Closing :tada:

**Comment by econne01** [comment]
I had the same issue in a project using `eslint-plugin-import` that started failing lint checks as of Jan 22nd, 2019.
I believe it is related to the upgrade of `eslint-module-utils` to version `2.3.0`, specifically this [change to import eslint resolver interfaces](https://github.com/benmosher/eslint-plugin-import/commit/825234402a3dbe58138781c2f44c3933c59babfe#diff-572fb0baf4daf70044716be9bb39388d). If I can read the [history](https://github.com/benmosher/eslint-plugin-import/commits/master/utils/resolve.js) correctly it looks like this change was merged in July but released with a new version last week.

I don't know how to resolve this as a PR, but I think it would help to patch version `2.13.0` like in this [PR#1274](https://github.com/benmosher/eslint-plugin-import/pull/1274)

**Comment by louieaa** [comment]
Resolve error: webpack with invalid interface loaded as resolver 

<img width="972" alt="WX20190325-094911@2x" src="https://user-images.githubusercontent.com/42113246/54890365-05e64d80-4ee4-11e9-97de-fae369435d24.png">

**Comment by benmosher** [comment]
@econne01 / @louieaa: see resolution above: https://github.com/benmosher/eslint-plugin-import/issues/1269#issuecomment-457552829

If you have a properly configured `webpack` resolver`, please open a new issue.
