### ISSUE TITLE
import/no-unresolved does not support multiple nested package.json

### ISSUE THREAD

**Issue by eightyfive** [benmosher/eslint-plugin-import#1272]
Folder / file structure:
```
// Project root
- .eslintrc
- package.json // Package 1
- src/
---- package.json // Package 2
---- components/
--------------- Foo.jsx
```

Content of `Package 2`:
```
{
  "name": "src"
}
```

This enables me to import `Foo.jsx` like so (from anywhere):
```js
import Foo from 'src/components/Foo';
```

This *node resolution behaviour is standard* as far as I know.

`eslint-plugin-import` is not able to resolve my files:
```
  5:23  error  Unable to resolve path to module 'src/components/Foo'  import/no-unresolved
```

**Comment by benmosher** [comment]
can you link docs for this behavior? I'm not aware of this. AFAIK you'd have to use something like `linklocal` to install your `src` package into `node_modules` (at which point this would work).

**Comment by eightyfive** [comment]
Hi,

I believe this is the official doc of that feature:
https://nodejs.org/api/modules.html#modules_folders_as_modules

But here are also famous comments mentioning it:

https://github.com/facebook/react-native/issues/3099#issuecomment-221815006

https://glebbahmutov.com/blog/subfolders-as-dependencies/

**Comment by ljharb** [comment]
This only works inside node_modules, though.

**Comment by ljharb** [comment]
In other words, if the path doesn’t start with dot or slash, then it’s always and only referring to something in node_modules.

**Comment by eightyfive** [comment]
I threw a small Node project on my laptop and @ljharb is right, it does *not* seem to work outside of `node_modules`.

The fact that it works when bundling a RN app, must be RN specific then.

I'll find an alternative, thanks for your help.

**Comment by ljharb** [comment]
If you put it in package.json, then it should Just Work with node and this plugin (separately from my personal advice not to do anything like this, and to just accept the `../` as a normal consequence of large and/or nested repos)

**Comment by eightyfive** [comment]
Ok thanks.

A better alternative (to my previous solution) is to use [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/):
```
// ./package.json (main)
{
  "private": true,
  "workspaces": ["src"]
}
```
_Note_: `./src/package.json` remains unchanged, see https://github.com/benmosher/eslint-plugin-import/issues/1272#issue-403798133.

This does *not* require to install/re-install the local `src` folder after every change.

And it works with `eslint-plugin-import` plugin.

More details [here (Stackoverflow)](https://stackoverflow.com/questions/10860244/how-to-make-node-js-require-absolute-instead-of-relative#answer-53179026).

**Comment by benmosher** [comment]
Thanks for the extra details @eightyfive!
