### ISSUE TITLE
import/named requires 'typescript-eslint-parser'

### ISSUE THREAD

**Issue by lednhatkhanh** [benmosher/eslint-plugin-import#1285]
This is my `.eslintrc` config:

```json
{
  "parser": "@typescript-eslint/parser",
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
  "extends": [
    "airbnb",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/typescript",
    "plugin:prettier/recommended",
    "prettier/@typescript-eslint"
  ],
  "plugins": ["react-hooks", "emotion"],
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "emotion/jsx-import": 0,
    "react/react-in-jsx-scope": 0,
    "react/jsx-filename-extension": [1, { "extensions": [".tsx"] }],
    "import/prefer-default-export": 0
  }
}
```

I'm importing like this:

```typescript
import { Button } from "../src/components/button";
```

The error:

```
Parse errors in imported module '../src/components/button': Cannot find module 'typescript-eslint-parser' (undefined:undefined)eslint(import/named)
```

**Comment by ljharb** [comment]
so for one, i think the parser needs to be `@typescript/eslint-parser`, doesn't it?

**Comment by lednhatkhanh** [comment]
@ljharb Yeah, `@typescript-eslint/parser` is the new one that replaces `typescript-eslint-parser`.

**Comment by ljharb** [comment]
hmm, the implication is that one of your plugins or shared configs is still pointing to the old typescript parser.

**Comment by lednhatkhanh** [comment]
So I updated my config to this:

```json
{
  "parser": "@typescript-eslint/parser",
  "settings": {
    "import/resolver": { "typescript": {} }
  },
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:import/errors",
    "plugin:import/typescript"
  ],
  "plugins": ["import"]
}
```

And the problem is still there.

**Comment by lednhatkhanh** [comment]
So I saw this pr #1283 and it fixes the problem, but requires me to install `typescript-eslint-parser` and `eslint-import-resolver-typescript`.

**Comment by billyjanitsch** [comment]
This was already fixed in bdc05aa1d029b70125ae415e5ca5dca22250858b. (Note the change to `config/typescript.js`.) eslint-plugin-import just needs a new release.

**Comment by kachkaev** [comment]
@benmosher it'd be awesome if you could cut a new release! 🙏 Can't wait to use `eslint-plugin-import` with `@typescript-eslint`! 🤩

**Comment by MatiasOlivera** [comment]
Until there is a new release, a workaround that works for me is:

```js
// .eslintrc.js

var jsExtensions = ['.js', '.jsx'];
var tsExtensions = ['.ts', '.tsx'];
var allExtensions = jsExtensions.concat(tsExtensions);

module.exports = {
  plugins: ['import'],
  settings: {
    'import/extensions': allExtensions,
    'import/parsers': {
      '@typescript-eslint/parser': tsExtensions
    },
    'import/resolver': {
      'node': {
        'extensions': allExtensions
      }
    }
  }

}
```

It's necessary not to extend the configuration from  `"plugin:import/typescript"`.

@lednhatkhanh There is no need to install `typescript-eslint-parser` and `eslint-import-resolver-typescript`

**Comment by gabrielizaias** [comment]
For anyone finding this ticket, this has not been released yet. @MatiasOlivera solution still works.

@ljharb Is there a big picture here that we are missing? If so, would it make sense to keep this ticket open until a new release is cut? At the moment the closed status feels a bit misleading. Thanks!

**Comment by ljharb** [comment]
@gabrielizaias no, issues (not tickets) are pretty universally closed when fixes are merged, not when they’re released (an unrelated action)

**Comment by kachkaev** [comment]
Can't wait for a release with this fix to migrate more projects from tslint to eslint 🙌 🙏  @MatiasOlivera, thanks for the workaround!

**Comment by nikolalukovic** [comment]
Any update on when is this going to get released?

**Comment by karbon62** [comment]
> Until there is a new release, a workaround that works for me is:
> 
> ```js
> // .eslintrc.js
> 
> var jsExtensions = ['.js', '.jsx'];
> var tsExtensions = ['.ts', '.tsx'];
> var allExtensions = jsExtensions.concat(tsExtensions);
> 
> module.exports = {
>   plugins: ['import'],
>   settings: {
>     'import/extensions': allExtensions,
>     'import/parsers': {
>       '@typescript-eslint/parser': tsExtensions
>     },
>     'import/resolver': {
>       'node': {
>         'extensions': allExtensions
>       }
>     }
>   }
> 
> }
> ```
> 
> It's necessary not to extend the configuration from `"plugin:import/typescript"`.
> 
> @lednhatkhanh There is no need to install `typescript-eslint-parser` and `eslint-import-resolver-typescript`
