### ISSUE TITLE
BUG? Typescript export namespace nested `Multiple exports of name`

### ISSUE THREAD

**Issue by NewFuture** [benmosher/eslint-plugin-import#1300]
`import/export`
```ts
export namespace API {
    //Multiple exports of name 'User' 👇
    export namespace User {
        export const A = 0;
    }

    export namespace M {
        //Multiple exports of name 'User' 👇
        export const User = {};
    }
}
```
But they are not the same `User`

**Comment by ljharb** [comment]
I'm not familiar with how namespaces work (since that's not a concept that exists in javascript) but clearly it seems like one is a sibling of M, and one is nested under M.

Do you think the rule should understand namespaces, or do you think it should ignore them?

**Comment by NewFuture** [comment]
it will be translated to 
```
exports.API = {
  User:{
    A:0
  },
  M:{
    User:{}
  }
}
```

* the first User's full name is `API.User`
* the second  User's full name is `API.M.User`

If namespaces can be parsed as above it will be resolved.

**Comment by ljharb** [comment]
In that case, there's only one export - API - and all the others are just object properties.

So, it seems like this plugin should ignore everything but the top-level one.

**Comment by NewFuture** [comment]
yes, it's ok.

**Comment by conorcussell** [comment]
@ljharb I'm experiencing this and happy to try and submit a PR to fix it. I'll start poking around the codebase anyway, but if you had any suggestions of what would need to change to enable this then that would help. Thanks!

**Comment by conorcussell** [comment]
I guess we could add a check to [`addNamed`](https://github.com/benmosher/eslint-plugin-import/blob/206d67653c0d6cd087a51233f81d911fd347ca8e/src/rules/export.js#L15) in the export rule. 

Would something like this be a terrible idea?

```javascript
function addNamed(name, node) {
  if (node.parent.type !== 'Program') return

  ... // rest of the code
}
```

**Comment by ljharb** [comment]
I'm not very knowledgeable on this part of the code; but it doesn't seem like skipping any top-level named export would be ideal :-)

**Comment by conorcussell** [comment]
@ljharb that example would do the opposite, but I'm sure it'll break something else instead. Was just hoping for some pointers of how this sort of thing would usually be approached. I'll see if I can take a proper look sometime in the next week 😀
