### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dantman** [benmosher/eslint-plugin-import#1309]
The last release was 2 months ago and a bunch of changes to the plugin have been made since then. In particular `typescript-eslint-parser` is obsolete and the fix for that in this plugin appears to have been fixed but not released for quite awhile.

**Comment by Asim13se** [comment]
@dantman you can use the new parser `@typescript-eslint/parser` using the current version like this:
```javascript
module.exports =  {
   settings: {
        'import/extensions': ['.js', '.jsx', '.ts', '.tsx', '.json'],
        'import/resolver': {
            'node': {
                'extensions': ['.js', '.jsx', '.ts', '.tsx', '.json'],
            },
        },
        'import/parsers': {
            '@typescript-eslint/parser': ['.ts', '.tsx'],
        },
    },
}
```

**Comment by ljharb** [comment]
v2.17.0 is released.
