### ISSUE TITLE
clean up!

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#1314]
Planning to merge as many open PRs as possible (with an emphasis on TS-related ones) and release this weekend. Maybe one release of what's pending and passing in `master` first.

I didn't realize there were folks migrating from tslint => ESLint. I assumed it was the opposite.

Also I'm really going to try to figure out a [robo-publish](https://medium.com/@schalkneethling/automate-package-releases-with-semantic-release-and-commitizen-d7d4c337f04f) strategy. it's gotten out of control that I am the bottleneck for new releases.

**Comment by ljharb** [comment]
tslint is deprecated; eslint is the only one TS users should be using :-)

I’m personally very opposed to autopublishing; would you be amenable to making a release checklist and giving me the publish bit? That way we can try out a higher bus factor before resorting to what imo is a very dangerous policy.

**Comment by benmosher** [comment]
That is fair, but I figure people can always roll back. More buggier versions >> never less buggy versions is the balance I'm thinking warrants striking.

BTW there is still this: https://github.com/benmosher/eslint-plugin-import/blob/master/RELEASE.md, IIRC it's still accurate.

Also, sad to report I didn't get a chance to dig in... 😭

> tslint is deprecated; eslint is the only one TS users should be using :-)

This is news to me, but consistent with the incoming issues for sure. Good to know. Will try to get on this and start supporting TS better. I am in this boat too now, we have started using TS (again) at work so I've already encountered at least one bug in the JS/TS interop that probably happens for pure-TS as well.

**Comment by benmosher** [comment]
also I think you have publish access but I'll look right now

**Comment by ljharb** [comment]
No, that should do it - I'll definitely be able to cut a release today then!

**Comment by ljharb** [comment]
v2.17.0 of the main package, and v0.11.1 of the webpack resolver, are published.

There's some appveyor tests failing on master (#1317), but otherwise it's clean for whatever's next.

**Comment by benmosher** [comment]
thanks so much!

**Comment by ljharb** [comment]
(update: appveyor tests are passing, v2.17.2 is out, and there's one super minor unreleased commit that could go in a v2.17.3)

Separately, once eslint v6 comes out, I'd love to see a last 2.x release that supports v2-v6, and then immediately switching to a 3.0 that drops support for eslint < 5 - there's a lot of code we can clean up, and having 2-5 so far has been super helpful for upgrading, but it's time.

**Comment by benmosher** [comment]
couldn't agree more, sounds like a plan 👍🏼
