### ISSUE TITLE
Do not report files containing `export {}` with `no-unused-modules`

### ISSUE THREAD

**Issue by ehmicky** [benmosher/eslint-plugin-import#1325]
The `missingExports` option of `no-unused-modules` is great to make sure we do not forget to export variables. 

However there are some cases where modules are only meant to introduce side-effects on global variables. This pattern is for example often used with `node -r somePackage/register`. In those cases, an empty `export {}` is perfect to declare that we are intentionally not exporting anything.

Should `missingExports: true` skip files when a `export {}` statement is present? This behavior could be either always there, or under a boolean option.

**Comment by ljharb** [comment]
In that case it should be excluded in the config - using the ignoreExporte option, which is intended for entry points like this.

**Comment by ehmicky** [comment]
It can be done with this option indeed. I was wondering whether that option should include main files bh default?

**Comment by ljharb** [comment]
I’m not sure it’s a good idea for a linter rule to encourage that convention, tbh.

The list can be as long as you like; especially if it can support globs (#1326) then i don’t think it’ll be too hard to manage that list.

**Comment by ehmicky** [comment]
I see what you mean that using files that only have side-effects should be discouraged.

On the other hand for files that do have side-effects, using `export {}` might be a good practice as it removes the ambiguity of whether the file is CommonJS or ESM (if the file does not import anything).

Also it depends on what `missingExports` purpose is:
  - if it's to prevent users from forgetting to `export`, then if an `export {}` is explicitly here, it should mean users haven't forgotten it.
  - but if the purpose is to prevent files which have side-effects instead of exporting something, then `export {}` is a bad thing.

Whichever you think is best works! I just wanted to bring it up in case you think it's a good enhancement. Thanks for the work on this feature!

**Comment by ljharb** [comment]
The purpose to me is to help you find what code you can safely delete.

**Comment by ehmicky** [comment]
From that perspective I am going to close this issue. Thanks for checking it!
