### ISSUE TITLE
Exclude package main files by default from `no-unused-modules`

### ISSUE THREAD

**Issue by ehmicky** [benmosher/eslint-plugin-import#1327]
`unusedExports: true` with the `no-unused-modules` rule should never report files that are exported as the main file (`main`, `browser` or `bin` fields in `package.json`). What do you think?

**Comment by ljharb** [comment]
That sounds like a good enhancement, no need for it to be behind an option, even.

**Comment by rfermann** [comment]
What package.json should be used for this purpose? 

- the package.json from the working directory,
- the package.json from the folder specified as `src` in the rule options (if existing) or
- the package.json closest to the file currently being linted (if existing and not the same as in the working directory)?

**Comment by ljharb** [comment]
For a given file, the closest package.json to it, that has a main, does not have private true, and points to it, marks it as used.

**Comment by ehmicky** [comment]
Thanks for implementing this @ljharb! :tada:

**Comment by ljharb** [comment]
Thank @rfermann :-)
