### ISSUE TITLE
allow 'conditional' import at first?

### ISSUE THREAD

**Issue by hibiyasleep** [benmosher/eslint-plugin-import#1329]
I personally groups my imports in usual order; npm module, components, local modules, and other.

```js
import { ... } from 'electron'
import { ... } from 'vuex'

import ... from '@/components/layout/...'
import ... from '@/components/...'

import ... from '@/lib/....js'
import { productName, version } from '@/../package.json'
```

so, the problem was, I need to modify this component for both of electron and *web*. `null-loader` not work here.

```js
const { ipcRenderer } = process.env.IS_WEB? {} : require('electron')
```

`import/first` throws me away since `electron` import was ordered at first line, but I want to keep my 'grouping' rules without turning it off.

May `import/first` can provide support for this? or, what can I do with configuration?

**Comment by ljharb** [comment]
I’m not sure about electron norms but usually one uses the browser field in package.json to control what loads on the web, rather than a conditional require.

**Comment by ljharb** [comment]
Also, regardless, imports are always hoisted - so they’ll happen before all your code runs no matter what order you put them in.

**Comment by hibiyasleep** [comment]
hoisting isn't really problem since all imports already on (nearly) top, just for consistent of orders.

**Comment by ljharb** [comment]
I don't think it makes sense for the "import order" rule to have an exception for a non-import.

**Comment by benmosher** [comment]
Sorry, this is just what `first` is for: ensuring nothing else comes..first. 😁
