### ISSUE TITLE
webpack resolver: issue with eslint-loader

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#134]
not sure what's happening, works fine from inside ESLint.

**Comment by xjamundx** [comment]
oh yes, just found this. happy to take a quick look at the code to figure it out...

**Comment by benmosher** [comment]
That would be awesome, I haven't had a chance yet. I'm hoping it's something simple, it was working fine with the Node resolver.

**Comment by xjamundx** [comment]
`file` varies depending on how this is called which affects `packageDir = findRoot(file)`.

- when run with eslint-loader `file` is only a relative path. 
- when run with eslint `file` is a fully qualified path

**Comment by xjamundx** [comment]
I'll file a PR, but I have no tests other than just trying it out....

**Comment by benmosher** [comment]
published in 0.1.4!
