### ISSUE TITLE
doc update request: "no-unused-modules" should indicate that it defaults to no-op

### ISSUE THREAD

**Issue by johndevedu** [benmosher/eslint-plugin-import#1351]
Reference https://github.com/benmosher/eslint-plugin-import/issues/1324 

Until the next semver when the defaults can be set to "true", I think it would be helpful to update the doc to state that settings default to "false" for both `missingExports` and `unusedExports`. As the referenced issue states, it was not obvious to me it had to be explicitly enabled, and effectively it was a no-op on the plugin. This no-op might deter some folks from using an awesome plugin! :)

**Comment by johndevedu** [comment]
@ljharb just noticed that `no-unused-modules` is not even listed on the README.md. Can I add that to the above PR or should I open another issue?

**Comment by ljharb** [comment]
Let’s do it all in one :-)

**Comment by johndevedu** [comment]
@ljharb Done with the additional change. Please lmk if I missed anything to get the PR completed. Thanks!
