### ISSUE TITLE
support for eslint 6

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#1362]
Tests currently run, but are allowed to fail, on the eslint v6 alpha.

We should figure out what changes are needed to make them pass.

(see #1361)

**Comment by PutziSan** [comment]
When I try to use eslint-plugin-import with eslint 6 I get the error `Cannot find module 'eslint/lib/util/glob-util'`. This is also described in an eslint-issue: https://github.com/eslint/eslint/issues/11720#issuecomment-492428578

**Comment by ljharb** [comment]
@PutziSan that's fixed in master, but still unreleased.

**Comment by PutziSan** [comment]
Okay, thx and sorry for the noise ;-)

**Comment by ljharb** [comment]
eslint 6 is now released.
