### ISSUE TITLE
Console.info statements in webpack config file causes resolve error

### ISSUE THREAD

**Issue by tinyearth** [benmosher/eslint-plugin-import#1373]
### Environment:
- linter-ui-default 1.7.1
- Atom 1.37
- webpack 4
- Mac 10.13.6

### Example webpack config file: 
```
const webpack = require('webpack');
const path = require('path');

module.exports = () => {
    const configToUse = {
        cache: true,
    };

    // eslint-disable-next-line
    console.info('This is breaking linter-ui-default.');
    return configToUse;
};
```

### Result: 
All import statements in a repository's files are flagged as "Unable to resolve path to module". Below is a screenshot of the resolve errors from Atom's bottom dock.

<img width="761" alt="bottom-dock-resolve-errors" src="https://user-images.githubusercontent.com/2474510/58582101-da465300-8205-11e9-9933-cdb2e15f481b.png">

**Comment by ljharb** [comment]
What happens on the command line?

**Comment by tinyearth** [comment]
Command line is clean with no linter errors.

**Comment by ljharb** [comment]
In that case, that suggests that Atom isn't using node, which would be strange. You may need to file a bug on Atom (since the command line is the source of truth)

**Comment by tinyearth** [comment]
Huh, ok... @Arcanemagus curious if you have thoughts on this?

I'm just trying to get the ticket to the right place and don't want to spam repos.

**Comment by Arcanemagus** [comment]
As I already told you in the other issue this is either a configuration problem or a bug, but without a way to reproduce this it's impossible to say for sure.

**Comment by tinyearth** [comment]
@Arcanemagus I was referring to specifically filing an issue in Atom as @ljharb suggested. I thought you may have some insight to the inner workings of Atom since you build packages for it and I do not.

**Comment by Arcanemagus** [comment]
This _extremely_ unlikely to be an issue with Atom itself. If it's an issue at all in that part of the ecosystem it's something in how `linter-eslint` is running things.

> As I already told you in the other issue this is either a configuration problem or a bug, but without a way to reproduce this it's impossible to say for sure.

**Comment by ljharb** [comment]
It certainly might not be in Atom, but it very well might be in whatever Atom plugin you're using - it's definitely not in eslint or this plugin, tho, since it works on the command line.

**Comment by tinyearth** [comment]
Ok thanks; then I'm closing this out. 

Based on the comments, it sounds like an issue with [linter-eslint](https://github.com/AtomLinter/linter-eslint). Until I have a public code available to demo the problem per @Arcanemagus request, I won't be opening a new issue in that repo (though if it needs to be documented, he may be able to transfer the [related issue](https://github.com/steelbrain/linter-ui-default/issues/542) since he's a contributor to both).
