### ISSUE TITLE
How to detect re-export?

### ISSUE THREAD

**Issue by theoptz** [benmosher/eslint-plugin-import#1385]
Could anyone provide eslintrc rules which detect re-exported fields?

```
exports.a = 5;

// something here

exports.a = 10;
```

Thanks

**Comment by ljharb** [comment]
Like, duplicate commonjs exports fields?

I'm not sure that's necessarily an error - there's a reason the best practice is to do `module.exports = {…}` and not to do `exports.something =`

**Comment by theoptz** [comment]
> Like, duplicate commonjs exports fields?

Yes

> I'm not sure that's necessarily an error - there's a reason the best practice is to do `module.exports = {…}` and not to do `exports.something =`

Maybe =)
But i have a lot of legacy code and just want to detect duplicates

Is there any way to do it?

**Comment by benmosher** [comment]
I am going to say this is out of scope for this plugin, which is focused more specifically on ES2016+ `import`/`export` syntax.

I double-checked the existing `export` rule which validates this for the "modern" syntax and it would not be trivial to extend it to cover CJS as well.

There may exist another ESLint plugin that does this, but I am not aware of any.

Cheers!

**Comment by helloyou2012** [comment]
I wrote a plugin to support commonjs duplicate exports check: [eslint-plugin-commonjs](https://github.com/d-band/eslint-plugin-commonjs)

**Comment by theoptz** [comment]
@helloyou2012 amazing, works for me =)
Thank you!
