### ISSUE TITLE
errors with eslint v6

### ISSUE THREAD

**Issue by weilinzung** [benmosher/eslint-plugin-import#1395]
Error: Failed to load plugin 'import' declared in '--config': Cannot find module 'eslint-plugin-import'
Require stack:
- /../project/__placeholder__.js

```
    "eslint": "^6.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": "^2.18.0",
```

**Comment by ljharb** [comment]
whats your eslint command and config?

**Comment by weilinzung** [comment]
just normal webpack.

and normal config file:
```
...
  extends: 'eslint:recommended',
  parser: 'babel-eslint',
...
```

**Comment by ljharb** [comment]
What eslint command are you running on the command line tho?

What happens on the CLI is the source of truth; running eslint via webpack or an IDE adds extra complexity that might be causing problems.

**Comment by weilinzung** [comment]
I use eslint inside of a webpack build project, I did not create a command line for that.

eslint v6 did a lot of updates, I am 100% sure it is the compatibility issue. I noticed `stylish` formatter change the path.

With V5+ no problem at all with this importer.

**Comment by ljharb** [comment]
linting needs to run by itself; and it doesn't really make sense to gate the build on linting, that just slows down development.

Your eslint config should be in a normal config file (`.eslintrc` or similar), and `eslint .` on the command line should work. If that's not working, we can fix it; if that is working, it's a webpack issue.

**Comment by weilinzung** [comment]
@ljharb just for clarify I did something like this: https://www.learnhowtoprogram.com/lessons/building-an-environment-automatic-linting-with-webpack

and I have a normal file `.eslintrc`.

**Comment by ljharb** [comment]
so can you `npx eslint .` on the command line, and provide the output in eslint 6?

**Comment by weilinzung** [comment]
yes~

**Comment by meatwallace** [comment]
i'm also unable to use it with ESLint 6.x, however I'm using Yarn v2 which was quick to point out the culprit. i'm *not certain* this is the same issue, however I'm aware ESLint 6 had changes in regards to how configs/plugins/presets are resolved that could effect tooling integration in some scenarios. the error:

```
❯ yarn run eslint --resolve-plugins-relative-to packages/eslint-config-base **/*.js
Error: Failed to load plugin 'import' declared in '.eslintrc.js » @meatwallace/eslint-config-base': A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't

Required package: eslint (via "eslint")
Required by: eslint-plugin-import@virtual:b2aadd09894d447c42a0dd2c8753d05cfe5d28d1061658c683615915339651d595438062190f5e75425de7387500692023505f4e9894090e04acbb56bec3eec3#npm:2.18.0 (via /home/meatwallace/projects/foundations/.yarn/virtual/eslint-plugin-import-virtual-27852718f1ed49c654311437e3a4f21a6d20ad80f107c17f133e85af424c6224/node_modules/eslint-plugin-import/lib/ExportMap.js)
```

`ExportMap.js` directly requires `eslint`, which is only listed in `eslint-plugin-import`s package manifest's peer and dev dependencies, and not it's actual dependencies. adding `eslint` as a dependency to my sharable config resolved the issue in my case, but it really should be done upstream in this package. i was going to open a PR, however when I dug in I saw you're testing against ESLint v2-6, so no solution comes to mind without simply dropping support for older versions or increasing complexity in your testing strategy.

@weilinzung - if you haven't, might be worth checking out https://eslint.org/docs/6.0.0/user-guide/migrating-to-6.0.0#-plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location - might be irrelevant, might not.

**Comment by weilinzung** [comment]
@meatwallace @ljharb It is because V6 deprecated the `plugins` option, so any solution for this plugin?

**Comment by ljharb** [comment]
I am not aware at all that that is the case; the plugins option is still very necessary afaik.

**Comment by weilinzung** [comment]
@ljharb yes! https://eslint.org/docs/6.0.0/user-guide/migrating-to-6.0.0#-plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location

**Comment by ljharb** [comment]
I certainly hope not - anything a project needs for linting should always have been only installed locally, not globally.

**Comment by aweber1** [comment]
For anyone that might be encountering the error message "Failed to load plugin 'import'" in VS Code while using eslint 6.x, this issue/comment VS Code repo resolved the issue for me:

https://github.com/microsoft/vscode-eslint/issues/696#issuecomment-566949199
