### ISSUE TITLE
run eslint on the entire project instead of only on `src`

### ISSUE THREAD

**Issue by golopot** [benmosher/eslint-plugin-import#1413]
Currently ci only run eslint on `./src`, therefore lots of codes outside of `./src` (especially .`/tests`) are unlinted. This causes lots of friction in development. In my case, when I edit a test file, I have to disable eslint in my editor in order to avoid unrelated changes.

**Comment by golopot** [comment]
There is a technical problem: Since we don't want to lint `tests/files`, an `.eslintignore` file needs to be added. But doing that alters the behavior of unit tests for `no-unused-modules`, the rule will consider `tests/files/**/*` to be ignored, hence failing the tests.

**Comment by ljharb** [comment]
we could provide a custom eslintignore file for tests (or for not tests), perhaps?

**Comment by ljharb** [comment]
Fixed in #1475.
