### ISSUE TITLE
import/no-unresolved: [2, { commonjs: true, amd: true }] not working

### ISSUE THREAD

**Issue by brendonco** [benmosher/eslint-plugin-import#1421]
can this detect minified library without source map?  Seems like it doesnt detect missing module.  The library imported doesnt have source map and minified. Using webpack to package the minified library.

**Comment by ljharb** [comment]
if it’s bundled, it’s entirely possible it can detect it - typically you’d never want to bundle a published library directly, and you’d especially not want to publish a UMD since there’s not really any value in that.
