### ISSUE TITLE
upgrade to @typescript-eslint/parser

### ISSUE THREAD

**Issue by chrisands** [benmosher/eslint-plugin-import#1428]
I'm using 1.13.0 version of `@typescript-eslint/parser` and getting an error `Cannot find module 'typescript-eslint-parser'`. 
[`typescript-eslint-parser`](https://github.com/eslint/typescript-eslint-parser) is deprecated and you should use [`@typescript-eslint/parser`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser)

`eslint-plugin-import` version: '2.16.0'

**Comment by ljharb** [comment]
Try upgrading eslint-plugin-import to the latest, v2.18.1.

**Comment by chrisands** [comment]
It helped, thank you! 
Sorry for the inconvenience.
