### ISSUE TITLE
Why can't I use "/" as a alias path?

### ISSUE THREAD

**Issue by phakphumi** [benmosher/eslint-plugin-import#1429]
When I set "/" to be my alias for the root folder many `eslint-plugin-import` rules do not work normally.

The first rule that has a problem is `import/no-absolute-path`
When I import the path like `import { UserContext } from '/contexts/UserContext';`
It shows me an error `Do not import modules using an absolute patheslint(import/no-absolute-path)`
So, I have to turn off this rule.

The second rule is `import/no-relative-parent-imports`.
I want to enforce this rule to prevent the developer to import from the relative parent path.
Like above, When I import the path like `import { UserContext } from '/contexts/UserContext';`
It shows me another error `Relative imports from parent directories are not allowed. Please either pass what you're importing through at runtime (dependency injection), move `useAuthorization.js` to same directory as `/contexts/UserContext` or consider making `/contexts/UserContext` a package.eslint(import/no-relative-parent-imports)`.

The important one is the second rule which I want to enforce its.

My question, how can I turn on `import/no-relative-parent-imports` while using "/" as an alias path?

**Comment by ljharb** [comment]
You can’t do this because node itself already interprets a leading / as the start of your filesystem. Aliases work best when they’re otherwise invalid paths.

**Comment by phakphumi** [comment]
We can use babel to override root path, can’t we?

**Comment by ljharb** [comment]
Pretty sure that's the root for babel transpilation / package root, it's not referring to "the filesystem root".

**Comment by phakphumi** [comment]
But, it also cause the error which I mention above.
Do I have to config babel-plugin-module-resolver in different way?

Right now, I just keep it empty because there is no alias to set except the root

**Comment by ljharb** [comment]
It might be possible, but you're fighting a losing battle - just pick another prefix, one that doesn't already have a *universal* meaning in the ecosystem. I tend to suggest `~`.
