### ISSUE TITLE
Parse error in mdx files

### ISSUE THREAD

**Issue by cdfa** [benmosher/eslint-plugin-import#1433]
Hi, I'm reporting here too, because I realized [an issue](https://github.com/tleunen/eslint-import-resolver-babel-module/issues/106) I originally reported at `babel-plugin-module-resolver` might not be specific to that resolver. Please read it for more information. 

As I commented there, I also get parse errors when using the default node resolver, but on a different import.

import:
```jsx 
import styled from "styled-components";
```

Error:
```
21:20  error    Parse errors in imported module 'styled-components': parser.parse is not a function (undefined:undefined)  import/namespace
21:20  error    Parse errors in imported module 'styled-components': parser.parse is not a function (undefined:undefined)  import/default
21:20  warning  Parse errors in imported module 'styled-components': parser.parse is not a function (undefined:undefined)  import/no-named-as-default
21:20  warning  Parse errors in imported module 'styled-components': parser.parse is not a function (undefined:undefined)  import/no-named-as-default-member
```

**Comment by JounQin** [comment]
Please try `@rxts/eslint-plugin-mdx@0.7.1`.

Notice about these new rules: https://github.com/rx-ts/eslint-plugin-mdx#rules

**Comment by ljharb** [comment]
i have no idea what mdx is, but it’s not JavaScript, or supported by node, or Babel, so you’d definitely need your own eslint parser.

**Comment by JounQin** [comment]
It would be better to support `parseForESLint` at https://github.com/benmosher/eslint-plugin-import/blob/master/utils/parse.js#L45, I can make a PR for it.

**Comment by ljharb** [comment]
I'm not sure what you mean.

That particular utility is for parsing ES Modules or CJS modules (which are files, one module per file) - it's not meant to parse anything else.

**Comment by JounQin** [comment]
@ljharb `.mdx` is handlered by `@rxts/eslint-plugin-mdx`, which exported a `parseForESLint` method without `parse` method, it should be supported by ESLint.

Reference: https://eslint.org/docs/developer-guide/working-with-custom-parsers

**Comment by ljharb** [comment]
Gotcha - in that case, I agree with your suggestion, and a PR would be great. Thanks!

**Comment by JounQin** [comment]
@cdfa Please take a look at #1435

**Comment by cdfa** [comment]
I updated to `@rxts/eslint-plugin-mdx@^0.8.1` and I'm getting a lot less errors, but still some. Please checkout my repo at https://github.com/cdfa/react-turn-reveal/tree/81bcee9cd3a34fdd18904f181c04fc9d5138a56e. The npm script to run `eslint` on MDX files is `lint:mdx:eslint`. You can also check out the [CI job](https://circleci.com/gh/cdfa/react-turn-reveal/155).

**Comment by JounQin** [comment]
@cdfa please add a separated issue to `@rxts/eslint-plugin-mdx` repository.
