### ISSUE TITLE
Support for bundledDependencies

### ISSUE THREAD

**Issue by schmidsi** [benmosher/eslint-plugin-import#1436]
I have some auto-generated code (through https://github.com/prisma/photonjs) that is located in `node_modules/@generated/photon`. 

How can I tell `eslint-plugin-import` to not throw a `import/no-extraneous-dependencies` error? The best solution I can think of so far is to put it into the [bundledDependencies](https://npm.github.io/using-pkgs-docs/package-json/types/bundleddependencies.html). But it seems like `eslint-plugin-import` does not look at these.

Related: https://github.com/prisma/prisma2/issues/314

**Comment by ljharb** [comment]
Absolutely things in bundledDependencies should not error; that seems like an (albeit very very rare) omission. A PR adding that support is welcome.

**Comment by schmidsi** [comment]
Thanks for the quick answer.

Just started to work on the PR. Comments are welcome. I will try to do more tomorrow.
