### ISSUE TITLE
Rule Suggestion: "enforce-optimal-require"

### ISSUE THREAD

**Issue by simlu** [benmosher/eslint-plugin-import#1457]
When a `require` references a relative file, but unnecessarily traverses up and down the file tree, this should be a warning.

I've implemented this recently and we've found it very useful. Please kindly consider moving it as a rule into this library.

Here are the references:
- [Code](https://github.com/blackflux/eslint-plugin-rules/blob/master/src/rules/enforce-optimal-require.js)
- [Tests](https://github.com/blackflux/eslint-plugin-rules/blob/master/test/rules/enforce-optimal-require.spec.js)

**Comment by golopot** [comment]
That rule already exists as [no-useless-path-segments] (https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-useless-path-segments.md) .

**Comment by ljharb** [comment]
Indeed, this is exactly what `no-useless-path-segments` is for.

**Comment by simlu** [comment]
Sweet, thank you for the feedback!

Any idea why this is not an airbnb rule?

**Comment by ljharb** [comment]
It absolutely is, and is enabled in the airbnb config for quite some time now.

**Comment by simlu** [comment]
Interesting! I'm super confused why it's not enforced by this config then https://github.com/blackflux/object-scan/blob/master/.eslintrc.json

Have some fundamental doubts about the setup now 🤷‍♂️

**Comment by ljharb** [comment]
Me too; but also your package.jsom should never have anything pinned, that’s the lockfile’s job. (that’s not the problem tho)

**Comment by simlu** [comment]
@ljharb Yeah that's a separate thing also on my list somewhere. Back to the rule; even if I add it explicitly as `"import/no-useless-path-segments": 1`, it still doesn't complain. All the other rules seem to work fine... Is this a bug? I fail to see how it could be a misconfiguration...

**Comment by ljharb** [comment]
Set it to 2? Maybe you have warnings suppressed.

**Comment by simlu** [comment]
I opened a bug report with a minimal test case here: https://github.com/airbnb/javascript/issues/2077
