### ISSUE TITLE
Bad performance of import/order

### ISSUE THREAD

**Issue by ulrichb** [benmosher/eslint-plugin-import#1458]
In my codebase, `import/order` is currently the worst behaving rule in terms of performance.

Run with `TIMING=1`:

![image](https://user-images.githubusercontent.com/388796/63466512-b2146c00-c463-11e9-9d1e-aa8d36b2bc6e.png)

Version: 2.18.2
ESLint: 6.2.1
@typescript-eslint/parser: 2.0.0 (running the rule 100 % in TypeScript files.)

Please let me know if (and how) I should provide more information.

**Comment by ljharb** [comment]
This isn't actually the case; it's just that the first import rule that runs has to build up an import cache. If you disable the order rule, you'll see a different rule taking up that much time.

**Comment by ulrichb** [comment]
Hmmm .. I disabled `import/order` and still enabled `import/no-default-export` (I have no other import rules) and this is my result:

![image](https://user-images.githubusercontent.com/388796/63467735-64e5c980-c466-11e9-9bba-01a7e4ddc7e2.png)

... so `import/order` is the problem ... and 1.7 secs for building the "import cache" is a lot.

**Comment by ulrichb** [comment]
BTW: Can you point me to this cache in the repo?

**Comment by ljharb** [comment]
The cache is at https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js, and for any rule that first uses it, I would expect the same performance hit. I don't know what other `import` rules you have enabled, but try enabling multiple, and then running it again without `order`?

**Comment by benmosher** [comment]
`no-default-export` is a dependency-free rule so it wouldn't build the cache.

A number of rules (including `import/order`) have to hit the filesystem because they need information about other files. Most lint rules are able to operate on only the structure of the file being linted (CPU-only) whereas many rules in this plugin need to evaluate _many_ other files on the FS.
