### ISSUE TITLE
Undocumented option "commonjs" for `import/no-useless-path-segments`

### ISSUE THREAD

**Issue by simlu** [benmosher/eslint-plugin-import#1459]
By default `import/no-useless-path-segments` only checks `require` when the rule option `commonjs` is set to true.

Unfortunately this is not documented. Not sure where the best place for that to happen would be, so opening an issue.

Also, why is `require` not checked by default? It is somewhat cumbersome that one has to manually enable this setting.

**Comment by ljharb** [comment]
It's not checked by default because that'd be a breaking change.

Documenting it is a great idea.

**Comment by simlu** [comment]
@ljharb Haha, asking the question "Why is the cat burning?" I wasn't really looking for the answer "Well it's too late now", more for something like "It got to close to the oven" :)

There must be a reason why someone decided they didn't want it enabled by default (or at least I'd hope so). Just curious what that reason was/is

Also; Breaking change should always be possible with major version bump (if it's the right thing to do)

**Comment by ljharb** [comment]
The reason is that that option didn't exist when the rule was created, and thus adding it later meant it couldn't be defaulted to "on" without being a breaking change.

It's certainly possible, but it's best to avoid breaking changes at all costs until they're absolutely necessary.
