### ISSUE TITLE
namespace: hashing the context is taking up a big chunk of time

### ISSUE THREAD

**Issue by epmatsw** [benmosher/eslint-plugin-import#1467]
I'm debugging some linting perf issues we're hitting, and the `import/namespace` rule is a big culprit. It currently takes **~53s** by itself.

While exploring this, I noticed that that `ExportMap.for` is the biggest chunk of that. The first thing that method does is hash the passed in context to get a cacheKey. An idea I had was to have a Map, where the keys are `JSON.stringify(context)` and the values are the current `cacheKey`. If we get the exact same context again, we can skip the expensive `hashObject` call and use the pre-generated cacheKey.

In our code base, that reduces our runtime to **~34s**, or a decrease of **~44%**.

Also of note, we stat the file:

https://github.com/benmosher/eslint-plugin-import/blob/7ffbf03fc832df41c4e90ffd27fee43de3685224/src/ExportMap.js#L298 

even if we're not going to hit a branch that uses the stat result. We could probably make that lazier.

We read the file even if it's going to be ignored and the read contents not used: https://github.com/benmosher/eslint-plugin-import/blob/7ffbf03fc832df41c4e90ffd27fee43de3685224/src/ExportMap.js#L313-L316

We never set a null cache value for ambiguous modules (this one might be intentional): https://github.com/benmosher/eslint-plugin-import/blob/7ffbf03fc832df41c4e90ffd27fee43de3685224/src/ExportMap.js#L326

I tried optimizing those a bit, but their impact was much lower than the impact of the hash caching.

**Comment by ljharb** [comment]
This isn't specific to the namespace rule; all rules that use ExportMap share this code and startup overhead.

A PR to improve these things seems great.
