### ISSUE TITLE
No internal module export

### ISSUE THREAD

**Issue by adjerbetian** [benmosher/eslint-plugin-import#1481]
# Proposition

Make the rule `no-internal-modules` also prevent *exporting* the submodules of other modules. 
(currently it only prevents importing)

# Description of the problem

When `no-internal-modules` is set to `error`, here is what we have:

```js
import { f } from "./modules/submodule"  // error
export { f } from "./modules/submodule"  // no error
```

This is annoying because **it breaks the idea that a folder decides what it makes available to the exterior**, and therefore, everything is accessible.

## Example

For instance, one could have

```
module1/
    private/
        f.js
module2/
    hacked_f.js
    g.js
```

with

```js
//hacked_f.js
export { f } from "../module1/private/f"

//g.js
import { f } from "./hacked_f.js"
```

**Comment by ljharb** [comment]
This seems like a good thing to add - although it would have to be behind an option to avoid being semver-major.
