### ISSUE TITLE
no-extraneous-dependencies ignore Babel Macros plugins

### ISSUE THREAD

**Issue by AndyOGo** [benmosher/eslint-plugin-import#1483]
An option to allow [Babel macros plugins](https://github.com/kentcdodds/babel-plugin-macros) would be nice.

**Comment by ljharb** [comment]
This is an eslint plugin; I’m not sure what that would entail, but i also have no idea what babel macros is.

**Comment by AndyOGo** [comment]
@ljharb 
Thanks for your quick response.
Yes, I'm totally aware that this is an eslint plugin.

Babel macros are by default enabled since Babel@v7.
- https://babeljs.io/blog/2018/08/27/7.0.0#babel-macros
- https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros

For example I use [`import-all.macro`](https://github.com/kentcdodds/import-all.macro) which prints a warning, though the expanded imports are all fine (non-dev-dependencies).

**Comment by ljharb** [comment]
This is the sort of thing - like path transformation - that goes beyond what static analysis can trivially do.

Linters run on the raw code; but these kinds of transformations (which predate macros) require the linter to either be tightly coupled to the transformer (a bad idea) or require partially-transpiled code to be what's linted (error messages get confusing).

My personal opinion is that a macro like that adds implicitness to your code, and thus is a terrible idea to use in the first place. The farther you drift from "standard node resolution" the harder your code is to understand and maintain.

**Comment by AndyOGo** [comment]
@ljharb Waauu, you are really taking care of your project, you are answering light speed mode :flushed:

> This is the sort of thing - like path transformation - that goes beyond what static analysis can trivially do.
I absolutely agree ... static, context-free grammars are easy to handle, in contrast to dynamic, context-sensitive grammars

> Linters run on the raw code;
You are all right

> but these kinds of transformations (which predate macros) require the linter to either be tightly coupled to the transformer (a bad idea) or require partially-transpiled code to be what's linted (error messages get confusing).
You are also right here in general ...  my intention is to ignore/avoid linting in case of an babel-macro `import`.
I think since it's possible to white-list globs, it would be also nice to white-list certain imports.

> My personal opinion is that a macro like that adds implicitness to your code, and thus is a terrible idea to use in the first place. The farther you drift from "standard node resolution" the harder your code is to understand and maintain.
Thank you for your opinion.
Though here I disagree, by explicitly `import`ing the babel macro, any implicitness is turned into explicitness. Furthermore macro-expansions in general used right, are always a maintainability boost.

IMHO Babel-Macros are genius approach and would like to ask you to study the full problem/motivation/solution write-up:
https://github.com/kentcdodds/babel-plugin-macros#the-problem

**Comment by ljharb** [comment]
I'm very much not convinced on macros as a whole, but that doesn't change the underlying issue - there's no maintainable way for any static analysis tool to generically support partial code transformation, something that was true long before babel macros existed.

The specific no-extraneous-deps rule could perhaps add an ignore list (altho you'll be able to use `bundledDependencies` in the next release to achieve the same thing), but that requires manual maintenance by the user, so I don't think that's a very elegant solution.

**Comment by AndyOGo** [comment]
Sure, I see it as an opt-in option and responsibility is at user-land.

**Comment by ljharb** [comment]
Happy to reopen if there appears a babel macro where it actually makes sense not to add it to dependencies explicitly.
