### ISSUE TITLE
very slow/bad performance of import/no-unused-modules

### ISSUE THREAD

**Issue by schumannd** [benmosher/eslint-plugin-import#1487]
on our medium sized codebase (20-30k loc) this is the TIMING=1 output:

```
Rule                              |  Time (ms) | Relative
:---------------------------------|-----------:|--------:
import/no-unused-modules          | 323947.982 |    91.7%
prettier/prettier                 |  13086.094 |     3.7%
import/namespace                  |   3886.312 |     1.1%
import/no-unresolved              |    817.742 |     0.2%
react/no-deprecated               |    658.417 |     0.2%
react/jsx-no-bind                 |    567.619 |     0.2%
max-len                           |    538.678 |     0.2%
react/sort-comp                   |    501.558 |     0.1%
import/no-named-as-default-member |    443.165 |     0.1%
import/default                    |    313.777 |     0.1%
```

with `time`:
real	15m3.000s
user 12m50.899s
sys	1m52.307s

without that rule it's:
```
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
prettier/prettier                   |  6009.924 |    41.2%
import/namespace                    |  3545.933 |    24.3%
import/no-unresolved                |   326.414 |     2.2%
react/no-deprecated                 |   279.664 |     1.9%
react/jsx-no-bind                   |   248.476 |     1.7%
max-len                             |   175.565 |     1.2%
react/sort-comp                     |   172.256 |     1.2%
react/prefer-stateless-function     |   145.210 |     1.0%
react/void-dom-elements-no-children |   133.263 |     0.9%
react/no-typos                      |   132.206 |     0.9%
```

`time`:
real	0m20.142s
user 0m25.184s
sys	0m2.012s

20s vs 15m is quite the duration change.

It might be related to this closed issue: #1364

**Comment by ljharb** [comment]
The first rule from this plugin that uses the export map is always the slowest; if you disable this rule but have another export-map-using rule enabled, that one will be slow.

**Comment by schumannd** [comment]
I am not sure what the export-map exactly calculates, but for this task nothing that takes this long should be needed if as far as I can see.

The task could be accomplished by regexing over all files twice and comparing those sets if I am not mistaken. Maybe this feature should be rewritten without using the export map?

**Comment by ljharb** [comment]
it runs over every single file in your repo, and builds up a dependency graph. Once the cache is built, it's shared by all the rules that use it.

In no way can proper parsing of non-regular text be accomplished with regexes.

**Comment by schumannd** [comment]
> In no way can proper parsing of non-regular text be accomplished with regexes.

true, I was a bit quick there.

But I would still argue, that building a whole dependency graph is not necessary. Or that this rule could be implemented much faster. Or is there a certain algorithmic complexity that I am not seeing here?

**Comment by ljharb** [comment]
It's necessary for a number of rules - this *one rule* could probably be much faster, but then all the other rules need to repeat a bunch of this rule's work to build up the ExportMap that is absolutely needed.

In other words, it's fine that individual rules are made slower if the common case of "most of the rules" ends up being faster.

That said, 15 minutes is obviously quite large. I suspect the unreleased #1449 would largely address it.

**Comment by JiaJiaJiayi** [comment]
May I ask how you calculated out the time used of different rules?

**Comment by jonathanj** [comment]
@JiaJiaJiayi Set a`TIMING` environment variable. See [the official documentation on per-rule timing](https://eslint.org/docs/developer-guide/working-with-rules#per-rule-performance).

**Comment by jorisw** [comment]
So how do we subtract the building of the export map and get real visibility into slow rules?

**Comment by ljharb** [comment]
@jorisw unfortunately eslint doesn't have any kind of a "prep" stage where we could build up the export map, and have that time measured separately :-/
