### ISSUE TITLE
import/order with webpack alias

### ISSUE THREAD

**Issue by xereda** [benmosher/eslint-plugin-import#1489]
Hi gurys,

How do I get imports containing webpack alias to fall between external and internal modules?

Expected:

![image](https://user-images.githubusercontent.com/14337850/65729798-e4823c00-e095-11e9-9f37-69185490e153.png)

What happens:

![image](https://user-images.githubusercontent.com/14337850/65729830-0aa7dc00-e096-11e9-9db0-fbb2e8d9a964.png)

.eslintrc.js:

```
'import/order': 'error',
```

**Comment by rasenplanscher** [comment]
duplicates #1306
