### ISSUE TITLE
Allow a cwd to be passed in for webpack resolver

### ISSUE THREAD

**Issue by Aghassi** [benmosher/eslint-plugin-import#1502]
https://github.com/benmosher/eslint-plugin-import/blob/e62011f2facc2a50206f32abb496fb7a0f774ba4/resolvers/webpack/index.js#L157-L169

The current logic here assumes that the user will always have webpack locally to their project such that it can be used to reference for the resolve functionality. However, this is not true if the project is built by a CLI tool. I work for Intuit, and we have a CLI tool that helps us to scale and build React apps at scale. As such, the CLI comes with the `webpack` module and version needed for the projects (which may reside on the user's path instead of in their local repo). The same goes for `eslint`.

Because of this, I'd like to request the ability to pass an option called `cwd` to the `eslint-import-resolver-webpack` package. This way, I can specify where it should look for `webpack`. Right now, this logic works with the fallback on a repo if the config and ESLint are run from within the repo. If they are executed from outside of the repo (like in a CLI), this breaks.

The `cwd` option would be used instead of `basePath` to set the `webpackFilename` lookup.

By the way, I'm not super familiar with this code, I have just narrowed down an issue I have been having. If this is not the right place to address this issue, please point me to the right code. I'm happy to try and contrib the fix.

**Comment by ljharb** [comment]
When do you imagine `basedir` would be correct but `process.cwd()` wouldn't be?

**Comment by Aghassi** [comment]
If I invoke this logic from within a CLI, the `basedir` to find webpack won't be `process.cwd()`. It will be the path of the CLI, which will have it's own `node_modules` to references. So for example, we use https://www.npmjs.com/package/pkg-dir in our CLI to determine the "root" directory in our CLI (which again, may be different than the `process.cwd()`). Usually, once we have that, we pass it to things that allow us to set the CWD so we can set it as the reference. So in this case, we may be operating on a project, and that project may be the current `process.cwd()`. However, the directory we need to reference for tooling dependencies will be in the CLI, not the `process.cwd()`. Does that make sense? I know this is a little hard to describe via a comment. The way we think about it is: for core tools (like webpack) the CLI brings them. The project just has code etc that the CLI knows how to build.

**Comment by Aghassi** [comment]
This is the same reason our CLI uses `require.resolve` internally: so that we don't pick up a version that the user brings because it may break compatibility with the logic we have in the CLI.

**Comment by ljharb** [comment]
I guess i'm confused; why wouldn't your CLI have webpack as a peer dep, forcing the top-level app to have it installed?

**Comment by Aghassi** [comment]
Our CLI is not installed in the project. It is installed separately. We build our CLI with https://www.github.com/oclif/oclif, so we ship it via `brew` as a single zip. Peer Dependencies aren't great at our scale because it requires developers to update versions as we change configs. Usually this just leads to breakages and problems. By isolating the tooling to a single tool on the user's path, we are able to control and vet compatible versions of tools without the need for the users to handle all of that. It doesn't make sense as much when you look at broader open source, but for an enterprise company it does since it creates a single source of truth for tooling and means a unified stack.

**Comment by ljharb** [comment]
I'm not sure that something that makes no sense for open source and only makes sense for enterprise is likely to be a useful change to make in an open source tool.

**Comment by Aghassi** [comment]
I guess, but then I'd like to know what is the recommendation for being able to leverage the `resolve` mechanism if my user sets a webpack alias? At this point, I can't use advertised functionality because my project structure is different than most. Otherwise, I'm providing false information for my users (`no-unresolved` error) for something that is resolvable.

**Comment by ljharb** [comment]
I mean, if they have `require('webpack')` in their project, it needs to be resolveable from their project. That's what `require` means.

**Comment by Aghassi** [comment]
In addition, an `options` object is just that, optional. If no one ever changes it, they get the same functionality you provide today. If someone does change it, they are "opting" out of the standard flow at their own risk, but doing so such that they can adapt to their flow.

And to your point about `require('webpack')`, our users don't have to do that since we handle all of that. Hence, their projects never needs to specify or care about Webpack. All they focus on is building their React code. This is both a pro and a con of our infra structure (micro frontends).

**Comment by ljharb** [comment]
You're totally right that adding an option is safe.

So, to rephrase: a user has a webpack config in their project, but declares no dependency on webpack, thus webpack isn't requireable from their project, thus the webpack resolver is unable to require it.

You want to provide an option to the resolver to override where webpack is required from?

**Comment by Aghassi** [comment]
Correct 😄 ! Thank you for rephrasing (sorry I did a terrible job of explaining, need to work on my issue communication skills).

**Comment by Aghassi** [comment]
@ljharb I opened #1503 as a draft to get feedback on this change. First time working in the codebase so I wanted to make sure I was approaching the change correctly. Thank you for working with me on this!

**Comment by Aghassi** [comment]
#1503 has been merged 😍
