### ISSUE TITLE
import/resolver not working for webpack aliases in VSCode eslint 

### ISSUE THREAD

**Issue by kumarharsh** [benmosher/eslint-plugin-import#1505]
Hi, I'm using this plugin along with eslint in a project which as this folder structure:

```
project_root/
|_ server/
  |_ src/
  |_ .eslintrc
|_ client/
  |_ src/
  |_ .eslintrc
  |_ tools
    |_ webpack.config.js
```

I have defined some aliases in webpack like so:

```js
/* client/webpack.config.js */
config = {
  resolve: {
    alias: {
        Common: path.resolve('src/common'),
        IP: path.resolve('src/apps/inv-planner'),
    },
    modules: ['node_modules', 'src'],
    extensions: ['.js'],
  },
}
```

This is my relevant eslint config:
```js
    settings: {
        'import/resolver': {
            node: {
                moduleDirectory: ['node_modules', 'src'],
            },
            webpack: {
                config: `${__dirname}/tools/webpack.config.js`, // vscode doesn't resolve this
                // config: `./tools/webpack.config.js`, // vscode doesn't resolve this either
            },
        },
    },
```

I have opened the `project_root` folder in vscode, and all eslint rules work fine in VSCode, except for `import/extensions`, which keeps throwing errors for imports from the `src/apps/inv-planner` directory, but not from the `src/common` directory.

```js
import AsyncRequests from 'IP/components/AsyncRequests'; // throws error
import Instrumentation from 'Common/extensions/instrumentation'; // doesn't throw
```

The eslint CLI works fine, but the vscode extension doesn't. Is there an issue in path resolution for non-root directories in this plugin?

**Comment by ljharb** [comment]
There’s an issue in vscode’s repo itself, i believe. Something about it incorrectly setting the project dir.

Specifically, as long as it works on the CLI, the issue is in the IDE, and there’s nothing an individual plugin can do about it.

**Comment by kumarharsh** [comment]
Okay, thanks for the pointers. I'll report this there
