### ISSUE TITLE
Unable to resolve path to module '@sapper/app'

### ISSUE THREAD

**Issue by soullivaneuh** [benmosher/eslint-plugin-import#1509]
To reproduce, install a fresh svelte template: https://github.com/sveltejs/sapper-template

If you run eslint with this plugin, you will have:

```
/code/src/client.js
  1:25  error  Unable to resolve path to module '@sapper/app'  import/no-unresolved
```

This is because `@sapper/app` is installed in `src/node_modules` instead of the root one.

Does this plugin support nested `node_modules`?

**Comment by soryy708** [comment]
I have a monorepo project with nested `node_modules` and the paths are resolved correctly. Perhaps the issue is on your end?

**Comment by ljharb** [comment]
there needn't be a package.json - just being in node_modules should be enough to resolve.

**Comment by soryy708** [comment]
Relevant discussion: https://github.com/benmosher/eslint-plugin-import/issues/677

**Comment by soryy708** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L8

The rules get the dependencies from the nearest package.json file not the node_modules dir

_Originally posted by @HenriBeck in https://github.com/benmosher/eslint-plugin-import/issues/677#issuecomment-262830030_

**Comment by ljharb** [comment]
That issue is for `no-extraneous-dependencies`, not `no-unresolved`. The former cares about package.json files, the latter should not.

**Comment by soullivaneuh** [comment]
> Perhaps the issue is on your end?

I really don't know. I just set up the template, run the given command to install it and ran eslint.

**Comment by maraisr** [comment]
We received a similar regression when we start to _only_ support esmodules, in that we removed the `main` property of the package.json in favor of a `module` property. As soon as we did this, these errors started to appear.

**Comment by ljharb** [comment]
@maraisr `module` is not a standard package.json field nor will it ever be supported by `node`; `main` is required until node's ESM implementation ships (at which point, it will require a different field that this plugin does not yet support)

**Comment by ljharb** [comment]
node's ESM implementation has shipped, ftr - all; packages should define a "main", and/or an "exports". "module" is irrelevant, and "jsnext:main" is archaic and only supported by some bundlers.

**Comment by henri9813** [comment]
Hello,

I have the same issue, i setup the default sapper tempalte with npx.

```
/code/src/client.js
  1:25  error  Unable to resolve path to module '@sapper/app'  import/no-unresolved
```

How can i solve this ?

**Comment by ljharb** [comment]
@henri9813 that error means that module isn't installed on disk. install it there, or, configure a module resolver for this plugin that can resolve it to something.

**Comment by henri9813** [comment]
Thanks, 

Do you have any recommendation or advise ? 

Best regards

**Comment by ljharb** [comment]
I'm not sure how; https://unpkg.com/@sapper/app isn't a package in the registry.
