### ISSUE TITLE
Import default with CSS Modules and Sass

### ISSUE THREAD

**Issue by startupthekid** [benmosher/eslint-plugin-import#151]
If the `no-named-as-default` rule is turned on as an error (which it should be, it's a fantastic rule), when importing Sass or CSS styles that use CSS Modules into javascript files like this:

```
import styles from './MyStyles.scss'
```
eslint throws an error saying: `Parse errors in imported module './MyStyles.scss'  import/no-named-as-default`

I believe that's from how CSS Modules exports the final styles object. If I change my import syntax to `import * as styles from './MyStyles.scss'`, the error goes away (but the `import/default` rule comes into effect then). That resulting `styles` object, when logged, has both a `default` and a `locals` property so it looks to me as if CSS Modules is in fact exporting default and others, although I can't be sure about that.

It'd be nice if there was a way to catch this in the linter because I much prefer the `import` syntax over using `require` for styles (which works fine).

**Comment by benmosher** [comment]
Ah, yeah, it's just trying to find ES6 exports in the original Sass source--thus the parser errors. Even with the Webpack resolver, it doesn't know anything about CSS modules. 

I can imagine doing something like evaluating through Webpack loaders and then looking at the result to lint the import, for non-JS sources. That would likely be a custom export finder; I'm thinking of exposing something that could do preprocessing and evaluation for source that isn't an ES6 module: Sass, CommonJS, etc. 

In the interim, you can add '\.scss$' to the import/ignore list and it will just ignore Sass imports completely. Upside: no false errors. Downside: no true errors. 

I'll keep this in mind when I try to work out parsing CommonJS modules for exports; this feels like a pretty simple next step once that's in place.

**Comment by startupthekid** [comment]
Yeah it doesn't seem something that the plugin should be handling since it already does its job quite well.  Maybe just a small caveat in the rule documentation that says "When importing sass and using webpack, add `.scss$` to the ignore field in your config".

Using `require` works fine to so I don't see a need to change the plugin to handle what's really an edge webpack case.
