### ISSUE TITLE
commonjs option off by default - why?

### ISSUE THREAD

**Issue by soryy708** [benmosher/eslint-plugin-import#1515]
The default for NodeJS is CommonJS. You'd have to do some fancy things in order to not use `require` and `module.exports`.

Some rules do not support CommonJS fully, like "cycles" for example.

For most rules, if you want them to work with CommonJS, you have to explicitly pass them the `commonjs` option with `true`. Why is CommonJS not the default behavior?

**Comment by golopot** [comment]
Most likely because of backward compatibility. The defaults can be changed in the next major release.

**Comment by ljharb** [comment]
Because enabling it by default would be a breaking change; it was added in a minor.
