### ISSUE TITLE
Handle TSExportAssignment exports other than namespaces

### ISSUE THREAD

**Issue by joaovieira** [benmosher/eslint-plugin-import#1527]
At the moment `eslint-plugin-import` only handles the `export = ` syntax in TypeScript if it references a namespace. 

Using [`@types/supertest`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/supertest/index.d.ts#L13) as an example. The module definition is:

```ts
import * as superagent from "superagent"

export = supertest;

declare function supertest(app: any): supertest.SuperTest<supertest.Test>;
declare namespace supertest {...}
```

And the generated `ExportMap` is:

```js
ExportMap {
  path: '/Users/joaovieira/.../node_modules/@types/supertest/index.d.ts',
  namespace: Map {
    'Response' => {},
    'Request' => {},
    'CallbackHandler' => {},
    'Test' => {},
    'AgentOptions' => {},
    'agent' => {},
    'SuperTest' => {}
  },
  reexports: Map {},
  dependencies: Set {},
  imports: Map {
    '/Users/joaovieira/.../node_modules/@types/superagent/index.d.ts' => { getter: [Function], source: [Object], importedSpecifiers: [Set] }
  },
  errors: []
}
```

Only the namespace is being exported. The declared function with the same name is not added to the exported namespace as 'default'.

Looking at the code, it is explicitly [only handling namespaces](https://github.com/benmosher/eslint-plugin-import/blob/c14c9bd665525865f023b7214bbaf3d0124563dd/src/ExportMap.js#L517).

This means, user code such as:

```ts
import request, { Test } from 'supertest';
```

Raises an eslint error `No default export found in module.eslint(import/default)`.

___

The same issue happens when the module re-exports an identifier as in [`@types/lodash`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/snakeCase.d.ts). The module definition is:

```ts
import { snakeCase } from "./index";
export = snakeCase;
```

The ExportMap in this case is an empty object:

```
ExportMap {
  path: '/Users/joaovieira/.../node_modules/@types/lodash/snakeCase.d.ts',
  namespace: Map {},
  reexports: Map {},
  dependencies: Set {},
  imports: Map {
    '/Users/joaovieira/.../node_modules/@types/lodash/index.d.ts' => { getter: [Function], source: [Object], importedSpecifiers: [Set] }
  },
  errors: []
}
```

So, this fails:

```js
import camelCase from 'lodash/camelCase';
```

___

Both are very common patterns in DefinitelyTyped.

**Comment by maribies** [comment]
I believe there is a related issue here with React Navigation import errors, see the issue opened here: https://github.com/eslint/eslint/issues/12761. A work around is to ignore the imports for the react navigation, but this is not desirable long term. Any suggestions? Thanks.

**Comment by PatricSachse** [comment]
Facing the exact same issue... Help is highly appreciated! :)

**Comment by joaovieira** [comment]
@maribies @PatricSachse your issue seems to have been resolved in `react-navigation` itself https://github.com/react-navigation/react-navigation/issues/6506.

**Comment by maribies** [comment]
@joaovieira - just tried bumping to 4.1.1 and am having the same errors. i'm having my team review in case i missed something and @PatricSachse - if you bump and it resolves please let us know!

**Comment by joaovieira** [comment]
@maribies would you mind continuing this conversation in that issue? thanks
