### ISSUE TITLE
2.18.2 has an incorrect dependency on eslint-module-utils in the published package

### ISSUE THREAD

**Issue by bradzacher** [benmosher/eslint-plugin-import#1530]
I found this whilst investigating https://github.com/typescript-eslint/typescript-eslint/issues/1160

---

It looks like it's declared correctly within this repo:
https://github.com/benmosher/eslint-plugin-import/blob/112a0bf442e52b25cd7029a9905df2508e191ac1/package.json#L89

However, it looks like the published package has the _wrong_ version specified:
https://registry.npmjs.org/eslint-plugin-import/-/eslint-plugin-import-2.18.2.tgz
The `package.json` has dependency:
`"eslint-module-utils": "^2.4.0",`

Because of this incorrect dependency, it meant that if a user upgrades from an older version of `eslint-plugin-import` (before the `2.4.1` release), then yarn will not upgrade the version of `eslint-module-utils`, because the version in the lock file satisfies the specified dependency.

This is obv a huge problem, as `2.4.1` includes https://github.com/benmosher/eslint-plugin-import/pull/1409, which has some huge wins for perf (and fixes the problem from the above issue).

**Comment by ljharb** [comment]
The semver range means it gets automatically upgraded. If you’re using a lockfile, you’ve opted in to having to manually update transitive deps.

I’m sure yarn has a command to update transitive deps in its lockfile; npm certainly does.

To reiterate, ^2.4.0 is the *right* version, and while the next publish will force it to be ^2.4.1, that publish isn’t required for consumers to benefit from that patch.
