### ISSUE TITLE
How to ignore a specified package in the `no-extraneous-dependencies` rule

### ISSUE THREAD

**Issue by realduolaf** [benmosher/eslint-plugin-import#1553]
Hi guys.

I don't want to bother you, but I really don't know how to handle this situation.

How do I ignore a specified package in this rule(no-extraneous-dependencies) in a case like this？

https://material-ui.com/styles/basics/#material-ui-core-styles-vs-material-ui-styles

when I import "@material-ui/styles"， I will get an error from eslint. But if I add the package to the dependencies, the package will not work as expected.

Thanks for all the answers~

**Comment by realduolaf** [comment]
really want help

**Comment by ljharb** [comment]
Why would it not work correctly if you add it to deps?

**Comment by Toromyx** [comment]
I have the same problem with [`electron`](https://www.npmjs.com/package/electron). The reason why `electron` needs to be in `devDependencies` is discussed in [this github issue](https://github.com/electron-userland/electron-builder/issues/912) and [this stackoverflow question](https://stackoverflow.com/questions/50803207/why-does-electron-need-to-be-saved-as-a-developer-dependency/50803712).

I opened pr #1571 to add a whitelist option to `no-extraneous-dependencies`.

**Comment by ljharb** [comment]
@Toromyx that issue implies that you have two package.jsons; is that the case for you?

**Comment by Toromyx** [comment]
No, this is not the case. The issue does not describe my case, [this issue](https://github.com/electron-userland/electron-forge/issues/1071) does. It also brought me to https://www.npmjs.com/package/eslint-plugin-import#importcore-modules which is the solution for this issues original question.

The pull request #1571 is therefore not needed.

**Comment by realduolaf** [comment]
@ljharb 

Thank you for your reply.

>  Why would it not work correctly if you add it to deps?

The reason is that `@material-ui/core` re-exported `@material-ui/styles` with default themes in `@material-io/core/styles`.  If I add the package to dependencies, there are two copies of `@material-ui/styles`. This will lead to themes not work as expected.

reference: https://material-ui.com/styles/basics/#material-ui-core-styles-vs-material-ui-styles

I won't discuss the advisability of material-ui behavior, but I suggest adding a whitelist of this rules.

**Comment by ljharb** [comment]
I'm very confused. If you're typing a package name into your code to import/require from, it should be in dependencies, or else it won't work (without incredibly nonstandard tooling that will massively confuse developers). Are you saying that using material-ui forces this scenario?

**Comment by magicmark** [comment]
babel macros might be an exception here?

they're packages names you type into code and import from, but could get removed totally at buildtime/runtime

This has come up here: https://github.com/lingui/js-lingui/issues/409

**Comment by ljharb** [comment]
That seems like a very strange thing to want to do and a very good way to massively confuse anybody who looks at that code :-/

In that particular case, I'd think you'd absolutely want it to be listed in your dependencies so any peer dep or transitive dep requirements it has can be satisfied.

Is there a concrete use case (or macro) you're thinking of where the thing you type into your code won't actually be an installable module?

**Comment by magicmark** [comment]
¯\_(ツ)_/¯ I agree it's certainly confusing at the very least :p

Also your point about macro deps not being transitively installed if the package in question is itself a library that will be installed elsewhere is an excellent one...not sure how that's supposed to be dealt with. 

Worth pointing out the docs for both js-lingui and babel-plugin-macros itself suggest installing macros as devDeps:

- https://github.com/kentcdodds/babel-plugin-macros#should-macros-be-dependencies-or-devdependencies
- https://lingui.js.org/ref/macro.html#installation

Can't seem to find discussion around this though - might be worth looping in some of those folks to see if there's anything we're missing

**Comment by ljharb** [comment]
I think in the absence of a concrete use case, where it isn't both possible and *advisable* to install the "thing named by the specifier" as an explicit dep/dev dep, this isn't something that should be allowed.

Happy to reopen if a use case presents itself.

**Comment by Livven** [comment]
Not sure I understand why Babel macros aren't a valid use case here. Since packages generally ship transpiled code macro deps should not be necessary anymore.

This feature already exists anyway with the [`import/core-modules` setting](https://github.com/benmosher/eslint-plugin-import#importcore-modules) as noted in #1571.

**Comment by ljharb** [comment]
@Livven it's not that babel macros aren't a valid use case; it's that nobody's presented a use case where the specifier in the code shouldn't also be a regular dependency in package.json (so as to get all the features of semver, peer deps, etc).

The deps should be there whether they're used or not, for compatibility reasons with the consumer.

**Comment by Ranguna** [comment]
@ljharb how about aws-sdk package for lambda functions ?

This package is already present inside the lambda environment and the reason to not include it in the dependencies it to decrease bundle size to for less heavy deployments and to improve (very slightly) lambda startup.

**Comment by ljharb** [comment]
That’s not a reason not to include it in deps - that’s a reason to configure your bundler to omit it. You’d still want a version in package.json so you could track compatibility.

**Comment by Ranguna** [comment]
So you are saying instead of simply removing it from the deps, we include it there but add extra configs for our bundler (which right now is a simple `cp` and zip of the  code + node modules) ?

If that's not reason enough for you, then I can go with using what was recommended above with import/core-modules setting. `aws-sdk` will be removed from the deps and will be added into this settings.

Thanks for the fast reply!

**Comment by ljharb** [comment]
Yes, that’s what I’m saying. Also, cp + zip is NOT a bundler, use an actual bundler that parses your JavaScript.

**Comment by ljharb** [comment]
That’s an archive or an artifact :-) a bundle is a single JavaScript file.

If you’re just using cp, then you’re already likely massively inflating your archive size, because you’re almost certainly copying files you don’t use in your app.
