### ISSUE TITLE
no-unused-modules does not work for modules  in files other than .js

### ISSUE THREAD

**Issue by stekycz** [benmosher/eslint-plugin-import#1555]
I have a few Typescript only projects I would like to turn the rule on. However, I am not able to do that because the rule loads files with `.js` extension only.

It is caused by `FileEnumarator` default settings that are used in [the rule implementation](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-unused-modules.js#L21).

I have tried to use `import/extensions` settings, however, that does not work (obviously when you see the code).

I can see 3 possible solutions:

1. use the default `FileEnumarator` from the eslint itself
2. use the `import/extensions` settings for the `FileEnumarator`
3. use another settings option for the `FileEnumarator`

I believe there is a reason why the default `FileEnumarator` from the eslint itself is not used so the first option is invalid. Adding another settings option might be unnecessary because it would be probably duplication of `import/extensions`.

**Comment by ljharb** [comment]
You still always have to invoke `eslint` itself with `--ext` - which can't be specified by config - to list all the extensions you want it to look at; there's no way to avoid that.

**Comment by ljharb** [comment]
However, if you're saying that eslint makes its own FileEnumerator instance, and we're making one *differently*, then that indeed seems like it should be fixed with option 1 or 2.

**Comment by stekycz** [comment]
Yes, that is the case.  I use `--ext` to specify extensions for files to be checked. I looked to the code and I have found a way to implement option 2. I will have some time on Monday to do that. Meantime, I will think about how to implement option 1 (if it is even possible).

**Comment by ljharb** [comment]
For option 1; i'd expect the internal extension list that the settings are based on should be pulled from `--ext` anyways - that might be a wider scoped change/fix to do separately.
