### ISSUE TITLE
[import/extensions] Missing file extension after upgrade to v2.19.1

### ISSUE THREAD

**Issue by raymondsze** [benmosher/eslint-plugin-import#1573]
here is the configuration
```json
{
  "extends": ["airbnb", "prettier", "prettier/react"],
  "plugins": ["@typescript-eslint"],
  "parser": "@typescript-eslint/parser",
  "env": { "jest": true, "browser": true },
  "parserOptions": {
    "project": "tsconfig.eslint.json",
    "sourceType": "module"
  },
  "rules": {
    "react/jsx-props-no-spreading": "off",
    "react/prop-types": 0,
    "import/prefer-default-export": "off",
    "import/no-default-export": "error",
    "import/no-unresolved": 0,
    "no-underscore-dangle": ["error", { "allow": ["__typename"] }],
    "@typescript-eslint/no-unused-vars": [2, { "args": "none" }],
    "react/jsx-filename-extension": [1, { "extensions": [".tsx", ".jsx"] }],
    "import/extensions": ["error", "ignorePackages", {
      "ts": "never",
      "tsx": "never",
      "js": "never",
      "jsx": "never",
      "mjs": "never"
    }]
  }
}
```

All import syntax (for ts and tsx files) got this kind of error
```
error  Missing file extension for "./Query"                import/extensions
```

This does not happen for v2.18.2.

**Comment by ljharb** [comment]
What file does `./Query` map to?

**Comment by raymondsze** [comment]
Query.ts

**Comment by ljharb** [comment]
You also need to configure https://github.com/benmosher/eslint-plugin-import#importextensions so that the plugin knows how to resolve `ts` extensions. This is a bugfix in the latest release.

**Comment by raymondsze** [comment]
it does not work even I added it.
my file right now
.eslintrc.json
```json
{
  "extends": ["airbnb", "prettier", "prettier/react"],
  "plugins": ["@typescript-eslint"],
  "parser": "@typescript-eslint/parser",
  "env": { "jest": true, "browser": true },
  "parserOptions": {
    "project": "tsconfig.eslint.json",
    "sourceType": "module"
  },
  "settings": {
    "import/extensions": [".js", ".jsx", ".ts", ".tsx", ".mjs"]
  },
  "rules": {
    "react/jsx-props-no-spreading": "off",
    "react/prop-types": 0,
    "import/prefer-default-export": "off",
    "import/no-default-export": "error",
    "import/no-unresolved": 0,
    "no-underscore-dangle": ["error", { "allow": ["__typename"] }],
    "@typescript-eslint/no-unused-vars": [2, { "args": "none" }],
    "react/jsx-filename-extension": [1, { "extensions": [".tsx", ".jsx"] }],
    "import/extensions": ["error", "ignorePackages", {
      "js": "never",
      "jsx": "never",
      "ts": "never",
      "tsx": "never",
      "mjs": "never"
    }]
  }
}
```

**Comment by raymondsze** [comment]
I found that my error looks like this
`error  Missing file extension for "./Query"`
but not 
`error Missing file extension ".ts" for "./Query"`

but the Query file is a ts file...

**Comment by ljharb** [comment]
That seems very strange.

**Comment by keitoliveira** [comment]
I got this error after upgrade too 😞

**Comment by ljharb** [comment]
Are you using the typescript resolver?

**Comment by garyking** [comment]
I get the error, even with the following settings:

```json
{
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [
          ".js",
          ".jsx",
          ".ts",
          ".tsx"
        ]
      }
    }
  }
}
```

**Comment by raymondsze** [comment]
I found out the reason now. I am using `~` as alias of `src` folder in tsconfig path setting.
I changed the eslintrc.json to eslintrc.js and it works now.
```
const path = require('path');

module.exports = {
  extends: ['airbnb', 'prettier', 'prettier/react'],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  env: { jest: true, browser: true },
  parserOptions: {
    project: 'tsconfig.eslint.json',
    sourceType: 'module',
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: {
          resolve: {
            alias: {
              '~': path.join(__dirname, 'src/app'),
            },
            extensions: ['.js', '.jsx', '.ts', '.tsx', '.mjs'],
          },
        },
      },
    },
  },
  rules: {
    'react/jsx-props-no-spreading': 'off',
    'react/prop-types': 0,
    'import/prefer-default-export': 'off',
    'import/no-default-export': 'error',
    'import/no-unresolved': 0,
    'no-underscore-dangle': ['error', { allow: ['__typename'] }],
    '@typescript-eslint/no-unused-vars': [2, { args: 'none' }],
    'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }],
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
        mjs: 'never',
      },
    ],
  },
};
```

**Comment by ljharb** [comment]
Glad you figured it out!

**Comment by geiszla** [comment]
I have the same problem and I'm not using any alias in the path. I have these settings in `.eslintrc`:

```json
"settings": {
    "import/extensions": [".js",".jsx",".ts",".tsx"],
    "import/parsers": {
        "@typescript-eslint/parser": [".ts",".tsx"]
        },
        "import/resolver": {
            "node": {
                "extensions": [".js",".jsx",".ts",".tsx"]
            }
        }
},
```

**Comment by ivanbanov** [comment]
@raymondsze thank you very much for this https://github.com/benmosher/eslint-plugin-import/issues/1573#issuecomment-565973643

@ljharb the same error was happening to me but only on sublime/vscode, in the terminal the plugin was not notifying anything

Seems like the resolver is not working properly only on IDEs since this commit https://github.com/benmosher/eslint-plugin-import/commit/982493d03acb30a05f46a9d41c31cf85f9acf4cb

**Comment by ljharb** [comment]
hm, i would not expect IDEs to use a query string in their paths (unless that was in the actual source)

**Comment by ivanbanov** [comment]
hey @ljharb I debugged it a bit more on my local env and in the end I found that the error is showing up because of some [standardx](https://github.com/standard/standardx) problem on IDEs.

In the resolve package used by `eslint-import-resolve-node` (more specifically in this line https://github.com/browserify/resolve/blob/master/lib/sync.js#L84) it does not get the correct absolute path to resolve 🤷🏻‍♂️

Just like I mentioned before, the strange part is that in the terminal it works, but on vscode and sublime it reports the error
![image](https://user-images.githubusercontent.com/2953018/87472906-fdf27580-c620-11ea-800a-cdcde908b699.png)

So seems like everything is 💯  on the eslint end

:)

**Comment by nickzylstra** [comment]
For anyone else who ends up here and doesn't find a fix - did you recently rename a file or directory by only changing the casing?  Did you NOT use `git mv` to do it?  Are you on a case insensitive file system like Mac OS?  If so, for me it caused ESLint to say no problem in VS Code and zsh locally, but when run in Teamcity it failed with to missing extension and can't resolve path lints.  

Rename your case sensitive files and directories this way:
https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

**Comment by tgwow** [comment]
> I get the error, even with the following settings:
> 
> ```json
> {
>   "settings": {
>     "import/resolver": {
>       "node": {
>         "extensions": [
>           ".js",
>           ".jsx",
>           ".ts",
>           ".tsx"
>         ]
>       }
>     }
>   }
> }
> ```

I Solved adding your config plus this one at rules property: 

```javascript
'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
```

**Comment by gotcs108** [comment]
> For anyone else who ends up here and doesn't find a fix - did you recently rename a file or directory by only changing the casing? Did you NOT use `git mv` to do it? Are you on a case insensitive file system like Mac OS? If so, for me it caused ESLint to say no problem in VS Code and zsh locally, but when run in Teamcity it failed with to missing extension and can't resolve path lints.
> 
> Rename your case sensitive files and directories this way:
> https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory

The worst part is vs code fix does it the wrong way.
Instead of queue it auto imported to Queue

**Comment by bradennapier** [comment]
One time this happens if the cache is dirty 

try 

```
rm -rf ./node_modules/.cache
```

sorry if been mentioned but wanted to provide a solution and in rush :-\

**Comment by inaciogu** [comment]
> 
Try a empty string instead of "error" in your rule. It works for me

**Comment by sera0731** [comment]
I was able to resolve it through this config setup with `eslint-import-resolver-alias` and `babel-plugin-module-resolver` :
```
settings: {
        'import/resolver': 
        {
            alias: {
                extensions: ['.js', '.jsx', '.ts', '.tsx'],
                map: [
                    ['@', path.join(__dirname, 'src')]
                ]
            },
        },
    },
```

**Comment by nyngwang** [comment]
To who wants to fu(k the world after debugging:

## This is the simplest form:

```
  "extends": [
    "airbnb",
    "airbnb-typescript"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module",
    "project": "./tsconfig.json"
  },
  "rules": {
    "import/extensions": [ "error", "ignorePackages", { "": "never" } ],
  }
```

the important parts are: `"airbnb-typescript"`, `"project": YOUR_CONFIG`, `"import/extensions": [ "error", "ignorePackages", { "": "never" } ],`

**Comment by ljharb** [comment]
(Just be aware that `airbnb-typescript` isn't actually from airbnb)

**Comment by deathemperor** [comment]
> 

`eslint-import-resolver-typescript` solved this for me

**Comment by kabtamu-degifie** [comment]
Just add this:  
rules: {
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        ts: 'never',
        tsx: 'never',
        js: 'never',
        jsx: 'never',
        '': 'never',
      },
    ],
  },

>

**Comment by mrjackyliang** [comment]
Wanted to add onto this as well, and this isn't just limited to my IDE (using WebStorm). I currently have a TypeScript ESM (yes, ESM) project with Airbnb configs as well. Sharing my config files below:

eslintrc.json
```json
{
  "env": {
    "node": true
  },
  "extends": [
    "airbnb-base",
    "airbnb-typescript/base"
  ],
  "ignorePatterns": [
    "/build/**/*"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2022,
    "project": "./tsconfig.json",
    "sourceType": "module"
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "root": true,
  "rules": {
    "import/no-default-export": [
      "error"
    ],
    "import/prefer-default-export": [
      "off"
    ],
    "max-len": [
      "off"
    ],
    "no-console": [
      "off"
    ]
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "./build",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "removeComments": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "target": "ESNext"
  },
  "include": [
    "./src"
  ]
}
```

**Comment by ljharb** [comment]
@mrjackyliang native ESM may work for some rules, but this plugin doesn't fully support it yet.
