### ISSUE TITLE
document how to configure this option

### ISSUE THREAD

**Issue by harm-meijer** [benmosher/eslint-plugin-import#1576]
Would be great if documentation exist on how to configure this rule as with all other rules.

**Comment by ljharb** [comment]
Which rule? This repo is for a plugin that contains many rules.

**Comment by harm-meijer** [comment]
Sorry to waste your time, had lots of linter errors on remote build process but local project did not have any eslinintrc. Mostly are easy to look up but for `import/first` I somehow ended up on wrong pages.

Now I realize the rules are well [documented](https://github.com/benmosher/eslint-plugin-import/tree/master/docs/rules)

**Comment by ljharb** [comment]
Yep, that's right. All eslint rules take a severity first, and then options after if applicable.
