### ISSUE TITLE
Rule proposal: no-core

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#158]
I have seen client app code import Node.js modules, e.g.

```js
import querystring from 'querystring';
```

This will potentially import a huge library that will vary depending on the node version used to build the bundle. Bundle should not depend on the version of node used to build it.

This is hard to catch because it will just work until it suddenly stops with no way to traceback the issue in the code itself.

The rule should restrict `import` to only modules declared in `package.json` (or another strategy used to make sure that Node.js modules are not imported).

**Comment by benmosher** [comment]
Ooo, interesting. Seems to be a similar rule to #126, maybe a `{core: false}` option on such a rule.

**Comment by benmosher** [comment]
need #126 first, to avoid rework, I think. thus the `accepted` label toggle.

**Comment by jfmengels** [comment]
Pretty easy to add, I don't mind adding it. Most of the code needed has been written in eslint-plugin-import-order https://github.com/jfmengels/eslint-plugin-import-order/blob/master/utils.js#L12-L14. It's similar to #126 but doesn't need to have IO since the list of builtin modules is known (and pretty stable too I think).

**Comment by benmosher** [comment]
@jfmengels works for me!

FWIW the resolvers return [`{found: true, path: null}`](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers#resolvesource-file-config---found-boolean-path-string-) for core modules, but I can't think of any cases where this beats a hardcoded list.

Only benefit is that substack/resolve is responsible for maintaining the list. (assuming that's how it's implemented, I haven't looked closely at [`resolve.isCore`](https://www.npmjs.com/package/resolve#resolveiscorepkg))

So fine to start there, at least. I think I'd probably like to ultimately use the resolvers for consistency, but that's just an implementation detail, and I think it can be amended later as a non-breaking change.
