### ISSUE TITLE
Proposal: a new configuration option for the `order` rule

### ISSUE THREAD

**Issue by miraage** [benmosher/eslint-plugin-import#1580]
Hi!

I'm a big fan of organizing imports in a right way, so it makes easier to track dependencies between modules. I played with configuration options and found none of them fitting my vision.

I'd like to propose a new option for `newlines-between`. The name for the option is something like `awlays-outside-and-around-multiline`. I'd like it to work in the following way:
- import groups are always separated by a blank line
- single line imports are placed above multiline imports within a group
- multiline imports are placed to the bottom of a group and separated with a blank line

Consider an example produced by `newlines-between = always-and-inside-groups`, the closest option to the proposed one.

```js
import React from 'react';
import {
  BrowserRouter,
  Redirect,
  Switch,
  Route,
} from 'react-router-dom';

import {
  export1,
  export2,
  export3,
} from 'store/articles';
import { export1 } from 'store/bank';
import {
  export1,
  export2,
  export3,
} from 'store/posts';
import { export1 } from 'store/user';
```

The new option would format in the following way:

```js
import React from 'react';

import {
  BrowserRouter,
  Redirect,
  Switch,
  Route,
} from 'react-router-dom';

import { export1 } from 'store/bank';
import { export1 } from 'store/user';

import {
  export1,
  export2,
  export3,
} from 'store/articles';

import {
  export1,
  export2,
  export3,
} from 'store/posts';
```

I'm not a expert in working with AST and manipulating with nodes/tokens. Would be glad to try myself if this feature looks okay.

**Comment by miraage** [comment]
Another thing came to mind mind is to keep `newlines-between` as `always` and add a boolean flag `newlines-multiline-imports` which would add blank lines around multiline imports.

**Comment by ljharb** [comment]
Why is it more readable for you to have whitespace around multiple imports, but not single imports?

**Comment by miraage** [comment]
@ljharb It could be my very personal perception of code. Here is kind of an algorithm of my eyes scanning the imports:
```js
if (isSingleLineImport) {
  // process immediately
  brain.processImportStatement(line)
} else {
  const imports = []
  for (const line of lines) {
    imports.push(brain.readLine(line))
    eyes.moveToTheNextLine()
  }
  // read line by line, increase accumulator, then process
  brain.processImportStatement(imports.join())
}
```
Having whitespace signalling "hey, there is something complicated. prepare yourself".
Having singleline imports separated does not force me to find it between multiline imports combined with other singleline imports.

Can't tell whether it's really personal or other people have the similar approach of reading code.
