### ISSUE TITLE
Option to make "alphabetize" sorting case insensitive

### ISSUE THREAD

**Issue by AdamWard1995** [benmosher/eslint-plugin-import#1581]
The new "alphabetize" option is great! For those of us migrating from tslint to eslint, it would be nice if we could have an extra option to make this alphabetical sorting case insensitive.

**Comment by ljharb** [comment]
In general, I don't think "tslint has it" is sufficient justification to add anything automatically. However, in this case, that seems like a reasonable option.

**Comment by AdamWard1995** [comment]
@ljharb when do you think the next release will be that will have this change?

**Comment by ljharb** [comment]
When i have time to make it.
