### ISSUE TITLE
`pathGroups` with different behaviour for external and internal groups

### ISSUE THREAD

**Issue by beatriz** [benmosher/eslint-plugin-import#1585]
I am using `pathGroups` to add some extra layers on the import orders. However, it would be nice for it to have the same behaviour on external and internal groups.

Currently, I have 

```
import React from "react";
import Icon from "antd/lib/Icon";
import Menu from "antd/lib/Menu";
``` 

but it would be really nice if I could add 
```
"pathGroups": [
  {
     "pattern": "antd/**",
     "group": "external",
     "position": "after"
  }
]
```
to force the separation of the `antd` imports, as they can be many. Is it possible currently? I find it not working.

**Comment by ljharb** [comment]
I believe this is achieved with the pathGroups option, added in #1386 and available in v2.19.0.

**Comment by beatriz** [comment]
I am using `pathGroups` already, but my issue is the behaviour for external dependencies isn't the same as for internal dependencies.

**Comment by ljharb** [comment]
aha, my mistake - in that case, I think #1570 will address your issue once released.
