### ISSUE TITLE
Timeline/process for next release?

### ISSUE THREAD

**Issue by obweger** [benmosher/eslint-plugin-import#1596]
Team, what are the plans for publishing a new release? I'm quite desperately waiting for recent improvements to `import/order` (alphabetical sorting, `pathGroupsExcludedImportTypes`).

Many thanks,
and apologies if this is already discussed elsewhere.

**Comment by ljharb** [comment]
Like always, there are no concrete plans and no concrete timeline. You can install from git in the meantime.

That said, I’m hoping to have a new version released this week, but no promises.
