### ISSUE TITLE
no-restricted-paths: `accept` config is not working

### ISSUE THREAD

**Issue by lannka** [benmosher/eslint-plugin-import#1599]
The feature was added in 2018 by this [commit](https://github.com/benmosher/eslint-plugin-import/commit/078b6f746b5766511822a95b54c280e900028d1f#diff-7dfeec346b2bbba7abb5c397cb4f22be).

But seems this commit is not included the latest 2.19.1 release ([comparison](https://github.com/benmosher/eslint-plugin-import/compare/v2.19.1...master)). Was it intentional?

**Comment by ljharb** [comment]
It wasn't actually added in 2018; that's just when the commit was authored. It landed in #1238, 9 days ago, and is one of a number of things in master that's still unreleased.
