### ISSUE TITLE
Rule proposal: consistent-relative-path

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#160]
Add option to select between:

``` js
import foo from './../foo';
```

or

``` js
import foo from '../foo';
```

**Comment by gajus** [comment]
If this is accepted, will submit a PR.

**Comment by benmosher** [comment]
Have at them! I forgot to add the `accepted` label when I was classifying these :sweat_smile:

**Comment by ljharb** [comment]
This seems like it's obviated by #912/#471.

Will reopen if there's still a use case here.
