### ISSUE TITLE
Using `import/resolver` in a global config file

### ISSUE THREAD

**Issue by garyking** [benmosher/eslint-plugin-import#1603]
I use a global ESLint config file. It contains most `import` rules, plus:

```js
module.exports = {
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
      },
    },
  },
}
```

I lint with it using the command `eslint . --resolve-plugins-relative-to /Users/gary/.dotfiles/` and a `.eslintrc.js` file of the following, in my projects:

```js
module.exports = {
  extends: '/Users/gary/.eslintrc.js',
};
```

Every `import` rule reports the error: `Resolve error: unable to load resolver "node"`.

This error only started appearing after upgrading from v2.18.2 to v2.20.0.

**Comment by ljharb** [comment]
eslint v6 no longer supports having globally installed plugins/configs, and eslint v7 will disable personal configs entirely. I'm not sure it's worth supporting that (long-deprecated) use case at this point.

**Comment by garyking** [comment]
Got a link for the v7 info? I hadn't heard of that.

I know that v6 doesn't support globally installed stuff. The method I'm using was what eslint recommended. It's been working great, up until this version of this plugin.

**Comment by ljharb** [comment]
Ah - this is, I think, the same issue as #1604 - namely, that you need to add `eslint-import-resolver-node` as an explicit dev dep if you're going to list the node resolver.

**Comment by johanneswilm** [comment]
That was actually not a solution for #1604 .

**Comment by garyking** [comment]
> Ah - this is, I think, the same issue as #1604 - namely, that you need to add `eslint-import-resolver-node` as an explicit dev dep if you're going to list the node resolver.

Nope, installing that didn't fix it for me.

**Comment by ljharb** [comment]
v2.5.2 of eslint-module-utils is released; hopefully that resolves the issue.

**Comment by garyking** [comment]
Yes that fixed it.
