### ISSUE TITLE
Definition for rule 'import/no-unused-modules' was not found 

### ISSUE THREAD

**Issue by fr-irene** [benmosher/eslint-plugin-import#1608]
using `"eslint-plugin-import": "^2.13.0",`

Added this rule in my `.eslintrc`
`"import/no-unused-modules": [1, {"unusedExports": true}],`

I got this error on all files
`1:1  warning  Definition for rule 'import/no-unused-modules' was not found  import/no-unused-modules`

other import rules are working fine

**Comment by ljharb** [comment]
That’s because the rule was added in v2.17. Try updating your semver range to the latest version.

**Comment by VictorDENSC** [comment]
Using "eslint-plugin-import": "2.21.2", I got the same exact issue. 
I'm using the rule as documented though: 
"import/no-unused-modules": [2, {"unusedExports": true, "missingExports": true}]

**Comment by ljharb** [comment]
@VictorDENSC please file a new issue
