### ISSUE TITLE
[import/extensions] 2.20.0 still shows errors for importing TS files from JS files without an extension

### ISSUE THREAD

**Issue by Methuselah96** [benmosher/eslint-plugin-import#1615]
```
C:\projects\path\to\code\ReduxDevTools.jsx
  6:40  error  Missing file extension for "../utilities/cookies"  import/extensions
```
This is the same error I was getting on 2.19.1 (as seen in https://github.com/benmosher/eslint-plugin-import/issues/1558). The error does not appear in 2.18.3.

**Comment by thewilkybarkid** [comment]
We're seeing `Missing file extension "ts" for ...` moving from 2.18.2 to 2.20.0 (refs https://github.com/libero/article-store/pull/174).

**Comment by denisinvader** [comment]
I had the same problem with `.vue` files. I missed this extension in `import/resolver` settings.

This fixed it for me:
```js
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.mjs', '.js', '.json', '.vue'],
      },
    },
  },
```

Try to replace `.vue` with `.ts`

**Comment by thewilkybarkid** [comment]
@denisinvader No luck unfortunately ([plugin:import/typescript](https://github.com/benmosher/eslint-plugin-import/blob/master/config/typescript.js) should still be working anyway).

**Comment by maclockard** [comment]
I'm also getting this error when importing `.ts` files in typescript as well.

Even explicitly changing the settings in my `.eslitntrc` to include `.ts` still results in an error:

```json
  "settings": {
    "import/extensions": [".js", ".mjs", ".jsx", ".js", ".jsx", ".ts", ".tsx"]
  },
```

**Comment by denisinvader** [comment]
@maclockard It seems like `settings['import/extensions']` doesn't work (or logic has changed) after 2.18 and you should use correct `import/resolver` config. 

Do you use [typescript resolver](https://www.npmjs.com/package/eslint-import-resolver-typescript)?

**Comment by Methuselah96** [comment]
Nevermind, this is working correctly for when I set this in the `rules`:
```
    'import/extensions': ['error', 'ignorePackages', {
      js: 'never',
      mjs: 'never',
      jsx: 'never',
      ts: 'never',
      tsx: 'never',
    }],
```

I believe in 2.18.3 it wasn't reporting errors that it should have been reporting based on my config (I was not overriding the default `import/extensions` that is used in airbnb).

**Comment by thewilkybarkid** [comment]
To clarify, when using `airbnb-base` and `plugin:import/typescript` you still need to include the `import/extensions` rule yourself?

**Comment by Methuselah96** [comment]
@thewilkybarkid I think you still need to override `import/extensions` in the `rules` section, not just the `settings` section. I don't know if that's intentional or not.

**Comment by ljharb** [comment]
The airbnb config doesn't include typescript extensions, so yes, you need to override both.

**Comment by thewilkybarkid** [comment]
`plugin:import/typescript` seems to cover `settings`; could `rules` be added there too to cover it?

**Comment by thewilkybarkid** [comment]
Tested locally and that works, so opened https://github.com/benmosher/eslint-plugin-import/pull/1637.

**Comment by javierguzman** [comment]
Hello @thewilkybarkid ! Is your change already in the codebase? I see it was committed however I still get this error. I use  "eslint-plugin-import": "^2.20.1"

**Comment by thewilkybarkid** [comment]
@javierguzman It was closed rather than committed (see https://github.com/benmosher/eslint-plugin-import/pull/1637#pullrequestreview-351678384). For my case I'm switching to using [eslint-config-airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) rather than eslint-config-airbnb-base directly.

**Comment by javierguzman** [comment]
@thewilkybarkid Thanks! I will keep that package in mind, I think for now I will stick with specifying the never rule thing mentioned above...

**Comment by maxiqboy** [comment]
> Nevermind, this is working correctly for when I set this in the `rules`:
> 
> ```
>     'import/extensions': ['error', 'ignorePackages', {
>       js: 'never',
>       mjs: 'never',
>       jsx: 'never',
>       ts: 'never',
>       tsx: 'never',
>     }],
> ```
> 
> and set this in the `settings`:
> 
> ```
>     'import/resolver': {
>       node: {
>         extensions: ['.js', '.jsx', '.ts', '.tsx', '.json']
>       }
>     },
> ```
> 
> I believe in 2.18.3 it wasn't reporting errors that it should have been reporting based on my config (I was not overriding the default `import/extensions` that is used in airbnb which only allows for normal JavaScript files).

I got the same problem with .vue file and it took me a whole day, read every single thread about these 2 rules (import/extensions and import/no-unresolved), and still got errors.

after trying your setting, it works like a charm, and I still have no idea why :-| 

```js
rules: {
 //...
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        mjs: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
        vue: 'never',
      },
    ],
  },
  settings: {
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.json', '.vue'],
      },
    },
  },
```

**Comment by lvdang** [comment]
@Methuselah96 - are you still having this issue for 2.22.0? I am still seeing issue.

**Comment by Methuselah96** [comment]
@lvdang Yeah, this was the solution: https://github.com/benmosher/eslint-plugin-import/issues/1615#issuecomment-577500405.

**Comment by nyngwang** [comment]
@Methuselah96: No, i doesn't work for me:


```
  "rules": {
    "react/function-component-definition": [2, {"namedComponents": "arrow-function"}],
    "indent": ["error", 2, { "ignoredNodes": ["VariableDeclaration[declarations.length=0]"] }],
    "@typescript-eslint/semi": [2, "never"],
    "simple-import-sort/imports": "error",
    "import/extensions": ["error", "ignorePackages", {
      "ts": "never",
      "tsx": "never"
    }]
  },
  "globals": {
    "React": true,
    "ReactDOM": true
  },
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [ ".js", ".jsx", ".ts", ".tsx" ]
      }
    }
  }

```

**Comment by gdibble** [comment]
**For those using `.eslintrc.yml`**, this [alone] worked for me _(derived from @Methuselah96's post [above](https://github.com/import-js/eslint-plugin-import/issues/1615#issuecomment-577500405))_
```yml
rules:
  # js/ts file extensions
  import/extensions: ["error", "ignorePackages", {js: "never", mjs: "never", jsx: "never", ts: "never", tsx: "never"}]
```
