### ISSUE TITLE
[import/order] auto fix not working with side-effect import

### ISSUE THREAD

**Issue by elzup** [benmosher/eslint-plugin-import#1634]
version :eslint-plugin-import@2.18.2

minimum demo repository: https://github.com/elzup/eslint-import-order-sample/blob/master/src/pages/index.js

eslint --fix works

<img width="750" alt="index_js_—_eslint-import-order-sample" src="https://user-images.githubusercontent.com/2284908/73323185-e9483e00-4289-11ea-9489-2409c2c0753b.png">

eslint --fix **NOT** works

<img width="750" alt="index_js_—_eslint-import-order-sample_and____ghq_github_com_elzup-sandbox_eslint-import-order-sample" src="https://user-images.githubusercontent.com/2284908/73323204-fcf3a480-4289-11ea-8731-a30aec1f48fb.png">

**Comment by ljharb** [comment]
Certainly nothing should ever be autofixed across any bindingless import.

**Comment by elzup** [comment]
Oh! That's right. 
Now that I understand that, I feel good about the current specifications.
thanks.

**Comment by elzup** [comment]
and duplicated this issue, sorry.
#1548

**Comment by lgenzelis** [comment]
For anyone arriving here in 2022, [`warnOnUnassignedImports`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#warnonunassignedimports-truefalse) may be what you need: it won't autofix, but it'll warn you, and that's what I wanted.
