### ISSUE TITLE
NPM package has memo-parser's node_modules bundled

### ISSUE THREAD

**Issue by gorner** [benmosher/eslint-plugin-import#1635]
While reviewing the latest changes to this package, I noticed that the latest packaged version of this module on NPM appears to (now) include a bunch of files under `memo-parser/node_modules`, as shown here: https://diff.intrinsic.com/eslint-plugin-import/2.19.1/2.20.0

I expect fixing this would simply require adding this path to .gitignore (in the absence of a .npmignore). I see "node_modules" is already there, perhaps NPM is processing this as the top level directory only.

**Comment by ljharb** [comment]
Hmm - memo-parser/node_modules is already gitignored, so it should be automatically npmignored. This might be an npm bug.

**Comment by ljharb** [comment]
ah nvm, turns out this package is unfortunately using the dangerous `files` field, without excluding nested node_modules. I'll fix this for the next release.

**Comment by benmosher** [comment]
@ljharb FWIW, I think the `memo-parser` can be EOL'd. doesn't make as much perf difference as it did originally.

**Comment by ljharb** [comment]
That’s fine also; it’s never been published that i can see.
