### ISSUE TITLE
Missing docs for imports-first

### ISSUE THREAD

**Issue by lolgab** [benmosher/eslint-plugin-import#1638]
Hi,
I just noticed that imports-first is the only rule that doesn't have a markdown documentation file in `docs/rules` folder.

**Comment by beatrizrezener** [comment]
Hi!
As I think this is due to `imports-first` being a depreciated alias, renamed to `first` ([docs/rules/first.md](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md)), I would like to know if you still think it would be interesting to have some documentation about it.

**Comment by ljharb** [comment]
@beatrizrezener thanks, good point :-) perhaps a symlink to the first docs would work?

**Comment by beatrizrezener** [comment]
Hi guys,
I have tested and it works well on macOS, unfortunately I have seen that unix **symlink** files are different from windows, so it didn't work there :( 

Also, I didn't find a way to make symlinks work in GitHub, although it identifies that it is a symlink file (the icon is different).

![image](https://user-images.githubusercontent.com/3225662/85409613-67a8c380-b53c-11ea-8622-e6e41a1933fc.png)

I don't know how common it is to use symlinks on github projects, so maybe you can enlighten me if it's okay to go on like this or if it would be better to just create a file that says it was replaced by `first`. A suggestion: https://github.com/beatrizrezener/eslint-plugin-import/commit/a2a755784b51aede7525cf79fa208498daff7fb6

**Comment by lolgab** [comment]
> I don't know how common it is to use symlinks on github projects, so maybe you can enlighten me if it's okay to go on like this or if it would be better to just create a file that says it was replaced by first. A suggestion: beatrizrezener@a2a7557

I'd say an honest deprecation notice it's much better than doing workarounds with system links that can create misconceptions.
