### ISSUE TITLE
Doesn't seem to support yarn v2

### ISSUE THREAD

**Issue by fifn2** [benmosher/eslint-plugin-import#1642]
Yarn v2 recently came out with a new module directory structure that doesn't seem to be supported by eslint-plugin-import.

**Comment by ljharb** [comment]
I’m quite aware of it; see #1591, a PR from the yarn maintainer to make it compatible.

Are you on the latest version of the plugin?

**Comment by AlexandreBonaventure** [comment]
I'm running latest version of the plugin (2.20.1) and with yarn v2 I run into :
`Resolve error: unable to load resolver "node"` erros

**Comment by ljharb** [comment]
I believe you'll need to add `eslint-plugin-resolver-node` to your top-level dev deps; either way, I think issues with yarn need to be filed on yarn.

**Comment by constgen** [comment]
Looking to this changes seems like it fixes only cases when `eslint-plugin-import` is installed directly in the project. But if the project imports another config which includes `eslint-plugin-import` then it doesn't work with Yarn 2. 

So speaking simply the bug still persists. You just have to use dependency structure `root-project-taht-is-linted` -> `my-custom-eslint-config` -> `eslint-plugin-import` to reproduce it

**Comment by ljharb** [comment]
@constgen anything that works in npm but breaks in yarn 2 is a bug in yarn 2; please feel free to file it there.
