### ISSUE TITLE
[import/first] Impossible to turn off absolute-import from dervied config

### ISSUE THREAD

**Issue by TheCrueltySage** [benmosher/eslint-plugin-import#1661]
The base config we use sets
`'import/first': ['error', 'absolute-first'],`
However, while we want the imports to be at the top, we don't need them to be sorted beyond that. As such, we don't need 'absolute-first' set.
Before, we redefined the rule through
`"import/first": ["error", ""],`
However, since 2.20.1 the config only allows 'absolute-first' string in options. Since there is only one option to redefine, and severity changes don't override options, it is impossible to unset 'absolute-first' from derived config right now.

This seems like unintended behavior.
Could you perhaps add an option to explicitly turn off absolute-first?

**Comment by ljharb** [comment]
That seems perfectly reasonable, a PR is welcome.

**Comment by TheCrueltySage** [comment]
Alright.
Should another option be just an empty string or something like 'disable-absolute-first'? Not sure which is the preferred way.

**Comment by TheCrueltySage** [comment]
Any news on the PR I made?
