### ISSUE TITLE
Interest in adding "no-restricted-glob-paths" rule?

### ISSUE THREAD

**Issue by vladimiry** [benmosher/eslint-plugin-import#1662]
- `no-restricted-paths` doesn't support globs.
- `no-restricted-imports` supports globs/git-ignore-like but just as strings, no path resolving support.

So if there is an interested I think I could PR the `no-restricted-glob-paths` rule. The functionality would be similar to https://github.com/vladimiry/tslint-rules-bunch.

I would prefer to use https://github.com/micromatch/picomatch module for globbing even though the `minimatch` module [is already used](https://github.com/benmosher/eslint-plugin-import/blob/12971f5ced52ede943515fac23b81b2a8d38ba60/package.json#L100). The reason is that `picomatch` [is faster](https://github.com/micromatch/picomatch#benchmarks) and supports arrays of patterns for both `str / pattern` arguments on [ismatch(str, pattern)](https://github.com/micromatch/picomatch#ismatch) function call.

Proposed configuration schema (`basePath` props both on top/zone levels are optional):
```javascript
schema: [{
  type: 'object',
  required: ["zones"],
  properties: {
    basePath: {type: ["string"]},
    zones: {
      type: "array",
      minItems: 1,
      items: {
        type: "object",
        required: ["target", "from"],
        properties: {
          basePath: {type: ["string"]},
          target: {
            anyOf: [
              {type: "string"},
              {type: "array", items: {type: "string"}},
            ],
          },
          from: {
            anyOf: [
              {type: "string"},
              {type: "array", items: {type: "string"}},
            ],
          },
        },
        additionalProperties: false,
      },
    },
  },
  additionalProperties: false
}]
```

Configuration example:
```json
{
  "plugins": [
    "import"
  ],
  "settings": {
    "import/resolver": {
      "typescript": {}
    }
  },
  "rules": {
    "import/no-restricted-glob-paths": [
      "error",
      {
        "zones": [
          {
            "target": "src/electron-main/**/*",
            "from": [
              "./**/*",
              "!./node_modules/**/*",
              "!src/electron-main/**/*",
              "!src/shared/**/*"
            ]
          },
          {
            "basePath": "./src",
            "target": [
              "!./electron-main/database/entity/**/*",
              "!./electron-main/database/validation.ts"
            ],
            "from": [
              "./electron-main/database/entity",
              "./electron-main/database/entity/**/*"
            ]
          }
        ]
      }
    ]
  }
}
```

#1132 is a possibly related issue, CC @Bessonov

**Comment by ljharb** [comment]
It seems like the first step would be adding path resolution configuration to `no-restricted-imports`, and then adding globs to `no-restricted-paths` - rather than a whole new rule.

As for switching from micromatch to something else, that would ideally be done in a separate PR.

**Comment by vladimiry** [comment]
Thanks for prompt and thoughtful response. Closing the issue as rejected.

> and then adding globs to `no-restricted-paths` - rather than a whole new rule.

`no-restricted-paths` supports `except` logic which after adding globs support won't make much sense since globbing handles the exceptions case. Dropping `except` logic support would be a breaking change.

> It seems like the first step would be adding path resolution configuration to `no-restricted-imports`

As I see it, `no-restricted-imports` serves a different need focusing on checking the names of the imports. So if we mix checking the import names and paths into a  single rule then the rule will likely get working slower since will be handling mixed logic.

**Comment by ljharb** [comment]
We could still add the glob support, and then plan to remove `except` in the future - they seem like they could coexist.

That's a really good point about `no-restricted-imports`. You can already use eslint's `overrides`, which has glob support, to target any files with any distinct config, so that's probably the better approach anyways?

**Comment by vladimiry** [comment]
> We could still add the glob support, and then plan to remove except in the future - they seem like they could coexist.

What if we make `zones` array to include second object type? So we keep existing `zones` object type and we change nothing in the respective logic. But we add a second object type and apply new logic with glob support for this object. If we go this way then there will be no breaking changes.

So the `zones` array type would look like:

```typescript
interface Options {
    zones: Array<
        // currently supported options zone type
        | {
            target: string;
            from: string;
            except?: string[];
        }
        // new options zone type which gets new handling logic
        // that doesn't interfere with existing logic
        | {
            basePath?: string;
            targetGlob: string | string[];
            fromGlob: string | string[];
        }
    >;
}
```

**Comment by vladimiry** [comment]
The issue about using `picomatch` is that [it declared support for "node >=8.6"](https://github.com/micromatch/picomatch/blob/66e1b200f3ea1784bdeae0770c8e5cd95f55e334/package.json#L18-L20) only. But `eslint-plugin-import` module declares https://github.com/benmosher/eslint-plugin-import/blob/12971f5ced52ede943515fac23b81b2a8d38ba60/package.json#L6

**Comment by ljharb** [comment]
Ah, in that case we can't use it. We support down to eslint 2, and need to support the same node versions that a supported version of eslint does (which, for eslint 2, is [v0.10](https://unpkg.com/browse/eslint@2.13.1/package.json), so we're already not achieving the goal, but eslint 2 is quite old).

Your suggestion for the schema seems viable.

**Comment by vladimiry** [comment]
> We support down to eslint 2, and need to support the same node versions that a supported version of eslint does

Got it. So `v2.20.1 => v6.x eslint-plugin-import` bump is not considered.

Unfortunately I would not be interested in implementing glob support in `no-restricted-paths` using `minimatch` module having known that there are better options (`minimatch` by the doesn't declare `engines.node` prop but it runs [node 4,6,7 only](https://github.com/isaacs/minimatch/blob/bafa295617d984c5863b13a33b2bb601c67e4a8b/.travis.yml#L3-L6) on Travis). So closing the issue again, this time with `won't fix` status.
