### ISSUE TITLE
(0.12.1) no-commonjs, no-amd missed in package?

### ISSUE THREAD

**Issue by ALF-er** [benmosher/eslint-plugin-import#167]
In version 0.12.1 there are no such rules in package on npm.

**Comment by benmosher** [comment]
That's right. They are as-yet-unpublished.

I should publish right now. :+1:

**Comment by ALF-er** [comment]
Oh =) Ok. Thank you!

**Comment by benmosher** [comment]
Sorry, got caught up in something else, but I will publish 0.12.2 ASAP. 😁
