### ISSUE TITLE
`Can't find module` when using monorepo / yarn workspaces 

### ISSUE THREAD

**Issue by simkessy** [benmosher/eslint-plugin-import#1677]
I'm trying to setup yarn workspaces with my docker instance. This is my directory structure: 

    /monorepo/
      /node_modules/
            @libs/common
            @services/common
            @services/project-A
            ...OTHER DEPS...
      package.json
      /services/
          /common/
             index.jsx
             package.json
          /project-A/  
               webpack.base.config.js
               **REACT project with babel, webpack, etc**
     
      /libs/
         /tools/
             /common/
                index.jsx
                package.json
                
To simplify my docker setup I just configured this volume within my docker compose that maps the entire monorepo directory: 

```    
volumes:
      - '../../../monorepo:/monorepo'
```

From there in my Project-A I import @libs/common and @services/common. This works fine when the common libraries are exporting simple functions like: 

`export const Add = (a,b) => a+b`

Webpack has no issue resolving this and building Project-A. 

However when I try to import a component from one of the common libraries like this: 

    /libs/tools/common: 
    
          import React from 'react' 
          export MySharedComponent = () => <>HELLLO</>

I get an error in the build process: 

     Error: Cannot find module '/monorepo/libs/tools/common/webpack.base.config.js'
    Require stack:
    - /monorepo/node_modules/eslint-import-resolver-webpack/index.js
    - /monorepo/node_modules/eslint-module-utils/resolve.js
    - /monorepo/node_modules/eslint-plugin-import/lib/rules/no-unresolved.js
    - /monorepo/node_modules/eslint-plugin-import/lib/index.js

The eslint file under Project-A: 

    {
        "parser": "babel-eslint",
        "env": {
          "browser": true,
          "node": true,
          "jest": true,
          "cypress/globals": true
        },
        "settings": {
          "import/resolver": {
            "webpack": {
              "config": "webpack.base.config.js"
            }
          }
        }
      }

The babel.rc under Project-A

    {
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": {
              "node": "current"
            }
          }
        ],
        "@babel/preset-react",
        "@babel/preset-flow"
      ],
      "env": {
        "test": {
          "plugins": [
            [
              "babel-plugin-webpack-alias",
              {
                "config": "./webpack.base.config.js"
              }
            ]
          ]
        }
      }
    }

My Question: 

 - Is the main issue that there's no webpack config set up in the common repositories. Therefore the workspace does not know how to compile my shared resources? 

 - Should there only be 1 webpack build config in my workspace used by all projects within the workspace? Currently I only have 1 config under Project-A? 

 - What happens if I have specific webpack needs per project, does 1 config (if that's the answer) make sense?

**Comment by ljharb** [comment]
I'm not sure why linting gates the build process, that doesn't make any sense to me - it should be a distinct thing, just like tests.

Does project A have a package.json?

**Comment by simkessy** [comment]
Yea `Project-A` has a `babelrc` `webpack.config.js` etc. 
The common project has nothing really, just a package.json and index.jsx file with this: 

```
import React from "react";

export const MyCommonComponent = () => {
    function sayHello() {
        alert("Hello, World!");
    }

    return <button onClick={sayHello}>Click me!</button>;
};
```

**Comment by ljharb** [comment]
If linting isn't being run as part of webpack, it seems like your webpack configuration needs to be fixed first?

**Comment by simkessy** [comment]
This is the webpack config I have in `project-a`

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');

const TerserPlugin = require('terser-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

const HappyPack = require('happypack');

const happyThreadPool = HappyPack.ThreadPool({ size: 5 });
// const {BundleAnalyzerPlugin} = require('webpack-bundle-analyzer')
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');

const smp = new SpeedMeasurePlugin();

const ROOT_PATH = path.resolve(__dirname);

// Compile all css into one css file
const ExtractPlugin = new MiniCssExtractPlugin({
  filename: '[name].bundle.css'
});

const PrettyEsLintFormatter = require('eslint-formatter-pretty');

const baseConfig = {
  // Each key value generate a page specific bundle
  entry: {
    app: './src/index.jsx',
    review: './src/review.jsx'
  },
  module: {
    rules: [
      {
        // will compile both js and jsx files
        // 'pre' will make sure it checks linting before it's compiled
        enforce: 'pre',
        test: /\.(js|jsx)$/,
        loader: 'eslint-loader',
        exclude: /node_modules/,
        options: {
          configFile: path.resolve(__dirname, './.eslintrc'),
          formatter: PrettyEsLintFormatter,
          cache: true,
          // fix: false,
          emitWarning: true,
          // emitError: false,
          // failOnError: false,
          failOnWarnings: false
          // quiet: true,
        }
      },
      {
        test: /\.(js|jsx)$/,
        use: 'happypack/loader?id=jsx',
        exclude: /node_modules/
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: 'happypack/loader?id=css'
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          'cache-loader',
          {
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'fonts/'
            }
          }
        ]
      }
    ]
  },

  // Optimizations
  optimization: {
    minimizer: [
      new TerserPlugin({
        cache: true,
        parallel: true,
        sourceMap: true, // Must be set to true if using source-maps in production
        terserOptions: {
          // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
        }
      })
    ]
  },

  // Automatically resolve below extensions
  // Enable users to leave off the extensions when importing
  resolve: {
    extensions: ['*', '.js', '.jsx', '.css', '.scss'],
    alias: {
      Root: path.resolve(__dirname),
      Utils: path.resolve(__dirname, './src/utils/'),
      Hoc: path.resolve(__dirname, './src/hoc/'),
      Components: path.resolve(__dirname, './src/components/'),
      'react-dom': '@hot-loader/react-dom'
    }
  },
  output: {
    path: path.resolve(ROOT_PATH, 'dist'),
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].bundle.js'
  },
  plugins: [
    ExtractPlugin,
    new CleanWebpackPlugin(),
    new HappyPack({
      id: 'css',
      threadPool: happyThreadPool,
      loaders: [
        'cache-loader',
        'style-loader',
        {
          loader: MiniCssExtractPlugin.loader,
          options: {
            hmr: true
          }
        },
        'css-loader',
        'sass-loader'
      ]
    }),
    new HappyPack({
      id: 'jsx',
      threadPool: happyThreadPool,
      loaders: ['cache-loader', 'babel-loader']
    })
  ]
};

module.exports = () => smp.wrap(baseConfig);
```

**Comment by ljharb** [comment]
I think it's important to verify that webpack works (or does not work) separately from eslint, that way we can figure out who's best able to help you.

**Comment by simkessy** [comment]
Ok well I removed the babel portion of my webpack settings and tried testing that but I get this error 

![image](https://user-images.githubusercontent.com/5871660/75940156-123b9000-5e41-11ea-8399-d90818eb9b4a.png)

Seems like it's not recognizing that my shared component is a react component?

**Comment by ljharb** [comment]
You need babel to parse jsx; this repo is an eslint plugin tho, so it's important to establish if it works or not both with and without eslint.

**Comment by ljharb** [comment]
Happy to reopen if it ends up being related to this eslint plugin.

**Comment by dirkpostma** [comment]
Not sure if it helps in this particular case, but I solved a similar issue by adding `"types":` property to the `package.json` of the dependency. Similar to the `"main"` prop, but for types.

Example:

`"types": "src/types.d.ts",` 

https://stackoverflow.com/questions/66081171/lerna-yarn-and-typescript-cannot-find-module-or-its-corresponding-type-declar

**Comment by aikhan** [comment]
Lif

> Not sure if it helps in this particular case, but I solved a similar issue by adding `"types":` property to the `package.json` of the dependency. Similar to the `"main"` prop, but for types.
> 
> Example:
> 
> `"types": "src/types.d.ts",`
> 
> Reference: https://stackoverflow.com/questions/66081171/lerna-yarn-and-typescript-cannot-find-module-or-its-corresponding-type-declar

Life saver

**Comment by aikhan** [comment]
> Not sure if it helps in this particular case, but I solved a similar issue by adding `"types":` property to the `package.json` of the dependency. Similar to the `"main"` prop, but for types.
> 
> Example:
> 
> `"types": "src/types.d.ts",`
> 
> Reference: https://stackoverflow.com/questions/66081171/lerna-yarn-and-typescript-cannot-find-module-or-its-corresponding-type-declar

Life saver
Wasted countless hours on this
