### ISSUE TITLE
Support Custom Paths

### ISSUE THREAD

**Issue by inmogr** [benmosher/eslint-plugin-import#1687]
Hi,

Sorry not sure if this is already supported but searched a lot and did not find what I'm looking for.
In my case I'm using custom path feature from type script where I can define `paths` in `tsconfig` and typescript will understand that the given path is not from `node_modules` but from the predefined path in `tsconfig`

lets say in my tsconfig I have the following:
```
{
    ...
    "compilerOptions": {
        "paths": {
            "my-example-name": [
                "./actual-directory-name"
            ]
        }
        ...
    },
    ...
}
```

I have huge advantages using this feature but now I'm switching from tslint to eslint and thought of this plugin and I got stuck on how to make eslint and this plugin get to understand that the `"my-example-name"` is referring to the directory `"./actual-directory-name"`

**Comment by ljharb** [comment]
You'd need a typescript resolver for that.
