### ISSUE TITLE
Can a new release be cut please to fix default export issues?

### ISSUE THREAD

**Issue by maniator** [benmosher/eslint-plugin-import#1697]
My team has been waiting for the changes introduced here to be released: https://github.com/benmosher/eslint-plugin-import/pull/1640

Thanks :-)

**Comment by ljharb** [comment]
There will be a new release when I have time to cut one.

**Comment by maniator** [comment]
Can someone else release somehow? :-) 

been a while

^_^

**Comment by ljharb** [comment]
It's been 3 weeks on a project with one primary maintainer that you get for free during a global pandemic, i think you can be patient.

**Comment by maniator** [comment]
Thank you @ljharb for the release!

It works amazing :-)
