### ISSUE TITLE
import/no-extraneous-dependencies not working on windows

### ISSUE THREAD

**Issue by SkReD** [benmosher/eslint-plugin-import#1698]
**What I am doing:**
Lint file with `import/no-extraneous-dependencies` enabled and which importing `debug` module, that is not presented in `package.json` dependencies

**Expected behavior:**
The error should be displayed

**Actual behavior:**
Linting finish successfully 

**OS:**
Windows 10 x64 1809

**Investigation**
Find problem in function `importTypes -> isSubpath`. It not treating module as external because of working only with forward slashes as path separators. Looks like normalization for paths is needed.

**Comment by ljharb** [comment]
`debug` is a core module. It doesn't have to be in package.json.

**Comment by SkReD** [comment]
`https://github.com/visionmedia/debug`. Any way other module imports are not linted either. Reopen please.

**Comment by ljharb** [comment]
I'm aware you can install it, but it's a core module - thus, the rule doesn't warn on it.

If you require `debug/` instead, you'll get the installed one, and the linter will warn on it if it's not in package.json.

What other imports?

**Comment by SkReD** [comment]
`lru-cache`, `classnames`

**Comment by SkReD** [comment]
And rule erroring on `debug` import if run with `bash` console through wsl

**Comment by ljharb** [comment]
A PR with a failing test case on windows would be great; then i can validate when it's fixed.

**Comment by SkReD** [comment]
This is fixed here https://github.com/benmosher/eslint-plugin-import/commit/47f912e74eccbb6009ea5778a7cdb33e918dd495. Tests for `no-extraneous-dependencies` are passing on windows now.
