### ISSUE TITLE
Flow type export awareness for import/group-exports rule

### ISSUE THREAD

**Issue by ernestostifano** [benmosher/eslint-plugin-import#1702]
When using `import/group-exports` rule, the following statements are considered problematic. I am being asked to group them in a single export.

```js
export type {FormAPI};
export {Form};
```

However, Flow type exports and JS exports can not be grouped.

Shall this be ignored by the rule? Shall we add some kind of rule option to customize this behaviour? Currently I can not see anyway to workaround this.

**Comment by ljharb** [comment]
Seems like it should ignore this by default.

**Comment by ernestostifano** [comment]
@ljharb I have already fixed this issue. Will submit a PR.
