### ISSUE TITLE
v2.20.2 - import/order - issue with pathGroups and alphabetize

### ISSUE THREAD

**Issue by gamegee** [benmosher/eslint-plugin-import#1714]
## Issue with the import/order rule
I want to add custom pathGroups
Not sure if I have a wrong configuration or if the issue come from the plugin.

### Current configuration
```
"import/order": ["error", {
  "pathGroups": [
    {
      "pattern": "src/**",
      "group": "internal",
      "position": "after"
    },
    {
      "pattern": "app-redux/**",
      "group": "internal",
      "position": "before"
    }
  ],
  "groups": [["builtin", "external"], "internal", "parent", "sibling"],
  "newlines-between": "always"
}]
```

### Expected behavior
I expect the command `eslint --fix` to format the imports like this.
```
import React from 'react'

import formStyles from 'src/styles/form'

import { getLocationsByAccountId } from 'app-redux/modules/locations/selectors'
import { fetchAccount } from 'app-redux/modules/locations/actions'

import AnnounceBar from '../AnnounceBar'

import accountId from './accountId'
```

### Current behavior
It looks like the pattern `app-redux` and `src` are not handled with the pathGroups.
```
import React from 'react'
import formStyles from 'src/styles/form'
import { getLocationsByAccountId } from 'app-redux/modules/locations/selectors'
import { fetchAccount } from 'app-redux/modules/locations/actions'

import AnnounceBar from '../AnnounceBar'

import accountId from './accountId'

```

### Current behavior with the alphabetize option
Note: the `alphabetize` option when set to `true` will break all eslint import behavior.
When I set the the option
```
"alphabetize": {
   "order": "asc"
}
```
I have the following behavior (newlines between each import statement, even in the same group)
```
import { fetchAccount } from 'app-redux/modules/locations/actions'

import { getLocationsByAccountId } from 'app-redux/modules/locations/selectors'

import React from 'react'

import formStyles from 'src/styles/form'

import AnnounceBar from '../AnnounceBar'

import accountId from './accountId'
```

**Comment by ljharb** [comment]
I'm a bit confused as to what you want versus what's happening. Would you be willing to make a PR with failing test cases?

**Comment by gamegee** [comment]
## Update - resolved

@ljharb I want to add custom import group for internal packages
I was able to make it work by defining custom `import/resolver` in my eslint config:

```tsx
//eslintrc.json

"settings": {
  "import/resolver": {
    "node": {
      "paths": ["app/", "packages/"]
    }
  }
}
```

Here is my project structure if it can help:

```
/app
  /src
    ...
/packages
  /app-redux
    ...
```
