### ISSUE TITLE
Definition for rule 'import/no-require' was not found

### ISSUE THREAD

**Issue by mericsson** [benmosher/eslint-plugin-import#173]
Getting this for any files using 'import'.

`warning  Definition for rule 'import/no-require' was not found  import/no-require`

Any ideas?  Other import rules are working such as:
`error    No default export found in module                       import/default`

Thanks!

.eslintrc
```
{
  "extends": ["airbnb/base", "import/warnings"],
  "parser": "babel-eslint",
  "plugins": ["modules", "import"],
  "rules": {
    "strict": 0
  }
}
```

package.json
```
"devDependencies": {
    "babel-eslint": "^4.1.8",
    "eslint": "^1.10.3",
    "eslint-config-airbnb": "^4.0.0",
    "eslint-config-import": "^0.9.1",
    "eslint-plugin-import": "^0.13.0",
    "eslint-plugin-modules": "^1.1.1"
  }
```

**Comment by benmosher** [comment]
Ah, dang. I need to update the shared config. `import/no-require` was replaced with `import/no-commonjs` in 0.13.

**Comment by benmosher** [comment]
Just published a new `eslint-config-import`. Also added tests and set the `peerDependencies` to peg it to the matched version (for now). Should be less of an issue with ESLint v2.

Thanks for the issue! :sweat_smile:
