### ISSUE TITLE
no-named-as-default-member.md has broken link

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [benmosher/eslint-plugin-import#1731]
The page has the sentence

> Furthermore, [in Babel 5 this is actually how things worked](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0). This was fixed in Babel 6. 

However the link is broken and it is hard to understand the sentence without more explanation

**Comment by ljharb** [comment]
While it's very sad that @kentcdodds has broken a URL ([cool URLs don't change](https://www.w3.org/Provider/Style/URI)); luckily, archive.org can save us: https://web.archive.org/web/20170108102530/https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0

**Comment by kentcdodds** [comment]
Blame medium.

https://kcd.im/tears

**Comment by ljharb** [comment]
Thanks, now i do :-) I’ll update the link to that one soon.
