### ISSUE TITLE
eslint rule 'import-order' was not found

### ISSUE THREAD

**Issue by cc616** [benmosher/eslint-plugin-import#1738]
![image](https://user-images.githubusercontent.com/9332135/80552881-99008980-89fa-11ea-94ba-ec593336de7e.png)
when i has setting eslint rules with "import/order" in , but it error, how i config this rule
this is my eslintrc file
![image](https://user-images.githubusercontent.com/9332135/80553276-c994f300-89fb-11ea-8fc9-066a75c4603f.png)

**Comment by ljharb** [comment]
The rule name is `import/order`, not `import-order`.
