### ISSUE TITLE
Unusual slowness with yarn 2 PnP feature

### ISSUE THREAD

**Issue by larowyn** [benmosher/eslint-plugin-import#1741]
Hi,

I realize that part of this issue is probably tied to the module resolution of yarn 2 Plug'n'Play being somewhat slower than the classic module resolution (with node_modules) and not directly to this plugin, but the difference between the two is so huge that it probably deserves to be pointed out.

Here is the (ridiculous) timing on a subset of my codebase with the yarn 2 PnP setup:

```
Rule                            |  Time (ms) | Relative
:-------------------------------|-----------:|--------:
import/no-cycle                 | 466543.870 |    76.3%
import/namespace                |  72755.307 |    11.9%
import/no-deprecated            |  69208.805 |    11.3%
indent                          |    302.711 |     0.0%
react/no-unknown-property       |    158.732 |     0.0%
react/destructuring-assignment  |    111.274 |     0.0%
import/no-unresolved            |     94.284 |     0.0%
no-unused-vars                  |     63.699 |     0.0%
react/prefer-stateless-function |     63.131 |     0.0%
react/no-deprecated             |     60.052 |     0.0%
```

10 minutes of eslint eating up 100% of my CPU.

For reference when ran on the full codebase (still relatively small) with a classic node_modules/ setup:

```
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
import/no-cycle                     |   683.181 |    16.1%
indent                              |   409.251 |     9.7%
import/namespace                    |   350.774 |     8.3%
react/no-unknown-property           |   302.858 |     7.1%
import/no-unresolved                |   191.842 |     4.5%
react/destructuring-assignment      |   123.256 |     2.9%
react/prefer-stateless-function     |    97.292 |     2.3%
react/no-deprecated                 |    86.106 |     2.0%
react/void-dom-elements-no-children |    71.407 |     1.7%
no-unused-vars                      |    57.248 |     1.4%
```

My best guess is that since with yarn 2 PnP there are no more `node_modules/`, instead the dependencies are kept in `.yarn/cache/` as `.zip` files, resolving them takes longer and since eslint-plugin-import is probably trying to resolve a ton of modules to do his job it takes a long time.

That said, that's the first thing for which that supposedly slower resolve (I don't actually know if it's true or not, that's just a guess) is an issue for me. Webpack handles it fine for example.

So maybe, and again I'm guessing here, eslint-plugin-import could keep a "cache" of the modules it already resolved instead of re-resolving a module when it sees it again? 

Let me know if you want more information.

**Comment by ljharb** [comment]
That is certainly *much* slower than it usually takes the ExportMap to be populated (which the first rule that uses it needs to do) - typically it's no more than 30s even on very large repos.

>  eslint-plugin-import could keep a "cache" of the modules it already resolved instead of re-resolving a module when it sees it again?

It does, building that up is the initial slowness you see regardless (that's the ExportMap).

cc @arcanis; is there any reason you can think of that building up our ExportMap would be this much slower in yarn v2?

**Comment by arcanis** [comment]
It would be useful to see a performance report from `--inspect-brk` - we use plugin-import at work but we didn't notice such slowdown. The resolution itself should be pretty fast (perhaps faster than Node), since all the resolutions are computed from data kept in memory.

That would suggest the loss happens with file loading, which may happen depending on how files are read. Ideally file loads should be collocated - we keep a store of at most 80 zip archives loaded at the same time, using a basic FIFO queue to garbage collect the stale ones. Loading one file from 200 different packages ten times will be less efficient than traversing package by package.

That's my best guess, but it's surprising it doesn't happen with Webpack or similar. If you have a reproduction I can give it a look, otherwise the report might be enough.

**Comment by larowyn** [comment]
Thanks for the quick responses.

For a reproduction I would need time, the repository is private so I would have to setup something alike. If the profile isn't enough, let me know and I'll try to get it done when I have the time.

Also I forgot to mention that I'm also using the workspaces feature of yarn, I thought that might be a factor since I import some package from other workspaces.

I couldn't run eslint with `--inspect-brk` for some reason it wouldn't work, but I managed to run it with `--inspect` and click very fast on record ^^. So hopefully you won't need the start of the record. Also the profiling of the whole codebase was too large and crashed the dev console so that's the profiling for one of the main offender, this one file takes several minutes.

[CPU-20200501T140819.cpuprofile.zip](https://github.com/benmosher/eslint-plugin-import/files/4564159/CPU-20200501T140819.cpuprofile.zip)

**Comment by arcanis** [comment]
Thanks! Looking at the profile (using [this tool](https://moar-things.github.io/moar-profile-viewer/)), I don't see anything wrong with the Yarn layer 🤔 In particular:

- `resolveRequest` (the resolution function) only takes 175ms total
- The zip-enhanced `readFileSync` wrapper is at 642ms

It would hint that something is wrong in eslint-plugin-import, but I'm not sure what could change from the nm linker. The parsing seems awfulling slow though...

**Comment by larowyn** [comment]
I figured out the problem, one of my own package had the main property of the package.json pointing to the built version so eslint was parsing that built version instead of the sources.
Correcting that, fixes it.

**Comment by ljharb** [comment]
I'm not sure why that would make a difference :-/
