### ISSUE TITLE
import/order sorts differently from VSCode/Typescript

### ISSUE THREAD

**Issue by chengyin** [benmosher/eslint-plugin-import#1742]
VSCode/TypeScript can automatically organize imports in JS/TS code.

Unfortunately, TypeScript sorts `_` after letters, leading to a different order from what `import/order` is expecting:

**Config:**
```
"import/order": ["error", { "alphabetize": { "order": "asc" } }],
```

**VSCode/TypeScript**
```
import PostView from '../views/PostView';
import Posts from '../../__fixtures__/Posts';
```

**import/order**
```
import Posts from '../../__fixtures__/Posts';
import PostView from '../views/PostView';
```

The difference was from TypeScript using `toUpperCase` while this plugin is using `toLowerCase`:

https://github.com/benmosher/eslint-plugin-import/blob/92caa3594e0f8d7bf143dedba0c7c2b47b541f34/src/rules/order.js#L282

TSLint had the same issue. [TypeScript developer decided to not change their core sorting function](https://github.com/microsoft/TypeScript/issues/25114#issuecomment-399288393), and provided a reason for using `toUpperCase`. TSLint [made the change on their end](https://github.com/palantir/tslint/pull/4064/files).

This isn't necessarily a bug for import/order to resolve, however, there is currently no way to config import/order to behave the same way as VSCode/Typescript. Your thoughts on how could we resolve the difference is appreciated.

**Comment by ljharb** [comment]
The best resolution is probably to disable vscode formatting (which you should do anyways) and delegate to eslint entirely.

**Comment by marcotoniut** [comment]
Wasn't this issue closed a bit too prematurely, perhaps? Some option to configure the feature wouldn't be as bad of an idea, as the TypeScript devs do make [a good point](https://github.com/microsoft/TypeScript/issues/25114#issuecomment-399288393) on their reasoning for upper case comparisons. Something like:

```ts
// @default "lowercase"
"caseInsensitiveCompare": ["uppercase", "lowercase"]
```

**Comment by ljharb** [comment]
I agree that Typescript should offer such a configuration option.

**Comment by marcotoniut** [comment]
I wouldn't mind that too much either, personally. Although, I can see how it could turn into a cumbersome situation than just having the correct eslint plugin deal with it at a project level. Is there a technical reason as to why `eslint-plutin-import` wouldn't support this? Or is it just personal preference? Over-complication of the API?

**Comment by ljharb** [comment]
It definitely would be adding complexity to the API.

There's a lot of things about default vscode formatting that are terrible, and given that eslint exists, I don't see any value in encouraging the use of "not eslint" to format JS or JS-adjacent code. Disabling vscode's autoformatting and deferring to eslint is an important part of a developer's journey, and hastening it helps everyone.

**Comment by ericanderson** [comment]
For others that find this in the future, typescript now will try to sort the way eslint does:

https://github.com/microsoft/TypeScript/issues/52292#issuecomment-1387466638

**Comment by nemchik** [comment]
Additional note for those who find this in the future:
The documentation https://github.com/import-js/eslint-plugin-import/blob/v2.28.1/docs/rules/order.md#groups-array shows an example of nested grouping. Nesting `builtin` and `external` together in the default order seems to satisfy TypeScript's `organizeImports` language server function (used by VSCode's `Organize Imports` feature).

```json
"import/order": [
  "error",
  {
    "groups": [
      [
        "builtin",
        "external"
      ],
      "parent",
      "sibling",
      "index"
    ]
  }
]
```

Also, just to note, I'm not using VSCode's `Organize Imports` but rather https://www.npmjs.com/package/prettier-plugin-organize-imports which uses the same `organizeImports` function from the TypeScript language server.

---

If the maintainers here are willing to accepting a PR to change https://github.com/import-js/eslint-plugin-import/blob/87051212306f8cd08cb62555b94fae259146468c/src/rules/order.js#L11 to:

```js
const defaultGroups = [['builtin', 'external'], 'parent', 'sibling', 'index'];
```

I don't mind to open a PR for this.

**Comment by ljharb** [comment]
That would be a breaking change, so we couldn’t accept it.
