### ISSUE TITLE
Support ESLint 7.0.0

### ISSUE THREAD

**Issue by janKir** [benmosher/eslint-plugin-import#1752]
Having eslint@7.0.0 installed results in a peer-dependency warning: 
```
eslint-plugin-import@2.20.2" has incorrect peer dependency "eslint@2.x - 6.x".
```
Can you please support the new eslint version? :) 

(For me, everything still works fine, so maybe only the peer-dependency version needs to be adjusted.)

**Comment by ljharb** [comment]
This is done in 6a110dd16a7fd775f08601054bf14ffd503eea7b, just not yet released. It will be in the next release.

**Comment by gabegorelick** [comment]
Any ETA on when the next release will be tagged?

**Comment by ljharb** [comment]
Nope, but not long.
