### ISSUE TITLE
compatibility with eslint 7.0.0

### ISSUE THREAD

**Issue by akkumar** [benmosher/eslint-plugin-import#1761]
eslint 7.0.0 got released recently. 

Using the latest version of eslint-plugin-import gives the following warning - 

`
npm WARN eslint-plugin-import@2.20.2 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
`

some relevant links - 

https://eslint.org/blog/2020/05/eslint-v7.0.0-released
https://eslint.org/docs/user-guide/migrating-to-7.0.0 . 

it would be useful to get eslint 7.0.0 supported .  tracking issue for the same

**Comment by akkumar** [comment]
PR #1762

**Comment by akkumar** [comment]
Apparently - the changes are already in the latest master for 7.0.0 compatibility. 

Can we just have a later release 2.20.3 or similar, to address that compatibility issue ?

**Comment by ljharb** [comment]
Indeed, this is done and only pending a release.
