### ISSUE TITLE
eslint 7

### ISSUE THREAD

**Issue by coreyfarrell** [benmosher/eslint-plugin-import#1768]
Now that eslint 7.0.0 is released I wanted to ask what is the process for getting this plugin verified and updating the eslint peer dependency to allow 7.x?

**Comment by ljharb** [comment]
Duplicate of #1756. Duplicate of #1761. Duplicate of #1752. 

This is done in 6a110dd16a7fd775f08601054bf14ffd503eea7b, just not yet released. It will be in the next release.
