### ISSUE TITLE
no-default-exports is missing documentation link/url

### ISSUE THREAD

**Issue by AlansCodeLog** [benmosher/eslint-plugin-import#1769]
I noticed while using the vscode lintlens extension and exploring the rules with it that this rule was missing the documentation link even though the docs for it exist:

https://github.com/benmosher/eslint-plugin-import/blob/92caa3594e0f8d7bf143dedba0c7c2b47b541f34/src/rules/no-default-export.js#L4

**Comment by ljharb** [comment]
Thanks, a PR to fix it would be appreciated :-)

**Comment by beatrizrezener** [comment]
I didn't know LintLens, it looks so useful, thank you for talk about it.
