### ISSUE TITLE
dynamic-import-chunkname doesn't work with latest babel-eslint

### ISSUE THREAD

**Issue by Hypnosphi** [benmosher/eslint-plugin-import#1771]
That's because it traverses `CallExpression`s while `import()` is now an `ImportExpression`:
https://github.com/babel/babel/pull/10828

**Comment by ljharb** [comment]
We’ll need to be sure to support both.

**Comment by noelebrun** [comment]
It seems like there's the same issue with `@typescript-eslint/parser`. I guess that's for the same reason.
