### ISSUE TITLE
Snowpack resolver

### ISSUE THREAD

**Issue by stefanfrede** [benmosher/eslint-plugin-import#1774]
I'm using snowpack and because of the `web_modules` folder `eslint-plugin-import` is not happy.

I read about writing a resolver, but I'm a tat bit lost.

How would I write a resolver for snowpack? Any push in the right direction is much appreciated.

**Comment by ljharb** [comment]
I’d take a look at the two resolvers in this repo for inspiration - https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers
