### ISSUE TITLE
Rule proposal: relative path start with "./"

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#178]
```js
import './test.js';
import './../test.js';
import '../test.js';
```

This is an OCD thing, but I'd like all relative paths to start with './'. I dislike the inconsistent use:

```js
import './../test.js';
import '../test.js';
```

I will submit a PR if accepted.

**Comment by benmosher** [comment]
duplicate of #160?

**Comment by gajus** [comment]
@benmosher Sorry. Forgot I have opened this before.
