### ISSUE TITLE
62 tests are failing

### ISSUE THREAD

**Issue by manuth** [benmosher/eslint-plugin-import#1780]
As mentioned in issue #1244 I just tried to create a PR for fixing said issue.
Sadly in the current state (without touching anything but just running `npm install` and `npm test`) there are 62 unit-tests failing.

That way it's a bit hard for me to tell whether changes made to the project "would" or "would not" cause any harm to the project.

**Comment by ljharb** [comment]
What OS are you using?

**Comment by manuth** [comment]
I tried it on Windows 10 (Build 1909) and Docker Images (`node:14` and `node:10`).

That said, I couldn't even build the project using Windows or `node:14`.

**Comment by manuth** [comment]
Alright I managed it to get it done using `WSL` with node v12 installed.
Looks like git for windows doesn't clone symbolic links and instead creates files containing the file-path.

Now all tests pass except for the `case sensitivity` ones as WSL neither is fully case sensitive nor fully case insensitive (directories are case sensitive while files aren't).

I'll create a separate PR for this.
