### ISSUE TITLE
The development-environment doesn't work on windows

### ISSUE THREAD

**Issue by manuth** [benmosher/eslint-plugin-import#1781]
When trying to test the module on a windows platform, weird errors appear as seen in AppVeyor:
https://ci.appveyor.com/project/benmosher/eslint-plugin-import/builds/33096831/job/gg7jvh5ehfb4s9ag

This also might be because the dependencies weren't updated for a long time and don't support `node 14.x`.

**Comment by ljharb** [comment]
Do they pass in node 12? Which dependencies are you thinking of?

Typically non-compiled deps that work in node 0.6 work in every version of node since :-)

**Comment by manuth** [comment]
I'm talking 'bout these deprecation-warnings:
```
npm WARN deprecated typescript-eslint-parser@22.0.0: Deprecated: Use @typescript-eslint/parser instead
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated typescript-estree@18.0.0: This package was moved to @typescript-eslint/typescript-estree, please install the latest version from there instead
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

Most importantly `chokidar@1.7.0` and `fsevents@1.2.13` as they have something like "will break on node 14+" in their messages.

Anyways - these are the issues I'm facing:
* When using windows w/ node 14 I get this error when running `npm run test`:  
 `Cannot find module 'E:\Users\Manuel\Documents\Projekte\Node-Modules\eslint-plugin-import\node'`
* When using `node:14` the container as well as the docker service get stuck

Also the `copy-metafiles`-script doesn't work on windows.

**Comment by ljharb** [comment]
Deprecation warnings aren't important, but breaking on node 14 is.

Happy to take a PR to tweak the copy-metafiles script.

**Comment by manuth** [comment]
@ljharb okay so I managed it to clearly verify that the issue is caused by the fact that a quite old babel-version is installed.
I've been trying to update babel for quite a while but I have some trouble, because `babel-eslint` has breaking changes.

Tests involving the `ExportMap`, like this here:
https://github.com/benmosher/eslint-plugin-import/blob/62b554bc5f5024695b40d8701fbd8267fb4eb73f/tests/src/core/getExports.js#L251-L259
Fail after updating `babel-eslint`.

To work around this issue I only updated the most important modules:
  - Replace `babel-cli` with `@babel/cli@latest`
  - Replace `babel-core` with `@babel/core@latest`
  - Replace `babel-register` with `@babel/register@latest`
  - Update `babel-plugin-module-resolver` to `latest`
  - Replace `babel-preset-es2015-argon` with `@babel/preset-env@latest`
  - Replace `babel-preset-flow` with `@babel/preset-flow`
  - Update `mocha` to `latest`

Now I'm ending up with these two errors:
```log
  1843 passing (13s)
  2 failing

  1) no-extraneous-dependencies
       invalid
         import "lodash.isarray":

      AssertionError [ERR_ASSERTION]: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1
      
      at testInvalidTemplate (node_modules\eslint\lib\rule-tester\rule-tester.js:657:24)
      at Context.<anonymous> (node_modules\eslint\lib\rule-tester\rule-tester.js:874:25)
      at processImmediate (internal/timers.js:439:21)

  2) no-extraneous-dependencies
       invalid
         var eslint = require("lodash.isarray"):

      AssertionError [ERR_ASSERTION]: Should have 1 error but had 0: []
      + expected - actual

      -0
      +1
      
      at testInvalidTemplate (node_modules\eslint\lib\rule-tester\rule-tester.js:657:24)
      at Context.<anonymous> (node_modules\eslint\lib\rule-tester\rule-tester.js:874:25)
      at processImmediate (internal/timers.js:439:21)
```

Should I create a PR anyways?

**Comment by ljharb** [comment]
For presets, we should drop the argon one and instead use the env preset with proper targets.

Upgrading to Babel 7 is fine but it requires using stages in Travis since older nodes won’t be able to build, and i don’t know how to do stages in Appveyor. I have an example repo for Travis if that’s the direction we end up going.

That said, could you elaborate on exactly what issue is caused by being on an old Babel?

**Comment by manuth** [comment]
As far as I can see, the error `Error: Cannot find module 'C:\projects\eslint-plugin-import\node'` which appears on every windows-based appveyor test is related to babel.

I'm quite sure because `cjs` is the name of babel's `CommonJS` module loader. Additionally the error disappeared once I updated babel to the latest version.

Although I did not test whether it works if babel is updated to any other version.

Sadly build-stages aren't possible in AppVeyor - its functions seem to be very limited.
As far as I can see, script-stacks are executed in the following order:
* `init`
* _Clone git into a clone folder_
* `install`
* `before_build`
* `build_script`
* `after_build`
* `before_test`
* **`test_script`** (this is the most important stack in our case as currently this stack contains all the mocha-stuff atm)
* `after_test`
* `before_deploy`
* `after_deploy`
* `on_success`
* `on_failure`
* `on_finish`
As seen on https://www.appveyor.com/docs/build-configuration/

You can create multiple jobs using the `configuration` array (so did I in order to create tests for native Windows and Windows using WSL).
AppVeyor doesn't allow you to override single scripts from configuration to configuration, but only allows you to override whole script-stacks (like `test_script`, for example).

The `for`-array allows you to set build-stacks for exactly one configuration (using `only`) or all configurations but one (using `except`).

In this piece of code, for example, I set some script-stacks only for the `Native` configuration.
https://github.com/benmosher/eslint-plugin-import/blob/8118170d6fc6d626829ccbedba4be10bd3b97c55/appveyor.yml#L29-L73

But I don't think it's handy to create a configuration for an old node & babel-version which don't work anyway (as you can see in AppVeyor's history)

**Comment by manuth** [comment]
@ljharb I btw found out what's causing these two errors.
These tests only succeed if `lodash.isarray` is in npm's dependency tree. Currently `lodash.isarray` is just in the dependency-tree by random (because `mocha@3` depends on it). If `lodash.isarray` isn't in the dependency-tree this test fails at this piece of code:
https://github.com/benmosher/eslint-plugin-import/blob/f790737c07f39058592b7eb8b6cda3de72c239b9/src/rules/no-extraneous-dependencies.js#L122-L123

I'd recommend to add `lodash.isarray` to the `devDependencies` to ensure these two tests work for sure.

**Comment by ljharb** [comment]
Oh wow, good catch. I'll try to push up a quick fix for that.

**Comment by ljharb** [comment]
Done, check it now? 6159ce9f

**Comment by manuth** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/6159ce9fb25c64526f89befa082d704e64796e68/tests/src/rules/no-extraneous-dependencies.js#L176-L182
This here either must be replaced with an existing module or completely removed from the tests.
Looks just fine apart from that

**Comment by ljharb** [comment]
Hmm - that test case is *supposed* to fail, so it has to match a nonexistent module.

**Comment by manuth** [comment]
I get you, but this code won't fail.
https://github.com/benmosher/eslint-plugin-import/blob/f790737c07f39058592b7eb8b6cda3de72c239b9/src/rules/no-extraneous-dependencies.js#L122-L154

As you can see here, errors are only reported if the name of the imported module can be resolved. If, for example `lodash.isarray` isn't in the `devDependencies` of `eslint-plugin-import`, the module-name cannot be resolved and therefore no errors will be reported.

**Comment by ljharb** [comment]
oh i see, it needs to be something that is in optional deps.

**Comment by manuth** [comment]
I added `lodash.isarray` to devDependencies of `eslint-plugin-import`. This did the trick. :smile:

In order to be able to resolve `lodash.isarray` it must at least be installed somewhere.

**Comment by ljharb** [comment]
i'd expect it to be inside `tests/files/` tho

**Comment by manuth** [comment]
In this case we would have to run `npm install` in `./tests/files` before testing.

Should I edit the CI configs accordingly?

**Comment by ljharb** [comment]
hmm, let me think about that one first.
