### ISSUE TITLE
feedback request: 1.0.0 beta

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#179]
If you've installed 1.0.0 and had no issues, please let me know!

I want to hear from 5-10 people, optimally, just to know I didn't rip anything out that people need, or miss some necessary/obvious new ESLint 2.0 feature/integration point.

Would love to hear from people about:

- [ ] noticing `import/parser` and `import/parse-options` are dead (long live `parser`)
- [ ] using no configured parser. was using `babylon` in this case, before, so some behavior may be different.
- [ ] shared config being moved into the plugin
- [ ] removed rules (`no-require`) not blowing up if still in your old config

**Comment by benmosher** [comment]
maybe I'm being paranoid, but I think there is a decent-sized userbase at this point. just trying to be careful. :sweat_smile:

**Comment by ALF-er** [comment]
Where I can find changelog for 1.0.0? =)

**Comment by benmosher** [comment]
Haven't put one together yet. those were the big ones though, mostly just that `import/parser` is no longer needed.

Might be able to get an impromptu one by diffing the README between v0.13.0 and v1.0.0-beta.0?

**Comment by benmosher** [comment]
@ALF-er https://github.com/benmosher/eslint-plugin-import/releases/tag/v1.0.0-beta.0

Turns out those are the only major external changes. And `no-require` was technically dropped between 0.12.1 and 0.13.0, but that was only a few days before I pushed 1.0.0-beta.0.

Also, as noted in #180, I flubbed the "beta" release anyway, so it's fundmentally 1.0.0 anyway, heh. :sweat_smile:

**Comment by ALF-er** [comment]
Works like a charm for me =) Thank you for this plugin

**Comment by benmosher** [comment]
Thanks for the feedback! I'm going to take the general lack of response as good news and close this. :smile:
