### ISSUE TITLE
upgrade eslint

### ISSUE THREAD

**Issue by rubiin** [benmosher/eslint-plugin-import#1790]
I get the warning message
```sh
warning " > eslint-plugin-import@2.20.2" has incorrect peer dependency "eslint@2.x - 6.x"
```
when using latest eslint version.

**Comment by ljharb** [comment]
That's because it doesn't support eslint 7 yet, which means you have to downgrade to eslint 6 until the next release of eslint-plugin-import.

When `npm ls` exits nonzero, your dependency graph is invalid, and you can't rely on anything working.
