### ISSUE TITLE
no-es6 rule

### ISSUE THREAD

**Issue by mmkal** [benmosher/eslint-plugin-import#1794]
As the converse to [no-commonjs](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-commonjs.md), could there also be a `no-es6` rule that reports on:

```js
import { foo } from './bar'
```

And auto-fixes to

```js
const { foo } = require('./bar')
```

This might seem anti-progressive, but there are still plenty of places where commonjs code is written (usually, js code that is run directly without transpilation). With a rule like this it'd be possible to enforce conventions for those kinds of scripts:

```js
// .eslintrc.js
module.exports = {
  rules: {
    'import/no-commonjs': 'error',
  },
  overrides: [{
    files: ['scripts/**.js'],
    rules: {
      'import/no-commonjs': 'off',
      'import/no-es6': 'error',
    },
  }],
}
```

This would also help with IDEs like VSCode auto-importing using es6 syntax - those could be auto-fixed on save. Right now `import { foo } from './bar'` has to be manually edited to `const { foo } = require('./bar')`.

**Comment by ljharb** [comment]
You don't need a lint rule for this, because you can set eslint's sourceType to `script`, and then it will be a syntax error.

**Comment by mmkal** [comment]
Oh, that's handy, thanks! I didn't know parser options could be specified in `overrides`, but I just tried it and it works fine. Even though there's no auto-fix this is probably the better way to go, since any rule would have to workaround syntax errors, so I'll close this.
