### ISSUE TITLE
1.0.0-beta.0 tagged as a release version

### ISSUE THREAD

**Issue by nevir** [benmosher/eslint-plugin-import#180]
Might catch some folk off guard.  I suspect you `npm publish`'d without a `--tag beta` (or similar)?  `npm publish` defaults to the `latest` tag, which gets picked up by a `npm install` w/o version constraints

**Comment by benmosher** [comment]
Yeah, I wondered if I had botched that. It was my first prerelease publish. I checked the docs but I didn't find anything about `--tag`. 

Thanks for the heads up. 😅 Not sure what to do at this point, it's been live for a few days and I haven't heard much.

**Comment by nevir** [comment]
Yeah, npm publish's default behavior there is pretty dumb :(

I think you can correct it via `npm dist-tag <package>@<version> latest` to
point the tag to the right place

**Comment by benmosher** [comment]
published real 1.0.0 :smile:
