### ISSUE TITLE
Last update to 2.21 broke analysis 

### ISSUE THREAD

**Issue by KonovalovaKV** [benmosher/eslint-plugin-import#1807]
Before this fix
https://github.com/benmosher/eslint-plugin-import/compare/v2.21.0...master?diff=unified

`
eslint -f json -o report.json src
`
work,
but now:
`
Error: Cannot find module 'typescript'
`

I do not use typescript

**Comment by ljharb** [comment]
Do you get the same error on v2.21.1, or just on v2.21.0 (#1805)?

**Comment by KonovalovaKV** [comment]
At that time there was version 2.21.0. I'll try 2.21.2

**Comment by KonovalovaKV** [comment]
It works! Thank you!
