### ISSUE TITLE
import/no-self-import incorrectly identifies self when similar directory is in moduleDirectory setting

### ISSUE THREAD

**Issue by kevo1ution** [benmosher/eslint-plugin-import#1813]
Here are the settings I specified in my `eslintrc.json`.
```
"settings": {
    "import/resolver": {
        "node": {
            "moduleDirectory": [
                "node_modules",
                "src"
            ]
        }
    }
}
```

The file structure for my project looks like this:
```
root
├── src
│   └── test.js
└── test
    └── src
        └── test.js
```

In file `test/src/test.js`:
```
// Attempt to require file from "src/test.js"
const test = require('test.js'); // causes "import/no-self-import" error
```
My expected outcome is that it does not error. It is really requiring `src/test.js` because the `moduleDirectory` includes `"src"`. Instead, eslint thinks I am requiring `test/src/test.js`.

**Comment by ljharb** [comment]
hmm, i see `moduleDirectory` in the readme for the node resolver but nothing in the code actually looks at it.

I think you want the `import/external-module-folders` global setting? https://github.com/benmosher/eslint-plugin-import#importexternal-module-folders

**Comment by kevo1ution** [comment]
This change seems to fix my problem:
```
"settings": {
    "import/resolver": {
        "node": {
            "paths": ["src"]
        }
    }
}
```
