### ISSUE TITLE
"`null` import" should occur before relative imports with TS `import =` syntax

### ISSUE THREAD

**Issue by acdibble** [benmosher/eslint-plugin-import#1821]
I am encountering the following issue when trying to import individual members from a TS namespace:

![image](https://user-images.githubusercontent.com/21286068/84480998-b7ae9d00-ac95-11ea-9581-d1e5e8de7d74.png)

This was last working without issue on v2.20.2. It first became an error in v2.21.0, but I saw there were some other issues opened around the same time about `import =` syntax, so I wanted to wait and see if it would be fixed in any of the subsequent releases.

[Here is a repo](https://github.com/acdibble/null-import) with a recreation of the issue.

**Comment by manuth** [comment]
Sorry, that's my bad - looks like the changes I've made caused object-imports to fail.
I just set up a PR to fix it, stay tuned
