### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by thadjbullet** [benmosher/eslint-plugin-import#1825]
An error occurred at line 565 of ExportMap.js of this package. 
`const exportedName = n.expression && n.expression.name || n.id.name`
Can be fixed by change to this:
`const exportedName = n.expression && n.expression.name || (n.id && n.id.name)`
Please assist.
<img width="1102" alt="Screenshot 2020-06-13 at 18 42 33" src="https://user-images.githubusercontent.com/17276356/84572966-4579ad80-ada6-11ea-8918-75e46d30a164.png">

Node v12.16.2
Deps:
`"@typescript-eslint/eslint-plugin": "^3.2.0",
    "@typescript-eslint/parser": "^3.2.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-import-resolver-typescript": "^2.0.0",
    "eslint-plugin-import": "^2.21.2",
    "prettier": "^2.0.5",
    "tsconfig-paths": "^3.9.0"`

**Comment by ljharb** [comment]
Can you provide client.ts around line 6, so i can see what code it's failing on?

**Comment by thadjbullet** [comment]
Sure.
`import debug from 'debug';
import uuid from 'uuid/v4';
import * as tokenServer from './tokenizationApi';
import { EmailLog, MailQueue, MailTask, EmailOpsQueue } from 'lib/sequelize';
import emailTemplate from './emailTemplate';
import texts from './texts';

import mappingList from './mappingList';
import ejs from 'ejs';
import assert from 'assert';

const debugEmailClient = debug('email_client');`
9 line is import of ejs.

**Comment by thadjbullet** [comment]
So, I found an issue in export in one of my modules. Now works fine. This issue no more needed. :)
