### ISSUE TITLE
New rule: ensure lowercase module names?

### ISSUE THREAD

**Issue by gausie** [benmosher/eslint-plugin-import#184]
In npm [you cannot have capital letters in module names](https://github.com/npm/validate-npm-package-name/blob/master/index.js#L67). We could expose a rule to ensure that no capital letters are used in code.

This is stylistic because it will work with incorrect case on some systems, but not all.

**Comment by benmosher** [comment]
I thought this was only relevant for the package name specified in the `package.json`?

Modules (i.e. file/directory paths within the package) can still have capitals, as I understand it?

**Comment by gausie** [comment]
You're right. But we can ensure lowercase node_modules references though?
i.e. if the require does not resolve to a relative file, ensure lowercase.

**Comment by benmosher** [comment]
`import/no-unresolved` is already case-sensitive. given 
```js
import React from 'React'
```

![screen shot 2016-02-22 at 8 26 32 am](https://cloud.githubusercontent.com/assets/3709196/13219441/09353380-d93e-11e5-8cf5-4616916bfcdf.png)

**Comment by gausie** [comment]
Yeah but that's just machine specific. So a lint might pass on the authors
computer but then fail on build server or on another dev.

**Comment by gausie** [comment]
Or have I misunderstood, in which case great!

**Comment by benmosher** [comment]
The linter rules are designed to check that the case matches the file exactly, regardless of the local FS case-insensitivity: https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/resolve.js#L7

I am on OSX with a case-insensitive filesystem, and I still see a lint error for case issues. :smile:
