### ISSUE TITLE
Add "forbid" option for import/no-internal-modules 

### ISSUE THREAD

**Issue by guillaumewuip** [benmosher/eslint-plugin-import#1842]
I would like to use `import/no-internal-modules` to allow all imports except some rules.

For example, given

```js
import React from 'react';
import { Toolbar } from 'reakit/Toolbar';

import { thing } from '../dir2/subdir';
import { somethingElse } from '../dir2/subdir/file';
```

I would like to allow everything except `reakit/Toolbar` and `dir2/subdir/*`. 
Because this should work for the full codebase (lot of node_modules dependencies, complex directory tree), I prefer maintaining an exclusion list of what is forbidden than an inclusion list of what is allowed.

Would you accept a PR to add a `forbid` option to `import/no-internal-modules` to be used like below ? 

```
{
  ...
  "rules": {
    "import/no-internal-modules": [ "error", {
      "forbid": [ "reakit/Toolbar", "*/dir2/subdir/*" ]
    } ]
  }
}
```

**Comment by ljharb** [comment]
As long as `forbid` and `allow` are mutually exclusive, that seems like a reasonable semver-minor PR.
