### ISSUE TITLE
newline-before-export

### ISSUE THREAD

**Issue by wenfangdu** [benmosher/eslint-plugin-import#1852]
I searched through the rules, didn't find a rule regarding this, could the team consider adding it?

**Comment by WinmezzZ** [comment]
> I searched through the rules, didn't find a rule regarding this, could the team consider adding it?

This native eslint rule could be helpful to you 
```javascript
{
    "padding-line-between-statements": [
        "error",
        { "blankLine": 'always', "prev": *', "next": 'export' }
    ]
}
```

see also: [https://eslint.bootcss.com/docs/rules/padding-line-between-statements](https://eslint.bootcss.com/docs/rules/padding-line-between-statements)

**Comment by ljharb** [comment]
Closing since there's an eslint core rule for this already.

**Comment by riteshjagga** [comment]
What if I DO NOT want to add line break for the single line export statements:

```
export {default as CardListItem} from './cardlist/CardList'
export {default as CardListItem} from './cardlist/item/CardListItem'
```

Tried and it can be achieve using 2 rules for export
```
"padding-line-between-statements": [
  "error",
  {"blankLine": "always", "prev": "*", "next": "export"},
  {"blankLine": "never", "prev": "export", "next": "export"},
]
```

but the above rule also report "Unexpected blank line before this statement" where I want to have line break for multiline export

```
export interface Interface1 {

}

export interface Interface2 {

}
```

Trying how to report
 - Unexpected line break for single line export statements
 - Missing line break for multi line export statements

**Comment by coder054** [comment]
"padding-line-between-statements": [
      "error",
      { blankLine: "always", prev: "const", next: "export" },
    ],

This code will cause an error:
```
const BREAKPOINT_TOGGLE_SIDEBAR = bps.lg
export const Home: React.FC<LayoutProps> = ({ children }) => {...}
```

**Comment by ljharb** [comment]
@coder054 that's because it's typescript. you need to use the typescript-eslint parser and replacement rules.
