### ISSUE TITLE
no-extraneous-dependencies : Cannot use 'in' operator to search for '}' in { Occurred while linting 

### ISSUE THREAD

**Issue by danm** [benmosher/eslint-plugin-import#1863]
In the extension output of VSCode, I am getting the following error which prevents the ESLint server running.

`TypeError: Error while loading rule 'import/no-extraneous-dependencies': Cannot use 'in' operator to search for '}' in {
Occurred while listing {...filename}`

I'm using Airbnb style guide with the version specified on their readme. Also using Typescript Parser. 

package.json dev deps
```
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.5",
    "eslint-plugin-react-hooks": "^4.0.0",
    "@typescript-eslint/eslint-plugin": "^3.7.1",
    "@typescript-eslint/parser": "^3.7.1"
```

eslintrc
```
{
 "extends": ["airbnb", "airbnb/hooks"],
 "parser": "@typescript-eslint/parser",
 "plugins": [
    "@typescript-eslint"
  ],
}
```

vscode_eslint : v2.1.8
vscode:  1.47.3

**Comment by danm** [comment]
actually, I think this is an issue with airbnb config- I'll raise something there

**Comment by ljharb** [comment]
@danm i very much doubt that, since the airbnb config just configures rules.

What happens on the command line? That determines whether it's a bug in vscode or not.

**Comment by danm** [comment]
When running `npx eslint src/**` with the above config, 
```
Oops! Something went wrong! :(

ESLint: 7.2.0

TypeError: Error while loading rule 'import/no-extraneous-dependencies': Cannot use 'in' operator to search for '}' in {
Occurred while linting /Users/danielmorrison/telescope/telescope-web/src/Admin/Status/Create.tsx
```

So it looks like it is related to my setup

**Comment by ljharb** [comment]
It'd be great to try eslint v7.5.0, and also to know the contents of `Create.tsx` :-)

**Comment by danm** [comment]
v7.5.0 fixed it. I hang my head in shame I didn't check that first. I can only guess that at some point `eslint-config-airbnb-typescript` required a specific version of ESLint. Either way, it's been fine since 7.5.0. Cheers.
