### ISSUE TITLE
no-extraneous-dependencies: use case missing?

### ISSUE THREAD

**Issue by jsg2021** [benmosher/eslint-plugin-import#1864]
Let's say you have a project that publishes with no public dependencies, but you do use some... however, you bundle them with `bundledDependencies` and specify them in `devDependencies`. How could `import/no-extraneous-dependencies` be configured to show an error if you reference a dependency that is not in the set of `dependencies | bundledDependencies`?

**Comment by ljharb** [comment]
The rule supports `bundledDependencies`, so you'd configure it with `{ dependencies: false, bundledDependencies: true, devDependencies: true }`.

**Comment by jsg2021** [comment]
ah, I will try that. Thanks!
