### ISSUE TITLE
[no-restricted-paths] rule. Needs help with implementation.

### ISSUE THREAD

**Issue by mikaarefyev** [benmosher/eslint-plugin-import#1870]
Hey guys. Thanks for a nice work with current library.
I would like to use no-restricted-paths inside my project, but faced some problems.

Idea: I need to disallow importing old components to the new rebirth component directory. My main directory is ./web.
This is current eslintrc.json:
![image](https://user-images.githubusercontent.com/11503329/89521271-dccc1180-d7e7-11ea-9dc5-f83573b2e620.png)

After running eslint I get this error
![image](https://user-images.githubusercontent.com/11503329/89521000-64fde700-d7e7-11ea-978a-61889d5c6638.png)

Eslint should show an error if someone will try to use old components from "components-legacy" in the new folder "components/PageBuilder/". 

Will be really appreciated for help

**Comment by ljharb** [comment]
The rule is `import/no-restricted-paths`, not `no-restricted-paths`.
