### ISSUE TITLE
[import/no-named-as-default-member] Cannot read property 'map' of undefined (undefined:undefined)

### ISSUE THREAD

**Issue by Kermit-Xuan** [benmosher/eslint-plugin-import#1894]
When using `pnpm` install deps, it appears errors in tsx:

![image](https://user-images.githubusercontent.com/33770367/92136353-8251bf80-ee3e-11ea-9c1c-3b8d3b199ffc.png)

But it work correctly when using `npm/yarn`.

**Comment by ljharb** [comment]
First, anything that works in npm but doesn't in another package manager is broken by definition, so it sounds like this is a pnpm bug.

Is there any stack trace beyond this image? What happens on the command line? (note when something works on the CLI but not in an IDE, it's usually an IDE bug)

**Comment by Kermit-Xuan** [comment]
This is indeed a `pnpm` bug, I hope to help analyze what caused it? So I can go to pnpm to open the issue.

The screenshot on the command line:

![image](https://user-images.githubusercontent.com/33770367/92189345-ffa62000-ee90-11ea-80db-b401d714b0f9.png)

**Comment by ljharb** [comment]
It's right there in the error message - you're using TS 4, and the parser you're using doesn't support it.

Upgrade the parser, or downgrade TS, but at the moment, I assume `npm ls` exits nonzero, which means your dep graph is invalid and you can't expect anything to work.

**Comment by Kermit-Xuan** [comment]
Thanks
