### ISSUE TITLE
UNMET PEER DEPENDENCY eslint@2.x

### ISSUE THREAD

**Issue by tiancheng2000** [benmosher/eslint-plugin-import#190]
don't know why `npm i -g` still complains about *peer dependency* in my env,
- upgraded npm to v3.7.3  (sublime 3 works fine after upgrade though, thanks)
- manually checked `eslint -v` which returns v2.2.0

**Comment by benmosher** [comment]
Strange. Do you have any other plugins installed? I just upgraded my `eslint-plugin-mocha` to 2.0, it was responsible for that same message for me.

**Comment by tiancheng2000** [comment]
@benmosher sure, currently installed plugins:
- babel-eslint
- eslint
- eslint-config-airbnb
- eslint-plugin-import
- eslint-plugin-react
- jshint
- npm
- react-native-cli

**Comment by benmosher** [comment]
`which eslint`? I see that same message for `npm list -g` when in an `nvm` version that didn't have ESLint installed at all.

**Comment by benmosher** [comment]
Which is to say: you could try `npm i -g eslint` or `npm up -g eslint` and see if it resolves?

or just `npm list -g  | grep eslint`

**Comment by tiancheng2000** [comment]
(sorry for the timDiff) result of `npm list -g | grep eslint` is, 
> +-- babel-eslint@5.0.0
> +-- eslint@2.2.0
> +-- eslint-config-airbnb@6.0.2
> +-- eslint-plugin-import@1.0.0
> | `-- eslint-import-resolver-node@0.1.1
> +-- eslint-plugin-react@4.1.0
> 

and I did `npm i -g eslint` before running `npm i -g eslint-plugin-import`...
whereas the latter just responsed, 
> C:\Users\Timothy\AppData\Roaming\npm
> +-- UNMET PEER DEPENDENCY eslint@2.x
> `-- eslint-plugin-import@1.0.1
> 
> npm WARN eslint-plugin-import@1.0.1 requires a peer of eslint@2.x but none was installed.
> 

Anyway, it's just a WARN in npm 3, looks better than in npm 2 :)) Thanks'

**Comment by benmosher** [comment]
Super weird. I'm not sure why that would happen. I didn't change the `peerDependencies` spec between 1.0.0 and 1.0.1, so I'm not sure why that would happen.

**Comment by thebearjew** [comment]
I am having same exact issue and I've been driving me mad when trying to deploy a vagrant box which installs eslint 2.x and eslint-plugin-import for a Meteor application.

I have run `npm clean cache` multiple times, `sudo`, as well as updating NPM to version `3.7.3`, also reinstalling `eslint` and nuking `/usr/local/lib`

```
→ npm install -g eslint-plugin-import
/usr/local/lib
├── UNMET PEER DEPENDENCY eslint@2.x
└─┬ eslint-plugin-import@1.8.1
  └── lodash.findindex@4.4.0

npm WARN eslint-plugin-import@1.8.1 requires a peer of eslint@2.x but none was installed.
```

**Comment by thebearjew** [comment]
My best understanding is that `npm 3.x` no longer manages `peerDependencies` directly. However that does not explain the fact that I have `eslint 2.10.2` installed in the same directory as `eslint-plugin-import`.


([source](https://github.com/npm/npm/releases/tag/v3.0.0))

> #### peerDependencies
> peerDependencies no longer cause anything to be implicitly installed. Instead, npm will now warn if a packages peerDependencies are missing, but it's up to the consumer of the module (i.e. you) to ensure the peers get installed / are included in package.json as direct dependencies or devDependencies of your package.
#3803 npm also no longer checks peerDependencies until after it has fully resolved the tree.

**Comment by gsabran** [comment]
So is the solution just to ignore the error message? I'm getting something similar for `eslint@3.x`:

```bash
$ npm --version
3.9.5
eslint --version
v3.2.2
$ npm install
...
├── UNMET PEER DEPENDENCY eslint@3.2.2
...
```

While my `package.json` contains `"eslint": "^3.0.1",`

**Comment by benmosher** [comment]
My suspicion was that this resulted from #437. What version of `eslint-import-resolver-node` is installed?

**Comment by gsabran** [comment]
`eslint-import-resolver-node` is on 0.2.2 and `eslint-plugin-import` is on 1.12.0:

```
$ npm list | grep eslint
├─┬ babel-eslint@6.1.2
├─┬ UNMET PEER DEPENDENCY eslint@3.2.2
├─┬ eslint-config-airbnb@9.0.1
│ ├── UNMET PEER DEPENDENCY eslint@^2.9.0
│ └── eslint-config-airbnb-base@3.0.1
├─┬ eslint-import-resolver-webpack@0.3.2
├─┬ eslint-plugin-import@1.12.0
│ ├── eslint-import-resolver-node@0.2.2
├─┬ eslint-plugin-jsx-a11y@1.5.5
├── eslint-plugin-react@5.2.2
npm ERR! peer dep missing: eslint@^2.9.0, required by eslint-config-airbnb@9.0.1
npm ERR! peer dep missing: eslint@^2.9.0, required by eslint-config-airbnb-base@3.0.1
```

**Comment by benmosher** [comment]
ah, got it. yeah, your issue is airbnb's config, looks like the version you've got wants 2.9.0

**Comment by gsabran** [comment]
Yeah, I was thinking this could be a separated issue because the error message is `UNMET PEER DEPENDENCY eslint@3.2.2`, which suggest that some package is looking for `3.x` that should be already be available.

**Comment by benmosher** [comment]
Ah, yeah, IIRC that message actually means you've _got_ `3.2.2` and it's not meeting a peer's dependency requirements. I see similar things while using React v14 with component libraries looking for v13.

**Comment by gsabran** [comment]
Hum, I'm confused! The part
```
├─┬ eslint-config-airbnb@9.0.1
│ ├── UNMET PEER DEPENDENCY eslint@^2.9.0
│ └── eslint-config-airbnb-base@3.0.1
```
would then suggest that `eslint-config-airbnb` is using `eslint 2.9.0` while it needs another version (from [here](https://github.com/airbnb/javascript/blob/a1edac348ad16a95259126884cd40216fa6d65dd/packages/eslint-config-airbnb/package.json#L53) is looks like it needs `eslint  3.2.2`)
(the wording of
`npm ERR! peer dep missing: eslint@^2.9.0, required by eslint-config-airbnb@9.0.1`
is then a bit confusing :)


And then does the part
```
$ npm list | grep eslint
├─┬ babel-eslint@6.1.2
├─┬ UNMET PEER DEPENDENCY eslint@3.2.2
```
means that some top packages level is using `eslint  3.2.2` and would need some other version?

**Comment by benmosher** [comment]
ah, right. that is bizarre.

**Comment by wangzhen10** [comment]
I got the same problem

**Comment by ljharb** [comment]
@wangzhen10 does `npm ls` exit zero?

**Comment by cloud-github** [comment]
```
npm install
npm info "eslint-config-airbnb-base@latest" peerDependencies
npm install -g install-peerdeps
install-peerdeps --dev eslint-config-airbnb-base
```

Add "extends": "airbnb-base" to .eslintrc file.
Finally, SUCCESS eslint-config-airbnb-base and its peerDeps were installed successfully.
