### ISSUE TITLE
Overriding built-ins with pathGroups

### ISSUE THREAD

**Issue by yossarian21** [benmosher/eslint-plugin-import#1902]
We are using typescript and have a folder (unfortunately named `util`) aliased as a search path so we can have imports like `import { thing } from 'util/foo';`
It appears that import/order is treating `util/foo` as a "builtin", because it still wants my `util/foo` import listed before external imports.

I have the order set up like this:
```
groups: [
                    'builtin',
                    'external',
                    'internal',
                    'parent',
                    'sibling',
                    'index',
                    'object',
                ],
```

And I defined a pathGroup like this:
```
                pathGroups: [
                    {
                        pattern: 'util/**',
                        group: 'internal',
                    },
```

Is there another way I can specify that `util` is a builtin but `util/**` is not?

**Comment by yossarian21** [comment]
I think I found a solution - set `pathGroupsExcludedImportTypes: [],` so that builtins (including `util`) are also considered by the `pathGroups` rules.

**Comment by ljharb** [comment]
See #1898 as well.
