### ISSUE TITLE
Extremely slow performance after update from ESLint 5 to 6 or 7

### ISSUE THREAD

**Issue by jehy** [benmosher/eslint-plugin-import#1915]
We have a huge project, and on ESlint 5 linting time looked like this:

```
import/no-unresolved           | 12226.921 |    18.8%
import/no-named-as-default     | 10055.898 |    15.5%
indent                         |  8877.540 |    13.6%
react/display-name             |  2663.403 |     4.1%
react/no-deprecated            |  2431.606 |     3.7%
react/no-direct-mutation-state |  2063.651 |     3.2%
react/no-string-refs           |  1353.248 |     2.1%
react/jsx-no-bind              |  1315.276 |     2.0%
react/require-render-return    |  1282.926 |     2.0%
import/extensions              |  1075.427 |     1.7%
```

After update to ESLint 6 or 7 (both produce same picture), linting time of eslint-plugin-import rules extremely degraded (10 minutes instead of 20 seconds):

```
import/no-unresolved              | 446864.448 |    61.4%
import/no-named-as-default-member | 233939.116 |    32.1%
indent                            |   9687.283 |     1.3%
react/jsx-no-bind                 |   2519.813 |     0.3%
react/no-deprecated               |   2486.111 |     0.3%
react/no-direct-mutation-state    |   2041.882 |     0.3%
react/display-name                |   1853.400 |     0.3%
react/no-string-refs              |   1379.716 |     0.2%
import/no-duplicates              |   1294.837 |     0.2%
react/require-render-return       |   1279.207 |     0.2%
```

I tried updating plugin version with no luck.
I found out that exactly this commit in ESLint is at fault: https://github.com/eslint/eslint/commit/6ae21a4bfe5a1566f787fbad798182a524b96d28 (PR https://github.com/eslint/eslint/pull/11546)
That's a pretty huge PR, and I couldn't find out what exactly has gone wrong. I also created an issue in ESLint repo: https://github.com/eslint/eslint/issues/13722
May be you could take a look at discussion and help to find out the problem?
I am afraid that for many projects which update from ESLint 5, eslint-plugin-import will be too slow and we will have to remove it. But it's a great plugin, and I'd like to debug and fix the problem :)

**Comment by ljharb** [comment]
This hasn't been the case on many large projects I've run eslint on. Additionally, you can use jest-eslint-runner and jest to parallelize your eslint runs.

I'll close this in favor of the eslint issue you filed, since there's nothing we can really do about it.

**Comment by jehy** [comment]
> This hasn't been the case on many large projects I've run eslint on.

I suppose, out project is really large - more then 10.000 JS files.

> Additionally, you can use jest-eslint-runner and jest to parallelize your eslint runs.

Yup, I alreay tried this. Still, with jest time still doubles in comparison with old ESLint version, and CPU time is very expensive.

> I'll close this in favor of the eslint issue you filed, since there's nothing we can really do about it.

I hoped you could communicate with ESLint developers to find out and fix the bottleneck.
