### ISSUE TITLE
Enforce order inside named import list

### ISSUE THREAD

**Issue by ThiefMaster** [benmosher/eslint-plugin-import#1921]
I haven't found a rule for it, so I'm assuming there is none yet. It would be nice if there was an option to enforce alphabetic order inside the list of named imports, ie being able to autofix this:

```diff
-import whatever, {d, b, c, a} from 'foo';
+import whatever, {a, b, c, d} from 'foo';
```

**Comment by ljharb** [comment]
Related to #1577.

Does https://eslint.org/docs/rules/sort-imports not cover this with `{ ignoreDeclarationSort: true }`?

**Comment by silveoj** [comment]
Native eslint `sort-imports` rule with `{ ignoreDeclarationSort: true }` works as expected for me. No any conflicts with `eslint-plugin-import`. Can be closed.
