### ISSUE TITLE
no-restricted-paths/ why it is not working? Please can you help me 🙏🙏🙏

### ISSUE THREAD

**Issue by jocoders** [benmosher/eslint-plugin-import#1928]
I have a folder structure:
```
my-project
 |----- private.modules
 |          |-----ConstService
 |----- src
 │         |----- main
 |                    |----- api.1
 |                             |------AccountService.js
 |                    |----- api.2
 |                    |----- components
 |                             |------ScreenLogin.js
```
My scheme looks like this:
```
'rules': {
    'import/no-restricted-paths': [
      'error',
      {
        'basePath': './src/main',
        'zones': [
          { 'target': './components', 'from': './api.1' },
        ],
      }
    ],
  },
```
I need to forbid the export entities from './src/main/api.1' to './src/main/components'.
It means I have to get the error if import in './src/main/components/ScreenLogin.js' the entities from the './src/main/api.1':
Linted file  './src/main/components/ScreenLogin.js':
```
import { AccountService } from '../api.1';
```
But I don't have the error. Even if I tried to set zones without basePath it does not work anyway. Please can somebody help me 🙏🙏🙏

**Comment by ljharb** [comment]
Without the basePath, i'd expect you need to include `./src/main/` in each of the relative paths. Does it work that way?

If not, this seems like a bug in the rule.

**Comment by jocoders** [comment]
> Without the basePath, i'd expect you need to include `./src/main/` in each of the relative paths. Does it work that way?
> 
> If not, this seems like a bug in the rule.

Thank you so much for your answer. Exactly I did it with './src/main' and the rule looks like this:
```
'rules': {
    'import/no-restricted-paths': [
      'error',
      {
        'zones': [
          { 'target': './src/main/components', 'from': './src/main/api.1' },
        ],
      }
    ],
  },
```
But anyway it does not work(((. But in the same time I need to forbid the import for example from './private.modules, in './src/main/components', and I add one more rule like this:
```
'rules': {
    'import/no-restricted-paths': [
      'error',
      {
        'zones': [
          { 'target': './src/main/components', 'from': './src/main/api.1' },
          { 'target': './src/main/components', 'from': './private.modules' },
        ],
      }
    ],
  },
```
The linted file is import './src/main/components/ScreenLogin.js':
```
import { AccountService } from '../api.1';  // NO ERROR!!! WHY???
import { ConstService } from '../../../private.modules';   // error  Unexpected path 
```
And in this case i get the error from the second zone about no-restricted-paths, but don't have the error from the first zone. Can you tell me please why it is not working? What I'm doing wrong?

**Comment by ljharb** [comment]
Can you try renaming things so the directory names don't have a dot in them (both in the config and on the filesystem), just to see if that's the issue?

**Comment by jocoders** [comment]
> Can you try renaming things so the directory names don't have a dot in them (both in the config and on the filesystem), just to see if that's the issue?

Thank you so much! I have just tried it, deleted dots from the folder names, and It is not working anyway. And I think the deal not in this, because in the case with the second zone (_folder components can not import from private.modules folder_) the from field named with the dot notation. And in this case I get the error as it should be. But how to make the first zone work too?

**Comment by jocoders** [comment]
I created the same folder structure like in your first example https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-restricted-paths.md:
<img width="216" alt="Screenshot 2020-10-22 at 10 41 21" src="https://user-images.githubusercontent.com/41040813/96840557-4953c580-1453-11eb-9fe6-d5f7017827dc.png">
Put exactly the same rule to .eslintrc.js:
```
 'rules': {
    'import/no-restricted-paths': [
      'error',
      {
        'zones': [
          { "target": "./client", "from": "./server" },
        ],
      }
    ],
  },
```
And exactly the same linted file my-project/client/foo.ts.
And exactly the same import:
<img width="844" alt="Screenshot 2020-10-22 at 10 45 33" src="https://user-images.githubusercontent.com/41040813/96840961-d0a13900-1453-11eb-977e-a31e1240e026.png">
And there is no error after linting. Only the one difference is my project on TS. Can you tell me please could be the reason of that strange behaviour because my project on TypeScript? But in this case why some zones is working? And some zones is not working?

**Comment by ljharb** [comment]
Are the imports that are failing to error _type_ imports, as opposed to value imports?

**Comment by jocoders** [comment]
> Are the imports that are failing to error _type_ imports, as opposed to value imports?

Thank you so much for you help. I have just found the decision. Before it the plugin has not worked as expected in my project:
```
  'settings': {
    'import/resolver': {
      'node': {
        'extensions': [
          '.ts',
          '.tsx'
        ]
      }
    }
  },
```

And can you tell me please is it possible to restrict some absolute path from the modules, for example if I want to forbid this: 
```
import { ChatBot } from 'brokermodule';
```
If I set my zone like this it is not working:
```
{ 'target': './src/main/components', 'from': 'brokermodule' },
```
How can I do it can you tell me please.

**Comment by jocoders** [comment]
And can you tell me please is it possible to reduce the zone's description, now it looks like this whith a lot of repeats:
```
      {
        'zones': [
          { 'target': './src/main/api.2', 'from': './modules.private' },
          { 'target': './src/main/boot', 'from': './modules.private' },
          { 'target': './src/main/components', 'from': './modules.private' },
          { 'target': './src/main/domain', 'from': './modules.private' },
          { 'target': './src/main/service', 'from': './modules.private' },
          { 'target': './src/main/store', 'from': './modules.private' },
          { 'target': './src/main/view', 'from': './modules.private' },
          { 'target': './src/main/workers', 'from': './modules.private' },

          { 'target': './src/main/boot', 'from': './src/main/api.1' },
          { 'target': './src/main/components', 'from': './src/main/api.1' },
          { 'target': './src/main/domain', 'from': './src/main/api.1' },
          { 'target': './src/main/service', 'from': './src/main/api.1' },
          { 'target': './src/main/store', 'from': './src/main/api.1' },
          { 'target': './src/main/view', 'from': './src/main/api.1' },
          { 'target': './src/main/workers', 'from': './src/main/api.1' },
        ],
      }
```
If **target** and **from** will be arrays, it would be possible to put all zones there, but they are strings. Of course, ideally, I would like to configure all this with only one zone, for example, like this: 
```
//you cannot import into the ‘./src/main’ zone from the ‘./modules.private’ zone, except for the ‘./src/main/api.1’ zone:

{ ‘target’: ‘./src/main’, ‘from’: ‘./modules.private’, ‘except’: ‘./src/main/api.1’ }
```
But this does not work unfortunately, since according to the documentation, the except field only refers to **from** and cannot go back to the parent directory. Any ideas how can I short it ?

**Comment by addlistener** [comment]
> > Are the imports that are failing to error _type_ imports, as opposed to value imports?
> 
> Thank you so much for you help. I have just found the decision. Before it the plugin has not worked as expected in my project. I added this to my .eslintrc.js:
> 
> ```
>   'settings': {
>     'import/resolver': {
>       'node': {
>         'extensions': [
>           '.ts',
>           '.tsx'
>         ]
>       }
>     }
>   },
> ```
> 
> And can you tell me please is it possible to restrict some absolute path from the modules to particular folder, for example if I want to forbid this:
> 
> ```
> import { ChatBot } from 'brokermodule';
> ```
> 
> If I set my zone like this it is not working:
> 
> ```
> { 'target': './src/main/components', 'from': 'brokermodule' },
> ```
> 
> How can I do it can you tell me please.

Your answer should be mentioned in the official docs

**Comment by ironsand-sou-eu** [comment]
> And can you tell me please is it possible to reduce the zone's description, now it looks like this whith a lot of repeats:
> 
> ```
>       {
>         'zones': [
>           { 'target': './src/main/api.2', 'from': './modules.private' },
>           { 'target': './src/main/boot', 'from': './modules.private' },
>           { 'target': './src/main/components', 'from': './modules.private' },
>           { 'target': './src/main/domain', 'from': './modules.private' },
>           { 'target': './src/main/service', 'from': './modules.private' },
>           { 'target': './src/main/store', 'from': './modules.private' },
>           { 'target': './src/main/view', 'from': './modules.private' },
>           { 'target': './src/main/workers', 'from': './modules.private' },
> 
>           { 'target': './src/main/boot', 'from': './src/main/api.1' },
>           { 'target': './src/main/components', 'from': './src/main/api.1' },
>           { 'target': './src/main/domain', 'from': './src/main/api.1' },
>           { 'target': './src/main/service', 'from': './src/main/api.1' },
>           { 'target': './src/main/store', 'from': './src/main/api.1' },
>           { 'target': './src/main/view', 'from': './src/main/api.1' },
>           { 'target': './src/main/workers', 'from': './src/main/api.1' },
>         ],
>       }
> ```
> 
> If **target** and **from** will be arrays, it would be possible to put all zones there, but they are strings. Of course, ideally, I would like to configure all this with only one zone, for example, like this:
> 
> ```
> //you cannot import into the ‘./src/main’ zone from the ‘./modules.private’ zone, except for the ‘./src/main/api.1’ zone:
> 
> { ‘target’: ‘./src/main’, ‘from’: ‘./modules.private’, ‘except’: ‘./src/main/api.1’ }
> ```
> 
> But this does not work unfortunately, since according to the documentation, the except field only refers to **from** and cannot go back to the parent directory. Any ideas how can I cut it ?

Doesn't it accept wildcards? Something like:
```
{
  'zones': [
    { 'target': './src/main/*', 'from': './modules.private' },
    { 'target': './src/main/*', 'from': './src/main/api.1' },
  ],
}
```
