### ISSUE TITLE
Rule proposal: one import per line

### ISSUE THREAD

**Issue by clar-cmp** [benmosher/eslint-plugin-import#1929]
Right now, I can't find a rule that would fix something like:

```
import './a'; import './b';
```

And fix it to:
```
import './a';
import './b';
```

Essentially, I'd like to force each import to have their own line.

Not sure if this should be part of `newline-after-import`, `order`, etc., but it seems like this should be covered somewhere.

**Comment by ljharb** [comment]
https://eslint.org/docs/rules/max-statements-per-line

**Comment by clar-cmp** [comment]
...oh. For some reason, none of the configs I've used have enabled that. Ignore this.
