### ISSUE TITLE
request: No nodejs imports rule

### ISSUE THREAD

**Issue by clshortfuse** [benmosher/eslint-plugin-import#1942]
To the point, I'm trying to create a structure for my projects centered around a single file that holds a list of all the dependencies. In `deno`, it seems to be a common practice to have a `deps.js` (or `deps.ts`) file that lists all the external dependencies in a project:

For example: https://deno.land/x/oak@v6.3.2/deps.ts

I would want to replicate this with NodeJS for the purpose of bundling just that one file. I'm not finding anything that allows me to set a rule of no external imports at all. I would want to set that as default for all files (in `.eslintrc.json`) but disable it for the `deps.js`. The `import/no-nodejs-modules` rule is close to what I want but that only works for NodeJS builtins, not for external modules.  `import/no-extraneous-dependencies` is similar, but basically, I don't want it to check `package.json`.

If there was a way to regex the module names, I believe I can enforce something that requires a path-like system (eg: `'./b.js'`). I just want to avoid something like `import _ from 'lodash'` from most files.

**Comment by ljharb** [comment]
This package, and eslint itself, are node modules - I'm having trouble understanding the use case of running node-based tools on non-node platforms. eslint may support deno, but most eslint plugins don't (including this one).

All that said, I think you can use a custom resolver here, which could tell this plugin how to resolve everything including core modules, and `no-unresolved` would error out on anything you didn't want included. Would that do what you need?

**Comment by clshortfuse** [comment]
Sorry if I wasn't clear. I'm not using `deno`. I'm using `node`. But the paradigm of putting all your dependencies in one file is common seen in `deno` (it's an example). 

The use case is all application code (let's say in `/src/*`) is environment agnostic. They would be pure ES modules that don't use `node` based resolution. Instead of

src/index.js
````js
import '_' from 'lodash';
import `readFile` from 'fs/promises';

/** CODE **/
````
-----

It would be:

deps.js
````js
export { default as _ } from 'lodash';
export { readFile } from 'fs/promises';
````

src/index.js
````js
import { _, readFile } from '../deps.js'
````

So, the application code has no idea (or care) how the external dependencies are resolved, or what the true source of the import is.

---

Another example is the ability to ship two different `deps.js` files based on the environment. For example,

deps.js (nodeJS)
````js
import { JSDOM } from 'jsdom';
export const EventTarget = new JSDOM().window.EventTarget;
````

deps.js (browser)
````js
export const EventTarget = window.EventTarget;
````

----

I can also swap out imported modules that may be referenced by multiple files. So if I choose to change a dependency from, (eg: `colors` to `bevry/ansi`), I don't have to change every file that uses that import, but instead just `deps.js`

----

The last example is my current predicament of bundling just `deps.js` for backend deployment. I would want to bundle `deps.js`, but not anything in `/src/*`. 

---

While writing this out, I think I got it working with:

````json
{
  "settings": {
    "import/resolver": {
      "node": {
        "moduleDirectory": []
      }
    }
  }
}
````

So I'm going to go ahead and close it. Thanks! `import/resolver` was the trick.

**Comment by vassudanagunta** [comment]
Please change the title of this closed issue as it comes up in searches where it shouldn't.
