### ISSUE TITLE
Dramatic performance regression in import/no-cycle

### ISSUE THREAD

**Issue by Blasz** [benmosher/eslint-plugin-import#1943]
We experienced a large performance regression in our linting after upgrading to `2.22.0` from `2.20.1`.

Running linting on a single file.

Before upgrade:

```
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
import/no-cycle                     |  3382.383 |    91.2%
...
```

After upgrade:

```
Rule                                     | Time (ms) | Relative
:----------------------------------------|----------:|--------:
import/no-cycle                          | 73731.106 |    99.3%
...
```

I narrowed the problem down to this PR https://github.com/benmosher/eslint-plugin-import/pull/1689. The `isEsModuleInterop` function tries to load a tsconfig file from disk and doesn't cache the result. The function is called for each file that is parsed by the plugin and is called multiple times in the same file. This is particularly bad when running `import/no-cycle` over a file with a large dependency graph as lots of files end up being parsed.

The fix would be to only lookup tsconfig once and cache the result.

**Comment by Blasz** [comment]
I'm happy to raise a PR for this.

**Comment by soryy708** [comment]
Here's an idea for how to make `import/no-cycle` faster:
https://github.com/import-js/eslint-plugin-import/issues/2937
