### ISSUE TITLE
Rule no-nodejs-modules doesn't work with "settings: {'import/resolver': {webpack}}"

### ISSUE THREAD

**Issue by mqklin** [benmosher/eslint-plugin-import#1946]
It's just ignored. But if I comment `'import/resolver` setting, it starts work.

**Comment by ljharb** [comment]
`{ webpack }` is not valid json syntax, can you share your whole config?

**Comment by mqklin** [comment]
@ljharb sorry, I meant normal syntax: 
```
    'import/resolver': {
      webpack: {
        config: path.resolve(__dirname, 'webpack-configs/dev.js'),
      },
```

**Comment by ljharb** [comment]
You also need the node resolver as well, if you want node modules resolveable.

If that doesn’t fix it, a repro would be great.

**Comment by mqklin** [comment]
@ljharb thanks a lot! It worked without it previously though. 
I added this line `node: true` and now it works.
