### ISSUE TITLE
[import/order] Consider subdirectories smaller than files

### ISSUE THREAD

**Issue by tobiaswaltl** [benmosher/eslint-plugin-import#1960]
The groups `sibling` and `parent` do not differentiate between subdirectories and files when using `alphabetize`.

Current order according to the plugin:
```
import { foo } from './a/foo`;
import { bar } from './bar`; // file between two folders
import { baz } from './something-else/baz';
```

Suggested order:
```
import { foo } from './a/foo`;
import { baz } from './something-else/baz';
import { bar } from './bar`; // file after folders
```

One might be able to achieve something similar using `pathGroups` but this would imply a required new line between subdirectories and files when using `newlines-between: "always"`.

To avoid a breaking change one could add an option to `alphabetize` which - when set to `true` - enforces the suggested behavior.

**Comment by ljharb** [comment]
The whole point of omitting the trailing slash is so the code/consumer has no idea if it’s a directory or a file. Encoding that in the file by making it affect the order would be a very bad thing.

**Comment by tobiaswaltl** [comment]
Ah, right. I forgot about that.
Thanks for your feedback!
