### ISSUE TITLE
Including `eslint-plugin-import` cause lint postpone

### ISSUE THREAD

**Issue by ogonkov** [benmosher/eslint-plugin-import#1961]
When including `eslint-plugin-import` (even without any rules) cause tests to "stuck" after showing lint results.

Lint shows results, and then waits for some time before shell receives exit code.

Installed eslint dependencies:

```
├── eslint@7.15.0
├── eslint-formatter-gitlab@2.0.0
├── eslint-import-resolver-node@0.3.4
├── eslint-import-resolver-webpack@0.13.0
├── eslint-plugin-import@2.22.1
├── eslint-plugin-jsx-a11y@6.4.1
├── eslint-plugin-react@7.21.5
├── eslint-plugin-react-hooks@4.2.0
├── eslint-plugin-testing-library@3.10.1
```

Reduced eslint config

```
{
    plugins: [
        'react',
        'react-hooks',
        'jsx-a11y',
        // 'import'
    ],
    parser: '@babel/eslint-parser',
    parserOptions: {
        ecmaVersion: 10,
        sourceType: 'module',
        impliedStrict: true,
        ecmaFeatures: {
            jsx: true
        }
    },
    env: {
        browser: true,
        amd: true,
        es6: true
    },
    'extends': [
        'eslint:recommended',
        'plugin:react/recommended',
        'plugin:jsx-a11y/recommended'
    ],
    settings: {
        'import/resolver': {
            webpack: {
                config: path.resolve(__dirname, 'app/webpack.config.js')
            }
        },
    }
}
```

When un-commenting `import` line, i see this strange behaviour, like something happens in background after lint finished.

```
✖ 23 problems (6 errors, 17 warnings)
  3 errors and 4 warnings potentially fixable with the `--fix` option.

// <-- Stuck happens here, before showing log bellow

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pdd@0.0.0 lint:js-staged: `CI_MERGE_REQUEST_TARGET_BRANCH_NAME=master ./contrib/ci/gitlab-lint-changed-js.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pdd@0.0.0 lint:js-staged script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ljharb** [comment]
That’s very strange; with no rules enabled, i wouldn’t expect the plugin to do anything. If you remove all the other things from your config, do you still see this behavior?

**Comment by ogonkov** [comment]
You mean other plugins? When config is run _without_ `import` plugin everything happen smooth.

**Comment by ogonkov** [comment]
Seems like without `settings.import/resolver` problem is gone.

**Comment by ljharb** [comment]
What’s in your webpack config? Perhaps the contents of that are contributing?

**Comment by ogonkov** [comment]
Oh. Wow. Thank you, @ljharb!

My webpack config returns promise, and looks like it was the reason of that stuck.

Even more, this seems was a reason of memory leak, that was the initial reason of debugging eslint config. Looks like that `eslint-plugin-import`/`eslint-import-resolver-webpack` is not working well with webpack configs, that returns promise.

Should i file another bug?

**Comment by ljharb** [comment]
Since eslint runs synchronously, I don't think it's *possible* for an async webpack config to integrate with eslint.

**Comment by ljharb** [comment]
Closing in favor of #883.

**Comment by ogonkov** [comment]
That should be added to readme, to avoid further mistakes.

**Comment by ljharb** [comment]
Sure, a PR to do so would be appreciated.
