### ISSUE TITLE
import/exports-last only(!) last 

### ISSUE THREAD

**Issue by What1s1ove** [benmosher/eslint-plugin-import#1972]
Hi there!

I couldn't find a solution, so I decided to check with you

I really like this rule, but is it possible to make it so that the exporters are **only** at the bottom of the file (even if the file has only one export)?

Now this is valid syntax, but I really want to avoid it
<img width="223" alt="изображение" src="https://user-images.githubusercontent.com/42296182/103854158-7873ed80-50b8-11eb-8cae-8559a2ebf3de.png">

Thanks guys 🙂

**Comment by ljharb** [comment]
I'm not clear on what you're asking for. In your example, there's one export and it's at the bottom of the file, so what would be warned on?

The `exports-last` rule shouldn't care if there's 0, 1, or a thousand exports - it will warn if any non-export statement happens before any export statement.

**Comment by What1s1ove** [comment]
> I'm not clear on what you're asking for. In your example, there's one export and it's at the bottom of the file, so what would be warned on?
> 
> The `exports-last` rule shouldn't care if there's 0, 1, or a thousand exports - it will warn if any non-export statement happens before any export statement.

Thanks for your answer 🙂

Let me explain this way:
Сan I make it so that "export" cannot be written near the declaration of variables? (Even if there is only one variable in the file, as in the screenshot above)
So that "export" can be written only at the bottom of the file (in any situation)

**Comment by ljharb** [comment]
Meaning, you want to ban usage of the `export` keyword with declarations?

You could use no-restricted-syntax for that, but it seems like a really strange subset of the language to prohibit.

**Comment by What1s1ove** [comment]
> Meaning, you want to ban usage of the `export` keyword with declarations?
> 
> You could use no-restricted-syntax for that, but it seems like a really strange subset of the language to prohibit.

Okay, thanks for all your answers 🙏

We can close this if needed

Good Luck 🙂

**Comment by ljharb** [comment]
If there’s a compelling reason to ban those export forms, it might be worth creating a rule, but i can’t conceive of one at the moment.

Thanks for the discussion!
