### ISSUE TITLE
Clarify order of imports example

### ISSUE THREAD

**Issue by silviogutierrez** [benmosher/eslint-plugin-import#1977]
Hi there,

Incredibly library, thanks for your work.

The example here: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#importorder-enforce-a-convention-in-module-import-order looks exactly like what I wanted, and expected from the plugin.

But when running the default settings, it kept shifting my internal modules to the bottom. After investigating, I realized it's because, correctly, the documentation points out that the defaults do not include "internal" modules.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#groups-array

Nothing is technically wrong here, but the example should either reflect the default ordering or make a note that internals is not included and will actually be bumped below, unlike the example.

Hopefully this helps other users.

Thanks,

Silvio

**Comment by ljharb** [comment]
I'd be happy to accept a PR that makes the docs clearer.

**Comment by silviogutierrez** [comment]
I'm happy to do so, just curious what direction you want to take it in. Personally — though infeasible because of backwards compatibility — I think the example is actually the "right" version and the defaults should be expanded to include `internal`. 

So I can either:

1. Reorder the example, putting `internal` at the bottom (where they would go with the defaults).
2. Add a note to the example saying, roughly paraphrasing: "this is the result *if the settings are set to so and so*".
3. Something else?
4. Remove internal modules from the example entirely.
5. Actually change the defaults, though obviously that has more impact.

Thanks for getting back to me.

**Comment by ljharb** [comment]
The defaults will indeed be expanded in the next semver-major, but can't be until then - and it's not worth doing a semver-major just for that.

Option 1 or 2 seem like the best choices?

**Comment by silviogutierrez** [comment]
@ljharb : went with #2
