### ISSUE TITLE
eslint-import-resolver-webpack cannot load webpack.config.js with `import`'s inside

### ISSUE THREAD

**Issue by basharov** [benmosher/eslint-plugin-import#1978]
My webpack.config.js contains `import` imports instead of `require`.

Example:
```
import fs from 'fs';
```

This causes this error:
> Cannot use import statement outside a module.

How can I fix it to properly load the file?

**Comment by ljharb** [comment]
Is your webpack config intended to be native ESM, or transpiled by babel?

Typically, webpack configs have to be CJS, or named `webpack.config.babel.js` so that webpack knows to babel-transpile it first.

**Comment by ljharb** [comment]
If you name it properly to include “babel”, i suspect that wouldn’t be necessary.

**Comment by basharov** [comment]
The reason I didn't want to change anything else in the project is to avoid changes in other places of the project but eslint to reduce the risk that something breaks.

**Comment by ljharb** [comment]
Understood, but webpack handles that filename by default, so it should Just Work.

closing, since this is answered.
