### ISSUE TITLE
Ability to create pathGroups from filename

### ISSUE THREAD

**Issue by guilhermetod** [benmosher/eslint-plugin-import#1980]
Firstly, I apologize if this is already achievable and this issue becomes pretty much a question, but when I write unit tests, I like to make the file being testes the last import line with a blank space.

The files are always named consistenty and put on the same directory, so a test file with another imports would look something like:

```js
// foo.test.js

import { bar } from './bar';
import { baz } from './baz';

import { foo } from './foo';

describe('foo', () => {
  ....
})
```

However, I don't think this is achievable with the current groups, since every file would be a normal "sibling" group. I was wondering if it would be possible to define groups with something based on the filename, e.g

```js
pathGroups: [
  {
    pattern: '**/<basename>(!.test).ts',
    group: 'sibling',
    position: 'after',
  },
]
```

Thanks for the attention!

**Comment by ljharb** [comment]
I agree, there's not really a way to do this, since all of your local imports are indistinguishable. A pattern would only work based on the specifier.

I'm happy to reopen this if you have a good idea of how to do it; but I'll close it for now.
