### ISSUE TITLE
New feature - get error at multiple named import

### ISSUE THREAD

**Issue by denisx** [benmosher/eslint-plugin-import#1994]
For better code split and tree shake, need this to warn/error

```
// not ok
import { a, b } from 'package'

// ok
import { a } from 'package'
import { b } from 'package'
```

Invert this group-exports rule

![Screenshot 2021-02-24 at 18 25 53](https://user-images.githubusercontent.com/427776/109024055-6680f500-76ce-11eb-95d1-1497d01b5ba4.png)

If possible, with regex, to ignore selected packages (like react, storybook, @types, etc)

**Comment by ljharb** [comment]
seems like https://github.com/benmosher/eslint-plugin-import/blob/f2db74a347a030c15a387826500cdc98203eac1e/docs/rules/no-duplicates.md does what you want.

**Comment by denisx** [comment]
@ljharb Ii see nothing for my problem, with you link =(
