### ISSUE TITLE
NPM 7 installs very old version

### ISSUE THREAD

**Issue by scottbert** [benmosher/eslint-plugin-import#2000]
This might be related to the #1986 issue so if it is apologies for the noise.

Running `npm i --save-dev eslint-plugin-import eslint-config-import ` in an empty project brings in a super old version of the plugin that seems pinned to the `eslint-config-import` version (0.13.0). In turn this is causing me problems when using `eslint-import-resolver-alias` which expects `eslint-plugin-import@">=1.4.0`

But all is fine if I force the npm install.

```shell
$ node -v
v15.11.0
$ npm -v
7.6.0
```

**Comment by ljharb** [comment]
What is eslint-config-import?

**Comment by scottbert** [comment]
https://www.npmjs.com/package/eslint-config-import

**Comment by ljharb** [comment]
I would suggest not using that package, as it hasn’t been maintained in 5 years, i don’t have publish rights on it, and i can’t find any record of that package.json file in this repo.

**Comment by ljharb** [comment]
Additionally, it’s peer dep on 0.13 of this plugin means that you are *forced* to use 0.13 of the plugin with it, otherwise your dep graph is invalid.

**Comment by scottbert** [comment]
OK thanks. Is an old project, will remove `eslint-config-import` and see what breaks :)

**Comment by ljharb** [comment]
For posterity, here’s https://github.com/benmosher/eslint-plugin-import/tree/v0.13.0/config, and it was removed in https://github.com/benmosher/eslint-plugin-import/commit/369c9ddb6036b7e4f139ed88107a53ecd50bc489#diff-b79606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 before this plugin reached v1.
