### ISSUE TITLE
import/no-internal-modules forbid option is not validated

### ISSUE THREAD

**Issue by denieler** [benmosher/eslint-plugin-import#2003]
Hi guys! I see you have committed for the rule `import/no-internal-modules` a `forbid` option. But it looks like in the latest `2.22.1` it has not been released - https://unpkg.com/browse/eslint-plugin-import@2.22.1/lib/rules/no-internal-modules.js. And now it fires the error:

<img width="890" alt="Screenshot 2021-03-11 at 19 18 40" src="https://user-images.githubusercontent.com/2836281/110827350-a59e7100-829e-11eb-817d-da22363d3af3.png">

**Comment by denieler** [comment]
related to https://github.com/benmosher/eslint-plugin-import/issues/1842

**Comment by ljharb** [comment]
Yes, it's not been released. On any github project, you should be reading the docs from the latest release tag: https://github.com/benmosher/eslint-plugin-import/blob/v2.22.1/docs/rules/no-internal-modules.md

The next release, which has no scheduled time, will contain that option and allow you to use it.
