### ISSUE TITLE
no-restricted-paths with absolute import paths

### ISSUE THREAD

**Issue by bbgvalayev** [benmosher/eslint-plugin-import#2011]
if I import module like
```js
// folder 1
import x from "src/folder2/module"; // expect no-restricted-paths error 

// folder 2
import x from "src/folder1/module"; // expect no-restricted-paths error 
```

however, this doesn't work for me with this setup
```json
        "import/no-restricted-paths": ["error", {
            "zones": [
                { "target": "src/folder2", "from": "src/folder1" },
                { "target": "src/folder1", "from": "src/folder2" }
            ]
        }],
```
Note: for relative path imports this rule works though.

Can someone help please?

**Comment by ljharb** [comment]
Note: these are not absolute paths (which start with `/`), they're bare identifier paths (which start with anything besides `.` or `/`).

What is `src`? How is it defined? Typically this rule is used only on relative paths - bare identifiers are generally "things in node_modules" and as such, it wouldn't make sense to warn on those since you can't change them.

**Comment by bbgvalayev** [comment]
`src` is main local directory, webpack resolver is setup so that people can import like `src/folder/...` instead of `../../../../folder/..`

this is how eslint import plugin setup
```json
    "settings": {
        "import/resolver": {
            "node": {
                "paths": ["."],
                "extensions": [".js", ".jsx"]
            }
        }
    },
```

**Comment by ljharb** [comment]
If you're using webpack to alias `src`, then `import/resolver` also needs to include a `webpack` entry - otherwise the eslint plugin doesn't have any idea what `src` means.

**Comment by bbgvalayev** [comment]
I see, trying different things here and no luck, could you please an example?
im looking at this https://www.npmjs.com/package/eslint-plugin-import#resolvers

**Comment by ljharb** [comment]
Add https://www.npmjs.com/package/eslint-import-resolver-webpack - and alongside `node`, add `"webpack": {}`.

**Comment by bbgvalayev** [comment]
Thank you! Everything works now
