### ISSUE TITLE
Definition for rule 'import/no-relative-packages' was not found

### ISSUE THREAD

**Issue by macecchi** [benmosher/eslint-plugin-import#2014]
I'm trying to enable the [no-relative-packages rule](https://github.com/benmosher/eslint-plugin-import/blob/6f5c52cec32ba94558ea31faa7dc0b6a7c7af982/docs/rules/no-relative-packages.md) as per the documentation, but eslint does not find the rule definition.

Here's my .eslintrc.json config. 

```
    "import/no-relative-packages": "error",
```

The error from eslint:
```
  1:1  error  Definition for rule 'import/no-relative-packages' was not found  import/no-relative-packages
```

I'm using eslint 6.8.0 and with latest plugin version, as per my yarn.lock file:
```
eslint-plugin-import@2.22.1:
  version "2.22.1"
  resolved "https://registry.yarnpkg.com/eslint-plugin-import/-/eslint-plugin-import-2.22.1.tgz#0896c7e6a0cf44109a2d97b95903c2bb689d7702"
  integrity sha512-8K7JjINHOpH64ozkAhpT3sd+FswIZTfMZTjdx052pnWrgRCVfp8op9tbjpAk3DdUeI/Ba4C8OjdC0r90erHEOw==
```

Other rules from the plugin (such as `import/order` work just fine).

**Comment by ljharb** [comment]
That's because that rule isn't released yet. Check the latest released tag, not master: https://github.com/benmosher/eslint-plugin-import/tree/v2.22.1
