### ISSUE TITLE
[Security updates] Update dependencies in general

### ISSUE THREAD

**Issue by rtrys** [benmosher/eslint-plugin-import#2018]
We are seeing a vulnerability in `eslint-plugin-import`, especially for:

```bash
eslint-plugin-import@2.22.1
  └─┬ read-pkg-up@2.0.0
    └─┬ read-pkg@2.0.0
      └─┬ normalize-package-data@2.5.0
        └── hosted-git-info@2.8.8 

```
see details in veracode database
https://sca.analysiscenter.veracode.com/vulnerability-database/security/regular-expression-denial-of-service-redos-/javascript/sid-29806

**Comment by ljharb** [comment]
Since this is an eslint plugin, and you can only run into this by providing a malicious string in _your own package.json files_, this CVE simply doesn't apply to this project. You can't attack yourself.
