### ISSUE TITLE
[no-unresolved]: Unable to resolve path to module with node: protocol specifier

### ISSUE THREAD

**Issue by karlhorky** [benmosher/eslint-plugin-import#2031]
Hi there, thanks for this plugin, super useful! 👍

Ran into an issue when using the new [`node:` prefix](https://twitter.com/jasnell/status/1385238402149150721) for builtin / core modules (currently in v16, but will be backported): `import/no-unresolved` cannot resolve the path to the module:

```js
import fs from 'node:fs';
                ~~~~~~~
                   ^---- Unable to resolve path to module 'node:fs'  eslint(import/no-unresolved)
```

**Comment by ljharb** [comment]
Indeed; the new protocol support isn’t added to `resolve` yet. Please file an issue there; I’ll get to it as soon as i can.

**Comment by karlhorky** [comment]
Great! ...uh where would that be? In ESLint core repo? https://github.com/eslint/eslint

**Comment by sverweij** [comment]
@karlhorky probably @ljharb means [browserify/resolve](https://github.com/browserify/resolve) which eslint-plugin-import uses that under the hood for module resolution. `browserify/resolve` already has an [issue for ESM features like protocol/ URL support](https://github.com/browserify/resolve/issues/222) b.t.w.

**Comment by ljharb** [comment]
resolve is https://github.com/browserify/resolve but it's actually in https://github.com/inspect-js/is-core-module now, and I'm already working on it :-) so no worries.

Can you cite a reference for where it will be backported? I'm pretty sure the addition of `node:` was considered semver-major.

**Comment by karlhorky** [comment]
Ah ok, thanks :)

Here's where I read from @jasnell about the backporting ("it'll take a while"): https://twitter.com/jasnell/status/1385239259838222336

**Comment by ljharb** [comment]
the "take a while" was referring to when it will be safe for library authors to use that syntax :-) "hopefully" is what describes the backporting.

**Comment by karlhorky** [comment]
Ah right, misread this one, good point!

**Comment by ljharb** [comment]
is-core-module v2.3.0 has been released, which should address the problem.

**Comment by karlhorky** [comment]
Hmm, just upgraded all versions of the transitive deps on `is-core-module` and still getting this reported from `import/no-unresolved`... 🤔

**Comment by ljharb** [comment]
Is eslint running on node 16? Perhaps you’re in vscode, and it’s using its bundled copy of node?

**Comment by karlhorky** [comment]
Ah yeah, in VSCode ESLint extension, it's still using Node 12:

```
ESLint server running in node v12.18.3
```

But on the command line, all is good! 🙌

**Comment by andreavaccari** [comment]
@ljharb I'm running eslint v7.32.0 on node v14.16.0 and I'm still getting `import/no-unresolved` errors.

Is this expected to work on v14 or is it necessary to upgrade to v16?

**Comment by ljharb** [comment]
@andreavaccari the `node:` prefix does not work at all on node 14. so yes, if you want them to resolve, you need to be on node 16 both when you run eslint and also in production.

**Comment by bmish** [comment]
Support for `node:` was backported to Node v14.13.1 and v12.20.0: https://nodejs.org/api/esm.html#esm_node_imports

**Comment by ljharb** [comment]
@bmish aha, well then that's what i was missing :-) i can update `is-core-module` shortly to account for that.

**Comment by sverweij** [comment]
☝️ what @bmish says - but only for ESM. For CJS node 14.17.5 and node 12.22.1 still barf with `cannot find module 'node:os'`  when running `console.log(require("node:os").cpus())`.

**Comment by ljharb** [comment]
ahhh, that's more complicated then. `is-core-module` is part of `resolve`, which only applies to CJS - and this plugin is not written for native ESM, it just works for it when specifiers also work in both.

In that case, there's nothing I can really do about it until `resolve` supports ESM, which is a ways off.

**Comment by andreavaccari** [comment]
Thanks for clarifying the situation! I reverted to the traditional imports and turned off [`unicorn/prefer-node-protocol`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md).

**Comment by ljharb** [comment]
I'd suggest keeping that rule off anyways; the advantage to using `node:` is close to zero, and the downsides are huge (because it hurts backwards compatibility)

**Comment by TriStarGod** [comment]
@ljharb 

When I try `import ... from "node:fs";` it fails with

`Unable to resolve path to module 'node:fs'. eslint(import/no-unresolved)`

node: v16.13.2
"typescript": "^4.5.5"
"eslint": "^8.7.0"
"eslint-plugin-import": "^2.25.4"

I reinstalled "eslint-plugin-import" and its package file claims its using "is-core-module": "^2.8.0". I'm not using unicorn but plan to in the future.

How can I troubleshoot this problem?

**Comment by ljharb** [comment]
@TriStarGod is this on the command line, or in your editor? vscode bundles its own node 12, i believe.

**Comment by TriStarGod** [comment]
@ljharb  Its in the vscode editor

![image](https://user-images.githubusercontent.com/8272754/151255198-954fc79f-c068-4c6a-8ff9-313a260f2859.png)

**Comment by ljharb** [comment]
@TriStarGod so that's your problem. On the command line, it will work fine. That means your "fix" is either "don't use `node:` as a prefix, because it adds zero value to do so anyways", or "configure vscode to use your system's node instead of the node it bundles".

**Comment by TriStarGod** [comment]
@ljharb My vscode version is 1.63.2 and its using Node.js 14.16.0 . I believe Node.js 14 is also suppose to support `node:` .

![image](https://user-images.githubusercontent.com/8272754/151257932-864c9f55-41d3-4422-8475-7a1dd17b6fa8.png)

Doesn't `node:` enforce using node specific package files?

**Comment by ljharb** [comment]
@TriStarGod that support was added in node v14.18, so v14.16 is too old for that.

No, if you import from `fs` that's always node's core `fs` module - using `node:fs` offers precisely zero guarantees, altho it may be a less ambiguous signal if you're using broken tooling that doesn't assume node's de-facto standard conventions.

**Comment by karlhorky** [comment]
@TriStarGod you're probably looking for the following setting in your VS Code `settings.json` (this enables your system version of Node.js:

```
"eslint.runtime": "node",
```

**Comment by TriStarGod** [comment]
@karlhorky I tried it and "eslint.runtime": "C:\\Program Files\\nodejs\\node.exe" but both didn't work. I'll take @ljharb advice and not even use it since there isn't any benefit.

**Comment by acidoxee** [comment]
Sorry to reignite the discussion, but this rule still seems to throw for CJS when requiring built-in modules with the `node:` protocol, despite its support having been added in Node v14.18.0.

I'm using Node v14.19.1, and when using `const path = require('node:path')`, the rule errors out with `Unable to resolve path to module 'node:path'`. Switching to Node v16.14.2 works, for instance.

Any chance of it being revisited for Node >=14.18? 🙏

**Comment by ljharb** [comment]
@acidoxee i've got lots of tests in is-core-module that this already works. Where does the rule error out - on the terminal or in an IDE?

**Comment by ljharb** [comment]
@acidoxee thanks; can you also confirm you have the latest version of `is-core-module` in your graph? It's possible your lockfile has you stuck on an older one.

**Comment by acidoxee** [comment]
There's indeed a bunch of different versions of it in my lockfile because of several packages that require them, but the version present at the very root of my `node_modules` folder is `2.8.1`. This does seems to be the version `eslint-plugin-import` is using if I'm not mistaken?

As there's no `is-core-module` folder in `node_modules/eslint-plugin-import/node_modules`, but there's one at the root `node_modules` (the `2.8.1` one), I also believe this should be the proper version required by `eslint-plugin-import` at runtime?

**Comment by ljharb** [comment]
yep, that sounds right. i just released v2.9.0 but that shouldn't affect this. If you could file a new issue that'd be great.

**Comment by acidoxee** [comment]
Sure, I'll continue this tomorrow and keep you updated. Thanks for your help!

**Comment by acidoxee** [comment]
Bad news, I couldn't reproduce the error with a minimal setup. My current ESLint config has a lot more plugins, configs and overrides than the example I was trying to set up, which seems to work great despite having exactly the same Node and package versions (I verified them manually in the lockfile and in my `node_modules`).

I don't really know what could make the rule fail in my current full-size setup, which is configured exactly the same, regarding the import plugin at least 😕 I absolutely can't downsize my current project bit by bit, because it's a huge monorepo with 30+ packages where ESLint was completely absent, so removing each piece to try the rule again would take forever.

I'll put this on the side for a while since I can't afford to spend much more time on this. Thanks for your help anyway @ljharb and for your reactivity, I'll ping you someday if I ever figure it out!

**Comment by karlhorky** [comment]
If it's a monorepo, you may have a central `yarn.lock` or `package-lock.json` file that contains the older versions, which you may be able to manually upgrade - for example, upgrading a version in `yarn.lock` by hand like this: https://www.youtube.com/watch?v=iOYTpHRzL0A
