### ISSUE TITLE
Document import/recommended

### ISSUE THREAD

**Issue by edemaine** [benmosher/eslint-plugin-import#2032]
I learned about the ruleset `import/recommended` from reading the CHANGELOG, but it's not in the README.  Presumably it should replace all the examples that use `import/errors` and `import/warnings`? (though those rulesets should also be mentioned once)

**Comment by ljharb** [comment]
Unfortunately recommended rulesets in plugins aren’t often up to date with what’s recommended, because of semver constraints. It should be mentioned, but not encouraged.

**Comment by edemaine** [comment]
@ljharb Is there a different source for "what's recommended"? I couldn't find anything in the documentation besides `import/errors` and `import/warnings`.

**Comment by ljharb** [comment]
Not really, no - but I’d suggest the Airbnb config.
