### ISSUE TITLE
Docs: import/extensions says node resolver resolves file extensions automatically

### ISSUE THREAD

**Issue by thernstig** [benmosher/eslint-plugin-import#2043]
From https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md

>  For example the node resolver can resolve ./foo/bar to the absolute path /User/someone/foo/bar.js because the .js extension is resolved automatically by default.

Is this true? Node.js requires the extension on files for relative paths: https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_mandatory_file_extensions

**Comment by ljharb** [comment]
It’s true for CJS (or ESM transpiled to CJS), which is the only resolution we deal with currently. That link references node’s native ESM, which isn’t supported here yet and shouldn’t really be used yet anyways.

**Comment by thernstig** [comment]
@ljharb thanks, that makes sense. But how come you say "shouldn't really be used yet anyways"? I decided to convert to ESM and use `--experimental-specifier-resolution=node` to get around not having to add `.js` to all files, and it works good for us.

But the biggest concern is that some packages will require ESM to be upgraded soon. See for example https://github.com/chalk/strip-ansi/releases/tag/v7.0.0 (77 million weekly downloads) and his reasoning https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c - this means we cannot upgrade many of the packages he uses, which is needed at times to get security fixes. So not using ESM is starting to become "not an option" if you want to stay on the latest and greatest.

**Comment by ljharb** [comment]
The experimental flag is likely to go away, and unlikely to ever become default.

Separately, the ecosystem and tooling around native ESM is nowhere near production-ready.

Packages that force consumers to use ESM will simply lose users, no matter how prolific the author is.

**Comment by thernstig** [comment]
> The experimental flag is likely to go away, and unlikely to ever become default.

Meaning that we will be forced to use `.js` on files? I think If I recall correctly I saw some posts by you saying that forcing `.js` on imports is a bad choice, and since you are indeed an authority in the Node ecosystem I listen with big ears 😄

**Comment by ljharb** [comment]
Yes, I think it is a terrible choice, and I would have preferred that that resolution behavior be the default. However, I don't make the decisions, and that doesn't look likely. The "exports" field, at least, relieves package consumers from having to use extensions, but, relative native ESM imports will have to use them, unfortunately.

Either way, until the ecosystem - and every commonly used tool - is fully updated to handle native ESM, I think it's too premature for anyone to be using.

**Comment by thernstig** [comment]
Closing this, I also appreciate very much you spent valuable time giving answers to me.
