### ISSUE TITLE
Security audit fails because of hosted-git-info vulnerability

### ISSUE THREAD

**Issue by mlarente** [benmosher/eslint-plugin-import#2048]
The npm security audit fails because of a [`hosted-git-info` vulnerability](https://www.npmjs.com/advisories/1677). This is a dependency through the `read-pkg-up` package. The latest version of `read-pkg-up` doesn't depend on the vulnerable package.

**Comment by ljharb** [comment]
We can never upgrade read-pkg-up, because it drops support for node versions we must support.

See #2047 which seeks to remove the dep altogether.

Duplicate of #2046.
