### ISSUE TITLE
"peerDependencies" option has no effect in "import/no-extraneous-dependencies" rule since 2.23.0

### ISSUE THREAD

**Issue by emilisb** [benmosher/eslint-plugin-import#2058]
With version `2.23.0` eslint fails due to `peerDependency` imports in our code:

`1:1  error  '{PACKAGE_NAME}' should be listed in the project's dependencies. Run 'npm i -S {PACKAGE_NAME}' to add it  import/no-extraneous-dependencies`

Our package is scoped (`@org-name/package-name`), not sure if it makes any difference.

Version `2.22.1` works fine.

Our config looks like this:

```
'import/no-extraneous-dependencies': [
      'error',
      {
        devDependencies: [
          //
        ],
        peerDependencies: true,
        packageDir: './',
      },
    ],
```

**Comment by ljharb** [comment]
cc @paztis / #1696, can you take a look at this?

**Comment by paztis** [comment]
I think #2097 will resolve it
