### ISSUE TITLE
Throwing circular JSON errors since 2.23.0

### ISSUE THREAD

**Issue by samuelfullerthomas** [benmosher/eslint-plugin-import#2060]
I've been getting this error since the update when using eslint with the new version:

```
(node:96994) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Node'
    |     property 'local' -> object with constructor 'Node'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
```

**Comment by ljharb** [comment]
Can you provide any info about the code that it's crashing on?

Also, the part of the stack trace you omitted is what I'd need to see what rule it's happening in, can you provide the entire trace?

**Comment by samuelfullerthomas** [comment]
it seems like it was just part of the issues around the broken 2.23 release
