### ISSUE TITLE
2.23.1: published version does not include "ExportMap" fix

### ISSUE THREAD

**Issue by bobaaaaa** [benmosher/eslint-plugin-import#2077]
Hey 👋,

I just updated this morning to the latest version and my installed version does not include this fix: https://github.com/benmosher/eslint-plugin-import/commit/d903477f4e31be71e016f8af56cbe2a8d4f11c9c

I tested it with yarn2 (empty cache, deleted node_modules) and a fresh npm project. Is it possible that something went wrong when publishing? I run your build script locally and everything looked fine.

#### Reproduce with a fresh project

```bash
# create a new empty random folder first
npm init -y
npm install eslint-plugin-import
less ./node_modules/eslint-plugin-import/lib/ExportMap.js
```

Thx for the awesome work ❤️

**Comment by ljharb** [comment]
Should be fixed in v2.23.2.
