### ISSUE TITLE
import/no-extraneous-dependencies rule does not check typescript

### ISSUE THREAD

**Issue by bingtimren** [benmosher/eslint-plugin-import#2095]
My eslint settings are as follows:

```
      parser: "@typescript-eslint/parser",
      parserOptions: {
        ecmaVersion: 12,
        sourceType: "module",
      },
      plugins: ["@typescript-eslint", "import", "prettier"],
      extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:import/recommended",
        "plugin:import/typescript",
        // put prettier LAST to override other configs
        "prettier",
      ],
```

eslint-plugin-import can pick out "import/no-unresolved" errors in Typescript files, but does not pick out "import/no-extraneous-dependencies" in Typescript files. At the same time "import/no-extraneous-dependencies" works on Javascript files.

**Comment by ljharb** [comment]
You're missing the `import/extensions` setting (unless typescript-eslint sets it) https://github.com/benmosher/eslint-plugin-import#importextensions

**Comment by bingtimren** [comment]
Thanks for responding. However I still can't make it work. I created a test repo to reproduce this issue.

In my test repo, I have package.json as follows:

```json
{
  "name": "eslint-ts-test",
  "version": "0.1.0",
  "description": "Test eslint on typescript project",
  "main": "index.js",
  "author": "Bing Ren <bingtimren@gmail.com>",
  "license": "MIT",
  "scripts": {
    "lint":"eslint index.ts"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.25.0",
    "@typescript-eslint/parser": "^4.25.0",
    "eslint": "^7.27.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.3",
    "eslint-plugin-prettier": "^3.4.0",
    "prettier": "^2.3.0",
    "typescript": "^4.2.4"
  }
}

```

And a typescript code index.ts:

```Typescript
import * as tslib from "tslib";
import {} from "somethingNotExist";

const someValue = 1;
export const value = someValue;
export const tlib = tslib;
```
Note that "tslib" is not listed as a dependency. However it's solvable as it's brought into node_modules by a development dependence.

Now the result of the lint:
```
$ eslint index.ts

/home/bing/tech-playground/temp/eslint-ts-test/index.ts
  2:16  error  Unable to resolve path to module 'somethingNotExist'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

I'm expecting "import/no-extraneous-dependencies" error being reported. 

To reproduce the issue, use the following commands:
```
git clone git@github.com:bingtimren/eslint-ts-test.git
cd eslint-ts-test/
yarn install
yarn lint
```

Did I miss something? Thanks!

**Comment by bingtimren** [comment]
Ok I solved this issue. I thought this rule is enabled by default, but I was wrong.

Now I added this to the "rules" section then it works.

```
"import/no-extraneous-dependencies" : "error"
```

Why not enable this rule by default?

I'm about closing this issue. However please consider enabling this rule by default.

**Comment by ljharb** [comment]
No rules are enabled by default; enabling new rules in a recommended config by default is a semver-major change.

Generally, configs like eslint-config-airbnb are a better choice than a plugin's own configs, for this reason.

**Comment by bingtimren** [comment]
Sorry, I mean I thought "import/no-extraneous-dependencies" is enabled in either "plugin:import/recommended" or "plugin:import/typescript". IMHO it's a useful rule and should be enabled in the recommended configs.

**Comment by ljharb** [comment]
It definitely is, and should be, but that can't happen until we have a semver-major release, which won't likely be happening any time soon.
