### ISSUE TITLE
import/order has no restrict unused imports rule and blocks similar

### ISSUE THREAD

**Issue by smalldazzy** [benmosher/eslint-plugin-import#2116]
Import/order has no such rule as restrict unused imports, moreover if use use import/order it blocks `unused-imports/no-unused-imports` plugin

**Comment by ljharb** [comment]
Can you provide more info? I'm not sure what the issue is.

I'm also not familiar with that plugin, but i don't know why any rule governing unused imports would be impacted whatsoever by any other rule.

**Comment by smalldazzy** [comment]
managed with this, was an error in config failing import/order plugin
