### ISSUE TITLE
Dependency cycle detected  import/no-cycle

### ISSUE THREAD

**Issue by SarvarKh** [benmosher/eslint-plugin-import#2119]
The requirement of the project is to separate DOM from logic in different files.
Thus, I have these files:

default.js
```
import { submitForm } from './logic'

function displayTaskForm(key) {
  // function create form HTML content with btn submit.
  submitForm(addTaskbtn, key);
  return form;
}

export { displayTable };
```

logic.js
```
import { displayTable } from './default';

const submitForm = (btn, key) => {
  // Adds event listener to add input to the table && local storage
  displayTable(key) // shows the table content including recent input
  return btn;
}

export { submitForm };
```

And I have a similar error as above:

default.js
`1:1  error  Dependency cycle detected  import/no-cycle`

logic.js
`1:1  error  Dependency cycle detected  import/no-cycle`

Could you advise how I could solve this issue? the problem is I have to split my DOM from the logic part. I don't see a way to link creating DOM based on if statement results.

Here is the [original repository link](https://github.com/SarvarKh/to-do-list)

**Comment by ljharb** [comment]
The warning is indeed correct, since you have files that depend on each other.

Your default.js is exporting displayTable but you’ve only shown the code for displayTaskForm, so I’m not sure why the files need to depend on each other - but the implication is that you’ve got many things in one file. Try aiming for one thing per file - it will make it much easier to avoid cycles.

**Comment by Slapbox** [comment]
Everything seems correct here to me. I think we can close this. 

@SarvarKh the rule is supposed to be off by default but it doesn't seem to be. You can always disable it if you'd like though. https://github.com/benmosher/eslint-plugin-import/issues/2103#issuecomment-858152817

**Comment by ljharb** [comment]
Every rule is off by default; a config enables them.

This rule is enabled in the airbnb config, for example, because it’s a very bad idea to have cycles of any kind.

**Comment by Slapbox** [comment]
Ah I see. Sorry for the issue clutter, I wasn't aware that this plugin was incorporated into their config.
