### ISSUE TITLE
Parse error if imported module contains private instance fields

### ISSUE THREAD

**Issue by jaydenseric** [benmosher/eslint-plugin-import#2124]
For example, `fetch-blob` uses [private instance fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#private_instance_fields) (available in Node.js v12+):

https://github.com/node-fetch/fetch-blob/blob/4747497b52c0d2b7e360b2281e1b51b779fc333c/index.js#L38

So if you try to lint a module importing it, with `import/default`, `import/namespace`, etc. rules:

```js
import Blob from 'fetch-blob';
```

You get ESLint errors like:

```
Parse errors in imported module 'fetch-blob': Unexpected character '#'
```

For example:

<img width="798" alt="Screen Shot 2021-06-11 at 6 48 58 pm" src="https://user-images.githubusercontent.com/1754873/121659543-c10b5900-cae5-11eb-9daf-a3f5252579d0.png">

**Comment by Slapbox** [comment]
@jaydenseric can you share the relevant code form 'fetch-blob' and what your ESLint config looks like? We use private fields in only one place in our project, but it works fine for us.

**Comment by Slapbox** [comment]
Try using `@babel/eslint-parser` as your parser with the following plugins configured:

```js
parser: '@babel/eslint-parser',
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2021,
    ecmaFeatures: {
      jsx: true,
      impliedStrict: true,
    },
    plugins: ['classPrivateProperties', 'classPrivateMethods'],
  },
```

And make sure your Babel config includes `@babel/plugin-proposal-private-methods`. I assume it does already since you're presumably able to compile your code - if you're using Babel. 

In any case, I don't think this is related to this project per se, but I'm happy to try to help you get this working if what I've mentioned isn't enough.

**Comment by ljharb** [comment]
The default parser doesn’t yet support ES2022 syntax, which includes private fields.

**Comment by ashokkumarmala7** [comment]
src/App.js
  Line 1:23:  Parse errors in imported module './components/Stopwatch': Line 105: Unexpected token

  103 | }
  104 |
> 105 | default export Stopwatch
