### ISSUE TITLE
[question] does this plugin support autofix of paths of typescript

### ISSUE THREAD

**Issue by hiroppy** [benmosher/eslint-plugin-import#2125]
We will resolve the paths aliases when we introduce eslint-import-resolver-typescript package, but this plugin doesn't support the auto-fix. I know this plugin doesn't focus on only typescript but do you plan to implement this feature? Or if no, is there a way to extend a rule?(or should I need to create another plugin? thanks

**Comment by ljharb** [comment]
I’m not sure what you mean, exactly. Can you elaborate?

**Comment by hiroppy** [comment]
yep, I want to respect the "paths" option than a relative path and enable no-relative-parent-imports rule. Even if users write a relative path, I think it's better to rewrite to the paths if possible automatically.

tsconfig

```json
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"],
    }
  }
}
```

```ts
import { foo } from '../../foo'; // I want to replace this relative path with "@/foo" by autofix
```

**Comment by ljharb** [comment]
That definitely seems like a rule better suited for the typescript-eslint plugin.

**Comment by hiroppy** [comment]
yeah, but the typescript-eslint doesn't support this rule. anyway, thank you for the answer

**Comment by ljharb** [comment]
Doesn’t, or will not?

**Comment by hiroppy** [comment]
currently, @typescript-eslint/eslint-plugin doesn't have this rule. I've not asked this to the plugin so I don't know an intention... Let's ask it
