### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#216]
It is impossible to keep up with fixes/ new rules added without a change log. A good example of a maintained CHANGELOG is https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md.

**Comment by benmosher** [comment]
I add release notes to the tags, could compile them into a file as such.

**Comment by benmosher** [comment]
Example: https://github.com/benmosher/eslint-plugin-import/releases/tag/v1.2.0

**Comment by gajus** [comment]
Didn't see that. Regardless, adding a step to the CI that compiles it to CHANGELOG.md would be very useful for a quick glance through the recent changes.
