### ISSUE TITLE
Why peer dependency of eslint 2?

### ISSUE THREAD

**Issue by danielfalk** [benmosher/eslint-plugin-import#218]
We're using eslint 1.x in our project, and we use plugins that haven't been updated to depend on eslint 2 yet.  eslint-plugin-import works for us with 1.x, even though the peer dependency is 2.x.  Why the requirement?  It's great that it still works, but npm keeps giving us EPEERINVALID warnings.

I love using this plugin.  It helps keep our windows devs from importing with a different case than the actual file paths, so I appreciate your work.  Thanks!

**Comment by benmosher** [comment]
Ah, yeah, if you're only using `no-unresolved`, I can imagine it working. 

Most or all of the rest of the rules parse the referenced module for info about what is exported to validate the imports. This requires a PR I submitted to ESLint that landed in 2.0. 

I would be surprised if the parsing rules work under ESLint 1.x. I removed a bunch of hacks for v1 of the plugin to make configuration simpler.

**Comment by benmosher** [comment]
If I get a chance, I'll see what it might take to back port to 1.x, but IIRC it would be a bit of a kludge.

FWIW, I use several plugins that declare 1.x as their peer dependency, but work fine on 2.x. I suspect you've already tried that, though, and/or you just end up with even more `EPEERINVALID`s that way.

**Comment by benmosher** [comment]
I'm going to close this. If someone wants to investigate and open a PR looking at supporting both, I will review, but it's not clear to me that there is a lot of payoff for effort surrounding supporting ESLint <2.x.
