### ISSUE TITLE
resolver plugin for `babel-plugin-module-alias`

### ISSUE THREAD

**Issue by chriddyp** [benmosher/eslint-plugin-import#219]
love this module, big thanks!
I'm using [`babel-plugin-module-alias`](https://github.com/tleunen/babel-plugin-module-alias). Has anybody in the community written a resolver plugin for this module?

**Comment by benmosher** [comment]
None that I know of. Only community one that I'm aware of currently is the jspm resolver that doctyper wrote.

Looks like it'd be straightforward. Could potentially write it as a wrapper that delegates to an inner resolver.

**Comment by benmosher** [comment]
Here's how I normally look at all the resolvers: https://www.npmjs.com/browse/keyword/eslint-plugin-import

**Comment by benmosher** [comment]
Just a heads-up, you may want towatch for #227 to land before implementing this.

**Comment by benmosher** [comment]
Resolver spec v2 is ready for you (or someone else) to implement this resolver, if you would like. Let me know if you do? :smile:
