### ISSUE TITLE
Uncaught TypeError in 1.2.0

### ISSUE THREAD

**Issue by doctyper** [benmosher/eslint-plugin-import#221]
I see the following error when eslint-plugin-import finds an unresolved import using `1.2.0`:

```
❯ eslint foo.js
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.statSync (fs.js:849:18)
    at Function._for (node_modules/eslint-plugin-import/lib/core/getExports.js:253:22)
    at Function.get (node_modules/eslint-plugin-import/lib/core/getExports.js:231:27)
    at processBodyStatement (node_modules/eslint-plugin-import/lib/rules/namespace.js:44:44)
    at Array.forEach (native)
    at EventEmitter.Program (node_modules/eslint-plugin-import/lib/rules/namespace.js:94:12)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (node_modules/eslint/lib/util/traverser.js:38:33)
```

The error does not occur using `1.1.0`. My (truncated) config is as follows:

```json
{
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "globalReturn": false,
            "experimentalObjectRestSpread": true,
            "jsx": true
        }
    },
...
    "settings": {
        "import/ignore": [
            "jspm_packages",
            "node_modules",
            ".(scss|less|css)$",
            ".[^js(x)?]+$"
        ],
        "import/resolve": {
            "moduleDirectory": [
                "jspm_packages",
                "node_modules",
                "."
            ]
        },
        "import/resolver": {
            "jspm": {
                "moduleDirectory": "jspm_packages",
                "pathsOverride": {
                    "public": "src"
                }
            },
            "node": true
        }
    }
}
```

**Comment by benmosher** [comment]
Can you paste the relevant source? Sounds like only the file you're linting is needed, if it's unresolved.

Also, could the `jspm` resolver be returning some non-null non-string? `getExports.get` should early exit if the path is null or undefined, so it must be some other non-string value.

**Comment by doctyper** [comment]
I believe the error occurs because my `eslint-import-resolver-jspm` resolver [returns `false`](https://github.com/nfl/jspm-resolve/blob/master/plugins%2Feslint-import-resolver-jspm%2Findex.js#L9) when a module is not found, but getExports is testing for a [`null` value](https://github.com/benmosher/eslint-plugin-import/blob/master/src%2Fcore%2FgetExports.js#L43). Should I be returning `null` instead?

**Comment by benmosher** [comment]
Yeah, I think that is likely the issue. Though I am not sure what changed since 1.1.0. I could just check truthiness.

**Comment by doctyper** [comment]
@benmosher If I return null the linter reports no issues with the unresolved path. I'm not sure that's the correct value to return.

**Comment by benmosher** [comment]
It might be `undefined`, then?

Sorry, it's been forever since I've looked behind the curtain of the resolvers :sweat_smile:

**Comment by benmosher** [comment]
Ah, yeah: https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/resolve.js#L76

`resolve` throws an error for unresolved paths, and then `core/resolve` returns `undefined`.

So you can either throw an error or return `undefined`, and that should work.

IIRC `null` is reserved to indicate that a path is a core module (like `fs` or `crypto`).

I need to document the resolver interface, for sure. :disappointed:

**Comment by benmosher** [comment]
Still not sure what changed between 1.1.0 and 1.2.0, though. `no-unresolved` was still checking for exactly `undefined` in 1.1.0: https://github.com/benmosher/eslint-plugin-import/blob/v1.1.0/src/rules/no-unresolved.js#L19

**Comment by benmosher** [comment]
Ah, it's because it used to call `fs.existsSync` on whatever came back from the resolver, and `fs.existsSync(false) === false`.

I removed that because `resolve` throws an error if it can't resolve, so the extra `fs.existsSync` is unnecessary disk activity.

Do you want me to support arbitrary non-null false-y values as being unresolved? Or are you good with returning `undefined` from the jspm resolver?

**Comment by doctyper** [comment]
Fixed in `jspm-resolve@1.1.1`

**Comment by benmosher** [comment]
Sorry about that! I will try to work out some sort of integration tests to avoid this in the future.

**Comment by benmosher** [comment]
@doctyper I just published v1.4.0 under the `next` tag. Added a v2 resolver interface that returns `{ found:Boolean, path: String? }` objects to reduce future confusion.

Should be backwards-compatible with the first version of the interface (works with the `node`/`webpack` v0.1.x resolvers AFAICT), but optimally you can confirm `jspm` is still working before I move it to `latest`? :sweat_smile:

**Comment by benmosher** [comment]
Also documented the interface more completely this time: https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers

**Comment by doctyper** [comment]
@benmosher :+1: Out in `eslint-import-resolver-jspm@2.0.0`
