### ISSUE TITLE
Is it possible to have a separate webpack config for tests?

### ISSUE THREAD

**Issue by axelson** [benmosher/eslint-plugin-import#223]
We have a separate alias that is only used for tests and it would be nice to have this supported in eslint-plugin-import.

**Comment by benmosher** [comment]
You can re-specify `import/resolver` in an `.eslintrc` for your test folder.

I do this for one of my projects, where I use the `webpack` resolver for `./src` and the stock `node` resolver for `./test`.

I think this covers what you're asking?

**Comment by axelson** [comment]
It seems like it should but I'm still having some issues. Might be related
to how the base weback configuration interacts with the test config.
Definitely possible that it's user error.

**Comment by benmosher** [comment]
Can you provide more details about the folder structure and the contents of the config files?

**Comment by benmosher** [comment]
closing for now, let me know if you want to discuss further
