### ISSUE TITLE
Mysterious error (ESLint cache)

### ISSUE THREAD

**Issue by loqusion** [benmosher/eslint-plugin-import#2260]
The `import/no-cycle` error error occurred in `packages/web/src/utils/index.ts`, and it printed something like `error Dependency cycle via web/src/lib/api-client:2=>./schema:3=>./schema:5` (this is from memory because I unfortunately cleared the log by habit). `utils/index.ts` didn't even import anything from those modules.

The way I fixed it is by adding the line `// eslint-disable import/no-cycle` in `utils/index.ts`, then removing that line. In other words, the file was exactly the same (at least in terms of visible characters) before and after I experienced the error.

I doubt this is easily reproducible, I'm just wondering if anyone knows why this could have happened.

<html>
<body>

package | version
-- | --
`@typescript-eslint/eslint-plugin` | `4.31.1`
`@typescript-eslint/parser` | `4.31.1`
`eslint-plugin-import` | `2.24.0`
`eslint-import-resolver-typescript` | `1.1.1`
`typescript` | `4.4.3`
`eslint` | `7.32.0`
`node` | `14.17.3`
`npm` | `6.14.13`
`yarn` | `1.22.15`

</body>
</html>

**Comment by sshmyg** [comment]
Same issue, in vscode.
Updated elsint and eslint-import and after that almost each file has cycle deps. But before updates all was fine.

**Comment by ljharb** [comment]
Restarting vscode didn’t help?

**Comment by sshmyg** [comment]
> Restarting vscode didn’t help?

Didn’t help any standard actions, restart vs, restart OS. Just turned off this cycle check for now. Looks like logic for cycle check was changed if compare with version 2.4. imho. Maybe Im wrong. But had no any problems with this rule until updates.

**Comment by ljharb** [comment]
@sshmyg do you see the same issues on the command line?

If so, it'd be great if you filed a new issue, since this one's about vscode's cache. If not, then it's your editor.

**Comment by loqusion** [comment]
I updated the title not to include `import/no-cycle` since this issue doesn't really have anything to do with that rule in particular.

**Comment by sshmyg** [comment]
> @sshmyg do you see the same issues on the command line?
> 
> If so, it'd be great if you filed a new issue, since this one's about vscode's cache. If not, then it's your editor.

Made ` npx eslint ./src` in terminal and got same errors as in VSCode.
Without cycle rule checks took ~ 2min.
With cycle rule ~ 47min
