### ISSUE TITLE
Remove no-duplicates

### ISSUE THREAD

**Issue by lencioni** [benmosher/eslint-plugin-import#242]
This rule appears to be part of ESLint as of 2.5.0. http://eslint.org/docs/rules/no-duplicate-imports

**Comment by benmosher** [comment]
Ah, cool, makes sense. 

I can't remember if this is in one of the canned configs, but probably ought to replace it with the ESLint rule upon removal.

**Comment by benmosher** [comment]
Oh, actually, I think I will keep it. The version of this rule in this plugin resolves the path, so if you use more than one way to get to the same module, it will still be flagged. So it's a bit more powerful than the core version.

It also disambiguates Flow types vs. "normal" imports. Which seems to be desired: 

- https://github.com/eslint/eslint/issues/6214 (ESLint rejected this, explicitly)
- https://github.com/babel/eslint-plugin-babel/issues/59
- https://github.com/gajus/eslint-plugin-flowtype/issues/25

Need to make note of both of these distinguishing features.
