### ISSUE TITLE
Rule proposal: Enforce imports be placed at the top of the file

### ISSUE THREAD

**Issue by sindresorhus** [benmosher/eslint-plugin-import#253]
Moved from https://github.com/jfmengels/eslint-plugin-import-order/issues/11.

Imports are hoisted to the top anyways. So better to be explicit about it.

Should either ignore `require` or have an option to ignore it, as `require` is often used inline and is not hoisted.

**Comment by sindresorhus** [comment]
Sorry, I missed the [`imports-first`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/imports-first.md) rule...

**Comment by benmosher** [comment]
Do you envision this as an option on the `order` rule?

**Comment by benmosher** [comment]
Ah, lol, right. I also forgot that one. 😅

**Comment by jfmengels** [comment]
I'd put this in the `order` rule. It will need to handle it anyway, otherwise stuff like the following will error:
```js
import foo from './foo'
var path = require('path'); // should have been before `./foo`
```

**Comment by benmosher** [comment]
I wouldn't be opposed to moving this into `order`. The existing rule is sort of a half-measure version of `order` anyway, could deprecate and drop the next time ESLint bumps major.

**Comment by sindresorhus** [comment]
I don't see how `import-first` is relevant to ordering though. It's just about enforcing imports at the top, in any order.

**Comment by benmosher** [comment]
I was thinking that if they are most frequently used together, it might be simpler to make it a single rule.

That's fair, though. Could move the opposite direction and take the absolute-first bit out of import-first, too.

On Apr 21, 2016, at 21:17, Sindre Sorhus <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see how import-first is relevant to ordering though. It's just about enforcing imports at the top, in any order.

-

**Comment by sindresorhus** [comment]
> Could move the opposite direction and take the absolute-first bit out of import-first, too.

👍 Agreed. It doesn't fit there.
