### ISSUE TITLE
remove `absolute-first` option from `imports-first`

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#259]
It's not documented, and it is very much superseded by the `order` rule.

**Comment by jfmengels** [comment]
As pointed out here https://github.com/benmosher/eslint-plugin-import/pull/277#issuecomment-215059238, it is actually documented.

**Comment by benmosher** [comment]
Yep, I don't know what I was thinking.

**Comment by benmosher** [comment]
This actually feels like a breaking change for breaking's sake. This option is a little lower-intensity than full-on `order`, so I think I'll just make a note in the README and keep it.
