### ISSUE TITLE
Support optionalDependencies in the `no-extraneous-dependencies` rule

### ISSUE THREAD

**Issue by sindresorhus** [benmosher/eslint-plugin-import#266]
I ran it on [AVA](https://ava.li) and got:

```
  test/cli.js:19
  ✖   19:2  'chokidar' is not listed in the project's dependencies. Run 'npm i -S chokidar' to add it  import/no-extraneous-dependencies
```

It is defined, but as an optionalDependency: https://github.com/sindresorhus/ava/blob/c4e58e3e7eeb6b966a32a964445ac5ced813793a/package.json#L171-L173

-

Using master (https://github.com/benmosher/eslint-plugin-import/commit/055201e32072de18250603f64befd5e292c2b7bc).

**Comment by benmosher** [comment]
Yeah, I suspect the `peerDependencies` version of this is inevitable as well (though those are often reflected in `devDependencies`, so maybe not).

Feels like the existing `devDependencies` strategy makes sense. Default to allowed, add as a flag to enforce as is if desired.

**Comment by sindresorhus** [comment]
> Feels like the existing devDependencies strategy makes sense. Default to allowed, add as a flag to enforce as is if desired.

Default to allowed yes. I don't see why you would want to disallow it though? `optionalDependencies` are more like `dependencies` than `devDependencies`.

**Comment by benmosher** [comment]
I can imagine turning it off for tests or "critical" regions or something. Easy enough to support (maybe even easier than not).

If whoever implements this wants to leave the option off, though, I won't argue. 😎

**Comment by sindresorhus** [comment]
👍 Alright. Was just curious.

**Comment by rexxars** [comment]
What happened to the `peerDependency` version of this? If you don't have tests that require it, they won't necessarily be in devDependencies..?

**Comment by benmosher** [comment]
@rexxars don't think anyone is looking at it. PR welcome. 😁

**Comment by ianstormtaylor** [comment]
+1 to `peerDependencies`

**Comment by benmosher** [comment]
@rexxars @ianstormtaylor created #423 to track, accepting PRs 😎
