### ISSUE TITLE
Node.js v6: Can't pass null to path module functions

### ISSUE THREAD

**Issue by strawbrary** [benmosher/eslint-plugin-import#272]
In Node.js v6, all `path` functions will now throw an error if they receive a non-string path argument. `eslint-import-resolver-node` returns `path: null` for core modules which causes [`fileExistsWithCaseSync`](https://github.com/benmosher/eslint-plugin-import/blob/ea1b0e3d2d0c58287d8513a71e79100b48feed38/src/core/resolve.js#L29) to throw an error.

I wasn't sure if it would be better to make the change in the resolver or the plugin itself so I'm just opening an issue about this for now.

**Comment by benmosher** [comment]
Oh, wild. Good to know.

We probably ought to go ahead and open a PR with v6 in the Travis config and start getting ready! Thanks!

**Comment by benmosher** [comment]
Also, for future reference: the `null` path from the resolver is part of the spec. The plugin should exit early and not pass it to the path functions.

**Comment by strawbrary** [comment]
Got it, thanks for the info. v6 isn't out officially yet so I'm not sure if there's a way to get Travis to build with it, but they're aiming to release it tomorrow I believe. In the meantime the rc builds are here: https://nodejs.org/download/rc/

**Comment by benmosher** [comment]
fixed in #273
