### ISSUE TITLE
import/no-unresolved with SystemJS plugins

### ISSUE THREAD

**Issue by screendriver** [benmosher/eslint-plugin-import#276]
I am using [eslint-import-resolver-jspm](https://github.com/nfl/jspm-resolve/tree/master/plugins/eslint-import-resolver-jspm) but don't get it running with [SystemJS](https://github.com/systemjs/systemjs) [plugins](https://github.com/systemjs/systemjs#plugins). For SystemJS plugins you have to add a `!` at the end of the import.

For example I am using [plugin-text](https://github.com/systemjs/plugin-text) and import a file like so

`import myText from './test-file.hml!text';`

Is there a way I can tell eslint-plugin-import to check that the file exists but don't parse the content? I played around with `"import/ignore"` and `import/no-unresolved: [2, { ignore: ['\.html$'] }]` but don't get it running 😕

If I set `ignore` in my rules the file will be completely ignored. That's what I want. But it doesn't check if the file exists. So I can write anything I want. If I only set `"import/ignore": ['.html$'],` it gives me an error because it can't find the file `test-file.html!text'` on the file system (it should only look for `test-file.html` and not for `test-file.html!text`)

**Comment by benmosher** [comment]
I wonder if the jspm resolver is removing the plugin reference from the path. 

Also, no-unresolved should ignore the ignore setting, IIRC. it would be better named no-parse or something, probably. 😅

**Comment by CharlieGreenman** [comment]
Hey, I am working through a similar issue, any further progress on this one?

**Comment by benmosher** [comment]
@CharlieGreenman I was going to recommend mentioning over at the resolver project, but: https://github.com/nfl/jspm-resolve/issues/7

So I don't understand the problem. Where is SystemJS coming into play? Is it plugged into jspm? or somewhere else?

I don't know anything about SystemJS or jspm, unfortunately, so it's unclear to me what needs to happen where to resolve this.

**Comment by ljharb** [comment]
Closing; if this is still relevant, and if the relevant resolver can't handle this, and if no-unresolved still isn't using the resolvers, then this can be reopened.
