### ISSUE TITLE
resolve: Upgrade to Node 6 tries to resolve `path`

### ISSUE THREAD

**Issue by kentcdodds** [benmosher/eslint-plugin-import#292]
Not sure why, but when I upgrade to node 6, it appears that the `namespace` plugin is trying to check whether the `path` file exists for my `import path from 'path'`.

I've put a bunch of console logs in my node modules and I get to [this line](https://github.com/benmosher/eslint-plugin-import/blob/e69561c027e2e2906e8c6cedfbef94837ad0067b/src/core/resolve.js#L35) where `filepath` is `null`.

I've dug in further and the `eslint-import-resolver` name is `node`.

Looks like when the resolver finds a core module, [it returns](https://github.com/benmosher/eslint-plugin-import/blob/e69561c027e2e2906e8c6cedfbef94837ad0067b/resolvers/node/index.js#L8): `{ found: true, path: null }` and we should probably do a null check [here](https://github.com/benmosher/eslint-plugin-import/blob/e69561c027e2e2906e8c6cedfbef94837ad0067b/src/core/resolve.js#L114) for that.

By adding that null check in my `node_modules`, things work great for me locally. I'll file a pull request in a moment to discuss fixing this :+1:

**Comment by kentcdodds** [comment]
Whoops! Looks like I was using an old version of this plugin! Latest (`1.6.1`) doesn't have this bug. Closing!

**Comment by jfmengels** [comment]
Thanks for making a PR anyway!
