### ISSUE TITLE
Webpack resolver doesn't apply `resolve.root` and `externals` option.

### ISSUE THREAD

**Issue by Beingbook** [benmosher/eslint-plugin-import#299]
My webpack configurations is

```js
// config.js
export webpackCommon = {
  // ...,
  resolve: {
    root: srcPath, // it's /src directory path
    extensions: ['', '.jsx', '.json', '.js'],
  },
  externals: [
    /^\.\/assets\.json$/,
    fs.readdirSync(modulePath).filter(x => x !== '.bin'),
  ],
  // ...,
};
```

```js
// config.es5.js
require('babel-register');
require('babel-polyfill');
module.exports = require('./config').webpackCommon;
```

My eslintrc setting is:
```json
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "./tools/conifg.es5.js"
      }
    }
  }
```

OS: OSX El Cap latest

this plugin can't resolve `./assets.json`
<img width="814" alt="2016-05-03 2 40 59" src="https://cloud.githubusercontent.com/assets/2682865/14975521/6ade95fe-113d-11e6-8e50-fd39b4631e88.png">

and root path modules as below:
There's two directories

* /src/components/A
* /src/components/B

In component A, it can resolve component B as `import B from 'component/B;` but it doesn't work.

**Comment by benmosher** [comment]
From your `.eslintrc`:
> `"config": "./tools/conifg.es5.js"`

is that a typo in the issue or a typo in your config?

**Comment by Beingbook** [comment]
@benmosher  that's my configuration.

**Comment by benmosher** [comment]
So what happens if you update 'conifg' to 'config'?

**Comment by Beingbook** [comment]
@benmosher I can't got what you mean.

**Comment by benmosher** [comment]
Your Webpack config path is misspelled in the resolver config.

**Comment by Beingbook** [comment]
@benmosher The path is correct. because I can reference the es5 configurations through using node-cli like:
```js
console.log(require('./tools/config.es5.js'));
```

the configuration files are placed at `<Project Root>/tools`.

**Comment by benmosher** [comment]
I get that, but "config" is misspelled as "conifg" in the eslintrc you pasted.

**Comment by Beingbook** [comment]
Wow... awesome... I couldn't find out... Thank you.

**Comment by benmosher** [comment]
Thus #300. No worries. 😎
