### ISSUE TITLE
Support module exceptions in `named` rule?

### ISSUE THREAD

**Issue by chase** [benmosher/eslint-plugin-import#30]
It would be nice to have the ability to exclude certain modules for the `named` rule.

Modules like [react-router](https://github.com/rackt/react-router) and [immutable](https://github.com/facebook/immutable-js) do not use ES6 exports, for example.

Alternatively, searching for modification of `exports` may allow it to work appropriately.

**Comment by benmosher** [comment]
This is related to #28. I have gone back and forth on supporting parsing of CommonJS and other non-ES6 modules, from doing some simple analysis of `exports`, like you suggest, to just silently ignoring non-ES6 modules. 

I assume given your comment that you use ES6 imports for all your modules? I have considered something like a `detect-common` setting that would allow for some interoperability with CommonJS. Feels like a pretty likely use case. 

Do you think this proposal would support your use case(s)?

**Comment by benmosher** [comment]
Also, FWIW, you can `//eslint-disable-line import/named` to squelch the report on a per-line basis. I think a pair of `//eslint-disable import/named` + `//eslint-enable import/named` around a block of CommonJS module imports would also work.

Though it's super lame to have to modify the source to deal with linting, IMO. So I am not suggesting this as a long-term solution, just a point of information.

**Comment by chase** [comment]
I do use ES6 imports for all modules. I'm using Webpack with Babel to compile things down to CommonJS and ES5, so the behavior is as expected.

I think that `detect-common` would be a more than decent solution for the long term, but if it would be easier to silently ignore non-ES6 modules in the short term then that works just as well.

For now I've simply disabled the `name` rule since as I use Immutable just about everywhere.

Thanks for taking time to help me out :smiley:

**Comment by benmosher** [comment]
2 new features: 
- `import.ignore` setting: a list of regex strings that will be ignored by all rules
- `all`/`relative-only` per-rule setting: most rules now ignore absolutely-pathed modules. (`no-unresolved` is the exception as this is useful whether the module is ES6 or CommonJS)

I believe one or both of these solve the problem. I figure ATM it's more likely than not that only in-project files are actually references to their ES6 representations; most node_modules will be CommonJS for the short- and mid-term, probably. (we can cross that bridge when it comes :sweat_smile:)

**Comment by chase** [comment]
Awesome! Thanks for putting time into this :+1:

**Comment by benmosher** [comment]
Let me know if you run into issues. I bumped up to 0.5.1 since the `relative-only` default is essentially a breaking change. I'm going to start using it again today (had to disable it for similar reasons to yours) and I'll knock out anything I run into.

**Comment by benmosher** [comment]
Another thought as I reflect: would it make more sense to ignore modules with `node_modules` in the _complete_ path vs. absolute-ish module source paths?

i.e. I have a `NODE_PATH=./src` on my build so I can do things like
```javascript
import { a, b } from 'jsx/some/module'
```
from anywhere in my code, but it's tough to distinguish at face value from something like

```javascript
import { findDOMNode } from 'react'
```

...but the resolved filesystem path should contain `node_modules`. I may play around with that as a default.

**Comment by chase** [comment]
Hm, that does seem like a better approach to base it off of whether the resolved path contains `node_modules`. It looks like you already addressed core modules of Node.js like `crypto`.

I haven't gotten time to adjust our lint file to use the new version just yet, but when I get to a point where I can test it thoroughly, I'll let you know if it works out.

**Comment by chase** [comment]
For some reason I just can't get this to ignore things in `node_modules`:

Here is a simple example with Immutable:
https://gist.github.com/chase/341f060e62bea8888955

I'm probably doing something incorrectly, but I honestly can't figure out what.

**Comment by benmosher** [comment]
Everything looks good with your settings, it should be disabling the parse by default.

I have been using it IRL with React/Immutable and it doesn't report for `import/default`...but I don't have many named imports from node modules, so there could be a difference there. 

Maybe I flubbed something with the ESLint tests I wrote? I'll investigate when I get a chance. 

--Ben

**Comment by benmosher** [comment]
I downloaded your gist and I am unable to reproduce. It works as expected (no output from ESLint), but then I do get that output when I explicitly set `import/ignore` to `[]`. (also expected)

I'm not sure what could be going on. One tenuous idea: could you have an old copy of the plugin installed globally / in an ancestor folder and it's somehow using that instead? (I think if ESLint is installed globally it might only use globally-installed plugins?) Not sure if that's possible, though. But I'm unable to reproduce on my machine. :confused:

**Comment by chase** [comment]
Good call on the globally-installed plugin inconsistency, that's exactly what was happening. I forgot I had it installed globally. I really wish that `./node_modules/.bin/eslint test.js` wouldn't use global plugins by default.
