### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#300]
Would be helpful to get more output in cases like #299, #238.

Would also help self-service in cases where it's just some simple config issue / typo (i.e. config not found).

**Comment by sindresorhus** [comment]
I would use [`debug`](https://github.com/visionmedia/debug), and then use it like this:

```sh
DEBUG=eslint-plugin-import eslint .
```

**Comment by benmosher** [comment]
Ah, cool idea. I have only used that in the browser before, forgot it was born for Node.

**Comment by benmosher** [comment]
done in webpack resolver (v0.3.1), will expand as needed
