### ISSUE TITLE
no-deprecated TomDoc support

### ISSUE THREAD

**Issue by josh** [benmosher/eslint-plugin-import#302]
I know `no-deprecated` is still a WIP, but I was wondering if you'd consider parsing [TomDoc](http://tomdoc.org/) `Deprecated:` annotations? 

Its basically a line like:

``` js
// Deprecated: Resize an object to the given dimensions.
```

I'd totally be willing to code up a PR, just wanted to check if you'd consider this in scope.

Thanks!

**Comment by benmosher** [comment]
I'm up for more flavors of docstring parsing, for sure. I'm not sure exactly how to work it in, though.

Naïvely, I can imagine some `{ flavor: 'tomdoc' }` rule option where `tomdoc` is a `doctrine`-compatible docstring parser, though that's probably not practical as `doctrine` is pretty heavily JSDoc-influenced. (for good reason).

How would you propose to integrate it?

**Comment by josh** [comment]
> where tomdoc is a doctrine-compatible docstring parser

If you wouldn't mind embedding a tiny parser function into the file, it'd probably be really short. TomDoc is less structured than JSDoc. We could probably just scan for `/Deprecated:/` and return it as `{ tags: [ "deprecated", ... ] }` so it aligns with the doctrine result object.

There is a more *legit* tomdoc parser on [npm](https://www.npmjs.com/package/tomdoc), but I don't know if its worth adding another dependency just for it.
