### ISSUE TITLE
Webpack resolver doesn't resolve aliased paths behind another package.json

### ISSUE THREAD

**Issue by leonid-bauxy** [benmosher/eslint-plugin-import#303]
The problem is when you have nested `package.json` and your top-level `.eslintrc` uses `webpack` resolver with defined aliases. In this case you can't import aliased paths inside the files in the nested folder(the one with `package.json`).

Let me show you the structure:

```
- router
    - package.json
    - ClientRouter.js
    - ServerRouter.js
- errors
    - ApplicationError.js
- .eslintrc.js
- webpack.config.js
- index.js
- package.json
```

webpack.config.js
```js
const path = require('path');

module.exports = {
  resolve: {
    alias: {
      errors: path.resolve(__dirname, 'errors')
    }
  }
};
```

.eslintrc.js
```js
module.exports = {
  rules: {
    'import/no-unresolved': 'error'
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: './webpack.config.js'
      }
    }
  }
};

.index.js
```js
import ApplicationError from 'errors/ApplicationError'; // everything is fine here, no errors
```

router/ClientRouter.js
```js
import ApplicationError from 'errors/ApplicationError'; // ERROR 'import/no-unresolved'
```

The nested `package.json` doesn't contain any dependencies. Here's it's contents:
```json
{
  "main": "./ServerRouter.js",
  "browser": "./ClientRouter.js"
}
```

**Comment by benmosher** [comment]
You should be able to get around that with an absolute path, i.e.

```js
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, 'webpack.config.js')
      }
    }
```

I'd take a PR that keeps looking if a config is not found adjacent to the first `package.json`, but this behavior is [consistent with the README](https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/README.md).

**Comment by leonid-bauxy** [comment]
Ah, i thought it was looking for webpack config relative closest to the `.eslintrc`, not to the currently linted file. Got it. I think it's good as is, although it forces the user to use `js` format of the `eslint` config. You can close it now. Thanks!

**Comment by benmosher** [comment]
Yeah, it's not perfect. Not sure exactly what would be ideal in this case. Glad it's working for you now, though.
