### ISSUE TITLE
suggestion to add rule prefer-default-export

### ISSUE THREAD

**Issue by gavriguy** [benmosher/eslint-plugin-import#304]
I was wondering if you would like me to add a PR with this rule [prefer-default-export](https://github.com/applicaster/eslint-plugin-apprime/blob/master/docs/rules/prefer-default-export.md) as it seams related to this repo.

P.S.
I want to give credit to @ilyavolodin for suggeting this in the eslint Gitter.

**Comment by benmosher** [comment]
Sure, works for me if it makes sense to you. 😄

**Comment by gavriguy** [comment]
Opened the PR - https://github.com/benmosher/eslint-plugin-import/pull/308

**Comment by jfmengels** [comment]
Closed in https://github.com/benmosher/eslint-plugin-import/pull/308

**Comment by benmosher** [comment]
Just released in 1.8.0! 😄
