### ISSUE TITLE
import/extensions is confused by "keen-js"

### ISSUE THREAD

**Issue by krainboltgreene** [benmosher/eslint-plugin-import#309]
```
error  Unexpected use of file extension "" for "keen-js"  import/extensions
```

```
import Keen from "keen-js"
```

**Comment by benmosher** [comment]
I think this should be solved in v1.7.0, if not let me know and we can debug.

**Comment by benmosher** [comment]
(fwiw, I think #296 would have solved it)

**Comment by krainboltgreene** [comment]
Thanks!

On Fri, May 6, 2016 at 5:36 AM, Ben Mosher <notifications@github.com> wrote:

> (fwiw, I think #296
> <https://github.com/benmosher/eslint-plugin-import/pull/296> would have
> solved it)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/benmosher/eslint-plugin-import/issues/309#issuecomment-217428155>
>



-- 
Kurtis Rainbolt-Greene, Software Developer
Founder of Difference Engineers

2985 San Marino St.
Los Angeles, CA 90006
202-643-2263
