### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by borisyankov** [benmosher/eslint-plugin-import#317]
I get "Cannot read property 'name' of undefined" in file no-mutable-exports.js:80:56

The line is 
export Something from './something';

**Comment by frostney** [comment]
While not a fix, you can get around this by setting `import/no-mutable-exports` to `0` in your `.eslintrc`.

**Comment by benmosher** [comment]
Ah, got it. So it doesn't support the ES7 export extensions. Good to know, thanks! 

Probably will just ignore them to start. Could check the referenced export for mutability but it will be flagged there anyway.
