### ISSUE TITLE
import/no-extraneous-dependencies does not work with scoped dependencies

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#330]
I am getting an error:

>  '@kadira' should be listed in the project's dependencies. Run 'npm i -S @kadira' to add it

even though `@kadira/storybook` is a package dependency.

**Comment by jfmengels** [comment]
Yes, this was fixed in https://github.com/benmosher/eslint-plugin-import/pull/324 but has not been released yet.

**Comment by benmosher** [comment]
Just released in 1.8.0 😄
