### ISSUE TITLE
add @jfmengels to npm publishers for published modules

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#347]
@jfmengels just wanted to bounce this off you. Would be good to have you authorized to publish, too.

Would add you to 
- plugin package
- core resolvers (currently Node + Webpack)
- the core module (eslint-module-utils), once I finish it up

Would just ask that you propose version bumps via a PR (or something else, I'm not sure what the de facto standard is for GitHub=>npm publish consensus) and let me review + approve before publishing.

I'm not saying you need to do publishes in general--I'm still planning to do most of the publishes, but I thought it would be good to have the option open. Seems like a good thing to have as a collaborator. :smile:

Also I would be willing to do PRs to propose publishes to get your feedback as well, if you'd like. Probably makes sense. I don't want to add a ton of process/burden either, though.

**Comment by jfmengels** [comment]
Cool! Thanks! :)

> Would just ask that you propose version bumps via a PR

Sure. Don't plan on doing any except if really necessary, but :+1:.

> Also I would be willing to do PRs to propose publishes to get your feedback as well

Let's try it, and if it doesn't work out well or feels too cumbersome (take too much time to reply, never give any useful feedback anyway), then let's review or cut this process.

**Comment by benmosher** [comment]
Sweet, not sure when I'll actually get around to this but I'll let you know when I do!

**Comment by jfmengels** [comment]
:+1: I'll probably get a mail anyway ;)

**Comment by jfmengels** [comment]
Thanks :D
