### ISSUE TITLE
webpack: Don't throw on externals function

### ISSUE THREAD

**Issue by kesne** [benmosher/eslint-plugin-import#349]
Currently, if externals is defined as a function, then the plugin will throw an error. This makes the webpack resolver completely useless if you ever use an externals function. Instead of throwing, maybe we could log out an error, or just list is as a limitation of the module? Just something that still makes the module useable in these cases.

This is the line of code that causes issues:
https://github.com/benmosher/eslint-plugin-import/blob/c15901b2deb70b414a25458ba6ae43b8e3825b82/resolvers/webpack/index.js#L170

I ran into this issue when pointing to a webpack config that uses `webpack-node-externals`, which made it impossible to use this plugin against that config.

**Comment by benmosher** [comment]
Ah, wild, I didn't realize that was an option. Should be easily fixed, I think. Thanks!

**Comment by benmosher** [comment]
Actually could you contribute a PR with a failing test? Looking again, I'm not sure how I would validate that this issue is resolved. I had hoped that the branch using enhanced-resolve would have handled it, but it did not.

**Comment by kesne** [comment]
contributed a PR with a basic fix in #363
