### ISSUE TITLE
peerDependency issue with eslint@1.0.0-rc-1

### ISSUE THREAD

**Issue by doctyper** [benmosher/eslint-plugin-import#35]
Hi, can you update your peerDependency to work with `eslint@1.0.0-rc-1`? This is the same issue as: https://github.com/yannickcr/eslint-plugin-react/issues/154.

The following should work:

```
"peerDependencies": {
    "eslint": ">=0.16.0 || ~1.0.0-rc-0"
}
```

**Comment by doctyper** [comment]
Awesome, thank you. Looking forward to the next npm release!

**Comment by benmosher** [comment]
I'm publishing 0.7.1 as soon as the Travis build succeeds! :sunglasses:
