### ISSUE TITLE
if relative paths are used, custom resolver cannot be a path relative to node_module root

### ISSUE THREAD

**Issue by lukeapage** [benmosher/eslint-plugin-import#367]
If I use a relative import, modulePath is relative and then pkg-dir cannot find the package directory and my custom resolver is not found.

**Comment by benmosher** [comment]
Can you provide an example?

**Comment by lukeapage** [comment]
@benmosher I think this was broken by you after merging the PR

https://github.com/benmosher/eslint-plugin-import/commit/9b9d905243f26ca94d17cd7050d0e19b5e6a263c

```
 pkgDir.sync(resolve(modulePath))
```
==>
```
pkgDir.sync((modulePath))
```

**Comment by lukeapage** [comment]
but putting that back then creates `Cannot read property 'report' of undefined`.
I would suggest passing the sourceDir too and then doing a simple resolve with path before passing to pkg-dir.

Does this make sense yet or do you still need an example?

**Comment by lukeapage** [comment]
aha perfect you fixed it already :)

**Comment by benmosher** [comment]
bizarre, not sure how that fell off.

Just pushed fixes. It should have been resolving relative to `sourceFile` anyway.

**Comment by benmosher** [comment]
If you get a chance, could you contribute some tests for this? It's not obvious to me how you and @le0nik intend to use it, but it _is_ obvious I'm going to break it without tests. 😅

**Comment by lukeapage** [comment]
its actually still broken because either it never worked or `resolve` has changed.

I think instead of calling `resolve(modulePath)` it needs to call `relative(modulePath, sourceDir)`

re: tests and fixing this bug, yes, next time I have some time, hopefully in the next couple of days

**Comment by lukeapage** [comment]
Please revert your 2nd commit d5ccad0148f208e6efb4ab247127d730e2447430 and all is good.
