### ISSUE TITLE
custom resolvers: must load `eslint-import-resolver-{x}` form _first_

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#373]
Allowing explicit packages to have precedence means that `webpack` is being loaded to resolve instead of `eslint-import-resolver-webpack`.

Blocks v1.9.0 release. (#372)

**Comment by avaragado** [comment]
@benmosher I've just spent an hour working out why my config wasn't working, and it's because of this issue. I have eslint-plugin-import 1.9.0, with eslint-import-resolver-webpack 0.3.1.

Any chance of releasing this fix soon?

**Comment by benmosher** [comment]
@avaragado just published 1.9.1 with just this patch.

How did you end up with 1.9.0 installed? I hid it behind the `next` tag on npm so that it wouldn't be public-facing, ideally.

**Comment by avaragado** [comment]
@benmosher Looking through my command-line history, it seems it was presented under the 'Wanted' column of `npm outdated`. The 'Latest' column showed 1.8.1. I guess I jumped the gun.

**Comment by benmosher** [comment]
I was worried that might happen. 😞  I think 1.9.x is semver-valid if your package.json has something like `^1.8.1`. So that's on me, I didn't realize npm would install versions past the `latest` tag.

**Comment by avaragado** [comment]
Yeah, that's the situation I was in. `npm update` ignores those tags, it seems, and follows the semver specified in `package.json`.

I've updated to 1.9.1 and it works, so thanks!
