### ISSUE TITLE
eslint-import-resolver-webpack npm version

### ISSUE THREAD

**Issue by zerkms** [benmosher/eslint-plugin-import#374]
```
Package                         Current  Wanted  Latest  Location
eslint-import-resolver-webpack    0.3.1   0.3.1   0.3.0  ...
```

For some reason I can install the `0.3.1`, but `npm` thinks the `0.3.0` is the latest available. Was it unregistered or something?

**Comment by maslianok** [comment]
Yep, the same for 
```
Package                               Current         Wanted  Latest
eslint-import-resolver-webpack  0.3.1          0.3.1   0.3.0 
eslint-plugin-import                    1.9.0          1.9.0   1.8.1  
```

**Comment by benmosher** [comment]
There are later versions tagged "next". 

0.3.1 is fine (thought I had moved it to latest) but there are issues in 1.9.1. 

See docs for npm tag.

**Comment by zerkms** [comment]
So the problem is back:

```
Package                Current  Wanted  Latest  
eslint-plugin-import    1.10.2  1.10.3  1.10.2  
```

**Comment by benmosher** [comment]
Again, not a "problem". I pushed 1.10.3 as `next` instead of `latest` just to feel it out, had some issues in QA so I was not positive it was all good.

Just moved `latest` tag up to 1.10.3.

**Comment by zerkms** [comment]
When someone tests in production - it is a *problem*.
