### ISSUE TITLE
webpack aliases don't work

### ISSUE THREAD

**Issue by FezVrasta** [benmosher/eslint-plugin-import#376]
I have a file structure like this:

```
app/
  components/
    FooBar.js
  utils/
    generateHtmlId.js
```

and in webpack I have:
```
const modules = [
  'app',
  'node_modules',
];

[...]

resolve: {
    modulesDirectories: modules,
    modules,
    extensions: [
      '',
      '.js',
      '.jsx',
      '.react.js',
      '.json',
    ],
    alias: {
      // required for enzyme to work properly
      sinon: 'sinon/pkg/sinon',
      app: path.join(process.cwd(), 'app'),
    },
  },
```

Inside `FooBar.js` I have:

```
import genId from 'utils/generateHtmlId';
```

But this plugin throws an error saying that the path can't be resolved.
Note that webpack compiles everything properly.

**Comment by benmosher** [comment]
what version of the plugin is installed? `npm ls | grep eslint-plugin-import`

**Comment by FezVrasta** [comment]
eslint-plugin-import@1.9.0

**Comment by benmosher** [comment]
Configuration of the Webpack resolver is broken in 1.9.0, use `latest` (1.8.1). I should really yank it. :-(

**Comment by FezVrasta** [comment]
I don't think the problem is there because I had the same problem even with 1.8.1

**Comment by rojobuffalo** [comment]
@FezVrasta This doesn't look like it got fixed. I'm still encountering the error with ^1.16.0
