### ISSUE TITLE
Unable to resolve path for relative .jsx files

### ISSUE THREAD

**Issue by mhlmhl** [benmosher/eslint-plugin-import#381]
I am importing .jsx files from other .jsx files.  The imports work fine if I specify an absolute path, but fail with import/no-unresolved when I use relative paths.

My folder structure:

/imports
  ui
    pages
      vocabulary
        test
          TestContainer.jsx
           TestView.jsx

in TestContainer.jsx, this statement works fine: 
        import { TestView } from '/imports/ui/pages/vocabulary/test/TestView.jsx';

... and both of these get "Error: Unable to resolve path to module './TestView.jsx'. (import/no-unresolved)"
        import { TestView } from './TestView.jsx';
        import { TestView } from 'TestView.jsx';

My .eslintrc:

{
  "plugins": [
    "meteor",
    "react"
  ],
  "extends": [
    "airbnb",
    "plugin:meteor/recommended"
  ],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
        "jsx": true,
        "impliedstrict" : true
    }
  },
  "rules": {
        "semi": 2
    },
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "meteor": true
  },
  "settings": {
    "react": {
      "pragma": "React",  // Pragma to use, default to "React"
      "version": "15.0" // React version, default to the latest React stable release
    },
    "import/resolver": { "meteor": {"extensions": [".js", ".jsx"]} },
  },    
  "scripts": {
    "lint": "eslint .",
    "pretest": "npm run lint --silent"
  },
  "eslintConfig": {
    "plugins": [
      "meteor"
    ]
  },
  "indent": [2, 2]
}

**Comment by mhlmhl** [comment]
The folder structure that I carefully indented above got messed up. Here's another way to describe it.  The two files are /imports/ui/pages/vocabulary/test/{TestContainer, TestView}.jsx.  I want to import these with relative rather than absolute references.

**Comment by mhlmhl** [comment]
I just noticed that I'm having the same problem with .js files, using "import { xxx } from './xxx.js';

I created these files a few days ago, and did not see this error when I last edited the files.  But when I opened them up today, I see these errors.

**Comment by benmosher** [comment]
It sounds like an issue with the meteor resolver. What happens if you switch to the node resolver?

**Comment by mhlmhl** [comment]
Yes, I agree. I intended to open this against the meteor resolver.  Will try again on that.
