### ISSUE TITLE
Unambiguous JavaScript Grammar

### ISSUE THREAD

**Issue by jdalton** [benmosher/eslint-plugin-import#384]
In the spirit of [UnambiguousJavaScriptGrammar](https://github.com/bmeck/UnambiguousJavaScriptGrammar) I'm wondering if a rule to enforce unambiguous module grammar with least an `import` or `export` is of interest?

By the way Babel [now supports](https://github.com/babel/babel/pull/3532) `export {}`.

**Comment by jdalton** [comment]
BTW Babel now supports `export {}`.

**Comment by jamestalmage** [comment]
See also: https://github.com/sindresorhus/eslint-plugin-xo/issues/41

How would we avoid reporting situations where the user intends it to be a script, not a module?

**Comment by jdalton** [comment]
> How would we avoid reporting situations where the user intends it to be a script, not a module?

You wouldn't. The rule would enforce ES modules.

**Comment by jdalton** [comment]
This rule would be combo'ed with `parserOptions:{sourceType:"module"}`

**Comment by benmosher** [comment]
Sorry, thought I had answered. I think that makes sense. The pair of 👍 's on the issue (before mine) suggest there is some community interest.

Not top of my list, but I'd merge a PR. Also not clear to me if it's likely to land via https://github.com/sindresorhus/eslint-plugin-xo/issues/41. I'm fine either way.

**Comment by benmosher** [comment]
See https://github.com/sindresorhus/eslint-plugin-xo/issues/41#issuecomment-230025254, but I think there should be a rule here, especially given how I've just redefined #270 for v2.

In contrast to the XO rule (and as noted in the comment) the rule here would be something to the effect of `This module may parse as a script. Add 'export {}' to ensure module parsing`. 

Also, I would expect such a rule to ignore a `"use strict"` and instead refer to the configured `parserOptions.sourceType`, and report iff it's `module`.
