### ISSUE TITLE
Rules run on non-JS imports

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#385]
We have `require.extensions` patched to import `.hbs` files - we also have `.json` imports in a few places.

Here's what I get in these cases:
```
  3:36  error  Parse errors in imported module '../path/to/file.hbs': Adjacent JSX elements must be wrapped in an enclosing tag (6:1)  import/no-named-as-default
  3:36  error  Parse errors in imported module '../path/to/file.hbs': Adjacent JSX elements must be wrapped in an enclosing tag (6:1)  import/no-named-as-default-member

---
  3:35  error  Unexpected use of file extension "json" for "../../fixtures/google_v3_geocoder/sf_united_states.json"                                import/extensions
  3:35  error  Parse errors in imported module '../../fixtures/google_v3_geocoder/sf_united_states.json': Unexpected token : (2:14)                 import/no-named-as-default
  3:35  error  Parse errors in imported module '../../fixtures/google_v3_geocoder/sf_united_states.json': Unexpected token : (2:14)                 import/no-named-as-default-member
  4:26  error  Unexpected use of file extension "json" for "../../fixtures/google_v3_geocoder/六本木6_10_3_港区_東京都_106_0032_japan.json"                 import/extensions
  4:26  error  Parse errors in imported module '../../fixtures/google_v3_geocoder/六本木6_10_3_港区_東京都_106_0032_japan.json': Unexpected token : (2:14)  import/no-named-as-default
  4:26  error  Parse errors in imported module '../../fixtures/google_v3_geocoder/六本木6_10_3_港区_東京都_106_0032_japan.json': Unexpected token : (2:14)  import/no-named-as-default-member
```

We have all these extensions defined in `settings` → `import/resolver` → `node` → `extensions`, because we want import resolution rules applied on them.

How can we apply resolution rules to these files, without applying JS-specific rules to them?

**Comment by evidens** [comment]
I was able to fix this in my `.eslintrc` with:
```
  "settings": {
    "import/ignore": [
      "node_modules",
      ".(json|css)$"
    ]
  },
```

by default import/ignore defines `node_modules` (so it won't complain about validation from legacy packages) so you'll have to add it in if you override.

**Comment by ljharb** [comment]
@evidens yes but then the "resolve" rule won't be able to verify that those files exist, will it?

**Comment by benmosher** [comment]
@ljharb nope, import/ignore does not impact resolution. Just parsing for exports. 

You can also specify what extensions to parse via import/extensions. See the README for more details.

**Comment by ljharb** [comment]
It'd be nice if I could specify a whitelist instead of a blacklist - ie, "only parse these extensions" instead of/in addition to "ignore these"

**Comment by benmosher** [comment]
That is what the import/extensions setting is: https://github.com/#importextensions

**Comment by ljharb** [comment]
Hmm - I already had that set to just JS and jsx when the original errors happened. Perhaps they're being overlooked for these rules?

**Comment by benmosher** [comment]
That would be a bug. Can you provide a test case that logs a parse error when the extensions setting is set?

**Comment by ljharb** [comment]
It's possible I was using an older version of the plugin - I'll post repro details here if I can reproduce the issue.

**Comment by ljharb** [comment]
I think I've confirmed that was the case. Sorry to bother.
