### ISSUE TITLE
`prefer-default-export`: reporting on files with multiple named exports

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#396]
I have a file that has `export const FOO = { … }` as well as 4 `export function foo() {}` declarations. However, `prefer-default-export` is erroring out on the last one.

**Comment by benmosher** [comment]
Can you provide a (sanitized) test case? I believe there are tests that are close to what you're describing.

**Comment by ljharb** [comment]
I do see [test cases](https://github.com/benmosher/eslint-plugin-import/blob/master/tests/src/rules/prefer-default-export.js) that seem similar.

Something like fifty files in our codebase that have multiple exports trigger the rule, but it'll be really hard to provide a sanitized version of one - here's an attempt:
```js
import Actions from '../actions/Actions';
import Store from '../stores/Store';
import Service from '../utils/Service';
import ServiceTypes from '../constants/ServiceTypes';
import { getUrl } from '../utils/ServiceUrls';
import { debounce } from 'underscore';

const gifTimeout = 6000;

export function refreshVisibilities({ x }) {
  return Service.get(
    getUrl(ServiceTypes.SOME_CONSTANT, { x })
  ).then(response => {
    Actions.refreshSucceeded(response.property);
  }).catch(Actions.refreshFailed);
}

export function stopGif() {
  const { isPlayingGif } = Store.getState();
  if (isPlayingGif) {
    Actions.gifPlayedLongEnough();
  }
}

export const stopGifDebounced = debounce(stopGif, gifTimeout);
```

**Comment by benmosher** [comment]
Sweet, thanks for the repro case. I'll take a look when I get a chance. 

Or if someone wants to PR it, have at it. 👍

**Comment by gavriguy** [comment]
@benmosher  I'll give it a shot later today

**Comment by gavriguy** [comment]
The code above is passing when I run it as a valid test. @ljharb maybe it has to do with some specific configuration you have...

**Comment by ljharb** [comment]
Crap, sorry about this. It seems that I had an older version of eslint-plugin-import installed (v1.8.1). I updated to v1.9.2, and the issue has gone (and it now finds many more proper instances of this rule violation).

Sorry for the inconvenience!

**Comment by benmosher** [comment]
Thanks for scoping it out, @gavriguy! 😎
