### ISSUE TITLE
eslint-import-resolver-webpack not working?

### ISSUE THREAD

**Issue by tleunen** [benmosher/eslint-plugin-import#398]
I updated from 1.5.0 to 1.9.1 and the webpack resolver doesn't seem to work anymore, while my webpack config hasn't changed.

Here's my settings:
```
"settings": {
    "import/resolver": {
      "webpack": {
        "config": "webpack.config.js"
      }
    }
  }
```

**Comment by benmosher** [comment]
IIRC 1.9.0 or 1.9.1 is broken. Try 1.9.2?

**Comment by benmosher** [comment]
Also: what version of the webpack resolver are you using? (I'd recommend 0.3.x)

**Comment by tleunen** [comment]
I'm actually using 1.9.2 and 0.3.1. Sorry for the confusion.

**Comment by tleunen** [comment]
Got some time to debug..

I get this error while requiring the webpack.config.js file. This is because my webpack config uses `path` and try to construct a path with an environment variable `process.env.something`.
```
Error during config lookup: [TypeError: Path must be a string. Received undefined]
```

@benmosher So the plugin doesn't know the variable. Is there a way to run the plugin with custom environment variables?

**Comment by benmosher** [comment]
Depends on how you're running ESLint. If you're using the command line, something like
```bash
something=/whatever eslint ...
```
would work.

If it's being run from inside Sublime, Atom, or some other application, you'd have to look at the integration docs.

I will close this as it sounds like nothing needs to be done inside the plugin.

**Comment by tleunen** [comment]
Yes it would be inside the editor (atom in my case but could be valid for all editors). What integration docs are you referring to?

**Comment by benmosher** [comment]
Whatever plugin is allowing you to run ESLint inside Atom. My hope is that either that project or Atom itself has guidance on setting env vars.

**Comment by tleunen** [comment]
Hmm... Maybe we could have an option in the import/resolver plugin to set specific env variables?

**Comment by benmosher** [comment]
You may be able to set them in JS config, or you could default them to something in your Webpack config.

I would expect the platform to handle it. If not, I think that env vars are outside the plugin's jurisdiction.
