### ISSUE TITLE
Definition for rule 'import/no-reassign' was not found.

### ISSUE THREAD

**Issue by doctyper** [benmosher/eslint-plugin-import#40]
I'm getting an error using `0.7.4`:

```
node_modules/eslint/lib/eslint.js:650
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'import/no-reassign' was not found.
    at node_modules/eslint/lib/eslint.js:650:27
```

**Comment by benmosher** [comment]
Ah, interesting. I end-of-life'd `no-reassign` as it was mostly redundant with the core ESLint `no-shadow` and `no-redeclare` rules--it was originally created when there were gaps in `escope`'s module handling and that was not the case--and moved the one novel bit into `import/namespace`.

I didn't realize it would be a breaking change. (though I have just realized I forgot to update the docs...)

I suspect you have the warning level set explicitly in your `.eslintrc`?

Not sure what to do as `0.7.4` fixes a different crash... I suppose for dogmatic semver observance I should put a dummy`no-reassign` back in, push `0.7.5`, update docs, and push `0.8.0`.

**Comment by benmosher** [comment]
Just pushed `0.7.5` with updated docs. In my local test, the dummy rule seems to fix it.

I will wait on `0.8.0` to another day, but I would recommend pulling that rule from your config to avoid breaking then. :sweat_smile:
