### ISSUE TITLE
update to ESLint 3+ rule format

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#406]
http://eslint.org/blog/2016/07/eslint-new-rule-format (see part about the auto-transform tool)

@ljharb [made an interesting point](https://github.com/yannickcr/eslint-plugin-react/pull/657#issuecomment-230107161) on the PR for the React plugin about maybe not being too aggressive/hasty about this.

I'm planning to do this as part of the semver-major bump to 2.x for this plugin, ~~though there is nothing else to really gain from being 3.x+ only with ESLint, other than that I want to drop support for Node 0.10 and 0.12. ~~

~~But it's not obvious to me why anyone would want to stay on ESLint 2 if they are using Node 4+, either.~~

~~So it feels like a major release would be the right time to bump to support ESLint 3. ~~

Feedback (especially arguments against this) desired/welcome.

**edit**: thanks to @jfmengels about digging in on this. turns out [new format is supported in v2](https://github.com/benmosher/eslint-plugin-import/issues/406#issuecomment-231132889)

**Comment by ljharb** [comment]
My preference would be to retain both eslint 2 + 3 compat, as well as node 0.10 compat - ideally, at least one version exists for the entire setup such that those who have not yet upgraded (and there are many valid reasons why someone may not have) can still have a smooth path to upgrading - ie, they can upgrade their linting deps, and *then*, separately, upgrade node - and then, separately, upgrade their linting deps again to the one that's functionally equivalent but drops old node/eslint.

**Comment by benmosher** [comment]
related: https://github.com/benmosher/eslint-plugin-import/commit/a55cd67dabae15ae6f95361e4452f46e0df69ebb#commitcomment-18156683

**Comment by jfmengels** [comment]
Correct me if I'm wrong, but I get the feeling that both ESLint 2 and ESLint 3 are compatible with both rule formats.

**Comment by ljharb** [comment]
If that's true then of course we should change it, but I can't conceive of how a brand new format would be supported by an old version.

**Comment by benmosher** [comment]
Docs don't confirm or deny that, AFAICT. Just that both formats are supported in 3.x.

Have you tested? It's not obvious to me how (or why) that would work.

**Comment by jfmengels** [comment]
https://gitter.im/eslint/eslint?at=577e7ebce483756e106004ad

https://gitter.im/eslint/eslint?at=577e82e359cfbd4c5e3e8378

cc @sindresorhus @jamestalmage @novemberborn in case you're interested

**Comment by ljharb** [comment]
I'm surprised the blog post about it was coupled with the v3 release, but that's great news. Upgrade away!

**Comment by benmosher** [comment]
fixed in 20079c6, will deploy via v2 anyway
