### ISSUE TITLE
Update to support ESLint 3.0

### ISSUE THREAD

**Issue by coryhouse** [benmosher/eslint-plugin-import#420]
I get this when trying to run with ESLint 3.0:

npm ERR! peerinvalid The package eslint@3.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-import@1.10.0 wants eslint@2.x

**Comment by coryhouse** [comment]
Nevermind, just needed to update some related packages.

**Comment by benmosher** [comment]
in case anyone else ends up here: 1.10.2 is the correct version to support ESLint 3.x
