### ISSUE TITLE
[no-extraneous-dependencies] Add exceptions?

### ISSUE THREAD

**Issue by tleunen** [benmosher/eslint-plugin-import#422]
For a specific package, I'm importing `babel-core` in my test files, but `babel-core` is set as a devDep because I'm compiling the files before publishing my package. Therefore, there's no reason to put the module as a direct dependency.

```
~/dev/babel-plugin-module-alias/test/index.js
  4:1  error  'babel-core' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

Would it be possible to not run `no-extraneous-dependencies` in specific directories/files?? Like `test.js`, `test/**/*.js`, `__tests__/**/*.js`, `**/*.test.js` or `**/*.spec.js`

**Comment by jfmengels** [comment]
> Would it be possible to not run no-extraneous-dependencies in specific directories/files?

You can, in some cases, but this is a limitation of ESLint.
If you want to disable the rule in a folder, you can add a `.eslintrc` file at the root of that folder where you disable the rule. Or the other way around: disable it by default in your root config, and activate it using a `.eslintrc` file where appropriate (a `src` folder for instance).

The other options are to:
- disable the rule in each file you want to disable it for using `/* eslint-disable import/no-extraneous-dependencies */` at the top of your file
- enable the rule in each file you want to enable it for using `/* eslint import/no-extraneous-dependencies: ["error", {options: ...}] */` at the top of you file
- (**probably the safest option**, as it's the only one that does not disable the rule for a whole file altogether) disable the line you want to ignore using `require('babel-core'); // eslint-disable-line import/no-extraneous-dependencies
- or a combination of all the previous possibilities

Or my favorite, use glob based configurations https://github.com/eslint/eslint/issues/3611. Unfortunately, that is not yet implemented :/ (should you be using `XO`, then it is)

Of course, we could disable the rule in the code if we notice that the file in question is in some directory, but this could be applied to so many rules that it's better to invest time to make it work in https://github.com/eslint/eslint/issues/3611 IMO.

Let me know if this answers your needs. If so, I'll close the issue :)

**Comment by tleunen** [comment]
Yep I was using the comment to disable it, I'm ok :)

I thought it was potentially an error in the rule but everything is ok if you suggest using the comment anyway :) Thanks!

**Comment by benmosher** [comment]
@tleunen you could set the option [`devDependencies: true`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) in an `.eslintrc` in your `test` folder:
```yaml
rules:
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
```
Then you'll get reports of any packages referenced that are not included `dependencies` or `devDependencies`. Then you get the goodness of the rule, with no noise from the disable comments.

I think that might work for you? This is how I would use the rule, in your case, since you have your test code separated into a `test` directory.

**Comment by tleunen** [comment]
Yep, you're right, but since it's just 1 specific dependency, I'm ok with the comment ;)

**Comment by tristanbbq** [comment]
@tleunen I had the same question. The Internet is small sometimes 😄

**Comment by benmosher** [comment]
FWIW: v1.15.0 shipped with #527, which allows globs in addition to booleans for the various dependency flavors.

(apparently we changed our minds 😅)

**Comment by Willibaur** [comment]
Hi all,
I've been through many of the Issues on this repo, and could not find what I'm looking for so I'm going to leave my question here, 
I have this rule in my `.eslintrc.js`
`'import/no-extraneous-dependencies': ["error", { devDependencies: true, }],`
But is still giving my a bunch of errors, all of them like this one
` 1:1  error  'ember' should be listed in the project's dependencies. Run 'npm i -S ember' to add it  import/no-extraneous-dependencies`

Any help would be appreciated
Thanks in advance

**Comment by ljharb** [comment]
Is it listed in your package.json anywhere?

It'd be better to file a new issue, so we can debug it properly.

**Comment by benmosher** [comment]
@Willibaur: if `ember` is a magic dependency (i.e. not listed in `package.json`), then you won't be able to use `no-extraneous-dependencies`, IIRC. It assumes a pretty standard `npm`/`node` view of the world.

**Comment by benmosher** [comment]
actually, scratch that: you may be able to specify `"import/core-modules": [ "ember" ]` in your `.eslintrc.js`.

refer to the [import/core-modules](https://github.com/benmosher/eslint-plugin-import#importcore-modules) docs for more info.

**Comment by Willibaur** [comment]
@benmosher Thanks, It solved the issue

**Comment by siddhartharora02** [comment]
@benmosher 
In console it says an object was expected instead of an array, but it's working alright
`vue.esm.js?efeb:571 [Vue warn]: Invalid value for option "components": expected an Object, but got Array.`

**Comment by benmosher** [comment]
@siddhartharora02 I don't understand what you're describing but if you're experiencing issues, feel free to open a new issue.

**Comment by TaylorPzreal** [comment]
Simple to do: 

```
"import/no-extraneous-dependencies": 0,
```
add this. to rules

**Comment by ljharb** [comment]
Sure, but then you're disabling this very useful rule.

**Comment by CyrilMaximov** [comment]
This solved my issue.

"rules": {
    "import/no-extraneous-dependencies": 0
  }

I have "eslint": "6.0.1"

**Comment by clshortfuse** [comment]
I'm my use case, I have a `/build` folder with dev dependencies. That isn't packaged when deploying since it's not part of runtime.

I think it should check the [files](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files) property in `package.json`.

If's not included in `npm`, then it's not extraneous.

**Comment by ljharb** [comment]
@clshortfuse i'm confused, is that for build output?

Whether a node project is published to npm or not, *every* dependency should be in package.json.

**Comment by clshortfuse** [comment]
Hi @ljharb !

For example, I have a `/build` folder that uses esbuild to compile the docs, which then gets used by a github action for uploading to `gh-pages`. It just bundles and minfies. But `esbuild` not a core dependency. it's a dev dependency. I don't even include the `/build` folder when i do `npm publish`, since it's not for people who want to install the package. But the plug will state:

>'esbuild' should be listed in the project's dependencies, not devDependencies.eslint[import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-extraneous-dependencies.md)

Though, at the same time, anything in my `/test` folder will *NOT* get picked up as an error. I never told eslint to ignore `/test`, but somewhere it does. Is there a secret allow list somewhere? How do I get my `/build` folder to be treated the same as my `/test` folder?

**Comment by ljharb** [comment]
To handle that, you set your eslint config to allow dev deps in `build/`. `test` is a default because that's a common use case, but `build` is almost universally used as a throwaway build output dir, not something that has actual code in it, so you need to configure that explicitly.

**Comment by clshortfuse** [comment]
Thanks. I see it's not the plugin, but my airbnb config that is setting the allow-list. 

I guess I should have been more specific about the error I was seeing. On that note, if a file is not in `files` or part of `.npmignore`, could the "not devDependencies" error not fire? I'll go ahead and figure out how to add that folder, but would be nicer to not have to. 😃

**Comment by ljharb** [comment]
@clshortfuse that would be an interesting enhancement of the rule to consider. Can you file a separate issue asking for that?
