### ISSUE TITLE
Support peerDependencies in the `no-extraneous-dependencies` rule

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#423]
Analogous to #266. Ideally should be implemented along the same rails.

**Comment by jfmengels** [comment]
I'm not too familiar with peerDependencies and their use. Is having a peerDependency a good excuse of not setting some package in your dependencies as you assume that it will be installed in the project using your package ?

I can add this. Should we have the option for this be true or false by default?

**Comment by benmosher** [comment]
`false` by default, let people enable. Might be good to explicitly state in the warning for `false` mode that the referenced package _is_ in `peerDependencies`.

Good example is `React`/ component relationships. React component packages will need to `import React from 'react'` but need to get the project react, not some local one. So they (should) declare the `react` dependency as a peer.
