### ISSUE TITLE
Tests fail with latest ESLint

### ISSUE THREAD

**Issue by ilyavolodin** [benmosher/eslint-plugin-import#430]
2 tests under webpack resolver fail with the ESLint's latest master:

```sh
  1) config finds compile-to-js configs:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/config.js:30:16)

  2) config finds compile-to-js config in parent directories:
     AssertionError: expected { found: false } to have a property 'path'
      at Context.<anonymous> (test/config.js:36:16)
```

I haven't looked at why they are filing (since I don't know anything about webpack), I'm just trying to create regression build for ESLint itself.

**Comment by benmosher** [comment]
Interesting. I'll scope it out. 

FWIW, those tests have historically been fussy. So may not be on your end.

**Comment by benmosher** [comment]
BTW, not sure _when_ I'll be able to look into it. Just want to set expectations. Hopefully sometime this week. 

I wouldn't hold up your build/release for just those failures. Those tests are for a fairly uncommon use case, AFAIK.

**Comment by ilyavolodin** [comment]
No rush on that. Just wanted to let you know. I removed resolver tests from the regression build. However, now it looks like the main code is failing with the following messages:

```js
  1) resolve case cache correctness ./CaseyKasem.js => ./CASEYKASEM.js gets cached values within cache lifetime:
     AssertionError: expected '/var/lib/jenkins/workspace/Regression Build/eslint-plugin-import/tests/files/CASEYKASEM.js' to not exist
      at Context.<anonymous> (tests/src/core/resolve.js:1258:79)

  2) resolve case cache correctness ./CaseyKasem.js => ./CASEYKASEM.js infinite cache lifetime: ��� still gets cached values after ~1s:
     AssertionError: expected undefined to exist
      at Context.<anonymous> (tests/src/core/resolve.js:1289:88)

  3) resolve case cache correctness ./CaseyKasem.js => ./CASEYKASEM.js infinite cache lifetime: Infinity still gets cached values after ~1s:
     AssertionError: expected undefined to exist
      at Context.<anonymous> (tests/src/core/resolve.js:1289:88)
```

Also, let me know if you want to know about those issues. I can't promise that I will post them here any time they happen (and some of them might be just noise anyways), but I can post then once in a while if they happen.

**Comment by benmosher** [comment]
What OS are you running under?

**Comment by benmosher** [comment]
Actually, those tests are failing on Travis (linux) with ESLint 2.x. So also not on your end. (I just realized those tests were never running last night and re-enabled.)
