### ISSUE TITLE
eslint-import-resolver-webpack silences require('.../webpack.config.js') load errors

### ISSUE THREAD

**Issue by Kovensky** [benmosher/eslint-plugin-import#435]
Which led me to a few hours long debugging session until I realized what was going on :(

A custom plugin (that was `required` by the `webpack.config.js`) accidentally had underspecified dependencies; it worked locally, but when my CI server (that doesn't run the webpack build yet, but does run eslint) tried running eslint, it'd get nonsense-looking `no-unresolved` errors. I would expect `eslint` to instead error out with a failure to load the `webpack.config.js`.

I could work around it myself by just having a void `require('webpack.config.js')` in an `.eslintrc.js`, though, but this would only be possible when using the `.js` format.

**Comment by benmosher** [comment]
Ah, interesting. Good point: it probably should bubble the error.

I think if the resolver failed to load (due to thrown error) that should be reported in the linter output (potentially for every file).
