### ISSUE TITLE
Path resolution doesn't work on Windows

### ISSUE THREAD

**Issue by illinar** [benmosher/eslint-plugin-import#44]
fc4f99ecda1d378c277e05fd9f8f7d72d08ffb60 breaks file resolution on Microsoft Windows. The implementation of [fileExistsWithCaseSync](https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/resolve.js#L8) fails to take into account drive letters and will always return false due to path.basename("C:\") returning an empty string.

**Comment by benmosher** [comment]
Bummer! 

Assuming there's not a simple way to fix the issue in the function itself (which I can't test, don't have a Windows box handy), it seems like a decent fix would be to make case-sensitive checking optional and expose it as a rule config option, i.e. `import/exists: [2, 'case-sensitive']`. 

Probably would turn it off by default.

@doctyper, would that still work for you? You'd have to update your config.

**Comment by doctyper** [comment]
Hail-mary stab might work if you just bail out on windows. Otherwise I'm ok with the flag.

**Comment by doctyper** [comment]
Which, actually, would be fine because the case-sensitivity issue is Mac-only.

**Comment by illinar** [comment]
Since NTFS is case-sensitive I am fine with this approach. I would also like to indicate that NTFS path does not have to start with the letter. You may want to keep a note regarding limitations of the current implementation on Windows.

**Comment by benmosher** [comment]
Ah, didn't realize NTFS was case-sensitive. OS X is truly the odd man out, then. Though I did have one machine formatted with case-sensitive HFS+, once upon a time.

I think I'll keep the flag, and try to set up an AppVeyor Windows build at some point just for good measure.

@doctyper: interesting idea to just skip Windows using `os.platform()`, but for some reason I don't love the idea of having a 'win32' floating around in there. Though I'll admit the drive-letter regex is essentially the same thing, stated less obviously. I'll think about it. :smile:

**Comment by doctyper** [comment]
Keeping the flag is fine, but I think it should be opt-out not opt-in. It's value is in warning the developer about casing pitfalls ahead of time.

**Comment by benmosher** [comment]
That's a fair point. I suspect Linux is the build/deploy target for most devs. Or at the very least, something other than OS X.

Would it make sense to only do the case-sensitive extra work for `os.platform() === 'darwin'`?

**Comment by benmosher** [comment]
Published fix via v0.7.8.
