### ISSUE TITLE
spin component modules out into separate repos?

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#446]
Pull the following out into separate GitHub repos?

- resolvers (or maybe just Webpack resolver)
- `utils` folder (`eslint-module-utils`)

pros:
- separate Travis builds, coveralls coverage, etc.
- separate issue tracking for each
- more consistent with community resolvers
- changelog can actually show commit diff for just a resolver
- decoupling resolver versions from core plugin

cons:
- separate repos (commit history no longer related)
- confusion about where issues should be reported

@jfmengels, curious what you think of this. Current setup (one repo, many npm packages) was inspired by Babel, but it feels like more work than it's worth for ~4 packages that ideally should be somewhat loosely-coupled. I think in Babel's case, it's more warranted.

**Comment by benmosher** [comment]
@jfmengels: bump. 😄

I'm thinking this is a bad idea, but I'm still curious what your perspective is.

**Comment by jfmengels** [comment]
Totally missed this issue.

I think it's better to have it all here, except if it's a lot of trouble to manage for you.

Btw, "separate issue tracking for each" is not right IMO, as people will pretty much always file issues/complain here anyway. The "confusion about where issues should be reported" will probably be much bigger than you think. It's probably more accurate to think that people will simply put it in the wrong repo than for them to be confused.

**Comment by benmosher** [comment]
Yeah, makes sense, thanks for the feedback.
