### ISSUE TITLE
Proposal: Disallow importing self

### ISSUE THREAD

**Issue by just-paja** [benmosher/eslint-plugin-import#447]
Hi,

I think it would be nice if we had a rule that prevents importing the current file. It might happen when refactoring and moving files across directories. What do you think?

file: foo.jsx

``` js
import foo from './foo';
```

``` js
import foo from './foo.jsx';
```

**Comment by benmosher** [comment]
I would accept a PR for that. 😎 

Call it `no-self-import`?
