### ISSUE TITLE
Webpack resolver doesn't handle all import forms with html

### ISSUE THREAD

**Issue by mthamil** [benmosher/eslint-plugin-import#460]
I am using the webpack resolver and it works for all cases but one that I've found. If I want to import html from a template for use with angular, for example, I can do this:

    import template from "./foo.html";
        ...
    $stateProvider.state("foo", {
            url: "/foo",
            template: template
        });

However, I get the following errors:

    Parse errors in imported module './foo.html': Unexpected token < (1:1)  import/namespace
    Parse errors in imported module './foo.html': Unexpected token < (1:1)  import/default.

`import "./foo.html"` by itself does not report any errors, but it's not what I want. The code works as desired, it's just the linting that shows an error.

**Comment by mthamil** [comment]
So... I assume I need to add html to the import/ignore section? If that's the proper solution I guess this should be closed.

**Comment by mthamil** [comment]
+1 for reading the docs

**Comment by benmosher** [comment]
[`import/extensions`](https://github.com/benmosher/eslint-plugin-import/blob/master/README.md#importextensions) is good for this too, will default to just `.js` in the next version to avoid this sort of issue.
