### ISSUE TITLE
import/external-module-folders is no worked on ReactNative

### ISSUE THREAD

**Issue by yutin1987** [benmosher/eslint-plugin-import#466]
when I setting
`"import/external-module-folders": ["node_modules", "Libraries"]`

and then have `react-native-firebase-sync` folder in Libraries,
but eslint show error.
<img width="914" alt="2016-08-01 9 44 34" src="https://cloud.githubusercontent.com/assets/2505934/17295908/39656b98-5831-11e6-811f-a2966cbb0b9f.png">

eslint-plugin-import version is 1.12.0

**Comment by benmosher** [comment]
`import/external-module-folders` (currently) only impacts the `order` rule. 

You will need to configure your resolver to also look in those folders.

That said, seems like a reasonable enhancement to do that automatically.

**Comment by benmosher** [comment]
If you're using the default `node` resolver, you'll want to add `Libraries` to the `paths` setting. See the readme: https://www.npmjs.com/package/eslint-import-resolver-node

**Comment by yutin1987** [comment]
@benmosher Thank you very much for reminder
