### ISSUE TITLE
detect up a directory then down the same directory

### ISSUE THREAD

**Issue by graingert** [benmosher/eslint-plugin-import#471]
I have a structure like:

```
/ham/egg/chips/index.js
/ham/egg/foo.js
```

then in /ham/egg/chips/index.js I sometimes have code that accidental ends up like:

``` js
import x from '../../egg/foo.js'
```

but I'd much rather it be:

``` js
import x from '../foo.js'
```

**Comment by benmosher** [comment]
Ooo, nice. Yeah, that would be cool. Not sure what to call it, but would be a pretty straightforward rule. Would basically enforce that the path be the same as the `path.resolve(currentFile, importedFile)`.

Need a good name, though. `shortest-path`?

**Comment by graingert** [comment]
import/no-up-a-directory-then-down-the-same-directory

Could also be an easy auto fix too

**Comment by jfmengels** [comment]
:+1:

`no-extraneous-path` / `no-extraneous-relative-path`?

**Comment by benmosher** [comment]
@jfmengels ooo, I like `[something]-relative-path`. `extraneous` doesn't have the right connotation for this case, though, I think. [#bikeshedding](http://www.instructables.com/id/Bike-Shed/)

`shortest-relative-path`?

**Comment by jfmengels** [comment]
I think `extraneous` fits, as you have extraneous "steps".
Otherwise `no-superfluous`, `no-unneeded`, `no-unnecessary`, ...


I'd be fine with `shortest-relative-path` too (though I dig it less than extraneous at the moment :smile: ).

**Comment by graingert** [comment]
I like extraneous

**Comment by benmosher** [comment]
I guess I've just got other meaning primed for `extraneous` from the `no-extraneous-deps` issue discussion. Feels like this is something else to me. also `no-extraneous-relative-path` is a mouthful. (keyboardful?)

also also I don't love `no-` for this, I think because it's more enforcing a good thing (shorter path) than rejecting a bad thing (longer path).

I have weak and meandering enough opinions on this that I'm going to abstain from further name discussion. `no-`/`extraneous`-something is fine. 🤓

**Comment by jfmengels** [comment]
I'm starting to like `shortest-relative-path` (I agree that extraneous is a mouthful). Maybe let me sleep on it :smile:

**Comment by graingert** [comment]
You can't use "relative" because it's redundant. All paths in node are
relative

**Comment by benmosher** [comment]
`NODE_PATH` lets you around that. I'm fine with `shortest-path` but I think it's less obvious. #abstainfail

**Comment by graingert** [comment]
NODE_PATH and support for other non relative paths is being removed
https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#521-removal-of-non-local-dependencies

**Comment by jfmengels** [comment]
> You can't use "relative" because it's redundant. All paths in node are relative

External modules (things installed with npm for instance), internal modules (when you use Webpack) are not relative. Also, I'm pretty sure you can specify an absolute path.

**Comment by jfmengels** [comment]
> NODE_PATH and support for other non relative paths is being removed
https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#521-removal-of-non-local-dependencies

Does that also apply to `require` statements, or only `import`?

**Comment by graingert** [comment]
External modules are actually relative to the current module, they just go
up to the nearest node_modules dir. Absolute paths will never trigger this
issue

**Comment by graingert** [comment]
Only import, but I presume everyone will switch to import/ whatever dynamic
module loading gets specified

**Comment by benmosher** [comment]
@graingert mind blown.

**Comment by jfmengels** [comment]
I'd still like to see this implemented. If someone wants to have a go at it, let's go with `no-extraneous-path` as the name until someone has a good reason against it or a better name. But let the name not be a blocker for this nice idea.

**Comment by graingert** [comment]
@benmosher another aberration I've discovered in my travels: 

```js
import foo from './../foo';
```

which should of course be 

```js
import foo from '../foo';
```

**Comment by graingert** [comment]
@benmosher I've bike-sheded this a bit more, and think that no-useless-path-segments would be the best. To go with the other eslint "no-useless-" rules.

**Comment by danny-andrews** [comment]
`simplest-path`?
`simplest-local-path`?

**Comment by graingert** [comment]
I'd like it to start with no- or no-redundant-

**Comment by ljharb** [comment]
`no-useless-path-segments`; see #912.
