### ISSUE TITLE
Disallow importing "default" as a named import

### ISSUE THREAD

**Issue by ljharb** [benmosher/eslint-plugin-import#481]
Babel allows `import { default as Foo } from 'foo'` - I'm not sure if the spec does too.

I'd like a rule that requires `import { default as Foo, Bar }` be written as `import Foo, { Bar }`.

**Comment by benmosher** [comment]
Last I checked, importing a default export as a name is valid ES6, but this seems like a reasonable style-guide rule. 

Name: `no-named-default`?

**Comment by giodamelio** [comment]
This should be closed now that #596 is merged right?
