### ISSUE TITLE
import/prefer-default-export should ignore type for flowtype

### ISSUE THREAD

**Issue by justin808** [benmosher/eslint-plugin-import#484]
I have a file with this:

``` js
// @flow
export type CommentType = {
  mobile_image_thumbnail: string,
  author_name: string,
  preview_text: string,
  updated_at: string,
}
```

I get this error:

app/bundles/comments/types/index.js
  2:1  error  Prefer default export  import/prefer-default-export

[See doc note](https://flowtype.org/blog/2015/02/18/Import-Types.html):

```
Note that we only support the explicit named-export statements for now (i.e. export type UserID = number;). In a future version we can add support for latent named-export statements (i.e. type UserID = number; export {UserID};) and default type exports (i.e. export default type MyType = ... ;)…but for now these forms aren’t yet supported for type exports.
```

I just checked and `export default type` is not supported in 0.27.

Any chance of ignoring `export type` as an option to this rule?

**Comment by benmosher** [comment]
Yeah, that should be fine.

Would love someone with Flow experience to submit a PR, I'm not familiar enough with it to confidently work this in.

**Comment by chrisblossom** [comment]
Another flow issue is ``no-duplicate-imports``. Unless I am mistaken, there isn't a way to import ``type`` on the same line as the module imports;

```js
import React, { PropTypes } from 'react';
import type { Element } from 'react'; // eslint error
```

**Comment by justin808** [comment]
@benmosher I don't think you need flow experience. Just ignore `export type` from the rule. I guess there's the edge case when you want `export type` to be recognized, in case you name a variable or function `type`. How about an option for the rule if `export type` should be ignored?

Or maybe a regexp to ignore?

**Comment by rodrigobdz** [comment]
The following file is generating a warning that default export should be used. 
> Prefer default export. (import/prefer-default-export)

```js
/* @flow */

export type AnswerState = {
  foo: string
}

export const answer: AnswerState = {
  foo: ''
}
```

This one however, is not generating any errors or warnings.

```diff
/* @flow */

- export type AnswerState = {
+ type AnswerState = {
  foo: string
}

export const answer: AnswerState = {
  foo: ''
}

+ export type { AnswerState }
```

Shouldn't it be consistent?

**Comment by ljharb** [comment]
Yes; please file a new issue for that one.
