### ISSUE TITLE
import/default rule triggered incorrectly when parent directory name matches module name

### ISSUE THREAD

**Issue by nhardy** [benmosher/eslint-plugin-import#488]
I have a directory structure for a project similar to this:

```
├─┬ tasks
│ └┬─ webpack
│  └─ index.js
└── src
```

Inside `./tasks/webpack/index.js`:

``` js
import webpack from 'webpack'; // Triggers `import/default`
```

**Comment by benmosher** [comment]
What version of `webpack` are you using?

**Comment by nhardy** [comment]
Sorry, I realise I've been a bit light on detail. I should add that `'node_modules'` is set to be ignored in the settings.

I don't believe this issue is related to webpack itself, as changing the 'webpack' folder name to 'nonsense-not-in-node-modules':

```js
import nonsense from 'nonsense-not-in-node-modules'; // Triggers `import/default`
```

For clarity though, I've noticed this issue with both the latest Webpack 1 and latest Webpack 2, but again, don't think Webpack is the issue.

**Comment by benmosher** [comment]
can you provide the exact ESLint output when running from a terminal? `eslint ./tasks/webpack/index.js`?

**Comment by nhardy** [comment]
Lint config is set to ignore node_modules: https://github.com/nhardy/eslint-config/blob/master/src/index.js#L46
`eslint <blah>/webpack/index.js`:

```
<blah>/webpack/index.js
  7:8  error  No default export found in module  import/default

✖ 1 problem (1 error, 0 warnings)
```

The offending line:

```
import webpack from 'webpack';
```

**Comment by benmosher** [comment]
Interesting. It must be resolving `webpack` to some file other that `node_modules/webpack`, possible your `tasks/webpack/index.js` file.

I think I'll need to add some debug logging to the Node resolver to find out exactly what's happening.

BTW, an aside: `'\\.(?!(?:js|jsx)$).*$'` in your `import/ignore` setting should be equivalent to setting [`import/extensions` to `['.js', '.jsx']`](https://github.com/benmosher/eslint-plugin-import/tree/v1.13.0#importextensions).

**Comment by benmosher** [comment]
Just published v0.2.3 of the Node resolver. Please replace the version you have (may be either a peer of, or in the `node_modules` folder for, your `eslint-plugin-import` installation) and run `DEBUG=eslint-plugin-import:resolver:node eslint <blah>/webpack/index.js`.

**Comment by nhardy** [comment]
Looks like it is resolving the current file as `webpack` instead of `webpack` in `node_modules`.
Output below:

```
$ DEBUG=eslint-plugin-import:resolver:node ./node_modules/.bin/eslint <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolving: +0ms gulp from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +3ms <blah>/node_modules/gulp/index.js
  eslint-plugin-import:resolver:node Resolving: +2ms gulp-util from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +1ms <blah>/node_modules/gulp-util/index.js
  eslint-plugin-import:resolver:node Resolving: +0ms nodemon from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +1ms <blah>/node_modules/nodemon/lib/nodemon.js
  eslint-plugin-import:resolver:node Resolving: +0ms webpack-dev-server from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +2ms <blah>/node_modules/webpack-dev-server/lib/Server.js
  eslint-plugin-import:resolver:node Resolving: +0ms webpack from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +10ms <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolving: +16ms ../../config from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +1ms <blah>/config/index.js
  eslint-plugin-import:resolver:node Resolving: +2ms ./factory from: <blah>/tasks/webpack/index.js
  eslint-plugin-import:resolver:node Resolved to: +0ms <blah>/tasks/webpack/factory.js

<blah>/tasks/webpack/index.js
  7:8  error  No default export found in module  import/default

✖ 1 problem (1 error, 0 warnings)
```

**Comment by benmosher** [comment]
I think the './' in your moduleDirectories setting might be responsible for that. Try without it, maybe?

**Comment by nhardy** [comment]
That did fix it. My mistake.
