### ISSUE TITLE
custom resolver(s)

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#50]
Add a setting to swap out and/or add a custom package resolver.

**Comment by benmosher** [comment]
@doctyper: just pushed this with 0.7.9. Undocumented for now.

**Comment by benmosher** [comment]
closed by #116

**Comment by doctyper** [comment]
@benmosher :+1: If you care: [eslint-import-resolver-jspm](https://github.com/nfl/jspm-resolve/tree/master/plugins/eslint-import-resolver-jspm)

**Comment by benmosher** [comment]
Sweet! 😎
