### ISSUE TITLE
eslint-import-resolver-webpack not resolving imports when using resolve.modules

### ISSUE THREAD

**Issue by grahamb** [benmosher/eslint-plugin-import#510]
Per the request in #352 (https://github.com/benmosher/eslint-plugin-import/issues/352#issuecomment-229636628) to open a new issue…

webpack version: 2.1.0-beta.21
eslint: 3.3.1
eslint-plugin-import: 1.14.0
eslint-import-resolver-webpack: 0.5.1

I have configured Webpack's `resolve.modules` property as follows:

```js
    resolve: {
      modules: [
        resolve('./client'),
        resolve('./node_modules')
      ]
    },
```
Full [webpack.config.js](https://github.com/sfu/student-dashboard/blob/284ecdc7f2e0ae2e0a463f40128061f07019b8d1/webpack.config.js) file

[.eslintrc file](https://github.com/sfu/student-dashboard/blob/284ecdc7f2e0ae2e0a463f40128061f07019b8d1/.eslintrc)

Project's file structure:

```
.
├── .DS_Store
├── .babelrc
├── .env.development
├── .env.example
├── .env.production
├── .env.test
├── .eslintrc
├── .gitignore
├── .npmrc
├── .nvmrc
├── .travis.yml
├── README.md
├── babelRelayPlugin.js
├── client
│   ├── components
│   │   ├── App
│   │   ├── CampusConditions
│   │   ├── Header
│   │   └── UserBio
│   └── index.js
├── data
├── environment.js
├── package.json
├── public
├── scripts
├── server
├── templates
└── webpack.config.js
```

In [`client/components/App/index.js`](https://github.com/sfu/student-dashboard/blob/284ecdc7f2e0ae2e0a463f40128061f07019b8d1/client/components/App/index.js#L3) I'm importing another module from `client/components` with `import UserBio from 'components/UserBio'`. This works, but eslint is throwing an `import/no-unresolved` error.

Output from running `DEBUG=eslint-plugin-import:* $(npm bin)/eslint client/components/App/index.js`: https://gist.github.com/grahamb/9f7ad28563af2c5a7fcece5f251a96d3

**Comment by benmosher** [comment]
Is your config file a function? I don't think that's supported ATM.

**Comment by grahamb** [comment]
Which config file, eslint or webpack? .eslint is JSON, webpack is a function that returns the config object. This is a supported way of configuring Webpack 2 (e.g. http://jonnyreeves.co.uk/2016/simple-webpack-prod-and-dev-config/)

**Comment by grahamb** [comment]
Adding a simple 

```
if( typeof webpackConfig === 'function' ) {
  webpackConfig = webpackConfig()
}
```
… after the config is `require`d seems to work, though I haven't run the test suite yet. Would you like a PR for this?

**Comment by benmosher** [comment]
👍 that would be great!

**Comment by grahamb** [comment]
PR #533
