### ISSUE TITLE
Parsing error: The keywork 'import' is reserved

### ISSUE THREAD

**Issue by SonofNun15** [benmosher/eslint-plugin-import#513]
I'm running eslint via `eslint-watch` from an npm script: `node_modules/.bin/esw webpack.config.* src tools"`

I have eslint-plugin-import installed.

Here's snippets of my eslint file:

```
"plugins": [
  "react",
  "import"
],
"parserOptions": {
  "ecmaVersion": 6,
  "sourceType": "module",
  "ecmaFeatures": {
    "jsx": true
  }
},
```
I have a bunch of import rules turned on as errors / warnings.

When I run this script, most of my files with import statements run fine, but one file (webpack.config.dev.js) fails with this error:

```
.../webpack.config.dev.js (1/0)
  ✖  1:1  Parsing error: The keyword 'import' is reserved
```

Any thoughts on what might be causing this issue?

I tried removing these imports and got a similar error related to `export`.

**Comment by benmosher** [comment]
Weird. Is `../webpack.config.dev.js` a sibling of your `.eslintrc`?

**Comment by SonofNun15** [comment]
Yes

**Comment by benmosher** [comment]
Not sure then. Certainly sounds like the `sourceType: module` config is not being applied to your Webpack config.

What version of `eslint` are you using? IIRC `sourceType` was renamed from v1 to v2.

**Comment by SonofNun15** [comment]
```
"eslint": "2.9.0",
"eslint-plugin-import": "^1.14.0",
"eslint-plugin-react": "5.0.1",
"eslint-watch": "2.1.11",
```

**Comment by SonofNun15** [comment]
I found the problem. Apparently I inadvertently put the .eslint file in a subfolder instead of the root folder. So as you suspected, the webpack file was an ancestor NOT a sibling. Seems to be working once I got the .eslint file moved to the root folder as intended.
