### ISSUE TITLE
eslint-import-webpack-resolver does not support named webpack configs

### ISSUE THREAD

**Issue by erosolar** [benmosher/eslint-plugin-import#516]
I'm trying to use the no-unresolved rule with a webpack.config.js of the following style:
```javascript
module.exports = {
    <name>: {
        resolve: <path>,
        ....
    },
    <another name>: {
        resolve: <path>,
        ...
    },
}
```

it would be nice if the configIndex option also took object property names (or there was another option for choosing a named config), as the current array/first with resolve options do not work at all with this structure.

**Comment by benmosher** [comment]
Didn't realize that was an option. Should be easy enough.

Can you link me to the Webpack docs for this?

**Comment by erosolar** [comment]
Ah. After some heavy googling and consulting with the person who wrote the webpack config, it appears that this is the result of some grunt config to build specific targets on their own (eg. using 'webpack:tests' to build tests), rather than some option in webpack.

It would still be nice to have the option to specify a named config, but given that it's not technically part of webpack, I can understand why it wouldn't be worth implementing.

**Comment by benmosher** [comment]
Ah, yeah. Interesting idea, but since it's not a Webpack-supported option, I will close. 

FWIW, you could extract the config you want to a separate file and configure the resolver to use that file, and have the original config require it.
