### ISSUE TITLE
npm install from repo fails

### ISSUE THREAD

**Issue by nzakas** [benmosher/eslint-plugin-import#524]
Over on ESLint, we do a regression build using popular projects like yours to make sure we don't break the ecosystem. On Tuesday, August 23, we started seeing an error when trying to `npm install` using the repo:

```
[Regression Build] $ /bin/sh -xe /tmp/hudson1435620304341608558.sh
+ git clone https://github.com/benmosher/eslint-plugin-import.git
Cloning into 'eslint-plugin-import'...
+ cd eslint-plugin-import
+ npm install
npm WARN package.json Dependency 'eslint-import-resolver-node' exists in both dependencies and devDependencies, using 'eslint-import-resolver-node@^0.2.0' from dependencies
npm WARN peerDependencies The peer dependency webpack@^1.11.0 || ^2.1.0-beta || ^2.1.0 included from eslint-import-resolver-webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.14

> eslint-plugin-import@1.14.0 prepublish /var/lib/jenkins/workspace/Regression Build/eslint-plugin-import
> gulp prepublish
```

At that point it just exits with an error.

**Comment by benmosher** [comment]
Strange. I thought it might be an npm 2 issue (CI uses npm 3, regardless of Node version) but it works fine for me (of course).

No additional output?

**Comment by nzakas** [comment]
Sadly no, it just stops at that point and exits. I think you should be able to see the full console here: http://jenkins.eslint.org/job/Regression%20Build/63/console

**Comment by benmosher** [comment]
Bummer. I hate to be crashing your build! I can't put my finger on anything between the commit history and those logs. The location of the `master` branch on 8/23 is lost forever...

Gulp is clearly failing to start up, though. What node/npm versions is that box running? Looks like npm@2 from the log, but tough to tell more than that.

**Comment by nzakas** [comment]
Node is v4.4.7
npm is v2.15.8

I'm not sure why, but the Gulp output is not being shown in Jenkins.

When I log into the Jenkins machine and run it manually, everything seems to work okay. That makes it seem like maybe there's a permissions issue going on. Were there any changes that would have required higher-level permissions (like linking somewhere)?

**Comment by benmosher** [comment]
Not that I can see/think of.

I added TypeScript parsing, so a `devDependency` showed up for `eslint-typescript-parser` at roughly that time, but I don't have any idea why it would error out and die during compilation as a result. Would expect an install error or something during test execution.

So I've got no ideas. 😖

**Comment by nzakas** [comment]
Whatever magically broke our regression build has now magically been fixed (no idea in either case what happened). So, closing.
