### ISSUE TITLE
Resolve `package.json` in higher level directory

### ISSUE THREAD

**Issue by vanesyan** [benmosher/eslint-plugin-import#526]
Hello there! Currently I develop an electron application and reach problem with `import/no-extraneous-dependencies` raise an error. I have two separated `package.json` files in different directories, one in `app/package.json` - which is main app manifest, which of dependencies should be resolved and other one `package.json` in the root directory - development manifest. So as I've said before I need to resolve my dependencies in the `app` directory, how can I do it? Thanks

**Comment by jfmengels** [comment]
Hey @vanesyan!

This seems very similar to https://github.com/benmosher/eslint-plugin-import/issues/458. Do you mind commenting over there too?

I think [this comment](https://github.com/benmosher/eslint-plugin-import/issues/458#issuecomment-241826520) goes in the right direction for your use-case. We don't know how people structure their apps when they have multiple `package.json` files, so if you could then give some input on that, that'd be great! :smile: 

(I'm closing this, but if you feel that this is a different issue, I'll re-open it)
