### ISSUE TITLE
eslint-import-resolver-node published with .nyc_output

### ISSUE THREAD

**Issue by lukeapage** [benmosher/eslint-plugin-import#531]
I see it is already in .gitignore at the root but not in sub .npmignore, which is probably why it was included.

**Comment by jfmengels** [comment]
Ah, good catch! @benmosher Maybe let's use the `files` field in package.json, just like is done for the main package?

**Comment by benmosher** [comment]
Ugh, yeah, that's my bad. Should have double-checked, that package has been just the one file for so long...
