### ISSUE TITLE
Not using webpack config to resolve

### ISSUE THREAD

**Issue by stevenmusumeche** [benmosher/eslint-plugin-import#537]
My webpack config works and the modules are correctly resolved in my build process.  However, ESLint is reporting `import-no-unresolved` errors for my packages, for example `Unable to resolve path to module 'redux'`

This occurs when I added the following config to my .eslintrc file:

    "settings": {
        "import/resolver": {
            "webpack": {
                "config": "./webpack/prod.js"
            }
        }
    },

(My webpack config is stored in ./webpack/prod.js)

**Comment by benmosher** [comment]
Have you installed he Webpack resolver package?

**Comment by stevenmusumeche** [comment]
Yes, "eslint-import-resolver-webpack": "0.5.1".  I actually solved the issue late last night.  The webpack config file uses ES6 and this package was unable to use it until I changed all the code to ES5.  Any way around that?

**Comment by benmosher** [comment]
One way is to name it `webpack.config.babel.js`. 

How is Webpack using it? Assuming your Node version can handle all the syntax, this plugin should understand it, as well.
