### ISSUE TITLE
About use with Sublime Text 3 + eslint_d

### ISSUE THREAD

**Issue by AoDev** [benmosher/eslint-plugin-import#540]
Hello, 
I am using eslint_d with sublime linter. Your comment in the readme helped me solve the same issue with eslint_d so I thought I'd share this particular case if it can help someone else.

For me the solution has been to edit the user settings of sublime linter and update the "args" config like you mentioned:

```
        "linters": {
            "eslint_d": {
                "@disable": false,
                "args": [
                    "--stdin-filename",
                    "@"
                ],
                "excludes": []
            }
        },
```

**Comment by soryy708** [comment]
I think this can be closed.
