### ISSUE TITLE
typescript: use *.d.ts

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#549]
Need to figure out some way to leverage TypeScript declaration files. 

Should use the same resolution strategy as TS itself does, ideally.

**Comment by benmosher** [comment]
temporary pseudo-workaround: set `jsnext:main` to `index.d.ts`. only works for package entry point, though.

**Comment by benmosher** [comment]
note: probably could use `typings` field from package.json, if available

**Comment by spencerhakim** [comment]
This is still an issue, but is it something that should be handled by `eslint-plugin-import` or by `eslint-import-resolver-typescript`? (cc: @alexgorbatchev)

**Comment by alexgorbatchev** [comment]
From what I understand resolver basically takes in a path and returns a path. I don't know if something else could be done at that step.

**Comment by spencerhakim** [comment]
Yeah, that was my understanding from skimming your source. I tried using `"eslint-import-resolver-typescript": { "extensions": [".ts", ".tsx", ".d.ts"] }` in my config, but I still get `import/no-unresolved` errors. It seems like it *should* work, no idea why it doesn't.

**Comment by alexgorbatchev** [comment]
Can you post a code sample? I'm not completely sure I understand what you are trying to do.

**Comment by spencerhakim** [comment]
I don't have a code sample I could quickly post right now, but basically: I have an automatically generated `GQL.d.ts` file (no corresponding `GQL.ts`, though) with some exported enums, interfaces, etc. that I import into various `.ts` files. TypeScript itself seems to be fine with me doing something like `import { OnboardingStep } from "./GQL";`, and the types resolve correctly, it's just `eslint-plugin-import` complaining that it can't find the module.

**Comment by alexgorbatchev** [comment]
I added `.d.ts` to https://github.com/alexgorbatchev/eslint-import-resolver-typescript/blob/master/index.js, let me know if that helps.

**Comment by spencerhakim** [comment]
Ugh, I'm an idiot. What I tried originally works fine, but I had a secondary config file I forgot about that was overriding it back to the defaults. Since you've updated your code, I think this can be closed.

**Comment by benmosher** [comment]
ah sweet, a typescript resolver should absolutely be what is handling it! thanks @alexgorbatchev and @spencerhakim!
