### ISSUE TITLE
support @providesModule

### ISSUE THREAD

**Issue by yutin1987** [benmosher/eslint-plugin-import#553]
as title, need support @providesModule
https://github.com/facebook/fbjs

Current solutions, but it's not good idea.

```
"import/core-modules": [
    "EventEmitter",
    "NativeError",
    "ColorPropType",
    "ImageSourcePropType",
]
```

**Comment by domsmith94** [comment]
This would be useful. We are using @providesModule extensively in our React Native project as well as this plug in.

**Comment by ljharb** [comment]
Using providesModule outside of FB is not a good idea; the read me on that repo supports that position.

I'd be hesitant to support something like that when the entire ecosystem is using node-style commonJS.

**Comment by benmosher** [comment]
I don't know anything about `@providesModule`, including what it is for and what its impact is.

If it can be supported via a resolver, that would be ideal, given what @ljharb has already noted about usage outside Facebook. 

If it can't be supported via resolver, I don't think it would make sense to add code directly to the plugin to ingest it.
