### ISSUE TITLE
`newline-after-import` should not apply to inline `require`'s

### ISSUE THREAD

**Issue by sindresorhus** [benmosher/eslint-plugin-import#570]
Only ones at the top. Or at least provide an option to ignore them.

When I have inline requires, it doesn't really help much to have a newline and it just get's in the way. I've been hit by this many times.

Example: https://github.com/zeit/hyperterm/commit/8a8fdacffe370ca0e267a7cffbff6734bef43036#diff-2460efa50e29d32731d41893921a7739R9

**Comment by jfmengels** [comment]
Same here, sounds good to me.

Does anyone see the value of keeping this behavior behind an option somehow? I don't. It's not really the purpose of this rule, though this should probably be better explained in the rule documentation.

Some (who like this) might consider this a breaking change (?), so it might be worth shipping with 2.0 (soon) just to be safe.

**Comment by sindresorhus** [comment]
I don't see the point in an option.

**Comment by benmosher** [comment]
It's not obvious to me what classifies the linked require as `inline`, but as long as @jfmengels has it under control, I'm cool with whatever you two decide upon. 

Breaking changes can certainly pile into v2, I haven't had a chance to publish the first beta yet, anyway.

**Comment by jfmengels** [comment]
> what classifies the linked require as inline

Hmm, I thought any require whose parent is not Program, but that's obviously not good enough (even `var a = require('a');` does not fit).

I see that we already have this kind of logic in `order`, so let's just use the same one.
https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/order.js#L195-L204

**Comment by jfmengels** [comment]
@singles do you have an opinion on this maybe?

**Comment by singles** [comment]
AFAIR @lo1tuma implemented most of the code which is being removed in linked PR, so it would be better to ask him :)
