### ISSUE TITLE
Meteor Packages Imports

### ISSUE THREAD

**Issue by jpmelnik** [benmosher/eslint-plugin-import#593]
Missing file Extension for import Something from 'meteor/username:package-name';

My package.json config:

> "eslintConfig": {
>     "parser": "babel-eslint",
>     "parserOptions": {
>       "allowImportExportEverywhere": true
>     },
>     "plugins": [
>       "meteor"
>     ],
>     "extends": [
>       "airbnb",
>       "plugin:meteor/recommended"
>     ],
>     "settings": {
>       "import/resolver": "meteor"
>     },
>     "rules": {
>       "import/no-extraneous-dependencies": 0
>     }
>   }

**Comment by nelsyeung** [comment]
https://github.com/airbnb/javascript/commit/f6dab799b8fa1346f1cc3fdfdbe9c9fbeef7baf6 have introduced:
```js
'import/extensions': ['error', 'always', {
  js: 'never',
  jsx: 'never',
}],
```
Previously was:
```js
'import/extensions': ['off', 'never'],
```
I don't like this fix but you just have to turn it off:
```json
"rules": {
  "import/extensions": ["off", "never"]
}
```
or:
```json
"rules": {
  "import/extensions": ["error", "never"]
}
```

**Comment by benmosher** [comment]
closing because 
- issue is due to `airbnb` breaking change
- workaround documented (thanks!)

**Comment by benmosher** [comment]
actually I think this is broken in `import/extensions` after looking at https://github.com/clayne11/eslint-import-resolver-meteor/issues/17

**Comment by benmosher** [comment]
adding to v3 milestone, resolver needs to be able to report that it's a "core" module so the `isBuiltIn` check returns `true`: https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/extensions.js#L72
