### ISSUE TITLE
[2.0.0] max-dependencies rule references removed dependency es6-set

### ISSUE THREAD

**Issue by clintwood** [benmosher/eslint-plugin-import#603]
[This commit](https://github.com/benmosher/eslint-plugin-import/commit/9880ae7db99865a6e4c887151d59dd4de97debfa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L83) removed `es6-set` from it's dependencies but it is still imported here: [`max-dependencies.js](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/max-dependencies.js#L1)!

**Comment by jfmengels** [comment]
Thanks for noticing and reporting @clintwood!
I'm marking this as a duplicate of #604.
