### ISSUE TITLE
[2.0.0] Missing dependencies fail on npm@2.x.x

### ISSUE THREAD

**Issue by Moeriki** [benmosher/eslint-plugin-import#604]
`eslint-plugin-import` seems to be missing a dependency on `es6-set` and `object-assign`.

This goes unnoticed in `npm@3.x.x` since they are included with `eslint-module-utils`, but fails on `npm@2.x.x`.

**Comment by jfmengels** [comment]
Thanks for noticing and reporting @Moeriki, and sorry for the inconvenience.

I will try to take some time tonight to fix this (probably by using the native `Set` and `Object.assign` that are available from Node 4 onwards).
