### ISSUE TITLE
React native absolute path imports

### ISSUE THREAD

**Issue by willlma** [benmosher/eslint-plugin-import#626]
Having the same issue as this [Stackoverflow Question](http://stackoverflow.com/questions/40025214/absolute-paths-with-react-native-raise-eslint-errors)

> in my React Native app, within my `package.json` I've set the name to `rpms`. This allows me to do:

```
import Component from 'rpms/App/common/Component'
```

> […] eslint-plugin-import raises […] `import/no-unresolved`.

**Comment by sindresorhus** [comment]
You need to create a [resolver](https://github.com/benmosher/eslint-plugin-import#resolvers) for React Native.

**Comment by guzart** [comment]
Just publish a package that piggy backs on eslint-import-resolver-node, hope this helps

https://www.npmjs.com/package/eslint-import-resolver-reactnative

**Comment by benmosher** [comment]
oo, thanks @guzart!

**Comment by Gapur** [comment]
You can use absolute paths like in this article

https://medium.com/better-programming/using-absolute-paths-in-react-native-3be369244fb1

I hope you found this piece useful.
