### ISSUE TITLE
New option for order rule to allow spaces inside import groups.

### ISSUE THREAD

**Issue by giodamelio** [benmosher/eslint-plugin-import#627]
I currently use the [`order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) rule with the [`newlines-between`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#newlines-between-ignorealwaysnever) option set to `always`, the problem is, I would like to be able to have newlines inside my import groups(to allow sorting by related categories).

The always rule states(emphasis mine)

> If set to always, at least one new line between each group will be enforced, and **new lines inside a group will be forbidden**. To prevent multiple lines between imports, core no-multiple-empty-lines rule can be used.

It would be nice to be able to control whether newlines are allowed within import groups. I was thinking maybe adding a boolean option `newlines-inside` that would allow you to make the choice. If the default is false, it should be backwards compatible.

I want to make a pull, but I was wondering what you think of this @benmosher, before I get started.

**Comment by jfmengels** [comment]
I'm fine with having this kind of option.

I'm thinking this should instead be a new possible value for `newlines-between`. It would be odd to be able configure `newlines-between` to `never`, and the new one to allow them. That would mean that you could only have empty lines inside groups, which is odd and counter to the idea of this rule.

**Comment by giodamelio** [comment]
Right, that wouldn't make much sense. So a new value it is. Not quite sure what to call it without being super verbose. `always-with-newlines`? `always-newlines`?

**Comment by jfmengels** [comment]
`ignore-everywhere`? It's more or less the same idea as the current `ignore`

**Comment by giodamelio** [comment]
I was talking about still forcing newlines between groups, but also allowing them within them.

**Comment by jfmengels** [comment]
Ah. That means that there are a few different new values to add...
- Option to enforce always but allow inside groups
- Option to enforce no newlines but allow inside groups (which we said was odd, so will not be added)
- Option to not enforce it and not report inside groups (which I'll have to check whether that's not already the behavior of ignore).

So you'd probably need two new options... What do you think?

**Comment by giodamelio** [comment]
Sounds good, #628 covers option 1, option 2 is ignored. If I understand you correctly option 3 is already covered by `ignore`.

**Comment by tiagocpontesp** [comment]
tag and pub? :)
btw https://github.com/benmosher/eslint-plugin-import/pull/628 still open.
