### ISSUE TITLE
`node-libs-browser` in `eslint-import-resolver-webpack`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [benmosher/eslint-plugin-import#631]
`node-libs-browser` does not seem to actually be used in `eslint-import-resolver-webpack` [outside of being a list of node core modules](https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/index.js#L42-L44).  Could it be replaced with a list of node core modules?

**Comment by wtgtybhertgeghgtwtg** [comment]
And I just realized that `webpack` [requires this, anyway](https://github.com/webpack/webpack/blob/master/package.json#L17), so the dependency would be there either way.  Apologies.

**Comment by sirlancelot** [comment]
Webpack no longer depends on `node-libs-browser`. Perhaps we could re-open this discussion? The module in question is quite heavy and I think if Webpack is able to remove its dependency to it, then perhaps this plugin can do the same?

**Comment by lopopolo** [comment]
@benmosher webpack 5 no longer depends on this npm package. Can we re-open this conversation?

**Comment by ljharb** [comment]
Sure, that seems reasonable.

At the moment, the best available list is in the `resolve` package; we should refactor to use that.

**Comment by andersk** [comment]
Even better, that part of `resolve` has now been split into its own package `is-core-module`. Submitted #1967 to use that.

**Comment by billyvg** [comment]
@ljharb Can you cut a new npm release for `eslint-import-resolver-webpack`? The version on NPM does not include these changes.

**Comment by ljharb** [comment]
@billyvg as soon as tests pass on master (#1986), i'll be cutting a release of all the packages.
