### ISSUE TITLE
Parser error on files in node_modules

### ISSUE THREAD

**Issue by BarryThePenguin** [benmosher/eslint-plugin-import#634]
I'm not sure where this issue belongs, I thought I'd start here as it's related to the rules in this package.

I'm using this plugin as it's included with [XO](https://github.com/sindresorhus/xo). I'm getting an error as a result of the following rules: `import/no-named-as-default`, `import/no-named-as-default-member`, `import/default`, `import/namespace` and `import/named`

``` bash
Parse errors in imported module browser-sync: Unexpected character # (1:1)
```

This happens when I'm importing `browser-sync`. It looks as though BrowserSync has a `#! /usr/bin/env node` at the top of their [main file](https://github.com/BrowserSync/browser-sync/blob/master/index.js), which I assume is causing the issue.

So appears there are a few things going on here:
- `eslint-plugin-import` is parsing files in my `node_modules` folder. I haven't spent much time understanding how this plugin works, I just consume it through XO.
- `browser-sync` has a `#! /usr/bin/env node` line at the top of their main file. I'm only aware of using this in node shell scripts, and I don't think the main BrowserSync file is a script
- it looks like the eslint parser falls over when it encounters a `#` as the first character in a javascript module file

There's a few things here and I'm happy to follow up with any changes to the other projects, I just wanted to check with others that the above is correct. Thanks! 😀

**Comment by benmosher** [comment]
Strange. I'm not sure where to go on this, though this file should never have been parsed to begin with, since it has no imports/exports. So this is related to #615 / #649.

I'm not sure how/if you can set ESLint settings in XO (@jfmengels?) but the same workaround for those issues should work for this too, until the root issue (overparsing of CJS node modules) is solved.

**Comment by jfmengels** [comment]
The way to set ESLint settings in `XO` is described [here](https://github.com/sindresorhus/xo/#settings).

**Comment by BarryThePenguin** [comment]
Woo! 👏

**Comment by benmosher** [comment]
@BarryThePenguin don't get your hopes up too high 😅 I'm pretty sure this should fix your issue without needing the aforementioned workaround, but not 100% sure. Let me know if it doesn't and I'll reopen.

**Comment by BarryThePenguin** [comment]
I'm sure I'll keep you posted if I run into anymore trouble 😰
