### ISSUE TITLE
how to make react ignore 'Forbid the use of extraneous packages '

### ISSUE THREAD

**Issue by zp1112** [benmosher/eslint-plugin-import#636]
``` js
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { Route, Router, browserHistory } from 'react-router';
import Todo from './containers/todo';
import createStore from './store';

const store = createStore();
render(
  <Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/login" title="登陆" component={require('react-router?name=login!./containers/login.js')} />
      <Route path="/" title="首页" component={Todo} />
    </Router>
  </Provider>,
  document.getElementById('example')
);/>
```

the react-lazy-loader config :"component={require('react-router?name=login!./containers/login.js')}" throws error like this: 
![image](https://cloud.githubusercontent.com/assets/14245159/19616875/1c2647c6-9852-11e6-8475-e279a9b6f95c.png)

**Comment by zp1112** [comment]
why the code inside render() didn't appeared??

<Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/login" title="登陆" component={require('react-router?name=login!./containers/login.js')} />
      <Route path="/" title="登陆" component={Todo} />
    </Router>
  </Provider>,
  document.getElementById('example')

**Comment by zp1112** [comment]
why the code inside render() didn't appeared??

```js
<Provider store={store}>
    <Router history={browserHistory}>
      <Route path="/login" title="登陆" component={require('react-router?name=login!./containers/login.js')} />
      <Route path="/" title="登陆" component={Todo} />
    </Router>
  </Provider>
```

**Comment by benmosher** [comment]
Are you using webpack? if so, this is similar to #646 and could be solved the same way.

**Comment by ljharb** [comment]
This seems like it's related to #954 / #987
