### ISSUE TITLE
Large performance regression in v2.0

### ISSUE THREAD

**Issue by schmod** [benmosher/eslint-plugin-import#649]
I'm observing a very large performance hit between v1.x and v2.0.1.  Linting my project used to take approximately 13 seconds with v1.x, and now takes about 25 minutes with v2.0.1. 

I'm using ESLint v3.9.1, `eslint-plugin-import` v2.0.1, `eslint-import-resolver-webpack` v0.6.0, and `babel-eslint` v7.1.0.  

I've tried reverting to earlier versions each of those packages, and I only see a noticeable performance regression with `eslint-plugin-import` v2.0.x.  

---

My `.eslintrc.js` is as follows:

```js
module.exports = {
  rules: {
    "import/default": 0,
  },
  parser: "babel-eslint",
  env: {
    browser: true,
    es6: true
  },
  globals: {
    console: false,
    require: false
  },
  extends: [
      "../.eslintrc.js",
      "plugin:import/errors",
      "plugin:import/warnings"
  ],
  plugins: [
      "import"
  ],
  settings: {
      "import/resolver": "webpack",
      "import/extensions": ['.js']
  }
}
```

I can't release the source code of my project, but would be happy to help track down this bug by some other means.  I've already thrown a profiler on the process, and unfortunately didn't see anything particularly interesting...

**Comment by benmosher** [comment]
Dang, yeah, something seems to not be properly detecting + rejecting CommonJS deps before parsing (which is what eats all the time).

See discussion on #615 for a workaround using `import/ignore` to always skip parsing `node_modules`:

```js
  settings: {
      "import/resolver": "webpack",
      "import/extensions": ['.js'],
      "import/ignore": ['node_modules']
  }
```

Beware, though, that it will not lint imported names/defaults for your `node_modules` thereafter. `no-unresolved` and others will still check that the imported files exist, it just won't parse them.

When I add debug logging to start digging into this, I may ping you and ask for some logs, if you're up for that. The v2 logic is not substantially different, so it should not be anywhere near that much slower.

**Comment by schmod** [comment]
Sure.  Happy to help. I've downgraded to v1.x, which should work fine for me in the short-term!

**Comment by schmod** [comment]
BTW, running ESLint with the `--debug` flag does not reveal anything particularly interesting.  

Watching the logs scroll by, each file is taking a long time to process, but the "timed" tasks listed in the log all claim to be very fast, despite an obvious 2-3 second pause between files.

```
  eslint:cli-engine Processing file1.js +3s
  eslint:cli-engine Linting file1.js +2ms
  eslint:config Constructing config for file1.js +0ms
  eslint:config Using config from cache +0ms

*** [long pause here]***

  eslint:cli-engine Processing file2.js +2s
  eslint:cli-engine Linting file2.js +2ms
  eslint:config Constructing config for file2.js +0ms
  eslint:config Using config from cache +0ms
```

**Comment by schmod** [comment]
**MUCH** better.  Thanks for the quick fix!

## v1.16.0

```
real	0m3.460s
user	0m2.973s
sys	0m0.307s
```

## v2.0.1:

```
real	0m47.238s
user	0m39.430s
sys	0m1.533s
```

# v2.2.0

```
real	0m3.726s
user	0m3.190s
sys	0m0.321s
```
