### ISSUE TITLE
Problem with default export after update to 2.1.0

### ISSUE THREAD

**Issue by adascal** [benmosher/eslint-plugin-import#653]
Hi, after updating from version `2.0.1` to `2.1.0` I start getting error for code like:

`export default from './Map.jsx';`

Stack trace:

`Node must be provided when reporting error if location is not provided`
`AssertionError: Node must be provided when reporting error if location is not provided`
    `at EventEmitter.module.exports.api.report (/node_modules/eslint/lib/eslint.js:970:20)`
    `at RuleContext.report (/node_modules/eslint/lib/rule-context.js:144:21)`
    `at EventEmitter.Program:exit (/node_modules/eslint-plugin-import/lib/rules/prefer-default-export.js:69:19)`
    `at emitOne (events.js:101:20)`
    `at EventEmitter.emit (events.js:188:7)`
    `at NodeEventGenerator.leaveNode (/node_modules/eslint/lib/util/node-event-generator.js:49:22)`
    `at CodePathAnalyzer.leaveNode (/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:628:23)`
    `at CommentEventGenerator.leaveNode (/node_modules/eslint/lib/util/comment-event-generator.js:110:23)`
    `at Controller.leave (/node_modules/eslint/lib/eslint.js:930:36)`
    `at Controller.__execute (/node_modules/estraverse/estraverse.js:397:31)`

**Comment by yvele** [comment]
I was going to open the exact same issue.

`eslint@3.9.1` with `eslint-plugin-import@2.0.1`

**Comment by adascal** [comment]
`eslint@3.9.1` with `eslint-plugin-import@2.0.1` work fine for me...
Check installed module, maybe it's `2.1.0`? :)

**Comment by yvele** [comment]
@adascal I'm using the exact same versions as you and I'm having the same error

**Comment by ljharb** [comment]
@adascal you're using proposed syntax https://github.com/leebyron/ecmascript-export-default-from - which isn't part of the language, and is only stage 1. Are you using babel-eslint for this?

@yvele `export notDefault from 'path'` is in the language. `export default from 'path'` is not, which is what the OP is using.

**Comment by yvele** [comment]
@ljharb Yep. I'm not using `default` but I still have the `Node must be provided..`error

**Comment by ljharb** [comment]
Ah, gotcha, thanks for clarifying.

**Comment by adascal** [comment]
@ljharb, yes, I'm using babel-eslint

**Comment by benmosher** [comment]
Hmm, I wonder if it's a babel-eslint change... not sure what would get into that situation. Regardless, we've got a bug here. Thanks for reporting!

**Comment by r3nya** [comment]
So … We can use this way:
```js
export { default } from './Map.jsx';
```
instead
```js
export default from './Map.jsx';
```

cc @adascal

**Comment by CalebDelbridge** [comment]
I'm still getting this issue on 2.21.2
```
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
    at assertValidNodeInfo (/usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:98:9)
    at /usr/local/lib/node_modules/eslint/lib/linter/report-translator.js:311:9
    at Object.report (/usr/local/lib/node_modules/eslint/lib/linter/linter.js:917:41)
    at Program (/Users/Caleb/Desktop/Barnabus-development/main-bot/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:265:23)
    at /usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:14)

```

**Comment by ljharb** [comment]
@CalebDelbridge can you file a new issue? it'd be great if you also provided your eslint/plugin versions, as well as the code that's causing this to crash.

**Comment by Jinwan5290** [comment]
sometime, this error maybe occured by export enum in ts file, finally I give up use enum to fix the error. but enum is a nice feature，anyone know how to change the lint rule to use enum

**Comment by yangtao00** [comment]
> sometime, this error maybe occured by export enum in ts file, finally I give up use enum to fix the error. but enum is a nice feature，anyone know how to change the lint rule to use enum

try this way
```js
// .eslintrc.js
'no-unused-vars': 'off',
'@typescript-eslint/no-unused-vars': ['warn']
```
