### ISSUE TITLE
Always require extensions except for externals

### ISSUE THREAD

**Issue by QuentinRoy** [benmosher/eslint-plugin-import#657]
My usual coding style is to always use the extensions on import *except* for externals (i.e. `node_modules`). Unfortunately, I could not find how to set up `import/extensions` for this.

Is it possible? If not, I would like to suggest it as an enhancement.

**Comment by benmosher** [comment]
dupe of #414?

**Comment by QuentinRoy** [comment]
Yep! I did not find that issue. Thanks.
