### ISSUE TITLE
webpack resolver import/no-unresolved issue with npm@2

### ISSUE THREAD

**Issue by anglee** [benmosher/eslint-plugin-import#664]
I have a project that uses webpack resolve alias like so, `webpack.config.js`:
```
  ...
  alias: {    
    'src': path.join(__dirname, './src'
  }
```
and in `.eslintrc`:
```
  ...
  "rules": {
    "import/no-unresolved": 1
  },
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "webpack.config.js"
      }
    }
  }
```

when I `npm install` with npm 2 (2.14.7), I will get `import/no-unresolved` problems reported.
when I `npm install` with npm 3 (3.10.9), I will NOT get `import/no-unresolved` problems reported.

I set up a example project, https://github.com/anglee/minimal-webpack, here are the exact steps to reproduce:
using npm@2
```
$ git clone https://github.com/anglee/minimal-webpack
$ cd $_
$ npm --version
2.14.7
$ npm install
$ ./node_modules/eslint/bin/eslint.js src/App.js
# see import/no-unresolved problems being reported
```
while with npm@3
```
$ git clone https://github.com/anglee/minimal-webpack
$ cd $_
$ npm --version
3.10.9
$ npm install
$ ./node_modules/eslint/bin/eslint.js src/App.js
# no eslint issues
```
the Node version doesn't seem to matter, I tested the combinations of both node 6 and 4 with npm 2 and npm 3.

I also noticed that if I configure by specifying 'eslint-import-resolver-webpack' instead 'webpack' in `eslintrc`, ie.
```
...
  "rules": {
    "import/no-unresolved": 1
  },
  "settings": {
    "import/resolver": {
      "eslint-import-resolver-webpack": { // !!
        "config": "webpack.config.js"
      }
    }
  }
```

then the npm@3 installed project still works fine, but npm@2 installed project will report, in addition to other `import/no-unresolved` problem:
```
  1:1   warning  Resolve error: unable to load resolver "eslint-import-resolver-webpack"  import/no-unresolved
```

can you please suggest what to solve the undesired behavior with npm2?

**Comment by ljharb** [comment]
Do you have eslint-revolver-webpack as a top level dep?

**Comment by anglee** [comment]
Do you mean `eslint-import-resolver-webpack`? yes, https://github.com/anglee/minimal-webpack/blob/master/package.json#L21

**Comment by benmosher** [comment]
hmm. nothing immediately obvious, other than: IIRC the config file path is expected to be relative to the working directory from which you run ESLint, _not_ relative to the `eslintrc`. If you'd like to configure it that way, you could use `path.join(__dirname, "webpack.config.js")`.

I'm not sure if that has any bearing on what you've observed, though.

**Comment by j3tan** [comment]
I encountered a similar issue when running linting on node `v4.6.1` with npm `2.15.9`.
The following error:
```
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-absolute-path
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-unresolved
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-extraneous-dependencies
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-duplicates
  1:1   error  Resolve error: unable to load resolver "node"                           import/extensions
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-named-as-default-member
  1:1   error  Resolve error: unable to load resolver "node"                           import/no-named-as-default
```
 was resolved after I had to manually run `npm install --save-dev eslint-import-resolver-node@0.2.3`. I did not have to do this on node 6.x/npm 3.x where it automatically installed the module just fine.

Next, I still had errors with the webpack resolver, `0.7.0`:
```
  2:1   error  'actions' should be listed in the project's dependencies. Run 'npm i -S actions' to add it  import/no-extraneous-dependencies
  2:34  error  Unable to resolve path to module 'actions/notifications'                                    import/no-unresolved
  2:34  error  Missing file extension for "actions/notifications"                                          import/extensions
```

which I tracked down to a missing dependency for `has` in `eslint-import-resolver-webpack/index.js:12`. Presumably, we can fix that problem by adding `has` as a dependency in the `package.json`.

Hope that helps!

**Comment by j3tan** [comment]
Also, it might be better if `requireResolver()` in `utils/resolve.js` throws an error when it can't `require` a module like `eslint-import-resolver-webpack`.

**Comment by j3tan** [comment]
Actually, it looks like `eslint-module-utils` is also missing a dependency on `eslint-import-resolver-node` when it tries to `require` it, it can't find it unless its installed at the root level. Simply put, even though it is an explicit dependency of `eslint-plugin-import`, `eslint-module-utils` can't call `require` on it since is stored in a separate `node_modules` directory with NPM 2

**Comment by ljharb** [comment]
Given that npm 2 doesn't even really work anymore, I think this can be closed.
