### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by fab1an** [benmosher/eslint-plugin-import#670]
For every practical purpose, it would be nice if this plugin could automatically remove duplicate imports.

**Comment by ljharb** [comment]
That'd have to be an autofixer for the [no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) rule.

**Comment by ljharb** [comment]
Actually, I see you've filed https://github.com/eslint/eslint/issues/7619 which is a better place for it.

**Comment by ljharb** [comment]
This is probably better as an autofixer for the core [no-duplicate-imports](https://github.com/eslint/eslint/blob/master/docs/rules/no-duplicate-imports.md) rule.
