### ISSUE TITLE
`pkg-up` vs `read-pkg-up`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [benmosher/eslint-plugin-import#675]
`pkg-up` is used to find the filepath of the nearest `package.json`.  That filepath is then [used to read that `package.json`](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-extraneous-dependencies.js#L15).  Could `pkg-up` be replaced with [`read-pkg-up`](https://github.com/sindresorhus/read-pkg-up)?  Both packages are written by the same author, but `read-pkg-up` reads the `package.json` and seems to be more maintained.
I can submit a Pull Request if you would like.

**Comment by benmosher** [comment]
Hmmm, I thought I remembered the path to the `package.json` being used beyond just reading the file, but a quick search of the repo suggests otherwise.

Wouldn't hurt. PR away, thank for the tip! 😄
