### ISSUE TITLE
Unable to resolve path to module 'v8'  

### ISSUE THREAD

**Issue by SkeLLLa** [benmosher/eslint-plugin-import#676]
Module v8 is built-in, but eslint-plugin-import tries to find it in node_modules.

**Comment by ljharb** [comment]
Interesting - https://nodejs.org/dist/latest-v7.x/docs/api/v8.html seems to be available only in io.js and node 4+.

This seems to be a bug in the `resolve` package - specifically that https://npmcdn.com/resolve@1.1.7/lib/core.json does not contain the string "v8" (which it would need to do conditionally by node version).

I've filed https://github.com/substack/node-resolve/issues/112 to address this.

**Comment by benmosher** [comment]
thanks @SkeLLLa for the note and @ljharb for the upstream issue!

**Comment by benmosher** [comment]
btw, can probably work around this with `import/core-modules` setting: https://github.com/benmosher/eslint-plugin-import#importcore-modules

**Comment by SkeLLLa** [comment]
@benmosher, thanks. At least for now I just use `// eslint-disable-line`.

**Comment by ljharb** [comment]
The `node-resolve` module will soon be updated to include all the proper core modules; I'll close this when that happens.

**Comment by SkeLLLa** [comment]
Great!

**Comment by ljharb** [comment]
v1.2.0 is released, and already included in the semver range for `eslint-import-resolver-webpack` and `eslint-import-resolver-node`, so this should already work.

I'll push up a commit shortly that bumps the minimum dep versions in both resolvers which will close this issue.

**Comment by benmosher** [comment]
heads up @SkeLLLa, just published v0.3.0 of the Node resolver with these changes.

**Comment by SkeLLLa** [comment]
@benmosher, great, thanks!

**Comment by benmosher** [comment]
agh, realization: probably can't install it since the Node resolver is a dependency of the plugin and is pegged to `^0.2.0`... hmm...

**Comment by benmosher** [comment]
created #690 to release v2.1.1 of the plugin that would allow it to be installed. stand by for release
