### ISSUE TITLE
Rule proposal: import name must match file name

### ISSUE THREAD

**Issue by gajus** [benmosher/eslint-plugin-import#678]
Here are some of the patterns that I have observed:

```diff
- import dfpAsyncHandler from '../../../ads-rendering/servers/dfp/handlers/DfpAsyncHandler';
+ import DfpAsyncHandler from '../../../ads-rendering/servers/dfp/handlers/DfpAsyncHandler';
```

```diff
- import createAsyncTracker from './AsyncTracker';
+ import AsyncTracker from './AsyncTracker';
```

I'd like there to be a rule that enforces that an import name must match the file name.

I think this rule should be enforced every time a file is imported without an extension.

**Comment by ljharb** [comment]
Duplicate of #662.

**Comment by ljharb** [comment]
Also, the extension wouldn't/shouldn't have an impact on a rule like that. It's a common best practice to always omit extensions, even for JS files.

**Comment by gajus** [comment]
Thank you.

For others, refer to https://github.com/selaux/eslint-plugin-filenames.

**Comment by gajus** [comment]
> Also, the extension wouldn't/shouldn't have an impact on a rule like that. It's a common best practice to always omit extensions, even for JS files.

I think you have meant "especially".

Regardless, while I said extensions, what I had in mind is files that include a dot in their name, e.g. "foo.spec.js". Its not something I'd do, but I have seen enough of it in other codes to take it under consideration.
