### ISSUE TITLE
import/extensions cannot understand .htaccess file name

### ISSUE THREAD

**Issue by KarandikarMihir** [benmosher/eslint-plugin-import#679]
`import 'file?name=[name].[ext]!./.htaccess';` gives me this-

`Missing file extension for "file?name=[name].[ext]!./.htaccess"  import/extensions`

**Comment by ljharb** [comment]
Is that a custom webpack syntax?

**Comment by KarandikarMihir** [comment]
@ljharb Yes, `file?name=[name].[ext]!` is a custom webpack syntax. You can ignore that. I can also turn this into a simpler form-  `import './.htaccess';`

Either way, eslint throws the aforementioned error :confused: Since, `.htaccess` does not have a file name, I thought `import/extensions` couldn't understand it. Please correct me if it's not a valid issue.

**Comment by benmosher** [comment]
ah yeah, so two issues here:

- `import/extensions` rule should probably ignore `.`-prefixed file names (such as `.htaccess`)
- `import/extensions` needs the new resolver goodness for path sanitizing (circa #479)

**Comment by tylucaskelley** [comment]
Any update on this? Annoying when trying to import dotfiles, for example `.eslintrc`

**Comment by ljharb** [comment]
Fixed by #1572, i believe, which will be in the next release.
