### ISSUE TITLE
no-duplicates rule with different webpack loaders

### ISSUE THREAD

**Issue by benmvp** [benmosher/eslint-plugin-import#682]
I have a file that has some imports like:

```js
import TextInputErrorExampleCode from '!raw!./TextInputErrorExample';
import TextInputErrorExample from './TextInputErrorExample';
```

The `no-duplicates` rule is considering these to be the same import even though one is code and the other is text.

Is there a configuration of the `webpack` resolver I can use to combat this?

Thanks!

**Comment by ljharb** [comment]
i'd recommend configuring webpack itself so that `!raw!` doesn't appear in your code (ie, don't use custom webpack syntax) and maybe do `import TextInputErrorExampleCode from './TextInputErrorExample.raw';`, and then configure the resolver for that extension.

**Comment by benmvp** [comment]
I like that idea! Probably will do something like `'./TextInputErrorExample.js.raw` so it could apply to any file, but I like it. Thanks!

**Comment by benmosher** [comment]
@benmvp are those not both referencing the same file?

**Comment by ljharb** [comment]
@benmosher the implication i heard was that one provides the source code as text, the other parses it and provides its export.

**Comment by benmvp** [comment]
Yep what @ljharb said. I ended up not able to try it out because the webpack config change would've taken longer than the time I had. I will circle back at some point!
