### ISSUE TITLE
eslint (and sublime-linter-eslint) cannot resolve .scss files

### ISSUE THREAD

**Issue by zhirzh** [benmosher/eslint-plugin-import#707]
Folder structure

    src/
    |-- styles/
    |   |-- foo.scss
    |
    |-- containers/
    |   |-- Foo.jsx
    |
    |-- modules/
        |-- foo.js

Foo.jsx

    import styles from 'styles/foo'; <--- error: import/extensions: Missing file extension "scss" for "styles/foo" 
    import styles from 'modules/foo'; <--- no errors
    ...

webpack.config.js

    {
      ...
      resolve: {
        extensions: ['', '.js', '.jsx', '.scss'],
        modulesDirectories: [
          path.resolve(__dirname, 'src'),
        ],
      },
    }

package.json

    "devDependencies": {
      ...
      "babel-eslint": "^7.1.1",
      "eslint": "^3.12.2",
      "eslint-config-airbnb": "^13.0.0",
      "eslint-import-resolver-webpack": "^0.8.0",
      "eslint-plugin-import": "^2.2.0",
      "eslint-plugin-jsx-a11y": "^2.2.3",
      "eslint-plugin-react": "^6.8.0",
      "extract-text-webpack-plugin": "^1.0.1",
    }

.eslintrc

    {
      "parser": "babel-eslint",

      "extends": "airbnb",

      "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ],

      "rules": {
        "no-param-reassign": 0,
        "react/prop-types": 0
      },

      "settings": {
        "import/resolver": "webpack"
      }
    }

**Comment by soryy708** [comment]
I don't see why you'd need to import `scss` files in `jsx`.
`import` is used for importing other ecmascript files, not styles.

**Comment by ljharb** [comment]
@soryy708 it's done so that bundlers (webpack) know when to include the relevant styles, and can link them together.

**Comment by ljharb** [comment]
You have to configure your `extensions` setting as well.

**Comment by ghbakhtiari** [comment]
@ljharb Can you please explain a bit more on what needs to be added to the settings?

I'm having the same problem with just the `scss` files!

```js
// webpack config:
resolve: {
    extensions: ['.js', '.jsx', '.scss'],
    alias: {
      // aliases...
    },
    modules: [
      // src path, ...
    ],
  },
```
```json
// .eslintrc
{
  "extends": [
    "eslint:recommended",
    "airbnb"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": "webpack.conf.js"
      }
    }
  }
}
```
And everything works for the `.js` and `.jsx` files, but with the `scss` files, if I omit the extension, I get this error:
```
 error  Missing file extension "scss" for "./App.styles"  import/extensions
```

Isn't the whole idea of defining `webpack` config as the `import/resolver` setting to prevent repeating the same settings in the eslint configs (for `resolve` and its options including `alias`es and `extensions`)?

**Comment by ghbakhtiari** [comment]
Ok, found the problem!
It wasn't related to the `"import/resolver"`'s settings.
It's the expected behavior of the `"import/extensions"` rule. Because I was using the `airbnb` settings, and their rule [only includes `js`, `mjs` and `jsx`](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L139):
```js
    'import/extensions': ['error', 'ignorePackages', {
      js: 'never',
      mjs: 'never',
      jsx: 'never',
    }],
```
So I had to add `scss`'s rule to my own `.eslintrc`...
```json
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "mjs": "never",
        "jsx": "never",
        "scss": "never"
      }
    ]
```
