### ISSUE TITLE
no-commonjs

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#71]
Complement to `no-require`.

Warn on `module.exports` and `exports.*`.

May want to optionally warn only on `exports.*` and `module.exports = {...}`.

Also: could implement `fix` rules for at least the `exports.*` => `export var * = ...` form.

**Comment by benmosher** [comment]
Combine with `no-require` as sibling of `no-amd`. Not sure why you'd want one and not the other.

**Comment by xjamundx** [comment]
You can use:
https://github.com/xjamundx/eslint-plugin-modules/blob/master/rules/no-cjs.js

**Comment by benmosher** [comment]
@xjamundx double thanks!
