### ISSUE TITLE
Add autofixer for order

### ISSUE THREAD

**Issue by AlexJuarez** [benmosher/eslint-plugin-import#711]
It would be nice if order/groups and order/newline had fix options.

I have done a little preliminary digging on what would be involved; order/newline looks like it will be easy to resolve and rather harmless as a whitespace only change. The difficulty seems to be in reordering imports with fix, since as far as I can tell its a little beyond the scope of a normal fix.

For food for thought, I have a [plugin ](https://github.com/AlexJuarez/eslint-plugin-import-order-autofix) that might make a good basis for conversation.

**Comment by dobryanskyy** [comment]
It's also interesting for me. However proposed plugin removes newlines for me (windows, no semicolons).

**Comment by AlexJuarez** [comment]
@dobryanskyy I changed the newline addition to use require('os').EOL, maybe that will help. Can you post an example snippet?

**Comment by dobryanskyy** [comment]
Sure. Its changing code 
```js
import reducer from '../reducers'
import {composeWithDevTools} from 'redux-devtools-extension/developmentOnly'
```
to 
```js
import {composeWithDevTools} from 'redux-devtools-extension/developmentOnly'import reducer from '../reducers'
```

**Comment by AlexJuarez** [comment]
@dobryanskyy I was able to track down the issue. I'll make a couple changes and lets see if that stabilizes it.

**Comment by lukeapage** [comment]
@AlexJuarez are you awaiting the owner to say they would like a pr? I would like to see this in the core plugin, maybe a pr would help that. I can help if you are too busy now.

**Comment by ljharb** [comment]
I'm skeptical this can be done correctly in a single pass (since currently the rule's warnings often require multiple passes to fix manually, if you're only operating based on the warnings) but that'd be a welcome improvement.
