### ISSUE TITLE
import/ignore not work

### ISSUE THREAD

**Issue by bayun2** [benmosher/eslint-plugin-import#715]
.eslintrc
```
"settings": {
    "import/extensions": [
      ".js"
    ],
    "import/ignore": [
      "node_modules",
      "\\.(css|less)$"
    ],
  }
```

file construction
```
.
├── component
├── data.js
├── fdt-socket.js
├── img
├── index.js
└── index.less
```

index.js  》》 import './index.less';

I want eslint all js ,but not contain less file. when i use config like top ,it not work.

console error show：
./src/index.less
Module build failed: ModuleError:

eslint version:

"eslint": "^3.13.0",
"eslint-loader": "^1.6.1",
"eslint-plugin-import": "^1.13.0",
"eslint-plugin-react": "^6.9.0",

what's wrong with me

**Comment by benmosher** [comment]
I think it's possible that the `eslint-loader` is trying to process `index.less`. can you post your webpack config?

**Comment by bayun2** [comment]
I use webpack and gulp at same time. 

Here is my configs:
webpack.config.js:
'use strict';

const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: {
    index: [
      './src/index.js'
    ]
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },
  externals:{
    react:'React',
    'react-dom':'ReactDOM',
    'react-router': 'ReactRouter',
    SockJS: 'SockJS',
    Stomp: 'Stomp'
  },
  resolve: {
    modulesDirectories: ['node_modules', './src'],
    extensions: ['', '.js']
  },
  postcss: [require('autoprefixer')],
  module: {
    loaders: [{
      test: /\.js?/,
      loaders: ['babel'],
      exclude: /node_modules/
    }, {
      test: /(index)\.less$/,
      loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!less-loader')
    }, {
      test: /\.less/,
      loaders: ['style', 'css', 'postcss', 'less'],
      exclude: /(index)\.less$/
    }, {
      test: /\.css$/,
      loaders: ['style', 'css', 'postcss']
    }, {
      test: /\.(png|jpg|jpeg|gif|svg)$/,
      loaders: ['url?limit=8192']
    }]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('shared.js'),
  ]
};

===================================

gulpfile.js

'use strict';
const webpack = require('webpack');
const gulpWebpack = require('webpack-stream');
const express = require('express');
const gulp = require('gulp');
const del = require('del');
const objectAssign = require('object-assign');
const merge = require('lodash.merge');
const wpConfig = require('./webpack.config.js');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const execSync = require('child_process').execSync;
const fs = require('fs');
const path = require('path');

gulp.task('clean', ['checkVersion'], cb => {
  del(['dist']).then(() => {
    cb();
  });
});

gulp.task('checkVersion', cb => {
  const cwd = process.cwd();
  let version;
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf-8'));
    version = pkg.version;
  } catch (e) {
    cb(e);
  }

  let exitCode = 0;
  try {
    execSync(`git ls-remote --exit-code --tags origin ${version}`, {
      cwd,
    });
  } catch (e) {
    exitCode = e.status;
  } finally {
    if (exitCode === 0) {
      cb('has tagged');
    } else if (exitCode !== 2) {
      cb('no response');
    } else {
      cb();
    }
  }
});

gulp.task('build', ['clean'], () => {
  const config = merge(wpConfig, {
    devtool: 'source-map',
    plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify(process.env.NODE_ENV)
        },
      }),
      new ExtractTextPlugin('index.css'),
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.optimize.UglifyJsPlugin({
        compressor: {
          warnings: false
        }
      })
    ],
    module: {
      preLoaders: [{
        test: /\.js?/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      }]
    }
  });
  return gulp.src('./src/**/*.js')
    .pipe(gulpWebpack(config))
    .pipe(gulp.dest('dist'));
});

gulp.task('dev', cb => {
  const app = express();
  wpConfig.module.loaders[0] = {
    test: /\.js?/,
    loaders: ['babel'],
    exclude: /node_modules/
  };
  const config = objectAssign({}, wpConfig, {
    devtool: 'eval',
    entry: {
      index: [
        './src/index.js'
      ]
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify(process.env.NODE_ENV)
        }
      }),
      new webpack.NoErrorsPlugin(),
      new ExtractTextPlugin('index.css'),
      new webpack.HotModuleReplacementPlugin()
    ]
  });
  const compiler = webpack(config);
  app.use(require('webpack-dev-middleware')(compiler, {
    noInfo: true,
    publicPath: '/dist/'
  }));
  app.use(require('webpack-hot-middleware')(compiler));
  app.use(express.static(__dirname));
  app.get('/pages/*', (req, res) => {
    res.sendFile(path.join(__dirname, 'pages', 'index.html'));
  });
  app.post('/data/:name', (req, res) => {
    res.sendFile(path.join(__dirname, 'data', req.params.name));
  });
  app.listen(8080, err => {
    if (err) {
      console.log(err);
      return;
    } else {
      console.log('Page is running at: http://local.forexmaster.cn:8080/pages/index');
    }
    cb();
  });
});

gulp.task('default', ['build']);
