### ISSUE TITLE
Disable import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by basickarl** [benmosher/eslint-plugin-import#729]
How does one disable `import/no-extraneous-dependencies` in the `.eslintrc` file?

I'm getting errors on local modules.

`"start": "NODE_PATH=\"$(pwd)\" node -r babel-register -r babel-polyfill src/index.js",`

By setting NODE_PATH to the root directory where package.json lies enables me to write imports from the root:

`import config from 'src/utils/config';`

I'd just like to disable the `import/no-extraneous-dependencies` rule completely. How does one do this?

**Comment by basickarl** [comment]
Got the answer: `"import/no-extraneous-dependencies": "off",` in the rules block.

**Comment by ljharb** [comment]
Heads up, you never ever want to set NODE_PATH, and it's not needed in your case because `npm start` already sets up the PATH for you.

**Comment by basickarl** [comment]
@ljharb Thanks for the reply, may I ask why one shuld not set the NODE_PATH? I've been setting it without any issues?

I'm aware of possible other solutions mentioned here: https://gist.github.com/branneman/8048520

**Comment by ljharb** [comment]
For one, it's deprecated, and ES modules (when node ships them) will not support it. That gist is from 2013 and is pretty out of date.

I'd recommend using a Babel transform so that you end up with proper relative paths in your code, and all tooling in the ecosystem will work properly with it.
