### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by craigcosmo** [benmosher/eslint-plugin-import#733]
**eslintrc**
```
"plugins": ["import"]
```

**file.js**
```
import 'homdes.scss'  // in reality this file does not exist
```

run: npm run lint

result: nothing

expect: error / unresolved

**Comment by ljharb** [comment]
That doesn't enable any of the rules - you need to add `"rules": { "import/no-unresolved": "error" }`.

**Comment by craigcosmo** [comment]
in the doc say all rule enable by default

And there is an example extracted from the doc
```
import 'electron'  // without extra config, will be flagged as unresolved!
```

**Comment by k15a** [comment]
> All rules are off by default.

at https://github.com/benmosher/eslint-plugin-import#installation

**Comment by ljharb** [comment]
No rules are ever enabled by default in eslint.
