### ISSUE TITLE
configuring for react/jsx?

### ISSUE THREAD

**Issue by tony-kerz** [benmosher/eslint-plugin-import#736]
right now, i'm doing something like:
```
    "settings": {
      "import/resolve": {
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    }
```

there is mention of some shared config [here](https://github.com/benmosher/eslint-plugin-import#importextensions), but i'm not familiar with the syntax for enabling that. 

can anyone shed some light?

best,
tony.

**Comment by hurrtz** [comment]
I think "import/resolve" is missing the trailing "r": "import/resolver".

**Comment by Graham42** [comment]
This is what worked for me 
```json
  "settings": {
    "import/resolver":{
      "node" :{
        "extensions": [".js",".jsx"]
      }
    }
  },
```

**Comment by jwalton** [comment]
This worked for me.  I notice, though, that there's a [react config here](https://github.com/benmosher/eslint-plugin-import/blob/master/config/react.js), although if you:

```
    "extends": [
        "plugin:import/react",
        "plugin:import/errors"
    ]
```

This doesn't seem to work.
