### ISSUE TITLE
Is it possible to manually add a path to be resolved?

### ISSUE THREAD

**Issue by wlingke** [benmosher/eslint-plugin-import#748]
I have a folder in my project a folder `main` that I am resolving like a module. For instance `import x from 'main/src'` imports `main/src/index.js`. This is done through webpack's resolve alias configuration.

An issue I am having is getting rid of the errors via eslint. I know eslint provides a webpack resolve plugin, however, I've been having trouble getting it to work. I suspect it is because I am on webpack 2 and using es6 in my webpack config files.

One solution that I've seen work is using import/core-modules but then I have to list out every folder in the subdirectory tree `main/src/bar`, `main/src/foo`, etc... This would not be ideal.

Is there a manual way to write a resolve setting that fixes this problem for my eslint? I don't want to spend hours debugging the webpack resolve plugin for such a simple use case.

**Comment by sota1235** [comment]
I think the link below helps you.
You can add resolving directories by using config.
https://github.com/benmosher/eslint-plugin-import#resolvers

**Comment by wlingke** [comment]
@sota1235 I've read that, but am confused as to how it works. It looks like you need to write a custom resolver to use this setting. Can you provide an example for how to do this?

**Comment by sota1235** [comment]
For example, if you want to resolve `src/`, you can write like below.

```json
{
  "settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  }
}
```

Then ESLint resolve from `src` directory.
You can require `src/hoge/moge.js` by writing `const moge = require('hoge/moge');` and ESLint knows it.

I am sorry if the answer is not suitable for you. Thank you :)

**Comment by wlingke** [comment]
@sota1235 Actually that's perfect. Thanks for the help.

If you want to add this answer on my stackoverflow question - I'd be happy to accept it: http://stackoverflow.com/questions/41769880/how-to-manually-add-a-path-to-be-resolved-in-eslintrc

**Comment by johvin** [comment]
Too late to see this question. I've added an answer on your stackoverflow question.
