### ISSUE TITLE
False Positive node_module import/no-unresolved

### ISSUE THREAD

**Issue by patrickml** [benmosher/eslint-plugin-import#761]
So, i am having something odd happen with a specific node_module package.

The package exists in my package.json and in my node_modules dir
![image](https://cloud.githubusercontent.com/assets/7581369/23664435/896cf762-0323-11e7-8ef5-b46649bd1fa6.png)

But the linter keeps puking on this.
![image](https://cloud.githubusercontent.com/assets/7581369/23664389/6bc75a5e-0323-11e7-8ea8-201e54bd601a.png)

The same thing happens on other machines even when running eslint from the cli

another odd thing is that In runtime the package is found and use though

**Comment by ljharb** [comment]
There's a bug in that package. https://unpkg.com/material-ui-superselectfield@1.1.0/package.json says "main" is `lib/superSelectField.js` but the filename is [`lib/SuperSelectField.js`](https://unpkg.com/material-ui-superselectfield@1.1.0/lib/SuperSelectField.js).

In other words, it would only work at runtime if you have a case-insensitive filesystem.

**Comment by patrickml** [comment]
Ahhhhh thanks I'll make a PR for them then. Thank you.
