### ISSUE TITLE
Add a new import group - style files?

### ISSUE THREAD

**Issue by ZxMYS** [benmosher/eslint-plugin-import#762]
Hi!

I think it makes sense to make style imports a separate group in imports, so CSS and LESS won't be mixed with 'code' imports. 
E.g. we can have
```
import foobar from './foobar';

import styles from './styles.css';
```

Thoughts?
(it can be supported if #674  is done)

**Comment by ljharb** [comment]
Style imports aren't a standard part of require, so reifying that here seems problematic.

**Comment by ZxMYS** [comment]
Ok, I guess then we should move towards regex.
