### ISSUE TITLE
no-extraneous-dependencies and component library

### ISSUE THREAD

**Issue by three60five** [benmosher/eslint-plugin-import#770]
I am assembling a component library from various third-party component libraries. The `package.json` file of my component library has each third-party package as a dependency like this:

>"dependencies": {
    "react-bootstrap": "^0.30.8",
    "react-styled-flexboxgrid": "^1.0.2"
}

Now when install my component library into a project with an `.eslintrc` file with the following rule:

>    "rules": {
      "import/no-extraneous-dependencies": [
        "error", {"devDependencies": ["**/*_test.js"]}]
    } 

I get the "no-extraneous-dependencies" error when I import a `react-bootstrap` component like:

>import { Button } from 'react-bootstrap';

I want to bundle these third-party component libraries together and make it easy to distribute to my teammates without them having to install them all individually without their linters complaining.

Is there a config option I'm not seeing that will help me quiet this error?

**Comment by ljharb** [comment]
If someone wants to require react-bootstrap, it must be a top level dependency.

Thus, you want to make it a peer dep and dev dep - not a regular dep - because react things are often singletons and need to be available at the top level.

**Comment by three60five** [comment]
Thanks for responding. If I make each third-party package a peer and dev dep, I feel like the developer experience using this bundled component library is really diminished. To use it in their project, they will get warned they don't have a peer dep when installing, then they have to manually install each third-party library themselves. It kinda defeats the purpose. 

Are there any config options that could be applied for this use case?

**Comment by ljharb** [comment]
There's no way around it. This is what the developer experience is in an ecosystem with singletons, including every single react package. React, not you, we have to make changes for this experience to change.
