### ISSUE TITLE
import/no-extraneous-dependencies doesn't work with nested eslintrc

### ISSUE THREAD

**Issue by atorkhov** [benmosher/eslint-plugin-import#777]
I have the following project hierarchy:
```
project
├── .eslintrc
├── project.json
└── test
        ├── .eslintrc  <- Not used
        └── test.js
```

When I'm putting following directive in `test/.eslintrc` it is not used:
```
{ rules: { "import/no-extraneous-dependencies": ["error", { "devDependencies": true }] } }
```

Same in top-level .eslintrc is working. Version of eslint-plugin-import is 2.2.0.

**Comment by ljharb** [comment]
Can you elaborate on "not working"? I've used this eslintrc setup for awhile and it works fine. What version of eslint?

**Comment by ljharb** [comment]
Closing pending a response.
