### ISSUE TITLE
Cannot make custom webpack alias to work 

### ISSUE THREAD

**Issue by sqal** [benmosher/eslint-plugin-import#779]
Hi, I have some trouble with webpack resolver and setting up webpack alias. Please look at this simple example.

- Clone the repo https://github.com/sqal/eslint-import-bug-repo 
- `yarn/npm install` 
- run `lint` command

With this import `import foo from '@app/modules/foo'` eslint  shows an error 

`@app/modules' should be listed in the project's dependencies. Run 'npm i -S @app/modules' to add it  import/no-extraneous-dependencies`

But there is no issue with the second one. Any ideas how can i fix it? i would appreciate any help you can provide. Thank you.

**Comment by sqal** [comment]
It looks like eslint has problem with @ sing, because if I change my alias to:

```
alias: {
  whatever: path.resolve('src/app')
}
```

Then this works `import foo from 'whatever/modules/foo';`  thoughts?

**Comment by skyrpex** [comment]
I can't get it working with any alias (@, ~, whatever).

**Comment by Sonblind** [comment]
I'm using ReactNative and have the same issue. Any alias with `@` throws the same error.

```
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      extensions: [".js", ".ios.js", ".android.js"],
      "alias": {
        "@components": "./app/components/",
        "@containers": "./app/containers",
        "@themes": "./app/themes",
      }
    }]
  ]
```
Any word-character based string works fine.

### Failing:
        `"@themes": "./app/themes",`

### Working:
        "themes": "./app/themes",

**Comment by Sonblind** [comment]
I'm using ReactNative and have the same issue. Any alias with `@` throws the same error.

```
  "plugins": [
    ["module-resolver", {
      "root": ["./src"],
      extensions: [".js", ".ios.js", ".android.js"],
      "alias": {
        "@components": "./app/components/",
        "@containers": "./app/containers",
        "@themes": "./app/themes",
      }
    }]
  ]
```
Any word-character based string works fine.

### Failing:
        `"@themes": "./app/themes",`

### Working:
        "themes": "./app/themes",

**Comment by michielmetcake** [comment]
Is there any update on this issue?

**Comment by sqal** [comment]
@michielmetcake It's pretty old issue.. I personally don't have this problem anymore.  Do you have all of your dependencies up to date?

**Comment by ljharb** [comment]
Closing then; please file a new issue if there's still problems.
