### ISSUE TITLE
Rule "no-anonymous-default-export" is not present in lib/rules folder

### ISSUE THREAD

**Issue by ipanasenko** [benmosher/eslint-plugin-import#791]
Hi, guys!

I wanted to use "no-anonymous-default-export" rule in my project, but seems like somehow there's no such rule in lib/rules directory.
Screenshot of folder inside node_modules: https://dl.dropboxusercontent.com/spa/lzmr7lr81mgaoil/xuycfqjw.png

eslint-plugin-import version: 2.2.0

Can someone have a look why this happens?

**Comment by ipanasenko** [comment]
Okay, seems like this rule has been added after 2.2.0 release and there hasn't been a release ever since. Will there be a new version any time soon?

**Comment by MatthewHerbst** [comment]
I'm having the same issue - ++ for releasing this rule ASAP!

**Comment by ljharb** [comment]
Closing in favor of #798
