### ISSUE TITLE
Rule Proposal: no-parent-import

### ISSUE THREAD

**Issue by danny-andrews** [benmosher/eslint-plugin-import#792]
In many of my projects, I set up a webpack alias or use a babel plugin like [this](https://github.com/entwicklerstube/babel-plugin-root-import) to prevent long relative imports (e.g. `import myThing from '../../../things/mything'`). It would be nice if there was a rule to prevent users from using `../` to reach into parent directory and to instead use the alias ((e.g. `import myThing from 'my-app/things/mything'`).

If this is something you would like to see added to this repo, I'd be happy to submit a PR. :)

**Comment by ljharb** [comment]
Duplicate of #784, i think

**Comment by danny-andrews** [comment]
Yup, sorie.

**Comment by danny-andrews** [comment]
Actually, more of a dupe of https://github.com/benmosher/eslint-plugin-import/issues/669#issuecomment-316438608.
