### ISSUE TITLE
Release 2.3.0

### ISSUE THREAD

**Issue by duncanbeevers** [benmosher/eslint-plugin-import#798]
2.2.0 was released last November and some new rules and options have hit master since then.

At a glance, the user-facing changes since then are:
* Add `no-anonymous-default-export` rule
* Add 'always-and-inside-groups' value to order's newlines-between option to allow newlines inside import groups
* Add `count` option to `newline-after-import`

**Comment by ljharb** [comment]
Adding new things requires a minor bump, so this would have to be v2.3.0

**Comment by tmc** [comment]
ping @benmosher

**Comment by benmosher** [comment]
makes sense to do. not sure when I'll have time.

really just need:

- [ ] confirmation that all changes landed in changelog. would love PRs for any missing bits.
- [ ] check current open PRs for things that ought to land in this release

if y'all can do that, any of the three of us could publish. I just don't want to publish without both of those, and the former is most of the time/labor.

**Comment by duncanbeevers** [comment]
@benmosher Thanks!

**Comment by duncanbeevers** [comment]
I see https://github.com/benmosher/eslint-plugin-import/pulls is still open, so I'm going to leave this as-is.

**Comment by benmosher** [comment]
just published!
