### ISSUE TITLE
cannot import third module correctly？

### ISSUE THREAD

**Issue by zp1112** [benmosher/eslint-plugin-import#800]
"eslint-plugin-import": "^2.2.0"
"antd": "0.11.3"

ESLint: 'antd' should be listed in the project's dependencies. Run 'npm i -S antd' to add it (import/no-extraneous-dependencies)

but i truely have listed third modules in my package.json dependencies,and why throw the eslint error?but React module is working all right

**Comment by ljharb** [comment]
eslint-plugin-import (like all eslint stuff) should be a devDependency. Can you share your entire package.json?

**Comment by zp1112** [comment]
I found the problem,it's definitely my fault,and i am sorry for openning this issue,and after you see my apologize, you can delete this issue.
