### ISSUE TITLE
Fail to resolve Node module sha3

### ISSUE THREAD

**Issue by jay1337** [benmosher/eslint-plugin-import#802]
Hello,

I get the error `Unable to resolve path to module 'sha3'.` when I install and import module sha3 with `import sha3 from 'sha3';.`.
When I run my script with Node (Windows 7) everything is ok. Everything is ok with other modules.

sha3 package don't have an `index.js` and instead has `"main": "build/Release/sha3"` in its `package.json` and a `sha3.node` file in its `build/Release/` subdirectory.

Is it a bug with `eslint-plugin-import-node` ?

Thanks for your help.

**Comment by ljharb** [comment]
Node itself imports from `.node` as one of the default require extensions; it's certainly possible that the node resolver does not do this (as its exceedingly rare for it ever to be used).
