### ISSUE TITLE
Definition for rule 'import/no-extraneous-dependencies' was not found 

### ISSUE THREAD

**Issue by LeonardoGentile** [benmosher/eslint-plugin-import#809]
Hello,
I've installed `"eslint-plugin-import": "^2.2.0",` and using it into my `./test` directory.

with 
```
{
  "env": {
    "mocha": true
  },
  "rules": {
    "import/no-extraneous-dependencies": [
      "error",
      {
        "optionalDependencies": false,
        "peerDependencies": true,
        "devDependencies": true
      }
    ],
    "no-unused-expressions": "off",
    "padded-blocks": "off"
  }
}
`
```
But whenever I run my npm lint script (that is `eslint src test tools`) I always get back:

```
 1:1   error  Definition for rule 'import/no-extraneous-dependencies' was not found  import/no-extraneous-dependencies
```
I don't understand if this is a bug or a misconfiguration. `eslint-plugin-import` is correctly installed, I'm sure..

**Comment by ljharb** [comment]
@LeonardoGentile you need `"plugins": ["import"]` to be able to override the rules.

**Comment by LeonardoGentile** [comment]
@ljharb oops, sorry for that 😆 
👍  thanks
