### ISSUE TITLE
eslint-plugin-import-webpack not working for es6 

### ISSUE THREAD

**Issue by isbdnt** [benmosher/eslint-plugin-import#813]
When I write webpack.config.file with es6 syntax, the resolver is not working.

**Comment by isbdnt** [comment]
I can not find any config option in the README.MD to set node interpreter to babel-node. I have tried set node interpreter of eslint to babel-node, but got error "Cannot get result of ESLint annotation" in webstorm.

**Comment by isbdnt** [comment]
![screenshot from 2017-04-27 19-11-40](https://cloud.githubusercontent.com/assets/26591233/25480896/6f9eff06-2b7d-11e7-9cc3-e2e7d9230aec.png)

**Comment by isbdnt** [comment]
![image](https://cloud.githubusercontent.com/assets/26591233/25480919/901893a0-2b7d-11e7-9741-fb43989f9b19.png)

**Comment by isbdnt** [comment]
![image](https://cloud.githubusercontent.com/assets/26591233/25480946/adc10018-2b7d-11e7-9042-6558829fb39d.png)

**Comment by jeron-diovis** [comment]
Can this issue be reopened? I came here with same problem.
For now I have to do smth like this:

```
// webpack.config.js
require("babel-register")
module.exports = require("./webpack.config.es6.js")
```

Not so big deal, but annoying.
Is there another way to solve this, or could it be added to resolver itself?

**Comment by ljharb** [comment]
I believe if the extension is .babel.js then webpack will do that for you automatically.

**Comment by jeron-diovis** [comment]
Webpack do that even for regular `webpack.config.js`. Webpack-resolver does not.

**Comment by ljharb** [comment]
is that new in v2? v1 definitely did not.

**Comment by jeron-diovis** [comment]
Yes, it's new v2.

**Comment by sylv3r** [comment]
Same problem here, when I tried to add the resolver with my webpack config (which obviously starts with `import`s), eslint crashed..

I will try @jeron-diovis workaround, but there should be a way to parse properly webpack config according to eslint `parser` and `parserOptions` configuration.
