### ISSUE TITLE
Definition for rule 'import/no-anonymous-default-export' was not found

### ISSUE THREAD

**Issue by seankoji** [benmosher/eslint-plugin-import#818]
using "eslint-plugin-import": "^2.2.0",

other rules working fine

```
"import/no-anonymous-default-export": "error"
```

**Comment by ljharb** [comment]
As you can see on the [commit](https://github.com/benmosher/eslint-plugin-import/commit/f43cf95dd7c3453cb73a24e9984b17e8fc2c74ef), it's in master but not in any tagged versions, which means it's not yet been released.
