### ISSUE TITLE
How to check if used modules miss `import` statement

### ISSUE THREAD

**Issue by iplaces** [benmosher/eslint-plugin-import#822]
Recently I have faced a problem: I'm trying to find if there are any modules used without `import` 
 statement with eslint. But I could not find how to do it with `eslint-plugin-import` or only `eslint`. So I'm wondering that are there any configurations for this feature. Thx.

**Comment by ljharb** [comment]
I'm not sure I understand; you're looking for modules that don't happen to import anything? Why?

**Comment by iplaces** [comment]
@ljharb I didnt' mean it that way. Just like when I use `React.Component` in one of my component files but I forgot to use `import React from 'react'`（As shown in the screenshot）. I wish eslint could help me check it out. And then when my teammates work together, we can find the same problem easily by using this rule.

![image](https://cloud.githubusercontent.com/assets/11191335/25756239/99c353e6-31f8-11e7-8b84-c8ddb722da52.png)

**Comment by ljharb** [comment]
It does. Enable jsx-uses-react, iirc.

**Comment by ljharb** [comment]
(In eslint-plugin-react)

Do you have a non-react use case too?

**Comment by iplaces** [comment]
@ljharb yes, I want to find a common use of these cases，not just for react. If I use any components or modules I forgot to import, eslint could show me errors. Just like the `no-use-before-define` rule. Is there a "`no-use-before-import`"(this name was made up only for explanation) rule for this?

**Comment by ljharb** [comment]
eslint core already has a number of rules that handle this. React is only special because of JSX.

Try enabling https://npmjs.com/eslint-config-airbnb and see if this shows you all the errors you're looking for.

**Comment by iplaces** [comment]
@ljharb Thanks for helping. I have found it in eslint core. When using JSX, this error could also be found by jsx-no-undef rule in eslint-plugin-react. Pretty awsome!
