### ISSUE TITLE
Relative imports with leading tilde

### ISSUE THREAD

**Issue by ManuSevenval** [benmosher/eslint-plugin-import#824]
we use project relative imports like 
`import MyComponent from '~/common/components/MyComponents';`

`eslint-plugin-import` only lints imports without a tilde `~` correctly. How could we solve the issue?

Our shortenend configuration in `.eslintrc`:

```
"extends": [
    "plugin:import/errors"
  ],
  "env": {
    "node": true,
    "browser": true,
    "jest": true
  },
  "rules": {
    "import" : [2, "no-unresolved", "named", "default"]
  }
```

**Comment by ljharb** [comment]
Since a leading tilde isn't part of the normal node require algorithm, I believe you'd have to write a custom resolver.

**Comment by benmosher** [comment]
@ManuSevenval: what is your environment / build system? a custom resolver may already exist. see https://github.com/benmosher/eslint-plugin-import/wiki/Resolvers
