### ISSUE TITLE
Store not found in 'redux'

### ISSUE THREAD

**Issue by zaaack** [benmosher/eslint-plugin-import#830]
I'm using type definitions for redux from flow-typed, 
```js
import type { Store, Middleware } from 'redux'
```
but eslint got an error:

```sh
Store not found in 'redux' (import/named)
Middleware not found in 'redux' (import/named)
```

flow is working, and at the same time importing types from `react-router_v4.x.x.js`  doesn't have this eslint error。

https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-router_v4.x.x/flow_v0.38.x-/react-router_v4.x.x.js
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js

**Comment by zaaack** [comment]
https://github.com/benmosher/eslint-plugin-import/issues/708

**Comment by IanVS** [comment]
@zaaack is this working for you now?  I'm still getting errors with the latest version of eslint-plugin-import.

**Comment by budarin** [comment]
I also have such error [#5238](https://github.com/facebook/flow/issues/5238)
