### ISSUE TITLE
no-unresolved caseSensitive weird edge case

### ISSUE THREAD

**Issue by OmgImAlexis** [benmosher/eslint-plugin-import#831]
I'm using [atom-xo-linter](https://github.com/sindresorhus/atom-linter-xo) which relies on this package. If I open atom with `atom ~/code/medusa/` `atom-xo-linter` shows the `casing does not match the underlying filesystem` warning yet if I open it using `atom ~/code/Medusa/` there's no warning.

I'm on macOS Sierra 10.12.3 (16D32).

**Comment by OmgImAlexis** [comment]
This may possibly be related to how Atom opens file.
Ref: https://github.com/atom/atom/issues/8221

**Comment by Arcanemagus** [comment]
`atom-xo-linter`, like all other linter providers there, uses [`TextEditor::getpath()`](https://atom.io/docs/api/v1.16.0/TextEditor#instance-getPath) [here](https://github.com/sindresorhus/atom-linter-xo/blob/v0.23.0/lib/lint.js#L13) to get the path sent to XO (and thus here in `eslint-plugin-import`), so I would agree with you that this is a problem that needs to be solved on Atom's part.

**Comment by ljharb** [comment]
Happy to reopen if it ends up being an issue here.
