### ISSUE TITLE
`filePath` is not provided to `parser` in `parserOptions`

### ISSUE THREAD

**Issue by sompylasar** [benmosher/eslint-plugin-import#839]
I'm trying to make a conditional eslint parser which decides based on filename which parser to execute: Babel or TypeScript (because my project will soon contain both types of files which need to live together under a single eslint config for some time).

The native eslint parse call provides `filePath` in the `parserOptions`, which turned out the only and the very useful way to determine the file name:
https://github.com/eslint/eslint/blob/3ec436eeed0b0271e2ed0d0cb22e4246eb15f137/lib/linter.js#L637
```js
function parse(text, config, filePath, messages) {

    let parser,
        parserOptions = {
            loc: true,
            range: true,
            raw: true,
            tokens: true,
            comment: true,
            filePath
        };
```

But when `eslint-plugin-import` parses its dependencies, it calls the custom parser on its own, and does not provide `filePath` in `parserOptions`:
https://github.com/benmosher/eslint-plugin-import/blob/90ef48b3ade57c77526b285f75dc0cfc41537831/utils/parse.js#L28
```js
exports.default = function parse(path, content, context) {

  if (context == null) throw new Error('need context to parse properly')

  let parserOptions = context.parserOptions
  const parserPath = getParserPath(path, context)

  if (!parserPath) throw new Error('parserPath is required!')

  // hack: espree blows up with frozen options
  parserOptions = Object.assign({}, parserOptions)
  parserOptions.ecmaFeatures = Object.assign({}, parserOptions.ecmaFeatures)

  // always attach comments
  parserOptions.attachComment = true

  // require the parser relative to the main module (i.e., ESLint)
  const parser = moduleRequire(parserPath)

  return parser.parse(content, parserOptions)
}
```

This should not be a big change to add that, I'll propose a PR soon.

**Comment by benmosher** [comment]
makes sense to me :+1:

**Comment by benmosher** [comment]
published under v2.4.0, thanks!

**Comment by benmosher** [comment]
uh oh, seems to break the cache! not sure why this isn't caught by tests but it introduces a substantial perf + memory regression. unpublishing v2.1.0 of eslint-module-utils!

**Comment by sompylasar** [comment]
@benmosher What? 0_o Which cache? How did you spot the regression?

**Comment by sompylasar** [comment]
Cache issue investigation here: https://github.com/benmosher/eslint-plugin-import/issues/863

**Comment by benmosher** [comment]
reiterating: leak is in `memo-parser` which I am probably the only person using. (or we'll find out soon enough)

republished with v2.1.1 of utils 👍🏻
