### ISSUE TITLE
Incorrect "No default export found"

### ISSUE THREAD

**Issue by jay1337** [benmosher/eslint-plugin-import#850]
Hello,

I get an incorrect "No default export found" error when importing "react-native-code-push".
Source code of this module is here : https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js

It would be great if you could fix this.

Thanks in advance.

**Comment by ljharb** [comment]
How are you importing it?

Since that module.exports is an object, the implication is that you should be named-importing it's properties as you need then.

**Comment by jay1337** [comment]
import codePush from "react-native-code-push";
codePush.codePushFunction(blabla);

... so with a default import which is working well.

**Comment by ljharb** [comment]
If you try `import { codePushFunction } from 'react-native-code-push';`, would it work as well, but without the linter complaining?

**Comment by Sparragus** [comment]
The same also happens with `import Swiper from 'react-native-swiper`. See https://github.com/leecade/react-native-swiper/blob/master/index.js

How can I help debug this?

**Comment by ljharb** [comment]
hmm, that one is just a function, so that should work fine.

@Sparragus any chance you could make a small repo that reproduces the problem?

**Comment by Sparragus** [comment]
@ljharb Sure. Will reply with it later.

**Comment by Sparragus** [comment]
@ljharb Here you go: https://github.com/Sparragus/eslint-plugin-import-bug

**Comment by ljharb** [comment]
Eesh, both of those are publishing untranspiled code.

Either way, `react-native-elements` *has* no named exports - that's explicitly using `module.exports =` which means you have to import that as an object, and then in a separate line, destructure out what you need.

I'm not sure why `react-native-swiper` isn't working.

However, I'm super confused why *either* of those packages publish untranspiled `import` but don't use `export` directly in their entry points.

**Comment by jay1337** [comment]
@ljharb linter still complains with `import { codePushFunction } from 'react-native-code-push';`

**Comment by ljharb** [comment]
@jay1337 react-native-code-push [also](https://unpkg.com/react-native-code-push@2.0.3-beta/CodePush.js) publishes untranspiled code.

eslint-plugin-import might need a custom resolver for untranspiled code. Sadly, react-native encourages publishing untranspiled code, which breaks every non-react-native user.

**Comment by benmosher** [comment]
since the imported module is a module (has `import`s), it is expected to `export` something.

the linter is correct: there is no default export. 

is this sort of module typical? I am unfamiliar with this usage of CJS export with ESM import.

you can `import/ignore` it to work around.
