### ISSUE TITLE
Webpack resolver doesn't seem to allow "/" alias

### ISSUE THREAD

**Issue by bw** [benmosher/eslint-plugin-import#854]
As far as I can tell (6+ hrs experimentation), the Webpack resolver doesn't allow for a slash prefix to be attached to absolute import paths we've redefined in Webpack.

We wanted our imports to be relative to the root of our project. If you don't use a prefixed slash, then IDEs like WebStorm won't refactor file structures correctly, so we also wanted them to be prefixed with a slash:

```js
import SomeModule from '/components/SomeModule';
```

Here is our Webpack configuration file:

#### webpack.dev.js
```js
...
resolve: {
    modules: [
        'node_modules',
        resolve(__dirname, 'src/js'),
    ],
    extensions: ['.js', '.jsx', '.scss'],
},
...
```

Webpack is very happy with this configuration and compiles without problem. But eslint will complain `import/no-unresolved` on all of our imports. For the record, here is the relevant portion of `.eslintrc` with our resolver:

#### .eslintrc
```json
...
"settings": {
  "import/resolver": {
    "webpack": {
      "config": "webpack.dev.js"
    }
  }
}
...
```

## Using an alias doesn't work

I was thinking that adding a slash alias might work. Using the `/$` alias does not cause problems with Webpack. I was thinking that this method might be enough to "trick" the eslint resolver into resolving these correctly. 

The below code works in Webpack but still does not work in eslint:

#### webpack.dev.js
```js
...
resolve: {
    modules: [
        'node_modules',
        resolve(__dirname, 'src/js'),
    ],
    alias: {
        '/$': resolve(__dirname, 'src/js/'),
    },
    extensions: ['.js', '.jsx', '.scss'],
},
...
```

## Aliases in general work

I strongly feel that this is a problem isolated to just the slash prefix. When we use another prefix, `~/` for example, Webpack works fine and eslint also works fine:

#### webpack.dev.js
```js
...
resolve: {
    modules: [
        'node_modules',
        resolve(__dirname, 'src/js'),
    ],
    alias: {
        '~/$': resolve(__dirname, 'src/js/'),
    },
    extensions: ['.js', '.jsx', '.scss'],
},
...
```

## Other packages

I've tried to use other resolver plugins, including [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) and [babel-plugin-root-import](https://github.com/entwicklerstube/babel-plugin-root-import). I feel like this is just something basic about the way the slash prefix works that I'm not understanding.

Is there just something I'm missing here?

**Comment by ljharb** [comment]
A leading slash means something in node - an absolute path. Generally it's a really bad idea to configure module aliases that *shadow* legitimate node-supported paths.

In other words, I think `/` is the wrong choice for a prefix, because it already means something.

**Comment by bw** [comment]
@ljharb without anything except a slash, our WebStorm IDE ([ticket #1](https://youtrack.jetbrains.com/issue/WEB-17254), [ticket #2](https://youtrack.jetbrains.com/issue/WEB-13409), both 2-3 years old) doesn't understand the paths :( So I understand the shadowing problem but prefixing with anything else also doesn't work.

Is there not a solution because it's completely impossible; or just that this is a matter of configuration, even if ill-advised?

Thanks so much by the way.

**Comment by ljharb** [comment]
I'm going to guess it's a matter of very ill-advised configuration, but since it's so ill-advised, it's likely it might be impossible without further fixes.

To be honest, if your IDE is forcing you to do something ill-advised, your time is better spent looking for a non-incompetent IDE.

**Comment by bw** [comment]
OK. I haven't found another IDE that does refactors as intelligently as WebStorm and there seems to be a good community around it. I guess we will just have to use relative paths or deal with no IntelliSense.

Much appreciation for the work you've done for this community. Thanks for your help.

**Comment by santiph** [comment]
It doesn't seem to work with aliases starting with "@", like in:

```
    resolve: {
        alias: {
            '@Styles': path.resolve(__dirname, 'styles'),
        }
    }
```
If I use `Styles` only it stops complaining.
