### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by benmosher** [benmosher/eslint-plugin-import#863]
when upgrading from v1.14.0 to v2.4.0, I can no longer lint my work project without out-of-memory crashing.

needs investigation.

**Comment by benmosher** [comment]
mmm, appears to be introduced by #839 pr. some relative path must be part of the cache key for module cache now

**Comment by sompylasar** [comment]
I've linted a large enough project with my fork just fine. What relative paths are you talking about? Please give an example.

**Comment by sompylasar** [comment]
@benmosher, _upgrading from v1.14.0 to v2.4.0_ is quite a big upgrade, are you sure it's not caused by anything else? Have you tried `v2.3.0` with success? I don't see how the `parserOptions` could be a part of [the utils/resolve cache key we were talking about here](https://github.com/benmosher/eslint-plugin-import/pull/840#discussion_r119950630). Please help to investigate by printing out [this `cacheKey` and `settings`](https://github.com/sompylasar/eslint-plugin-import/blame/60b524b3d6299cfedeb19f1e94d9bf65b691aa42/utils/resolve.js#L55) in the project you're seeing issues with.

**Comment by benmosher** [comment]
I tried 2.3.0 with the previous utils version and did not see the issue. thus my suspicion that the utils bump is what killed it.

I need to look more closely and understand what the issue was, for sure, but until I have time to do that I'm not comfortable releasing it.

**Comment by benmosher** [comment]
> Please help to investigate by printing out this cacheKey and settings in the project you're seeing issues with.

fair, looks like it probably isn't that. was my first guess given the change was small and the memory ran out + ran super slow (smells like a cache issue).

**Comment by sompylasar** [comment]
> I tried 2.3.0 with the previous utils version and did not see the issue. thus my suspicion that the utils bump is what killed it.

Could you please try 2.3.0 with the parserOptions.filePath line added to parse function manually? That's the only change.

> I need to look more closely and understand what the issue was, for sure, but until I have time to do that I'm not comfortable releasing it.

Fair, though I won't be able to help without a repro.

**Comment by benmosher** [comment]
Makes sense, will try ASAP. not sure when though

**Comment by benmosher** [comment]
it's possible that the codebase from #615 will also bear out the issue since it is also large. might not OOM but you might be able to repro the slowdown.

**Comment by piecyk** [comment]
Hi how can i help ? also waiting for `parserOptions.filePath` line to be added

**Comment by benmosher** [comment]
seems like it is some interaction between v2.4.0 and utils/v2.1.0 after all, so I just published utils 2.1.0 after confirming it seems to work okay with plugin v2.3.0

**Comment by benmosher** [comment]
ahhh, I think I finally found it: https://github.com/benmosher/eslint-plugin-import/blob/master/memo-parser/index.js#L25

the leak is in the memo-parser. I suspect I'm the only person using it. nonetheless, will fix 😅

**Comment by benmosher** [comment]
fixed. turns out filePath wasn't added until ESLint v3.5.0 so cache would miss between ESLint proper and dependency parsing

**Comment by sompylasar** [comment]
🎉
