### ISSUE TITLE
2.4.0 removed from npm?

### ISSUE THREAD

**Issue by NiGhTTraX** [benmosher/eslint-plugin-import#864]
Greenkeeper notified me of 2.4.0 being published but [npmjs](https://www.npmjs.com/package/eslint-plugin-import) shows 2.3.0 being the latest. One of my 2 Travis builds managed to install 2.4.0 but the other one failed to find it. What's going on?

**Comment by BerkeleyTrue** [comment]
I also have two packages of mine are also not able to find 2.4.0

https://travis-ci.org/BerkeleyTrue/react-redux-subdivide/builds/238805745
https://travis-ci.org/BerkeleyTrue/react-redux-epic/builds/238794725

**Comment by ljharb** [comment]
I believe it was unpublished due to a regression. Greenkeeper seems unable to handle unpublishes.

**Comment by bonesoul** [comment]
same here

**Comment by NiGhTTraX** [comment]
Ok, thanks @ljharb for the info.

**Comment by bonesoul** [comment]
npm still shows 2.3.0 - https://www.npmjs.com/package/eslint-plugin-import

any fixes?

**Comment by ljharb** [comment]
2.4.0 will never reappear; versions once unpublished can never be restored. a 2.4.1 will be released once the underlying issue in 2.4.0 is fixed.
