### ISSUE TITLE
Glob in "import/no-extraneous-dependencies" doesn't work as expected

### ISSUE THREAD

**Issue by olalonde** [benmosher/eslint-plugin-import#866]
`eslint v3.19.0`

My eslintrc looks like: 

```json
{
  "extends": "binded",
  "rules": {
    "import/no-extraneous-dependencies": [
      "error", {"devDependencies": ["test/*"]}
    ]
  }
}
```

This doesn't work as expected (still getting `error  'knex' should be listed in the project's dependencies, not devDependencies       import/no-extraneous-dependencies` in `test/index.js`). I tried various globs with no success: `test/*.js`, `./test/*`, `./test/**/*`, etc.

The only thing that seems to work is:

```json
{
  "extends": "binded",
  "rules": {
    "import/no-extraneous-dependencies": [
      "error", {"devDependencies": true}
    ]
  }
}
```

**Comment by ljharb** [comment]
Are you getting this on the command line or in an editor? Are you running the command in the project root?

**Comment by olalonde** [comment]
Yes to both.

**Comment by ljharb** [comment]
I know these settings work: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L71-L86

Try adding `"root": true` to your eslint config in the project root, just in case?

**Comment by olalonde** [comment]
`"root": true` didn't help. I did however upgrade the version of `eslint-config-airbnb-base` I was extending which seemed to fixed the issue.
