### ISSUE TITLE
ESlint v4

### ISSUE THREAD

**Issue by KoltesDigital** [benmosher/eslint-plugin-import#870]
Hi! Today is the official release of eslint v4.0.0. `eslint --init` can break because `eslint-plugin-import` only support eslint v3.x.

```
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? YAML
Local ESLint installation not found.
Installing eslint, eslint-plugin-standard, eslint-plugin-promise, eslint-config-standard
...
├─┬ eslint@4.0.0
├── UNMET PEER DEPENDENCY eslint-plugin-import@>=2.2.0
```

**Comment by ljharb** [comment]
This is an open issue with eslint --init, not something this plugin needs to address.

That said, it'd be nice if it could publish a version that supports both v3 and v4. A PR would be helpful.

**Comment by brettz9** [comment]
Can't [this line](https://github.com/benmosher/eslint-plugin-import/blob/master/package.json#L77) just be updated to include 4.0 (if not also [this one](https://github.com/benmosher/eslint-plugin-import/blob/master/package.json#L59))?

**Comment by brettz9** [comment]
After updating to ESLint 4, I'm getting the same unmet peer dependency error in attempting to  shrinkwrap [our package](https://github.com/axemclion/IndexedDBShim).

A very [easy change](https://github.com/amilajack/eslint-plugin-compat/pull/88/files) was made for another ESLint plug-in. I could prepare a PR, but the change ought to be trivial for anyone with access.

**Comment by ljharb** [comment]
@brettz9 it's not necessarily easy; but we also already have an open PR (#871).

**Comment by benmosher** [comment]
I'll publish in the morning as 2.6.0

**Comment by benmosher** [comment]
published 👍🏻
