### ISSUE TITLE
How to ignore aliases?

### ISSUE THREAD

**Issue by SilentImp** [benmosher/eslint-plugin-import#872]
Hi, 
I have added alias in my webpack configuration:
~~~js
    alias: {
      config: resolve(baseDir, `./config/application.${env}.js`),
    },
~~~
And now my code can't pass eslinter, which is sad. 
How I may exclude aliases?
Or many you may advice me some other nice solution on such situation?

**Comment by ljharb** [comment]
See the [resolvers](https://github.com/benmosher/eslint-plugin-import#resolvers) section of the readme.

**Comment by benmosher** [comment]
closing but willing to re-open if webpack resolver is insufficient. AFAIK it handles this.
