### ISSUE TITLE
webpack-2 support?

### ISSUE THREAD

**Issue by tony-kerz** [benmosher/eslint-plugin-import#874]
[this issue](https://github.com/benmosher/eslint-plugin-import/issues/265) is marked closed and [this changelog](https://github.com/benmosher/eslint-plugin-import/blob/4e475203bea5f9dc930c3e1d76a89f2e1f66e36e/resolvers/webpack/CHANGELOG.md#changed) implies that support is available, but i can't seem to find any related documentation/examples, does anyone have any experience around this they can share?

**Comment by mastilver** [comment]
check this: https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack

**Comment by markwoon** [comment]
I can confirm that it works for webpack 2.

**Comment by benmosher** [comment]
works for v3 as well, AFAICT
