### ISSUE TITLE
In NPM@5 the -s flag is deprecated

### ISSUE THREAD

**Issue by Nicholaiii** [benmosher/eslint-plugin-import#884]
no-extraneous-dependencies reports that I should "Run `npm i -S package`"

**Comment by ljharb** [comment]
`-s` is `--silent` I thought; `-S` is `--save-dev`.

If that eslint-plugin-import rule is complaining, it likely means your package.json is missing a dependency.

**Comment by benmosher** [comment]
I thought `-D` was `--save-dev` and `-S` is `--save` (which is on by default as of npm v5, right?).

Not clear to me how to emit an npm-version-agnostic message...

**Comment by ljharb** [comment]
Ah whoops, true.

It's not deprecated in npm 5 tho, it's just not needed by default.

**Comment by benmosher** [comment]
ah sweet, closing this then. @Nicholaiii feel free to comment back if we've misunderstood 😅

**Comment by Nicholaiii** [comment]
Ben is right :) I think it's best practise to show relevant information; and I think it might prompt people to keep thinking `npm install package` doesn't save packages. If you `npm help install` it does not show any -S flag anymore and I think that's a strong sign that it's deprecated.

**Comment by ljharb** [comment]
deprecations don't have "signs", either it's deprecated or it's not. In this case, it's not. It's just not necessary in npm 5+ by default.

a) not everyone is on npm 5; b) not everyone likes npm 5's default behavior (:wave:) so they add `save=false` to `.npmrc`, such that `-S` is required to get the save behavior.
