### ISSUE TITLE
Unable to load resolver when using custom webpack config file name

### ISSUE THREAD

**Issue by gaastonsr** [benmosher/eslint-plugin-import#885]
If I use 

```json
  "settings": {
    "import/resolver": "webpack"
  }
```

as my settings and my webpack config file is `webpack.config.js` everything works.

But if I try to do 

```json
  "settings": {
    "import/resolver": {
      "config": "webpack.config.dev.js"
    }
  }
```

and rename my webpack config file name to `webpack.config.dev.js`.

I get this error when I'm linting

`Resolve error: unable to load resolver "config"`

I'm using

- webpack `2.6.1`
- eslint-plugin-import `2.6.0`
- eslint-import-resolver-webpack `0.8.3`

**Comment by ljharb** [comment]
What if the path starts with `./`? node's require algorithm requires all relative paths start with a dot.

**Comment by gaastonsr** [comment]
Doesn't work either.

**Comment by fastfrwrd** [comment]
Similarly, mine fails if my webpack config is in a subdirectory, such as `./config/webpack.config.js`.

**Comment by kossel** [comment]
you need  to wrap it to the `webpack` object 😄 

```
"settings": {
    "import/resolver": {
      "webpack": {
        "config": "./webpack.config.web.dev.js"
      }
    }
  }
```

**Comment by gaastonsr** [comment]
This solved it! I missed that. Thanks @kossel.
