### ISSUE TITLE
default envs?

### ISSUE THREAD

**Issue by jdalton** [benmosher/eslint-plugin-import#893]
*Sorry for the noob-ish question.*
I noticed I don't have to specify an `env` of ` { es6: true, node: true }`.
Is eslint-plugin-import setting that somewhere?

**Comment by ljharb** [comment]
https://github.com/benmosher/eslint-plugin-import/blob/master/config/recommended.js#L23-L27 sets the ecmaVersion; I don't see anything setting env properties. What's your eslint config look like?

**Comment by jdalton** [comment]
```js
module.exports = {
  extends: ["plugin:import/errors"],
  parser: "eslint-plugin-import/memo-parser",
  parserOptions: {
    ecmaVersion: 8,
    parser: "babel-eslint"
  },
  rules: {
    "no-unused-vars": 2
  }
}
```
