### ISSUE TITLE
Expected empty line after require statement not followed by another require.

### ISSUE THREAD

**Issue by overflowz** [benmosher/eslint-plugin-import#894]
title says it all, when using following:
````
const { Router } = require('express');
````

any thoughts?

**Comment by ljharb** [comment]
That's just one line - what's the rest of it look like?

**Comment by overflowz** [comment]
only that one line triggers this error. anyways, here's the another part, which does the same thing.

````
import { Router } from 'express';
const router = Router();

module.exports = router;

````

**Comment by ljharb** [comment]
Right, it wants a new line after the import or the require.

**Comment by overflowz** [comment]
doh... I'm sorry. My English skills betrayed me. You are right, this issue makes no sense.

Thanks for the clarification!
