### ISSUE TITLE
[Help Requested] Resolver for Ember

### ISSUE THREAD

**Issue by micky2be** [benmosher/eslint-plugin-import#896]
I would like to keep using this plugin but ember has such weird stuff that I need a resolver for it.
I don't see any in the wiki. So if someone already made one or feel up to the task that would be great.

**Comment by gabrielcsapo** [comment]
working on something here https://github.com/ember-cli/ember-cli-eslint/issues/288

**Comment by ljharb** [comment]
Looks like the resolver exists now. Feel free to list it in [the wiki](https://github.com/benmosher/eslint-plugin-import/wiki/Resolvers)

**Comment by gabrielcsapo** [comment]
Just added @ljharb thanks!
