### ISSUE TITLE
Resolve environment variables with webpack

### ISSUE THREAD

**Issue by DJviolin** [benmosher/eslint-plugin-import#900]
I'm still getting the `import/no-unresolved` error.

I followed closely the [Simple approuch](https://webpack.js.org/guides/production/#simple-approach) tutorial on webpack's website.

Now I have the following files:

```
webpack.config.babel.js
webpack.common.js
webpack.dev.js
webpack.prod.js
```

I have this in my `webpack.config.babel.js`:

```js
module.exports = function(env) {
  return require(`./webpack.${env}.js`);
};
```

I starting webpack with the following in `package.json`:

```js
"build:dev": "webpack-dev-server --open --env=dev --progress --profile --colors",
"build:dist": "webpack --env=prod --progress --profile --colors",
```

The actual resolving object in webpack is in the `webpack.common.js` file:

```js
resolve: {
  extensions: ['.js', '.json'],
  alias: {
    'three/GLTF2Loader': path.join(__dirname, 'node_modules/three/examples/js/loaders/GLTF2Loader.js'),
    'three/Stats': path.join(__dirname, 'node_modules/three/examples/js/libs/stats.min.js'),
    'three/OrbitControls': path.join(__dirname, 'node_modules/three/examples/js/controls/OrbitControls.js'),
  },
},
```

This is in my `eslintrc.js` file:

```js
settings: {
  'import/resolver': {
    webpack: {
      config: 'webpack.common.js',
    },
  },
},
```

**Comment by KrisOlszewski** [comment]
@DJviolin have you found a solution? I have the same problem. Aliases are not recognized.

**Comment by DJviolin** [comment]
Not yet, in fact I didn't worked with Webpack since. I'm building the project without bundling.

Just a note, tree shaking also broken with three.js, AR.js. I'm constantly getting bigger file sizes than without. Webpack is "awesome"... :(

**Comment by AoDev** [comment]
@KrisOlszewski Have you found some solution?

I am using this config to disable the warning for now:

```
  "settings": {
    "import/core-modules": ["my-alias"]
  }
```

**Comment by ljharb** [comment]
I think that perhaps you want a fallback, so that `--env` can be omitted, and this will work?

Happy to reopen if not.
