### ISSUE TITLE
Look for unresolved `jest.mock()` calls

### ISSUE THREAD

**Issue by cowchimp** [benmosher/eslint-plugin-import#906]
Hi.

This is a feature suggestion.
Would be interested in submitting a PR if you think you're likely to accept it and can point me in the right direction.

When working with [Jest](https://facebook.github.io/jest/) its very typical to have test files that start like this:

```javascript
import { foo } from '../../../src/utils/bar';
import baz from '../../../src/baz';

jest.mock('../../../src/utils/bar');
jest.mock('../../../src/baz');
```

As you can see the path for each dependency you want to mock is repeated twice- once for the import statement, and once for the `jest.mock()` call.

Currently, if I have an unresolved path in the import statement I can use `eslint-plugin-import` to catch it, but as-can-be-expected it won't catch an unreasonable path in the `jest.mock()` call. Ideally I would like to catch cases like these with an eslint rule as well.

There is already an eslint plugin specifically for Jest called `eslint-plugin-jest` and I suggested to them to contribute a rule that will help catch cases like this, but [they declined](https://github.com/facebook/jest/issues/4172) (which is fine of course).

So now as I see it there are two options:
1. Create a rule specifically to catch unresolved paths in `jest.mock` calls.
2. Make this a bit more generic and write a rule that can find unresolved paths in any call to any service that's relevant to whatever framework\library the user is working with. (e.g. if tomorrow there's some new hot testing framework where you have to mock your dependencies by calling `hi.there('.../a/b')`).  
I also found this issue #585 which is basically the exact same requirement. If you make it configurable there is no difference between `require.resolve(path)` and `jest.mock(path)`.

For both options I would like to create and contribute this rule to `eslint-plugin-import` to make use of the heavy-lifting it does for determining if a path is resolvable (revolvers mechanism, caching, casing issues), and also for sheer reach because I think this use-case will be relevant for a lot of people.

So, my question(s):
* Would you consider accepting a PR that adds this rule?
* Would you prefer option 1 or option 2?

Thank you!

**Comment by ljharb** [comment]
This seems like something that belongs in eslint-plugin-jest, not here.

**Comment by ljharb** [comment]
Also note that jest has lots of config that may one day affect how mocks are resolved, and this plugin wouldn't want to manage that.

**Comment by cowchimp** [comment]
Thanks for the reply.
In that case would you be willing to consider a PR that implements options # 2 in my post?
Like I mention, you can let the user configure any function that needs a valid path, be it `jest.mock('../a/b')`, `require.resolve('../a/b')`, or `foo.bar('../a/b')`.

**Comment by ljharb** [comment]
For the same reason, I don't think so - alternate require functions could have all kinds of different rules applied, and you can't just swap out node's `require` for something else without lots of other configuration.

**Comment by ljharb** [comment]
Closing; this belongs in eslint-plugin-jest.
