### ISSUE TITLE
vscode import/extensions no use

### ISSUE THREAD

**Issue by willin** [benmosher/eslint-plugin-import#913]
```js
const path = require('path');

module.exports = {
  root: true,
  extends: [
    'dwing',
    'plugin:vue/recommended'
  ],
  rules: {
    'import/extensions': [2, 'always', { js: 'never', vue: 'never' }]
  },
  settings: {
    'import/resolver': {
      webpack: {
        config: 'build/webpack.config.js'
      }
    }
  }
};
```

<img width="1369" alt="wx20170809-170602 2x" src="https://user-images.githubusercontent.com/1890238/29113920-2f254548-7cb8-11e7-975c-582ede93790d.png">

```js
// webpack
```js
  resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname, '../src')
    ],
    extensions: ['.js', '.vue', '.json', '.css'],
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      public: path.resolve(__dirname, './public')
    }
  }
```

source code can found: https://github.com/AirDwing/vuetify-demo/blob/master/src/router/index.js#L3

**Comment by ljharb** [comment]
What happens on the command line? Editor integrations often have issues; eslint CLI is what's important to test.

**Comment by willin** [comment]
![wx20170810-093358 2x](https://user-images.githubusercontent.com/1890238/29150731-19eb47a6-7d42-11e7-9fc7-f96b230b48ef.png)

**Comment by ljharb** [comment]
Linting should be run via an npm run-script, and should be run on the command line as part of tests and CI. You shouldn't have or need a global eslint installation.

**Comment by willin** [comment]
sourcecode at: https://github.com/AirDwing/vuetify-demo/

**Comment by ljharb** [comment]
Try `npx eslint .`?

**Comment by willin** [comment]
```bash
 ~/Desktop/vuetify-demo   master ●  npx eslint .
 ~/Desktop/vuetify-demo   master ● 
```

nothing print

**Comment by ljharb** [comment]
hm, that's strange - `npm install && ./node_modules/.bin/eslint .`?

**Comment by willin** [comment]
```
 ~/Desktop/vuetify-demo   master ●   ./node_modules/.bin/eslint .
 ~/Desktop/vuetify-demo   master ● 
```

**Comment by ljharb** [comment]
ok - that implies there's no linting errors. have you configured vscode to use the local eslint? (you can verify by `npm uninstall -g eslint`, since you shouldn't need a global one)

**Comment by ljharb** [comment]
Closing pending a response.
