### ISSUE TITLE
eslint-plugin-import@2.7.0 requires a peer of eslint@2.x - 4.x but none was installed

### ISSUE THREAD

**Issue by JustFly1984** [benmosher/eslint-plugin-import#916]
I have this weird warning.
<img width="453" alt="screenshot 2017-08-18 06 14 46" src="https://user-images.githubusercontent.com/2255993/29436090-9a31504a-83dc-11e7-89fa-7504ec03f3f0.png">

**Comment by ljharb** [comment]
You have it installed globally, but nothing should be installed globally. Install everything locally per project instead.

**Comment by JustFly1984** [comment]
I can't install localy, cos I have dependency conflict with
create-react-app

2017-08-18 6:16 GMT+08:00 Jordan Harband <notifications@github.com>:

**Comment by ljharb** [comment]
If that's the case, then you have to eject from CRA to customize it, or stick to whichever versions CRA requires.

**Comment by benmosher** [comment]
Could you install this plugin globally? (if you just want to get rid of the warning)

FWIW, I have resigned myself to these peer warnings in my projects. They are occasionally useful, and often noise, and the former more or less warrants the latter. 🤷🏼‍♂️
