### ISSUE TITLE
Facing issue regarding setting up React Native with eslint-config-rallycoding

### ISSUE THREAD

**Issue by saumikbhattacharya** [benmosher/eslint-plugin-import#924]
Hi All,

I have been facing this issue for quite some time regarding setting up my React Native environment. I have started using ESLint config Rallycoding in Atom. I am getting the below error --

> Unable to resolve path to module 'react' (import/no-unresolved).
>Unable to resolve path to module 'react-native' (import/no-unresolved).

My .eslintrc file goes here --

``{
  "extends": "rallycoding"
}``

And my package.json file also goes here -- 

``{
	"name": "FirstReactAndroidApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start"
	},
	"dependencies": {
		"babel-eslint": "^6.1.2",
		"eslint": "^3.19.0",
		"eslint-import-resolver-node": "^0.2.3",
		"eslint-plugin-class-property": "^1.0.6",
		"eslint-plugin-import": "^1.16.0",
		"eslint-plugin-jsx-a11y": "^2.2.3",
		"eslint-plugin-react": "^6.10.3",
		"react": "15.3.1",
		"react-native": "0.33.0"
	},
	"devDependencies": {
		"eslint-config-rallycoding": "^3.2.0"
	}
}``

Please help me with this issue. Let me know incase you need any more info.

**Comment by williamdwarke** [comment]
I'm having the same exact problem. Did you ever find a solution?

**Comment by richardstephenz** [comment]
Same here, any luck finding a fix?

**Comment by robertofrontado** [comment]
I'm facing the same issue 👎  any luck with it?

**Comment by cocosribbons** [comment]
same issue here, and I think I figured it out, finally! it's a case sensitivity issue. 

- if you opened your project directory from Terminal using a series of "cd"s, then open it using command line "atom .", the full path sent to Atom somehow is recognised as all in lower case, and is displayed at the window header in lower case, eg. like below,
<img width="298" alt="screen shot 2018-01-03 at 08 38 10 pm" src="https://user-images.githubusercontent.com/35039907/34521170-57605d62-f0c7-11e7-95d8-f0f80064bae0.png">

- but it really needs to be in the correct case, ie. if your path had upper cases, they need to be in the upper cases, like below, 
<img width="264" alt="screen shot 2018-01-03 at 08 33 33 pm" src="https://user-images.githubusercontent.com/35039907/34521167-54bc017e-f0c7-11e7-9f30-be5eecc542ed.png">

- the way to fix it I found is to simply open the project from Atom itself, via, File > Open > [Project Folder] Once in the correct case, the unresolved error went away for me. 

Please try for yourself and see if it works.

**Comment by ljharb** [comment]
I'm going to close this; if it turns out not to be editor-related, I'm happy to reopen.

**Comment by saber-mazoji** [comment]
hi i having this problem ,
how can i fix it?
`{
	"parser": "babel-eslint",
	"extends": "rallycoding",
	"plugins": [
		"react",
		"import",
		"jsx-a11y"
	] }
`
