### ISSUE TITLE
Extensions: exception/option for global imports

### ISSUE THREAD

**Issue by QuentinRoy** [benmosher/eslint-plugin-import#934]
Enhancement proposal: global case for extensions.

I think it is starting to be good practice to alway specify the extension of a file, i.e. `"import/extensions": ["error", "always"]` as this will be required with browsers' module loaders.

However, this causes issues when using with webpack or others and importing libraries installed in the `node_modules` (e.g. `import 'react'`) that cannot have the `'.js'` extension.

It would be useful to be able to create a case for global imports, e.g. `[<enabled>, "alway", { "globals": "never" }]`.

**Comment by ljharb** [comment]
When you say "global", do you mean bare specifiers, i.e. things in node_modules? If so this might be a duplicate of #414.

**Comment by QuentinRoy** [comment]
Oops. Indeed I missed this issue. Thanks.
