### ISSUE TITLE
Dependency parser doesn't respect ecmaFeatures

### ISSUE THREAD

**Issue by jameslnewell** [benmosher/eslint-plugin-import#94]
This style of code is very common in projects using React and higher order components. This rule doesn't seem to detect the default export in this case.

    //connect a redux store
    export default connect()(App);

**Comment by benmosher** [comment]
Weird. Not sure why it wouldn't be picked up. I'll add a test and scope it out.

**Comment by benmosher** [comment]
Test passes on my machine OS X w/ Node 4. Can you fork `redux-default` and see if you can write a `default` test that fails?

Or send me the `import` statement that is being errantly reported as having no default (with your `.eslintrc`)?

**Comment by jameslnewell** [comment]
Ah sorry, it actually appears that JSX is the cause.
My classes with JSX were wrapped in connect calls and didn't work but my classes with standard exports worked fine.

App.js
    
    export default class App {
      render() {
        return <h1>Hello World!</h1>; //comment this line out and it works
      }
    }
    
index.js

    import App from './App';

.eslintrc

    {
      "root": true,

      "env": {
        "es6": true
      },
    
      "ecmaFeatures": {
        "classes": true,
        "modules": true,
        "jsx": true
      },
    
      "plugins": [
        "import"
      ],
    
      "rules": {
        "import/default": 2
      }
    
    }

eslint ./index.js

    /Users/james/demo/index.js
      1:8  error  No default export found in module  import/default

**Comment by benmosher** [comment]
Ah, yeah, you have to configure the parser for JSX. It only parses spec ES6 by default. 

If you look at the `config/es7-jsx` shared config, you can see how to configure it; or you can just `extends: "import/es7-jsx"` if you install the config package. (eslint-config-import)

**Comment by benmosher** [comment]
Actually, I'll take another look and see if I can read the `ecmaFeatures` from inside the plugin and avoid explicit config on the dependency parser.

**Comment by benmosher** [comment]
Yep, plugin context includes `ecmaFeatures`. I will make the parser sensitive to `jsx` defined there.

I think I may actually use an `es7` flag there too. Or just feed whatever is there to the parser. Seems obvious, in retrospect. 😅

**Comment by jameslnewell** [comment]
Awesome!
