### ISSUE TITLE
Definition for rule 'import/exports-last' was not found

### ISSUE THREAD

**Issue by matikrk** [benmosher/eslint-plugin-import#953]
Hi,
I would like to use 'import/exports-last' rule, but isn't working. 
When I try use it i got error 
` Definition for rule 'import/exports-last' was not found  import/exports-last`

In eslint config i had
`'import/exports-last': 'error'`
Other rules from package working well

**Comment by ljharb** [comment]
It's not released yet. See #950.

**Comment by sevor005** [comment]
Good afternoon! The question is: can I cancel the rule (put it in ignor) for classes that are exported at the beginning of the file export default class SomeClass, followed by defaultProps and PropTypes?
