### ISSUE TITLE
Tag v2.8.0?

### ISSUE THREAD

**Issue by eventualbuddha** [benmosher/eslint-plugin-import#967]
I see a release on [npm](https://www.npmjs.com/package/eslint-plugin-import), but [no tag in git](https://github.com/benmosher/eslint-plugin-import/releases).

**Comment by benmosher** [comment]
I see one? https://github.com/benmosher/eslint-plugin-import/releases/tag/v2.8.0

**Comment by eventualbuddha** [comment]
Weird. Thanks!

**Comment by ljharb** [comment]
It definitely wasn’t there at the time this was filed :-) must have been created locally and only pushed up later.
