### ISSUE TITLE
no-extraneous-dependencies wont work with globs

### ISSUE THREAD

**Issue by vzaidman** [benmosher/eslint-plugin-import#974]
this is how i try to configure it to prevent devDependencies from being imported inside "src" but it also applies to all the files that are in other folders instead of only to the "src" folder as i expected.
```
import/no-extraneous-dependencies: [error, { devDependencies: ['src/**/**.js'] }]
```

**Comment by ljharb** [comment]
I think you have it backwards; the glob is for when it's *true*. In other words, you'd want to disable devDependencies everywhere, and then only selectively *enable* them in test dirs, eg.

**Comment by vzaidman** [comment]
thanks it worked:
```
import/no-extraneous-dependencies: [error, { devDependencies: ['src/**/**.js'] }]
```
its a little counterintuative for me actually because it says `no-extraneous-dependencies` but in the glob you specify where it is "yes extraneous dependencies"
