### ISSUE TITLE
Cut new version

### ISSUE THREAD

**Issue by sdemjanenko** [benmosher/eslint-plugin-import#976]
Can we cut a new version of this package? I use webpack externals heavily and this [commit](https://github.com/benmosher/eslint-plugin-import/commit/ae3731874d6e835904c97d5b05867e5b5056f489) makes the `import/no-extraneous-dependencies` no longer warn on missing externals. Thanks!

**Comment by graingert** [comment]
@sdemjanenko currently waiting on @benmosher to document a release process https://github.com/benmosher/eslint-plugin-import/pull/912#issuecomment-352643841

**Comment by isiahmeadows** [comment]
@ljharb @benmosher Status?

**Comment by michaelhogg** [comment]
I too am looking forward to the next release, specifically for the `ignorePackages` enhancement to the `extensions` rule – many thanks to @collinsauve and @millerized for your work on this in PR #827 :tada:

@benmosher @ljharb: Do you have an estimated date for the next release? Many thanks in advance :slightly_smiling_face:

**Comment by ljharb** [comment]
No estimated date; it will be released as soon as I have time to do so.

**Comment by isiahmeadows** [comment]
Well...we can add [`import/no-default-export`](https://github.com/benmosher/eslint-plugin-import/pull/936#event-1480806797) to this mix.

**Comment by graingert** [comment]
@benmosher so hyped for this release!

**Comment by benmosher** [comment]
no worries @ljharb, you've been doing so much already! much appreciated

**Comment by benmosher** [comment]
shipped it! v2.9.0 is published. had to follow my own RELEASE document so hopefully I didn't botch it 😄

**Comment by graingert** [comment]
🎉

**Comment by sdemjanenko** [comment]
Thanks so much. You all rock.

**Comment by graingert** [comment]
new stuff to add to airbnb-base! https://github.com/airbnb/javascript/pull/1743

**Comment by jimmy34323** [comment]
No need to wait any longer...Thanks[!](https://getcapcut.in/)
