### ISSUE TITLE
requires a peer of eslint@2.x - 4.x but none was installed

### ISSUE THREAD

**Issue by TriMoon** [benmosher/eslint-plugin-import#989]
#916 Still happens with 2.8.0...
```
~/ sudo npm -g update eslint-plugin-import
- ms@0.7.1 node_modules/eslint-plugin-import/node_modules/eslint-module-utils/node_modules/ms
- debug@2.2.0 node_modules/eslint-plugin-import/node_modules/eslint-module-utils/node_modules/debug
- object-assign@4.1.1 node_modules/eslint-plugin-import/node_modules/object-assign
- pkg-up@1.0.0 node_modules/eslint-plugin-import/node_modules/pkg-up
/usr/lib
├── UNMET PEER DEPENDENCY eslint@2.x - 4.x
└── eslint-plugin-import@2.8.0 

npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none was installed.
```
```
~/ sudo npm -g list eslint eslint-plugin-import
/usr/lib
├── eslint@4.14.0 
└── eslint-plugin-import@2.8.0 
```

---
Could someone **fix** this for _once and all_?
It's totally brain damaging to have a module that requires some version of another module but throws exceptions like this, while the "actual intended" version of that module **IS** available... :roll_eyes: 
I guess you need to use ```eslint: '>=2 <=4',``` see: [semver-ranges](https://docs.npmjs.com/misc/semver#ranges)

---
Another note:
Why is the next version numbered lower as the latest? :confused: 
```
~/ sudo npm -g view eslint-plugin-import
 
{ name: 'eslint-plugin-import',
  description: 'Import with sanity.',
  'dist-tags': { latest: '2.8.0', next: '2.0.0-beta.1' },
  versions: 
......
```

**Comment by TriMoon** [comment]
After doing ```sudo npm -g install semver``` it seems to have gone :confused:

**Comment by ljharb** [comment]
In general, things shouldn't be installed globally, especially linters like eslint and their plugins (since these are per-project tools). Glad you figured it out.

**Comment by TriMoon** [comment]
@ljharb , in contrary those that you mentioned are commonly used by many projects and thus warrant a global install.
Unless you're the kind that believes the shell is also per user and should be installed per user ...doh...
anyway, i think you guys should mention a fix for this problem in some documentation of your install guides...
cheers

**Comment by ljharb** [comment]
No, used by 1000 projects means you should have 1000 local installs - that way each project as all its dependencies easily reproducible, and version-tracked.

In general, nothing should be globally installed.

**Comment by TriMoon** [comment]
LMFAO, then go persuade the node+npm makers to remove the option to install globally...
<smacks back of your head>
/signoff from thread

**Comment by ljharb** [comment]
They’ve already removed respecting the “preferGlobal” option, for exactly this reason.

You don’t have to follow best practices, but none the less, global installs are a bad practice, full stop.

Also, anything with peer deps is a nightmare to globally install, as you discovered.
