### ISSUE TITLE
eslint-import-resolver-node needs a dep bump to resolve 1.5.0

### ISSUE THREAD

**Issue by shellscape** [benmosher/eslint-plugin-import#992]
What the title says. That resolver is still using an older version, perpetuating the issue in https://github.com/benmosher/eslint-plugin-import/issues/948. Needs a bump and publish.

**Comment by ljharb** [comment]
The range is `^1.2.0` which automatically includes v1.5+, so no bump is needed. You may simply need to uninstall+reinstall / update eslint-plugin-import.

**Comment by ljharb** [comment]
v0.3.2 is released.
